deploy/src/objects/IPM_Bosscard__c.object
<CustomObject>
    <description>This object is created to hold the Bosscard Details</description>
    <fields>
        <fullName>IPM_Bosscard_Status__c</fullName>
        <description>Contains the status of Bosscard</description>
        <label>IPM Bosscard Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IPM Company Card</label>
        <referenceTo>IPM_Company_Card__c</referenceTo>
        <relationshipLabel>IPM Bosscard</relationshipLabel>
        <relationshipName>IPM_Bosscard</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Bosscard</label>
    <nameField>
        <label>IPM Bosscard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Bosscard</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Company_Card__c.object
<CustomObject>
    <description>This object store company cards details</description>
    <label>IPM Company Card</label>
    <nameField>
        <label>IPM Company Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Company Card</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

deploy/src/objects/IPM_Financial__c.object
<CustomObject>
    
    <fields>
        <fullName>Parent_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Financials (Consolidated)</relationshipLabel>
        <relationshipName>IPM_Financials_Consolidated</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Financial</label>
    
    <nameField>
        <displayFormat>FIN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Financials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

deploy/src/objects/IPM_Milestone__c.object
<CustomObject>
    <description>This object is used to capture Milestone Dates</description>
    <fields>
        <fullName>IPM_Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Market_Type__c</fullName>
        <label>Market Type</label>
        <picklist>
            <picklistValues>
                <fullName>Developing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developing &amp; Emerging</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IPM Milestone</label>
        <referenceTo>IPM_Milestone__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Name__c</fullName>
        <label>Milestone Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_No_Of_Days_for_Developing__c</fullName>
        <label>No Of Days for Developing</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Launch Evaluation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Type_of_Milestone__c</fullName>
        <label>Type of Milestone</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhoc</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Milestone</label>
    <nameField>
        <label>IPM Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_Bosscard_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bosscard Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Bosscard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bosscard</label>
        <referenceTo>IPM_Bosscard__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IPM Company Card</label>
        <referenceTo>IPM_Company_Card__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Complexity__c</fullName>
        <label>Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Fast_Track_Project__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IPM Fast Track Project</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Market_Type__c</fullName>
        <label>Market Type</label>
        <picklist>
            <picklistValues>
                <fullName>Developed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Developing &amp; Emerging</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Target_Launch_Dates__c</fullName>
        <label>IPM Target Launch Date</label>
        <type>Date</type>
    </fields>
    <label>IPM Project</label>
    
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document__c.object
<CustomObject>
    <description>THis is used in IPM to store Project documents</description>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>Relation to the Project Object</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Documents</relationshipLabel>
        <relationshipName>Project_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Project Document</label>
    <nameField>
        <label>Project Document Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Section__c.object
<CustomObject>
    <description>This will be the main section object, Using this object, it will be roll out to Project/Gate Document Sections are defined.</description>
    <label>IPM Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Task__c.object
<CustomObject>
    <fields>
        <fullName>IPM_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User to whom the task is assigned</description>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Due_Date__c</fullName>
        <description>Due date of the milestone</description>
        <label>Milestone Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Function__c</fullName>
        <description>Function describes the Role of the user task is related</description>
        <label>Function</label>
        <picklist>
            <picklistValues>
                <fullName>CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MKTG DEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MKTG LOCAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>Field for the phase of the task</description>
        <label>Phase</label>
        <picklist>
            <controllingField>IPM_Type_of_Gate__c</controllingField>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Launch Evaluation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>The project for which the task is created</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The section of the document for which the task is created</description>
        <label>IPM Section</label>
        <referenceTo>IPM_Section__c</referenceTo>
        <relationshipLabel>IPM Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Task_Complexity__c</fullName>
        <description>The complexity of the task</description>
        <label>Task Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Task</label>
    <nameField>
        <label>Task ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/src/classes/IPM_MyProjects_Test.cls
/**
* IPM_MyProjectsTest: This Test class for IPM_MyProjects apex class
* @author 
*
*/
@istest
public class IPM_MyProjects_Test{
    
    public static User platformUser;
    public static User BDUser;
    public static list<IPM_Project__c> projectList;
    public static list<IPM_Project__c> updateProjectList;
    public static list<IPM_Project__c> projectDetailList;
    public static list<IPM_Project_Document__c> ipmProjDocumentTestList;
    
    @testSetup static void projectSetUpData() 
     {
        System.runAs(IPM_TestFactory_Helper.createUserAdmin(true)){
            platformUser = IPM_TestFactory_Helper.createIPMPlatformProfileUser('');
            BDUser = IPM_TestFactory_Helper.createIPMPlatformProfileUser('BD');
        }
        // Create Company Card information 
        IPM_Company_Card__c globalCompanyCard = IPM_TestFactory_Helper.createGlobalCompanyCard(false);
        IPM_Company_Card__c regionalCompanyCard = IPM_TestFactory_Helper.createRegionalCompanyCard(false);
        IPM_Company_Card__c localCompanyCard = IPM_TestFactory_Helper.createLocalCompanyCard(false);
        
        List<IPM_Company_Card__c> companyCardList = new List<IPM_Company_Card__c>{globalCompanyCard,regionalCompanyCard,localCompanyCard};
        insert companyCardList;
        
         IPM_TestFactory_Helper.getProjectMasterData();
         
         projectList = IPM_TestFactory_Helper.projectSetUp(5,platformUser);
         
         updateProjectList =  NEW list<IPM_Project__c> ();
         
         System.runAs(platformUser)
         {
            for(Integer i = 0; i < projectList.size(); i++)
            {
                IPM_Project__c proj = projectList[i];
                proj.IPM_Market_Type__c = IPM_ConstantUtils.MARKETTYPE_DEVELOPED;
                proj.IPM_Fast_Track_Project__c = false;
                proj.IPM_Target_Launch_Dates__c = system.today().addMonths(6+i);
                updateProjectList.add(proj);
            }
           insert updateProjectList;
         }  
         system.assertEquals(5, [Select Id from IPM_Project__c limit 5].size(),'Projects are created');
         
      }
    
    public static void createTestData(){
        set<string> projIdSet = new set<string>();
        Set<String> projectNameSet = new Set<String>{'TestComments1','TestComments2','TestComments3','TestComments4','TestComments5'};
        projectDetailList = [Select Id,IPM_Phase__c,Name,IPM_Complexity__c,
                                                    (Select Id from Project_Documents__r),
                                                    (Select Id from IPM_Financials_Consolidated__r ),
                                                    (Select Id,Name,IPM_Task_Complexity__c,IPM_Project__c,IPM_Function__c,IPM_Section__c from Tasks__r),
                                                    (Select Id,Name,IPM_Phase__c from IPM_Milestones__r)
                                                  from IPM_Project__c where Name in:projectNameSet];
        
        list<IPM_Bosscard__c> ipmBosscardTestList = IPM_TestFactory_Helper.createIPMBosscardList(false, 5);
        
        for(Integer i = 0; i < ipmBosscardTestList.size(); i++){
            ipmBosscardTestList[i].IPM_Bosscard_Status__c = IPM_ConstantUtils.STATUS_IN_PROGRESS;
            ipmBosscardTestList[i].OwnerId = UserInfo.getUserId();
        }
        insert ipmBosscardTestList;
        
        System.Assert(ipmBosscardTestList[0].IPM_Bosscard_Status__c == IPM_ConstantUtils.STATUS_IN_PROGRESS, IPM_ConstantUtils.MSG_SHOULD_BE_SAME);
        
        
        ipmProjDocumentTestList = new list<IPM_Project_Document__c>();
        for(IPM_Project__c project : projectDetailList)
        {
            projIdSet.add(project.id);
            for(IPM_Project_Document__c  projDoc : project.Project_Documents__r)
            {
                ipmProjDocumentTestList.add(projDoc);       
            }
        }
        // Test Data
        Id mileMRecordType=Schema.SObjectType.IPM_Milestone__c.getRecordTypeInfosByName().get('IPM Project Milestones').getRecordTypeId();
        
        List<IPM_Milestone__c> ipmMileStoneTestList = IPM_TestFactory_Helper.createIPMMilestoneList(false, 5);
        
        for(Integer i = 0; i < ipmMileStoneTestList.size(); i++){
            ipmMileStoneTestList[i].IPM_No_Of_Days_for_Developing__c = '2' + i;
            ipmMileStoneTestList[i].IPM_Due_Date__c = system.today() + i;
            ipmMileStoneTestList[i].IPM_Type_of_Milestone__c = IPM_ConstantUtils.STANDARD;
            ipmMileStoneTestList[i].IPM_Name__c = 'Market Ready Gate Approval';
            ipmMileStoneTestList[i].recordtypeid = mileMRecordType;
            ipmMileStoneTestList[i].IPM_Project__c = projectDetailList[i].Id;
            ipmMileStoneTestList[i].IPM_Phase__c = projectDetailList[i].IPM_Phase__c;
        }
        insert ipmMileStoneTestList;
        system.assertEquals(5, [Select Id from IPM_Milestone__c limit 5].size(),'Milestones are created');
        
    }
    
    /***
    * @Description: Running Test Method
    */
    public static testmethod void IPM_MyProjectsTest()
    {
        User globalUser = [Select Id,LastName from User where LastName='PLATFORM_USER' limit 1];
        system.runAs(globalUser)
        {
            Test.startTest();
                createTestData();
                IPM_MyProjects ipmp = new IPM_MyProjects();
                new IPM_MyProjects(new IPM_HomePageController());
                ipmp.getProjects();
                System.Assert(ipmp.getProjects() != null,'Should not be null');
                new ApexPages.StandardController(ipmProjDocumentTestList[0]);
            Test.stopTest();
        }
      
    }
}