deploy/src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <label>IPM Project</label>
    
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document__c.object
<CustomObject>
    <description>THis is used in IPM to store Project documents</description>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>Relation to the Project Object</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Documents</relationshipLabel>
        <relationshipName>Project_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Project Document</label>
    <nameField>
        <label>Project Document Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/src/objects/IPM_Project_Document_Section__c.object
<CustomObject>
    <description>To be used in IPM project to store Gate Document Sections. It refers to the IPM Section object to pick what section/subsection it needs.</description>
    <fields>
        <fullName>IPM_Project_Document__c</fullName>
        <label>IPM Project Document</label>
        <referenceTo>IPM_Project_Document__c</referenceTo>
        <relationshipLabel>IPM Project Document Sections</relationshipLabel>
        <relationshipName>IPM_Project_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Project Document Section</label>
    <nameField>
        <label>Section Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Document Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/src/objects/IPM_Project_Document_Section_Content__c.object
<CustomObject>
    <description>This is used in IPM to hold section contents</description>
    <fields>
        <fullName>IPM_Project_Document_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IPM Project Document Section</label>
        <referenceTo>IPM_Project_Document_Section__c</referenceTo>
        <relationshipLabel>IPM Project Document Section Contents</relationshipLabel>
        <relationshipName>IPM_Section_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project Document Section Content</label>
    <nameField>
        <displayFormat>SecCon-{0000}</displayFormat>
        <label>Section Content Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Document Section Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

deploy/src/classes/IPM_ProjectDocSecContentTriggerHandler.cls
/****************************************************************************************************************************
@Author Cognizant
@name IPM_ProjectDocSecContentTriggerHandler
@CreateDate 28/11/2015
@Description Trigger Handler for the IPM_Project_Document_Section_Content__c SObject.
@Version 1.0
@reference  
*/

public with sharing class IPM_ProjectDocSecContentTriggerHandler {
	
	public static String CLASS_NAME = IPM_ProjectDocumentSectionContentHandler.class.getName();		    
    /********************************************************************************
    **@Description: Trigger context of BulkBefore Update
    **@param1 - list of IPM_Project_Document_Section_Content__c object records
    **********************************************************************************/
    
    public void UpdateRecordOwner(list<IPM_Project_Document_Section_Content__c> newprojDocSecConList, list<id>projDocSecIdList){
    	
    	map<id,IPM_Project_Document_Section__c> projDocSecmap;
    	
    	try{
    		projDocSecmap = new map<id,IPM_Project_Document_Section__c>([SELECT Id, IPM_Project_Document__r.IPM_Project__r.ownerid FROM IPM_Project_Document_Section__c where id IN: projDocSecIdList]);
    	}catch(Exception ex)
        {
           ExceptionLoggingHelper.createErrorLog(UserInfo.getUserId(),CLASS_NAME,'query',ex.getMessage(),ex, IPM_ConstantUtils.ERROR, null,null,null,null); 
        }	
    	
    	if(!projDocSecmap.isEmpty()){ 
	    	for(IPM_Project_Document_Section_Content__c seccon:newprojDocSecConList){
	    		if(projDocSecmap.containskey(seccon.IPM_Project_Document_Section__c)){
	    			seccon.ownerid= projDocSecmap.get(seccon.IPM_Project_Document_Section__c).IPM_Project_Document__r.IPM_Project__r.ownerid;
	    			system.debug('@@ Owner Id Updated ' + seccon.ownerid + ' @@ Project Owner Id  ' + projDocSecmap.get(seccon.IPM_Project_Document_Section__c).IPM_Project_Document__r.IPM_Project__r.ownerid );   			
	    		}	 	
	    	}
    	}
    }

}