src/objects/ACCL__Fund__c.object
<CustomObject>
    <fields>
        <fullName>ACCL__Amount__c</fullName>
        <label>Amount</label>
        <summarizedField>ACCL__Fund_Transaction_Row__c.ACCL__Amount__c</summarizedField>
        <summaryForeignKey>ACCL__Fund_Transaction_Row__c.ACCL__Target_Fund__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>UL_Available_to_Spend__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount - Uncommmitted - Committed</description>
        <label>Available to Spend</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{0000000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Fund_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ACCL__Amount__c</fullName>
        <description>Transaction Amount</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Source_Fund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Source fund for the transaction</description>
        <label>Source Fund</label>
        <referenceTo>ACCL__Fund__c</referenceTo>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Target_Fund__c</fullName>
        <description>Target fund for the transaction</description>
        <label>Target Fund</label>
        <referenceTo>ACCL__Fund__c</referenceTo>
        <relationshipName>Transactions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Transaction_Type__c</fullName>
        <formula>Text(ACCL__Fund_Transaction_Template__r.ACCL__Transaction_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Transaction Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UL_Status__c</fullName>
        <description>Status Field for Cross Category Transaction</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sent/Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Fund Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Fund Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UL_fundTransferAvalbToSpendUpdateHandler.cls
/***************************************************************
    Name: UL_fundTransferAvalbToSpendUpdateHandler()
    Copyright © 2016 Salesforce
    ======================================================
    Purpose:
    Handler class for UL_FundTransactionTrigger for IsInsert and Isafter.
    ======================================================
    History
    -------
    VERSION: 1.0                                         
    AUTHOR: Soumyodeep                   
    DATE: 06/12/2016
    DETAIL: INITIAL DEV
    Description:This handler class updates the Available to Spend field on the Funds when a Transfer transaction is created.
    Caveat: This calls is not marked with Sharing as the record modified in the trigger is locked by the Approval process, so this class needs to be executed in system context                                                           
*******************************************************************/
public without sharing class UL_fundTransferAvalbToSpendUpdateHandler{

private Static final String FUND_APPROVED_STATUS = 'Approved';
private Static final String FUND_TRANSFER_TRANSACTION = 'Transfer';

/*******************************************************************
Purpose: On Approval of the Cross Category transaction creates the related Fund Transaction rows record 
Version 1.0
Parameters: trigger.new(list of type ACCL__Fund_Transaction__c)
Returns: N/A
Throws N/A
********************************************************************/ 
public static void UL_fundTransferTransaction(list<ACCL__Fund_Transaction__c> transferTransactionList){

List<ACCL__Fund_Transaction_Row__c>listTransactionRow = new list<ACCL__Fund_Transaction_Row__c>();
set<id> fundIdSet=new set<id>();
ACCL__Fund__c sourceFund;
ACCL__Fund__c targetFund;


for(ACCL__Fund_Transaction__c createFundSetLoop:transferTransactionList){

       
    // Adding the source and the target fund ids to a set
       fundIdSet.add(createFundSetLoop.ACCL__Source_Fund__c);
       fundIdSet.add(createFundSetLoop.ACCL__Target_Fund__c);

}

 // Storing Fund records in a map
map<id, ACCL__Fund__c> FundRecordMap=new map<id, ACCL__Fund__c>([Select id, name, UL_Available_to_Spend__c from ACCL__Fund__c where id in:fundIdSet LIMIT:(Limits.getLimitQueryRows()-Limits.getQueryRows())]);


for(ACCL__Fund_Transaction__c transferTransactionLoop:transferTransactionList){

if(FUND_APPROVED_STATUS.equalsIgnoreCase(transferTransactionLoop.UL_Status__c) && FUND_TRANSFER_TRANSACTION.equalsIgnoreCase(transferTransactionLoop.ACCL__Transaction_Type__c) &&
   transferTransactionLoop.ACCL__Source_Fund__c!=null){
       
   //Fetching the Fund records
     sourceFund=FundRecordMap.get(transferTransactionLoop.ACCL__Source_Fund__c);
     targetFund=FundRecordMap.get(transferTransactionLoop.ACCL__Target_Fund__c);
     
   //Updating the Available To Spend on the Source and the Target Fund
     sourceFund.UL_Available_to_Spend__c=sourceFund.UL_Available_to_Spend__c-transferTransactionLoop.ACCL__Amount__c;
     targetFund.UL_Available_to_Spend__c=targetFund.UL_Available_to_Spend__c+transferTransactionLoop.ACCL__Amount__c;
     
   FundRecordMap.put(sourceFund.id, sourceFund);
   FundRecordMap.put(targetFund.id, targetFund);
   }
   
}

    try{
    
    database.update(FundRecordMap.values());
    }
    catch(Exception ex){
        UL_Utility.logError(ex, UserInfo.getUserId());
    }
}

}