src/objects/ACCL__Promotion__c.object
<CustomObject>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Decides whether a promotion is available.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to promotion template.</description>
        <label>Promotion Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Promotion_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Promotion_Template__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <formula>TEXT (ACCL__Promotion_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UL_Current_Status__c</fullName>
        <label>Current Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banded Pack Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UL_Finance_Check_Approvers__c</fullName>
        <label>Finance Check Approvers</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UL_Free_Text__c</fullName>
        <label>Free Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UL_Manager_Check_Approvers__c</fullName>
        <label>Manager Check Approvers</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UL_ThresholdViolated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Threshold Violated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UL_Threshold_Window_Result__c</fullName>
        <label>Threshold Window Result</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <!---->
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Promotion_Template__c.object
<CustomObject>
    <description>Template for the creation of a promotion.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the template active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
   <!---->
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <globalPicklist>ACCL__Sales_Org</globalPicklist>
        <label>Sales Org</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UL_Approval_Process_Identifier__c</fullName>
        <description>Approval Process Identifier</description>
        <label>Approval Process Identifier</label>
        <picklist>
            <picklistValues>
                <fullName>AccountSpecificWorkflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ParentBandedPackWorkflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ParentWorkflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ChildWorkflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ParentPastDatedUrgentWorkflow</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Promotion Template</label>
    <nameField>
        <label>Promotion Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
    <!---->
    <!---->
</CustomObject>

src/classes/UL_InboundEmailHandler.cls
/***************************************************************
Name: UL_InboundEmailHandler
Copyright © 2016 Accenture
======================================================
Purpose:
Utility class for processing inbound emails related to Approval Process (functionally known as Workflow)
======================================================
History
-------
VERSION     AUTHOR        DATE           DETAIL                 Description
1.0         Badri         1/1/2016      INITIAL DEV            
***************************************************************/
global without sharing class UL_InboundEmailHandler implements Messaging.InboundEmailHandler {    
    //class level variables
    public final static String APPROVE = 'approve' ;
    public final static String REJECT = 'reject' ;
    public final static String STR_YES = 'yes' ;
    public final static String STR_NO = 'no' ;
    public final static String PROM_NAME_FORMAT = 'P-' ; 
    public final static String ENTER_CHAR = '\n' ;  
    /*******************************************************************
    Purpose: 1. Processes inbound email body, looks for Promotion Name using string functions, queries DB with the promotion Name.
            2.  Uses string functions to look for Approve/Reject in the email body, calls respective function to approve/reject the Workflow.
            3. Approve/Reject terms accepted - approve,yes,reject,no 
    Version 1.0
    Parameters: Messaging.InboundEmail, Messaging.InboundEnvelope  
    Returns: Messaging.InboundEmailResult
    Throws : N/A 
    ********************************************************************/ 
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {        
        //function variables
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();       
        List<ACCL__Promotion__c> promoLst = new List<ACCL__Promotion__c>() ;
        
        try{        
            //fetch email body
            String body = email.plainTextBody ;
            system.debug('body '+body) ;
            //fetch email subject
            String subject = email.subject ;
            system.debug('subject '+subject) ;
            //fetch Promotion Name from email subject
            Integer promoNameIndex = subject.indexOf(PROM_NAME_FORMAT) ;
            system.debug('promoNameIndex '+promoNameIndex) ;
            String promoName = subject.substring(promoNameIndex, promoNameIndex+10) ;
            system.debug('promoName '+promoName) ;
            
            //fetch promotion details from DB with Promotion Name
            promoLst = [SELECT UL_PromotionTemplateType__c, UL_Threshold_Window_Result__c,Id, Name, CreatedById,createdby.UL_Finance_Manager__c,UL_Current_Status__c,UL_ThresholdViolated__c, UL_Finance_Check_Approvers__c,UL_Manager_Check_Approvers__c,ACCL__Date_From__c,ACCL__Date_Thru__c,ACCL__Promotion_Template__r.UL_Approval_Process_Identifier__c, ACCL__Sales_Org__c, ACCL__Active__c, ACCL__Promotion_Template__c 
            FROM ACCL__Promotion__c WHERE Name =: promoName LIMIT 1] ;
            system.debug('promoLst '+promoLst) ;        
            
            /*get: 1. 1st line from email body - which would give Approve/Reject
            2. 2nd line from email body - which would give approval/rejection comments.*/
            String[] myStrings = new String[2]; 
            myStrings = body.split(ENTER_CHAR);
            body = myStrings[0] ;
            String comments = myStrings[1] ;
            
            //if email response is approve, call respective function of UL_PromotionWorkflowService class to approve the Workflow.
            if(body.containsIgnoreCase(APPROVE) || body.containsIgnoreCase(STR_YES)){
                UL_PromotionWorkflowService.approveWorkflow(promoLst[0].Id, promoLst,promoLst[0].UL_Current_Status__c,true) ;
                //update comments
                ACCL__Promotion__c promoObj = new ACCL__Promotion__c() ;
                promoObj.id = promoLst[0].id ;
                promoObj.UL_Free_Text__c = comments ;
                update promoObj ;
            }
            
            //if email response is reject, call respective function of UL_PromotionWorkflowService class to reject the Workflow.
            if(body.containsIgnoreCase(REJECT) || body.containsIgnoreCase(STR_NO)){
                UL_PromotionWorkflowService.rejectWorkflow(promoLst[0].Id, promoLst, true) ;
                //update comments
                ACCL__Promotion__c promoObj = new ACCL__Promotion__c() ;
                promoObj.id = promoLst[0].id ;
                promoObj.UL_Free_Text__c = comments ;
                update promoObj ;
            }
        }
        catch(Exception ex){
            throw ex;
            UL_Utility.logError(ex, UserInfo.getUserId());
        }        
        return result; //
    }
}