src/objects/ACCL__Fund__c.object
<CustomObject>
    <fields>
        <fullName>ACCL__Anchor_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Anchor Product</label>
        <referenceTo>ACCL__Product__c</referenceTo>
        <relationshipLabel>Funds</relationshipLabel>
        <relationshipName>Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Fund_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fund Template</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>ACCL__Fund_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Fund_Template__c</referenceTo>
        <relationshipLabel>Funds</relationshipLabel>
        <relationshipName>Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <formula>TEXT( ACCL__Fund_Template__r.ACCL__Sales_Org__c )</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <label>Valid Thru</label>
        <type>Date</type>
    </fields>
    <label>Fund</label>
    <nameField>
        <displayFormat>F-{0000000}</displayFormat>
        <label>Fund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Fund_Template__c.object
<CustomObject>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determines whether the template is active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Type__c</fullName>
        <description>Specifies the anchor type of the fund.</description>
        <label>Anchor Type</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Product</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <globalPicklist>ACCL__Sales_Org</globalPicklist>
        <label>Sales Org</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ACCL__Sort__c</fullName>
        <description>Sort number</description>
        <label>Sort</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Fund Template</label>
    <nameField>
        <label>Fund Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Product__c.object
<CustomObject>
    <description>ACSF - Custom Product object</description>
    <fields>
        <fullName>ACCL__Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Accumulators</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cigarettes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Detergent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frozen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HouseholdGoods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Snacks</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Valid_From__c</fullName>
        <description>Begin of the validity period for the product state &quot;Delivery&quot;</description>
        <label>Delivery Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Valid_Thru__c</fullName>
        <defaultValue>date(12,31,2099)</defaultValue>
        <description>End of the validity period for the product state &quot;Delivery&quot;</description>
        <label>Delivery Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_1_Language_1__c</fullName>
        <description>Holds the description 1 of language 1</description>
        <label>Description 1 Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Field_Valid_From__c</fullName>
        <description>Begin of the validity period for the product state &quot;Field&quot;</description>
        <label>Field Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Field_Valid_Thru__c</fullName>
        <defaultValue>date(12,31,2099)</defaultValue>
        <description>End of the validity period for the product state &quot;Field&quot;</description>
        <label>Field Valid Thru</label>
        <type>Date</type>
    </fields>
   <!-- <fields>
        <fullName>ACCL__Fund_Valid_From__c</fullName>
        <description>Fund Role status valid from date.</description>
        <label>Fund Role Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Fund_Valid_Thru__c</fullName>
        <description>Fund Role status valid thru date.</description>
        <label>Fund Role Valid Thru</label>
        <type>Date</type>
    </fields>-->
    <fields>
        <fullName>ACCL__KAM_Valid_From__c</fullName>
        <description>Begin of the validity period for the product state &quot;KAM&quot;</description>
        <label>KAM Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__KAM_Valid_Thru__c</fullName>
        <defaultValue>date(12,31,2099)</defaultValue>
        <description>End of the validity period for the product state &quot;KAM&quot;</description>
        <label>KAM Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__New_Item_Valid_From__c</fullName>
        <description>Begin of the validity period for the product state &quot;New Item&quot;</description>
        <label>New Item Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__New_Item_Valid_Thru__c</fullName>
        <defaultValue>date(12,31,2099)</defaultValue>
        <description>End of the validity period for the product state &quot;New Item&quot;</description>
        <label>New Item Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Product_Code__c</fullName>
        <description>Unique Identification of product</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Product_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Template__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <formula>TEXT(ACCL__Product_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
   <!---->
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Private</sharingModel>
    <!---->
</CustomObject>

src/objects/ACCL__Product_Template__c.object
<CustomObject>
    <description>ACSF - Template for ACSF Products</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Product Template is a sales org enabled object</description>
        <globalPicklist>ACCL__Sales_Org</globalPicklist>
        <label>Sales Org</label>
        <type>Picklist</type>
    </fields>
    <label>Product Template</label>
    <nameField>
        <label>Product Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UL_UserCustomerProduct__c.object
<CustomObject>
    <fields>
        <fullName>AccessType__c</fullName>
        <description>Defines user access type - Read/Write</description>
        <label>AccessType</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Write</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>ACCL__Product__c</referenceTo>
        <relationshipLabel>User Customer Product Categorysies</relationshipLabel>
        <relationshipName>User_Customer_Product_Categorysies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Customer_Product_Categorysies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Customer Product Category</label>
    <nameField>
        <label>User Customer Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Customer Product Categorysies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UL_FundShareTest.cls
/**
 * @author          Devesh Murdiya
 * @version         1.0
 * @date            12/15/2016
 * @description     Test class for Fund Share
 */
@isTest
private class UL_FundShareTest {    
    /**
    * @author           Devesh Murdiya
    * @version          1.0
    * @date             12/15/2016
    * @description      Method to call FundshareTrigger handler class and UserCustomerTriggerHandler class
    */
    static testMethod void createfundShare() {
        test.starttest();
        /*User Record Creation*/
        Profile p = [select id from profile where name='System Administrator' Limit 1];                
        User u = new User(FirstName = 'test1',LastName = 'of Arendelle',Email = 'elsa@disney.com', Alias = 'elsa1',Username  = 'test1@disney.com',LocaleSidKey= 'en_US', TimeZoneSidKey='America/Los_Angeles',ProfileID=  p.id,LanguageLocaleKey = 'en_US',EmailEncodingKey  = 'UTF-8');
        User u1 = new User(FirstName = 'test2',LastName = 'of Arendelle1',Email = 'elsa1@disney.com', Alias = 'elsa2',Username  = 'test2@disney.com',LocaleSidKey= 'en_US', TimeZoneSidKey='America/Los_Angeles',ProfileID=  p.id,LanguageLocaleKey = 'en_US',EmailEncodingKey  = 'UTF-8'); 
        insert u;
        insert u1;
        
        /*Product Template Creation*/
        ACCL__Product_Template__c prodTemp = new ACCL__Product_Template__c();
        prodTemp.Name = 'testShareProductTeamp';
        prodTemp.ACCL__Description_Language_1__c = 'TestEnglish';
        //prodTemp.ACCL__Sales_Org__c = 'AR01';
        insert prodTemp;
        
        /*Product Record Creation*/
        ACCL__Product__c product = new ACCL__Product__c();
        product.Name = 'testShareProd';        
        product.ACCL__Description_1_Language_1__c = 'testdescription';
        product.ACCL__Product_Code__c = 'testProductCode';
        product.ACCL__Product_Template__c = prodTemp.Id;
        product.ACCL__Field_Valid_From__c=System.today();
        product.ACCL__Field_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__Delivery_Valid_From__c=System.today();
        product.ACCL__Delivery_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__KAM_Valid_From__c=System.today();
        product.ACCL__KAM_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__New_Item_Valid_From__c=System.today();
        product.ACCL__New_Item_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__Fund_Valid_From__c=System.today();
        product.ACCL__Fund_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__Category__c = null;
        insert product;
        
        /*Fund Template Creation*/
        ACCL__Fund_Template__c fundTemplate = new ACCL__Fund_Template__c();
        fundTemplate.Name = 'testfundTemaplate'; 
        fundTemplate.ACCL__Active__c = True;
        fundTemplate.ACCL__Anchor_Type__c= 'Customer Product';
        fundTemplate.ACCL__Description_Language_1__c ='English';
        fundTemplate.ACCL__Sort__c= 1  ;        
        insert fundTemplate;
        
        /*Fund Record Creation*/
        ACCL__Fund__c fundRecord = new ACCL__Fund__c(); 
        ACCL__Fund__c fundRecord2 = new ACCL__Fund__c();
        fundRecord.ACCL__Anchor_Product__c=product.id;        
        fundRecord.ACCL__Fund_Template__c=fundTemplate.id;
        fundRecord.ACCL__Status__c='Active';
        fundRecord.ACCL__Valid_From__c=System.today();
        fundRecord.ACCL__Valid_Thru__c=System.today().addMonths(5);                
        insert fundRecord;
        
        /*UserCustomerProduct Record Creation*/
        List<UL_UserCustomerProduct__c> lstUsCus = new List<UL_UserCustomerProduct__c>();
        UL_UserCustomerProduct__c userCPobj = new UL_UserCustomerProduct__c();
        userCPobj.AccessType__c = 'Read';
        userCPobj.Product__c = product.id;
        userCPobj.User__c = u.id;
        lstUsCus.add(userCPobj);
        
        UL_UserCustomerProduct__c userCPobj1 = userCPobj.clone(false,false,false,false);
        userCPobj1.User__c = u1.id;
        lstUsCus.add(userCPobj1);
        insert lstUsCus;
        
        /*Fund Record Creation*/
        fundRecord2 = fundRecord.clone(false,false,false,false);
        insert fundRecord2;             
        
        test.stoptest();
        
    }    
    
    /**
    * @author           Devesh Murdiya
    * @version          1.0
    * @date             12/15/2016
    * @description      Method to call FundshareTrigger handler class and UserCustomerTriggerHandler class
    */
    static testMethod void deletefundShare() {
        test.starttest();
        /*User Record Creation*/
        Profile p = [select id from profile where name='System Administrator' Limit 1];                
        User u = new User(FirstName = 'test1',LastName = 'of Arendelle',Email = 'elsa@disney.com', Alias = 'elsa1',Username  = 'test1@disney.com',LocaleSidKey= 'en_US', TimeZoneSidKey='America/Los_Angeles',ProfileID=  p.id,LanguageLocaleKey = 'en_US',EmailEncodingKey  = 'UTF-8');
        User u1 = new User(FirstName = 'test2',LastName = 'of Arendelle1',Email = 'elsa1@disney.com', Alias = 'elsa2',Username  = 'test2@disney.com',LocaleSidKey= 'en_US', TimeZoneSidKey='America/Los_Angeles',ProfileID=  p.id,LanguageLocaleKey = 'en_US',EmailEncodingKey  = 'UTF-8'); 
        insert u;
        insert u1;
        
        /*Product Template Creation*/
        ACCL__Product_Template__c prodTemp = new ACCL__Product_Template__c();
        prodTemp.Name = 'testShareProductTeamp';
        prodTemp.ACCL__Description_Language_1__c = 'TestEnglish';        
        insert prodTemp;
        
        /*Product Record Creation*/
        ACCL__Product__c product = new ACCL__Product__c();
        product.Name = 'testShareProd';        
        product.ACCL__Description_1_Language_1__c = 'testdescription';
        product.ACCL__Product_Code__c = 'testProductCode';
        product.ACCL__Product_Template__c = prodTemp.Id;
        product.ACCL__Field_Valid_From__c=System.today();
        product.ACCL__Field_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__Delivery_Valid_From__c=System.today();
        product.ACCL__Delivery_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__KAM_Valid_From__c=System.today();
        product.ACCL__KAM_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__New_Item_Valid_From__c=System.today();
        product.ACCL__New_Item_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__Fund_Valid_From__c=System.today();
        product.ACCL__Fund_Valid_Thru__c = System.today().addMonths(5);
        product.ACCL__Category__c = null;
        insert product;
        
        /*Fund Template Creation*/
        ACCL__Fund_Template__c fundTemplate = new ACCL__Fund_Template__c();
        fundTemplate.Name = 'testfundTemaplate'; 
        fundTemplate.ACCL__Active__c = True;
        fundTemplate.ACCL__Anchor_Type__c= 'Customer Product';
        fundTemplate.ACCL__Description_Language_1__c ='English';
        fundTemplate.ACCL__Sort__c= 1  ;
        //fundTemplate.ACCL__Sales_Org__c = 'AR01';
        insert fundTemplate;
        
        /*Fund Record Creation*/
        ACCL__Fund__c fundRecord = new ACCL__Fund__c(); 
        ACCL__Fund__c fundRecord2 = new ACCL__Fund__c();
        fundRecord.ACCL__Anchor_Product__c=product.id;        
        fundRecord.ACCL__Fund_Template__c=fundTemplate.id;
        fundRecord.ACCL__Status__c='Active';
        fundRecord.ACCL__Valid_From__c=System.today();
        fundRecord.ACCL__Valid_Thru__c=System.today().addMonths(5);                
        insert fundRecord;
        
        /*UserCustomerProduct Record Creation*/
        List<UL_UserCustomerProduct__c> lstUsCus = new List<UL_UserCustomerProduct__c>();
        UL_UserCustomerProduct__c userCPobj = new UL_UserCustomerProduct__c();
        userCPobj.AccessType__c = 'Read';
        userCPobj.Product__c = product.id;
        userCPobj.User__c = u.id;
        lstUsCus.add(userCPobj);
        
        UL_UserCustomerProduct__c userCPobj1 = userCPobj.clone(false,false,false,false);
        userCPobj1.User__c = u1.id;
        lstUsCus.add(userCPobj1);
        
        insert lstUsCus;
                
        /*Fund Share Record*/
        ACCL__Fund__share fundshare = new ACCL__Fund__share();
        fundshare.parentid = fundRecord.id;
        fundshare.userorgroupid = u.id;
        fundshare.accesslevel = 'Read';
        insert fundshare;
        
        /*Delete the UserCustomerProduct record*/
        delete lstUsCus;
        test.stoptest();
        
        
    }
    
}