src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <fields>
        <fullName>Segment__c</fullName>
        <description>Purpose : This field describes the operator segment (important for reporting)
Data Source : SAP | Integration : Mule | Security Level : Restricted</description>
        <label>Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cruise Travel Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Healthcare BusInd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Foodservice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Caterers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pubs/Bars/Entertaining center/Caffee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Take Away</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canteens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesalers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QSR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A-Center Led</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-Local Led</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Liquidator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D-Redistribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Office Coffee System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F-Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-C Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H-Retail Food Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-Meal Replacement Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M-Manufacturers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O-Operator/Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R-Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S-C&amp;C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubSegment__c</fullName>
        <description>Purpose : The value of this field are depended from Operator Segment
Data Source : SAP | Integration : Mule | Security Level : Restricted</description>
        <label>Sub Segment</label>
        <picklist>
            <controllingField>Segment__c</controllingField>
            <picklistValues>
                <fullName>QSR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Casual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casual Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid-Scale Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fine Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cruise Lines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports &amp; Leisure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business &amp; Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (C&amp;U)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (K-12)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare/Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Living</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C Stores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supermarkets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi Segment Contract Caterer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workplace Canteens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FS_CHD_GFCCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store GFCCode and subsegment value from CHD</description>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>FS CHD GFCCode</label>
</CustomObject>

src/classes/FS_CHDUtilityTest.cls
/**********************************************************************
Purpose: Test class for FS_CHDUtility.
History :
VERSION           AUTHOR              DATE                         DETAIL Description
1.0              Accenture        2/December/2016                       Created
***********************************************************************/
@isTest
private class FS_CHDUtilityTest {
   private static testMethod void CHDTest (){
       FS_UtilTestDataSetup testData=new FS_UtilTestDataSetup();
       User testUser=testData.createTestUser();        
       system.runAs(testUser){
           FS_CHD_GFCCode__c cust= new FS_CHD_GFCCode__c(Name='3380',Segment__c='Club, Cash & Carry');
           insert cust;
               FS_CHD_GFCCode__c cust1= new FS_CHD_GFCCode__c();
               List<Account> acclist = new  List<Account>() ;
               List<Account> accounts = new List<Account>();
               Account acclistTemp1 = new Account();
               List<string> strList = new List<String>();
               RecordType rt=[select id,name from RecordType where SObjectType='Account'and Name='Operator'];
               Test.startTest(); 
                  acclist= new List<Account>();
                  Account acc1 = new Account();
                  acc1.name = 'FS Test Acc1';
                  acc1.RecordTypeId = rt.Id;
                  acc1.SubSegment__c='3380. Stores';
                  acclist.add(acc1);
                  insert acclist;
               Test.stopTest();
                     
          }
          }
          private static testMethod void CHDTesttwo (){
          FS_UtilTestDataSetup testData=new FS_UtilTestDataSetup();
          User testUser=testData.createTestUser();        
       system.runAs(testUser){
           FS_CHD_GFCCode__c cust= new FS_CHD_GFCCode__c(Name='3380',Segment__c='Club, Cash & Carry');
           insert cust;
           RecordType rt=[select id,name from RecordType where SObjectType='Account'and Name='Operator'];
          List<Account> newacclist = new  List<Account>() ;
           Account acc2 = new Account();
                  acc2 .name = 'FS Test Acc1';
                  acc2 .RecordTypeId = rt.Id;
                  acc2 .SubSegment__c='3380. Stores';
                  newacclist.add(acc2 );
                  insert newacclist;
          FS_CHDUtility.getsegment(newacclist );
          }
          }
          }