src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>A rostered agency</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Agency_Estimate__c.object
<CustomObject>
    <description>Will represent an agency base fee estimate for a particular brand and agency combination</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <description>AgencyFee#GLOBAL#Created for the sharing Rules, To share Agency estimates related data to corresponding agency. Value will be populated using a trigger.</description>
        <label>Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store brand estimate.</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Agency Estimates</relationshipLabel>
        <relationshipName>Agency_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Fiscal year.</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AgencyFee#GLOBAL#To know whether the record is locked or not.</description>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand Name</description>
        <formula>AF_Brand_Estimate__r.Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <label>Agency Estimate</label>
    <nameField>
        <label>Agency Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Matrix__c.object
<CustomObject>
    <description>Will represent an Agencies annual bonus results on an entity level</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store brand estimate.</description>
        <label>Brand Estimate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Fiscal year.</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand Name</description>
        <formula>AF_Bonus_Results__r.AF_Bonus_Thresholds__r.AF_Brand_Estimate__r.Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <label>Bonus Matrix</label>
    <nameField>
        <label>Bonus Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Results__c.object
<CustomObject>
    <description>Will represent the quantitative and qualitative quarterly and annual bonus figures. There can be one or more bonus input records associated to one brand estimate</description>
    <fields>
        <fullName>AF_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AgencyFee#GLOBAL#To store the status for Bonus Results</description>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Bonus Results</label>
    <nameField>
        <displayFormat>BR-{00000000}</displayFormat>
        <label>Bonus Results Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Summary__c.object
<CustomObject>
    <description>It Will represent a Unilever Bonus Fee estimate for a particular brand, fiscal year and agency combination.</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the Agency name / id</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bonus Summaries</relationshipLabel>
        <relationshipName>Bonus_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>Stores fiscal year</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bonus Summary</label>
    <nameField>
        <label>Bonus Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Threshold__c.object
<CustomObject>
    <description>Will represent the threshold bonus targets for a brand estimate. There can be one or more thresholds per brand estimate, on a country by country basis.</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To Store the values for Brand Estimate</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Bonus Thresholds</relationshipLabel>
        <relationshipName>Bonus_Thresholds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bonus Threshold</label>
    <nameField>
        <label>Bonus Threshold Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Thresholds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>AgencyFee#GLOBAL#To check state of Brand Estimate</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers1__c</fullName>
        <description>Holds Email address of agency user. Used for sending notifications to</description>
        <label>AF_AgencyUsers1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store Agencies associated to account</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Copied__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the base fee has been copied - Raise new PO / Batch Process or Created Manually</description>
        <label>Copied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To the fiscal year details</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Base fee is locked in approval process</description>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Status_Base_Fees__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Status for Base Fees</description>
        <label>Status Base Fees</label>
        <picklist>
            <picklistValues>
                <fullName>Initiate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency (Draft)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With CMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Controller Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Bonus Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store the Brands associated to Brand Estimate</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Category_Brand__c.object
<CustomObject>
    <description>Used to store Categories and associated brands related to Agency Fee Application.</description>
    <fields>
        <fullName>AF_Category_Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To associate brands to corresponding Categories</description>
        <label>Category</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Category-Brands</relationshipLabel>
        <relationshipName>Category_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Category-Brands</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category-Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AF_Currency__c.object
<CustomObject>
    <description>Will represent exchange and spot rate figures for all the world currencies</description>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To Store the date when currency uploaded</description>
        <label>Upload Date</label>
        <type>Date</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Currency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AF_Entity__c.object
<CustomObject>
    <description>Will represent the geographic working area where Unilever or an agency is operating. There will be 2 record types, one for Unilever Entities and one for Agency Entities</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate Entity with Agency</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entity</relationshipLabel>
        <relationshipName>Entity</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AF_OOPS_Actual__c.object
<CustomObject>
    <description>Will represent the actual quarterly expenses recorded by an agency for a particular brand</description>
    <fields>
        <fullName>AF_AgencyUsers1__c</fullName>
        <description>Email address for Agency User</description>
        <label>AgencyUsers1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_year__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Fiscal year.</description>
        <label>Fiscal year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OOPS Actual</label>
    <nameField>
        <label>OOPS Actual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OOPS Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_OOPS_Estimate__c.object
<CustomObject>
    <description>Will represent the out of pocket expense estimation agreed upon between Unilever and an agency for a particular brand</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate OOPs Estimate to brand estimates</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>OOPS Estimates</relationshipLabel>
        <relationshipName>OOPS_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To store the fiscal year related values</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AgencyFee#GLOBAL#To check the status for OOPs Estimate</description>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_OOPS_Actual__c</fullName>
        <description>Parent record of oops estimate</description>
        <label>OOPS Actual</label>
        <referenceTo>AF_OOPS_Actual__c</referenceTo>
        <relationshipLabel>OOPS Estimates</relationshipLabel>
        <relationshipName>OOPS_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OOPS Estimate</label>
    <nameField>
        <label>OOPS Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OOPS Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AF_BonusMatrixOverrideController_Test.cls
/*****************************************************************************************************************************
@Author :Cognizant
@name : AF_BonusMatrixOverrideController_Test
@CreateDate : 29/9/2014
@Description : This is a Test class for AF_BonusMatrixOverrideController class, 
@Version : 1.0
@reference : none
****************************************************************************************************************************/
@isTest(SeeAlldata=false)
public class AF_BonusMatrixOverrideController_Test
{  
    Static Integer IcurrYear = System.Today().year();
    Static string currYear=string.valueof(IcurrYear);
    static user userforBonusMatrixOverride;
    private static string CHPARENTID='CHParentId';
    private static string ID='id';
    /***********************************************************************************
*  @Description: this method will the test data
*  @name : AF_bonusMatrixOverrideController
*  @param : none.
*  @return: none.
*************************************************************************************/
    Static testMethod void AF_bonusMatrixOverrideController()
    {
        Test.startTest();
        userforBonusMatrixOverride=AF_TestFactory_Helper.createuser(true);
        User u=[SELECT id,Email FROM user WHERE id=:userforBonusMatrixOverride.id LIMIT 1];
        System.runAs(u)
        { 
            //Insert Account
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,false);
            List<Account> accLst = new List<Account>();
            for(Account ac: acc){
                ac.published__c=true;
                accLst.add(ac);
            }
            insert accLst;
            List<Account> acctQuery = [SELECT id FROM account LIMIT 1];
            System.Assert(acctQuery[0].Id != null, AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,true);
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE and Id IN:AFCategoryBrand LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.BRAND_RECORD);
            //Insert BrandEstimate
            List<AF_Brand_Estimate__c> BrandEst = AF_TestFactory_Helper.insertAFBrandEstList(1,false);
            List<AF_Brand_Estimate__c> BrandEstLSt = new List<AF_Brand_Estimate__c>();
            for(AF_Brand_Estimate__c brst : BrandEst){
                brst.AF_Status_Base_Fees__c=AF_Constants.BASE_FEES_READYFORPO;  
                brst.AF_Fiscal_Year__c=currYear;
                brst.AF_Active__c = true;
                brst.AF_Copied__c= false;
                brst.AF_Locked__c = false;  
                brst.AF_AgencyUsers1__c=u.Email;
                BrandEstLSt.add(brst);
            }
            insert BrandEstLSt;
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c where Id IN:BrandEstLSt LIMIT 1]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRANDESTIMATE_RECORD);
            //Insert Currency
            List<AF_Currency__c> AFCurrency = AF_TestFactory_Helper.insertAFcurrencyList(1,true);
            List<AF_Currency__c> AFCurrencyQuery = [SELECT Id FROM AF_Currency__c where Id IN:AFCurrency LIMIT 1];
            System.Assert(AFCurrencyQuery[0].Id != null, AF_TestFactory_Helper.CURRENCY_RECORD);
            //insert OOPS Actual.
            List<AF_OOPS_Actual__c> OopsactualList = AF_TestFactory_Helper.insertOOPSActual(1,true);
            List<AF_OOPS_Actual__c> OopsactualListQuery = [SELECT ID,AF_Agency__c FROM AF_OOPS_Actual__c WHERE ID IN : OopsactualList LIMIT 1];
            System.assertEquals(OopsactualListQuery[0].AF_Agency__c, acc[0].id,AF_TestFactory_Helper.OOPSACTUCAL_RECORD);
            //Insert Agency Entity
            List<AF_Entity__c> AFEntity = AF_TestFactory_Helper.insertAgencyEntityList(1,true);
            List<AF_Entity__c> AFEntityQuery = [SELECT AF_Agency__c FROM AF_Entity__c where RecordTypeId=:AF_TestFactory_Helper.AF_AGENCY_ENTITY_RECTYPE and Id IN:AFEntity LIMIT 1];
            System.assertEquals(AFEntity[0].AF_Agency__c, acc[0].id,AF_TestFactory_Helper.AGENCY_ENTITY);
            //Insert Unilever Entity
            List<AF_Entity__c> AFUnileverEntity = AF_TestFactory_Helper.insertUnileverEntityListRec(1,true);
            List<AF_Entity__c> AFUnileverEntityQuery = [SELECT Id FROM AF_Entity__c where RecordTypeId=:AF_TestFactory_Helper.AF_UNILIVER_ENTITY_RECTYPE and Id IN:AFUnileverEntity LIMIT 1];
            System.Assert(AFUnileverEntityQuery[0].Id != null, AF_TestFactory_Helper.UNILEVER_ENTITY);
            //Insert Agency Estimate.
            List<AF_Agency_Estimate__c> AgencyEsitmate = AF_TestFactory_Helper.insertAgencyEstimate(1,false);
            List<AF_Agency_Estimate__c> AgencyEsitmateLst = new  List<AF_Agency_Estimate__c>();
            for(AF_Agency_Estimate__c agency : AgencyEsitmate){
                agency.AF_Status__c =AF_Constants.BASE_FEES_WITH_AGENCY;
                agency.AF_Fiscal_Year__c=currYear;
                agency.AF_Adaptation__c=22;
                agency.AF_Digital__c=22;
                agency.AF_Traditional__c=22;
                AgencyEsitmateLst.add(agency);
            }
            insert AgencyEsitmateLst;
            List<AF_Agency_Estimate__c> AgencyQuery = [SELECT Id ,AF_Brand_Estimate__c FROM AF_Agency_Estimate__c WHERE ID IN : AgencyEsitmate limit 1];
            System.assertEquals(AgencyQuery[0].AF_Brand_Estimate__c, BrandEst[0].id,AF_TestFactory_Helper.AGENCYESTIMATE_RECORD);
            //Insert OOPS Estimate.
            List<AF_OOPS_Estimate__c> OOPSEstimateList = AF_TestFactory_Helper.InsertOOPsEstimate(1,true);
            List<AF_OOPS_Estimate__c> OOPSEstimateListQuery =[SELECT ID,AF_OOPS_Actual__c FROM AF_OOPS_Estimate__c WHERE ID IN :OOPSEstimateList LIMIT 1];
            System.assertEquals(OOPSEstimateListQuery[0].AF_OOPS_Actual__c, OopsactualList[0].id,AF_TestFactory_Helper.OOPSESTIMATE_RECORD);
            //Insert Bonus Summary
            List<AF_Bonus_Summary__c> AFBonusSummary = AF_TestFactory_Helper.insertBonusSummary(1,true);
            List<AF_Bonus_Summary__c> AFBonusSummaryQuery = [Select AF_Agency__c from AF_Bonus_Summary__c where Id IN:AFBonusSummary LIMIT 1];
            System.assertEquals(AFBonusSummaryQuery[0].AF_Agency__c,acc[0].id, AF_TestFactory_Helper.BONUSSUMMARY_RECORD);
            //Insert Bonus Threshold
            List<AF_Bonus_Threshold__c> BonusThreshold =  AF_TestFactory_Helper.insertBonusThreshhold(1,true);
            List<AF_Bonus_Threshold__c> BonusThresholdQuery = [Select Agency_Name__c from AF_Bonus_Threshold__c where Id IN:BonusThreshold LIMIT 1];
            System.assertEquals(BonusThresholdQuery[0].Agency_Name__c,acc[0].id, AF_TestFactory_Helper.BONUSTHERSHOLD_RECORD);
            //Insert Bonus Results 
            List<AF_Bonus_Results__c> AFBonusRes = AF_TestFactory_Helper.insertBonusResults(1,true);
            List<AF_Bonus_Results__c> AFBonusResQuery = [Select AF_Bonus_Thresholds__c from AF_Bonus_Results__c where Id IN:AFBonusRes LIMIT 1];
            System.assertEquals(AFBonusResQuery[0].AF_Bonus_Thresholds__c,BonusThresholdQuery[0].id, AF_TestFactory_Helper.BONUSRESULT_RECORD);
            //Insert Bonus Matrix
            List<AF_Bonus_Matrix__c> AFBonusMat = AF_TestFactory_Helper.insertBonusMatrix(1,false);
            List<AF_Bonus_Matrix__c> AFBonusMatLst = new List<AF_Bonus_Matrix__c>();
            for(AF_Bonus_Matrix__c bm : AFBonusMat){
                bm.AF_Value__c=decimal.valueOf(5500);
                bm.AF_Base_Fee_Country_Total__c =35353;
                bm.AF_BonusableFee__c=86588;  
                AFBonusMatLst.add(bm);
            }
            insert AFBonusMatLst;
            List<AF_Bonus_Matrix__c> AFBonusMatQuery = [Select AF_Bonus_Results__c from AF_Bonus_Matrix__c where Id IN:AFBonusMat LIMIT 1];
            System.assertEquals(AFBonusMatQuery[0].AF_Bonus_Results__c,AFBonusResQuery[0].id, AF_TestFactory_Helper.BONUSMATRIX_RECORD);
            ApexPages.currentPage().getParameters().put(ID,AFBonusMatLst[0].id);
            AF_BonusMatrixOverrideController bonMatCtrl=new AF_BonusMatrixOverrideController();
            bonMatCtrl.Save();  
            ApexPages.currentPage().getParameters().put(CHPARENTID,AgencyEsitmate[0].id);
            AF_ViewAllController viewCtrl1=new AF_ViewAllController();
            ApexPages.currentPage().getParameters().put(CHPARENTID,OOPSEstimateList[0].id);
            AF_ViewAllController viewCtrl2=new AF_ViewAllController();
            ApexPages.currentPage().getParameters().put(CHPARENTID,AFBonusMat[0].id);
            AF_ViewAllController viewCtrl3=new AF_ViewAllController();
            Test.stopTest();
        }
    }
    /***********************************************************************************
*  @Description: this method will the test data
*  @name : AF_bonusMatrixOverrideController1
*  @param : none.
*  @return: none.
*************************************************************************************/
    Static testMethod void AF_bonusMatrixOverrideController1()
    {
        Test.startTest();
        userforBonusMatrixOverride=AF_TestFactory_Helper.createUserAdmin(true);
        User u=[SELECT id,Email FROM user WHERE id=:userforBonusMatrixOverride.id LIMIT 1];
        System.runAs(u)
        { 
            //Insert Account
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,false);
            List<Account> accLst = new List<Account>();
            for(Account ac: acc){
                ac.published__c=true;
                accLst.add(ac);
            }
            insert accLst;
            List<Account> acctQuery = [SELECT id FROM account LIMIT 1];
            System.Assert(acctQuery[0].Id != null, AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,true);
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE and Id IN:AFCategoryBrand LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.BRAND_RECORD);
            //Insert BrandEstimate
            List<AF_Brand_Estimate__c> BrandEst = AF_TestFactory_Helper.insertAFBrandEstList(1,false);
            List<AF_Brand_Estimate__c> BrandEstLSt = new List<AF_Brand_Estimate__c>();
            for(AF_Brand_Estimate__c brst : BrandEst){
                brst.AF_Status_Base_Fees__c=AF_Constants.BASE_FEES_READYFORPO;  
                brst.AF_Fiscal_Year__c=currYear;
                brst.AF_Active__c = true;
                brst.AF_Copied__c= false;
                brst.AF_Locked__c = false;  
                brst.AF_AgencyUsers1__c=u.Email;
                BrandEstLSt.add(brst);
            }
            insert BrandEstLSt;
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c where Id IN:BrandEstLSt LIMIT 1]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRANDESTIMATE_RECORD);
            //Insert Currency
            List<AF_Currency__c> AFCurrency = AF_TestFactory_Helper.insertAFcurrencyList(1,true);
            List<AF_Currency__c> AFCurrencyQuery = [SELECT Id FROM AF_Currency__c where Id IN:AFCurrency LIMIT 1];
            System.Assert(AFCurrencyQuery[0].Id != null, AF_TestFactory_Helper.CURRENCY_RECORD);
            //insert OOPS Actual.
            List<AF_OOPS_Actual__c> OopsactualList = AF_TestFactory_Helper.insertOOPSActual(1,true);
            List<AF_OOPS_Actual__c> OopsactualListQuery = [SELECT ID,AF_Agency__c FROM AF_OOPS_Actual__c WHERE ID IN : OopsactualList LIMIT 1];
            System.assertEquals(OopsactualListQuery[0].AF_Agency__c, acc[0].id,AF_TestFactory_Helper.OOPSACTUCAL_RECORD);
            //Insert Agency Entity
            List<AF_Entity__c> AFEntity = AF_TestFactory_Helper.insertAgencyEntityList(1,true);
            List<AF_Entity__c> AFEntityQuery = [SELECT AF_Agency__c FROM AF_Entity__c where RecordTypeId=:AF_TestFactory_Helper.AF_AGENCY_ENTITY_RECTYPE and Id IN:AFEntity LIMIT 1];
            System.assertEquals(AFEntity[0].AF_Agency__c, acc[0].id,AF_TestFactory_Helper.AGENCY_ENTITY);
            //Insert Unilever Entity
            List<AF_Entity__c> AFUnileverEntity = AF_TestFactory_Helper.insertUnileverEntityListRec(1,true);
            List<AF_Entity__c> AFUnileverEntityQuery = [SELECT Id FROM AF_Entity__c where RecordTypeId=:AF_TestFactory_Helper.AF_UNILIVER_ENTITY_RECTYPE and Id IN:AFUnileverEntity LIMIT 1];
            System.Assert(AFUnileverEntityQuery[0].Id != null, AF_TestFactory_Helper.UNILEVER_ENTITY);
            //Insert Agency Estimate.
            List<AF_Agency_Estimate__c> AgencyEsitmate = AF_TestFactory_Helper.insertAgencyEstimate(1,false);
            List<AF_Agency_Estimate__c> AgencyEsitmateLst = new  List<AF_Agency_Estimate__c>();
            for(AF_Agency_Estimate__c agency : AgencyEsitmate){
                agency.AF_Status__c =AF_Constants.BASE_FEES_WITH_AGENCY;
                agency.AF_Fiscal_Year__c=currYear;
                agency.AF_Adaptation__c=22;
                agency.AF_Digital__c=22;
                agency.AF_Traditional__c=22;
                AgencyEsitmateLst.add(agency);
            }
            insert AgencyEsitmateLst;
            List<AF_Agency_Estimate__c> AgencyQuery = [SELECT Id ,AF_Brand_Estimate__c FROM AF_Agency_Estimate__c WHERE ID IN : AgencyEsitmate limit 1];
            System.assertEquals(AgencyQuery[0].AF_Brand_Estimate__c, BrandEst[0].id,AF_TestFactory_Helper.AGENCYESTIMATE_RECORD);
            //Insert OOPS Estimate.
            List<AF_OOPS_Estimate__c> OOPSEstimateList = AF_TestFactory_Helper.InsertOOPsEstimate(1,true);
            List<AF_OOPS_Estimate__c> OOPSEstimateListQuery =[SELECT ID,AF_OOPS_Actual__c FROM AF_OOPS_Estimate__c WHERE ID IN :OOPSEstimateList LIMIT 1];
            System.assertEquals(OOPSEstimateListQuery[0].AF_OOPS_Actual__c, OopsactualList[0].id,AF_TestFactory_Helper.OOPSESTIMATE_RECORD);
            //Insert Bonus Summary
            List<AF_Bonus_Summary__c> AFBonusSummary = AF_TestFactory_Helper.insertBonusSummary(1,false);
            List<AF_Bonus_Summary__c> AFBonusSummarylist=new List<AF_Bonus_Summary__c>();
            for(AF_Bonus_Summary__c bonus:AFBonusSummary ){
                bonus.AF_Status__c=AF_Constants.BASE_FEES_READYFORPO;
                AFBonusSummarylist.add(bonus);
            }
            insert AFBonusSummarylist;
            List<AF_Bonus_Summary__c> AFBonusSummaryQuery = [Select AF_Agency__c from AF_Bonus_Summary__c where Id IN:AFBonusSummary LIMIT 1];
            System.assertEquals(AFBonusSummaryQuery[0].AF_Agency__c,acc[0].id, AF_TestFactory_Helper.BONUSSUMMARY_RECORD);
            //Insert Bonus Threshold
            List<AF_Bonus_Threshold__c> BonusThreshold =  AF_TestFactory_Helper.insertBonusThreshhold(1,true);
            List<AF_Bonus_Threshold__c> BonusThresholdQuery = [Select Agency_Name__c from AF_Bonus_Threshold__c where Id IN:BonusThreshold LIMIT 1];
            System.assertEquals(BonusThresholdQuery[0].Agency_Name__c,acc[0].id, AF_TestFactory_Helper.BONUSTHERSHOLD_RECORD);
            //Insert Bonus Results 
            List<AF_Bonus_Results__c> AFBonusRes = AF_TestFactory_Helper.insertBonusResults(1,true);
            List<AF_Bonus_Results__c> AFBonusResQuery = [Select AF_Bonus_Thresholds__c from AF_Bonus_Results__c where Id IN:AFBonusRes LIMIT 1];
            System.assertEquals(AFBonusResQuery[0].AF_Bonus_Thresholds__c,BonusThresholdQuery[0].id, AF_TestFactory_Helper.BONUSRESULT_RECORD);
            //Insert Bonus Matrix
            List<AF_Bonus_Matrix__c> AFBonusMat = AF_TestFactory_Helper.insertBonusMatrix(1,false);
            List<AF_Bonus_Matrix__c> AFBonusMatLst = new List<AF_Bonus_Matrix__c>();
            for(AF_Bonus_Matrix__c bm : AFBonusMat){
                bm.AF_Base_Fee_Country_Total__c =35353;
                bm.AF_BonusableFee__c=86588;  
                AFBonusMatLst.add(bm);
            }
            insert AFBonusMatLst;
            update AFBonusMatLst;
            List<AF_Bonus_Matrix__c> AFBonusMatQuery = [Select AF_Bonus_Results__c from AF_Bonus_Matrix__c where Id IN:AFBonusMat LIMIT 1];
            System.assertEquals(AFBonusMatQuery[0].AF_Bonus_Results__c,AFBonusResQuery[0].id, AF_TestFactory_Helper.BONUSMATRIX_RECORD);
            ApexPages.currentPage().getParameters().put(ID,AFBonusMat[0].id);
            AF_BonusMatrixOverrideController bonMatCtrl=new AF_BonusMatrixOverrideController();
            bonMatCtrl.Save();  
            bonMatCtrl.SavePo();
            bonMatCtrl.CalculateLocalC();
            ApexPages.currentPage().getParameters().put(CHPARENTID,AgencyEsitmate[0].id);
            AF_ViewAllController viewCtrl1=new AF_ViewAllController();
            ApexPages.currentPage().getParameters().put(CHPARENTID,OOPSEstimateList[0].id);
            AF_ViewAllController viewCtrl2=new AF_ViewAllController();
            ApexPages.currentPage().getParameters().put(CHPARENTID,AFBonusMat[0].id);
            AF_ViewAllController viewCtrl3=new AF_ViewAllController();
            Test.stopTest();
        }
    }
}