src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <fields>
        <fullName>Region__c</fullName>
        <description>Purpose : Created to display region value from user object 
Data Source : SAP | Integration : Mule | Security Level : Restricted</description>
        <label>NFS Region</label>
        <picklist>
            <controllingField>Zone__c</controllingField>
            <picklistValues>
                <fullName>10007 Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10100 Non-Comm Region 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10200 Retail FS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10500 Redistribution - US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10600 Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10610 Club Stores - US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10620 Cash &amp; Carry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10800 C-Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53000 East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53010 Mid Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53015 Tri State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53020 New England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54100 Obsolete/Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54200 Pepsi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55000 West Zone Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55005 Non-Comm Region 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55015 Midwest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55020 North central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55030 South Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55035 Mountain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55040 West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55045 West Client delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56005 Non-Comm Region 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56010 Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56015 Buying Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56020 Corporate Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56025 OCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59000 South CDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59005 East CDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59010 Redistribution - CA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PQN_DC_Hierarchy__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DC__c</fullName>
        <label>DC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCO__c</fullName>
        <label>MCO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Cluster__c</fullName>
        <label>Sub Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PQN DC Hierarchy</label>
</CustomObject>

src/objects/PQN_Pallet_Loss_Tree__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Loss_Code__c</fullName>
        <label>Loss Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loss_L1__c</fullName>
        <label>Loss L1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loss_L2__c</fullName>
        <label>Loss L2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loss_L3__c</fullName>
        <label>Loss L3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loss_L4__c</fullName>
        <label>Loss L4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PQN Pallet Loss Tree</label>
</CustomObject>

src/objects/PQN_Pallet_Quality_Non_Conformance__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <description>Cluster to be Auto-populated based upon DC master data</description>
        <label>Cluster</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Offer of corrects based on standard English</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DC_Country__c</fullName>
        <description>Auto-populated based upon DC master data</description>
        <label>DC Country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Pallet_Received__c</fullName>
        <description>Date on which the pallet was recieved</description>
        <label>Date Pallet Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Note_Number__c</fullName>
        <description>The delivery number of the pallet recieved</description>
        <label>Delivery Note Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCO__c</fullName>
        <description>MCO to be Auto-populated based upon DC master data</description>
        <label>MCO</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_compliance_reason_code__c</fullName>
        <description>Manually keyed/ Copied in/ drop-down box based upon Pallet or Customer Loss tree.Code within product and Customer loss tree L4. Errorred if outside of valid range</description>
        <inlineHelpText>Loss Level 4</inlineHelpText>
        <label>Non-compliance reason code</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Pallets_Per_SKU_Non_Compliant__c</fullName>
        <description>Number of pallets per SKU that are non-compliant.</description>
        <label>Number of Pallets Per SKU Non-Compliant</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Product Category is auto-populated based upon SKU master data</description>
        <label>Product Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>Product Group to be auto populated based upon SKU master data</description>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Product Name is auto-populated Based upon SKU master data</description>
        <label>Product Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Auto-populated Based upon DC master data</description>
        <label>Region</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_DC__c</fullName>
        <description>Auto-populated based upon user if a single DC user, Copied in, drop-down box populated with DCs based upon user</description>
        <label>Reporting DC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <description>Manually keyed/ Copied in. Validated against SKU master data. Show error if not correctly entered.</description>
        <label>SKU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Cluster__c</fullName>
        <description>Sub-cluster to be Auto-populated based upon DC master data</description>
        <label>Sub-Cluster</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Number__c</fullName>
        <description>supplier number for a supplier</description>
        <label>Supplier Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Auto-populated based upon SKU if a single supplier per SKU, Copied in, drop-down box populated with suppliers based upon SKU</description>
        <label>Supplier Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_type__c</fullName>
        <description>Auto populated based upon supplier Master data</description>
        <label>Supplier type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pallet Quality Non Conformance</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pallet Quality Non Conformance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PQN_Supplier__c.object
<CustomObject>
    <fields>
        <fullName>Supplier_Number__c</fullName>
        <label>Supplier Number</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Supplier_Type__c</fullName>
        <label>Supplier Type</label>
        <picklist>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PQN_UploadNCData_Clone.cls
global without sharing class PQN_UploadNCData_Clone{
    
    public string selectedfile{get; set;}
    public List<selectoption> filetype{get; set;}
  
    public PQN_UploadNCData_Clone (){
        selectedfile = apexpages.currentpage().getparameters().get('fileType');
        filetype = new List<selectOption>();
        filetype.add(new SelectOption('Unilever','Unilever'));
        filetype.add(new SelectOption('Cannock','Cannock'));
        filetype.add(new SelectOption('Heilbronn','Heilbronn'));
    }
    
    @RemoteAction
    global static Database.UpsertResult[] getSheetData(List<PQN_Pallet_Quality_Non_Conformance__c> xPQN, String selectedFileType,String timeStamp) {
        Delete [select id From PQN_Pallet_Quality_Non_Conformance__c where Is_Error__c=true and createdbyid=:UserInfo.getUserId()];
        system.debug(xPQN);
        
        List<PQN_Pallet_Quality_Non_Conformance__c> xPQNLIST= xPQN;
        Map<string,PQN_DC_Hierarchy__c> mapmasterdata = new Map<string,PQN_DC_Hierarchy__c>();
        Map<string,PQN_DC_Hierarchy__c> mapdcdata = new Map<string,PQN_DC_Hierarchy__c>();
        mapmasterdata = PQN_DC_Hierarchy__c.getAll();
        
        for(PQN_DC_Hierarchy__c dc: mapmasterdata.values()){
            mapdcdata.put(dc.dc__c,dc);             
        }
        
        String errorDesc = '';
        List<Account> xAcc = new List<Account>();
        Map<String,Id> mapAcc = new Map<String,Id>();
        
        Map<String,PQN_Supplier__c> mapSupplier = new Map<String,PQN_Supplier__c>();
        Map<Decimal,PQN_Pallet_Loss_Tree__c> mapLossTree = new Map<Decimal,PQN_Pallet_Loss_Tree__c>();
        Map<String,PQN_Pallet_Quality_Non_Conformance__c> mapProducts = new Map<String,PQN_Pallet_Quality_Non_Conformance__c>();
        Set<String> accName = new Set<String>();
        
        Set<String> productNos = new Set<String>();
        Set<String> supplierALias = new Set<String>();
        Set<Decimal> lossCodes = new Set<Decimal>();
        
        for(PQN_Pallet_Quality_Non_Conformance__c xP : xPQNLIST){
                accName.add(xP.Reporting_DC__c);
                productNos.add(xP.SKU__c);
                supplierALias.add(xP.Supplier__c);
                lossCodes.add((Decimal) xP.Non_compliance_reason_code__c);
         }
         for(PQN_Pallet_Quality_Non_Conformance__c xP : [select id,Product_Category__c,Product_Name__c,Product_Group__c,SKU__c from PQN_Pallet_Quality_Non_Conformance__c where SKU__c =:productNos]){
             mapProducts.put(xP.SKU__c,xP);
         }
         for(PQN_Supplier__c xSP: [Select Id,Name,Supplier_Alias__c,Supplier_Number__c,Supplier_Type__c from PQN_Supplier__c where Supplier_Alias__c =:supplierALias]){
             mapSupplier.put(xSP.Supplier_Alias__c,xSP);
         }
         for(PQN_Pallet_Loss_Tree__c xLos: [SELECT Loss_Code__c,Loss_L1__c,Loss_L2__c,Loss_L3__c,Loss_L4__c,Name FROM PQN_Pallet_Loss_Tree__c where Loss_Code__c=:lossCodes order by Loss_Code__c]){
             mapLossTree.put(xLos.Loss_Code__c,xLos);
         }
         
        if(selectedFileType=='Unilever'){
            for(Account xA : [Select Name, Id from Account where Name=:accName]){
                mapAcc.put(xA.Name, xA.Id);
            }
        }
        if(selectedFileType=='Cannock'){
            xAcc = [Select Id,Name from Account where name ='Cannock' limit 1];
        }
        if(selectedFileType=='Heilbronn'){
            xAcc = [Select Id,Name from Account where name ='Heilbronn auto' limit 1];
        }
        Id errAccId = [Select Id,Name from Account where Name='Error DC' limit 1].Id;
        
        for(PQN_Pallet_Quality_Non_Conformance__c xP : xPQNLIST){
        
            errorDesc = '';
            if(selectedFileType=='Unilever'){    
                if(mapAcc.get(xP.Reporting_DC__c)!=null){
                    xP.Account__c =mapAcc.get(xP.Reporting_DC__c);
                    if(mapdcdata.get(xP.Reporting_DC__c)!=null){
                        xP.Region__c = mapdcdata.get(xP.Reporting_DC__c).region__c;
                        xP.DC_Country__c = mapdcdata.get(xP.Reporting_DC__c).country__c;
                        xP.Cluster__c = mapdcdata.get(xP.Reporting_DC__c).cluster__c;
                        xP.Sub_Cluster__c = mapdcdata.get(xP.Reporting_DC__c).sub_cluster__c;                 
                        xP.MCO__c = mapdcdata.get(xP.Reporting_DC__c).mco__c;
                    }
                }else{
                    xP.Account__c =errAccId;
                    errorDesc+='Reporting DC is not in system. </br>';
                }
               
            }
            if(selectedFileType=='Cannock'){
                if(xAcc.size()>0){
                    xP.Account__c =xAcc[0].Id;
                     if(mapdcdata.get('Cannock')!=null){
                        xP.Region__c = mapdcdata.get('Cannock').region__c;
                        xP.DC_Country__c = mapdcdata.get('Cannock').country__c;
                        xP.Cluster__c = mapdcdata.get('Cannock').cluster__c;
                        xP.Sub_Cluster__c = mapdcdata.get('Cannock').sub_cluster__c;                 
                        xP.MCO__c = mapdcdata.get('Cannock').mco__c;
                    }
                }else{
                    xP.Account__c =errAccId;
                    errorDesc+='Reporting DC is not in system. </br>';
                }
               
            }
            if(selectedFileType=='Heilbronn'){
            
                if(xAcc.size()>0){
                    xP.Account__c =xAcc[0].Id;
                    if(mapdcdata.get('Heilbronn auto')!=null){
                        xP.Region__c = mapdcdata.get('Heilbronn auto').region__c;
                        xP.DC_Country__c = mapdcdata.get('Heilbronn auto').country__c;
                        xP.Cluster__c = mapdcdata.get('Heilbronn auto').cluster__c;
                        xP.Sub_Cluster__c = mapdcdata.get('Heilbronn auto').sub_cluster__c;                 
                        xP.MCO__c = mapdcdata.get('Heilbronn auto').mco__c;
                    }
                }else{
                    xP.Account__c =errAccId;
                    errorDesc+='Reporting DC is not in system. </br>';
                }
            }
        
            
            
            if(xP.Supplier__c.length()<1){
                errorDesc +='Supplier can not be empty. </br>';
            }else{
                
                if(mapSupplier.get(xP.Supplier__c)!=null){
                   xP.Supplier_Number__c = mapSupplier.get(xP.Supplier__c).Supplier_Number__c;
                   xP.Supplier_type__c = mapSupplier.get(xP.Supplier__c).Supplier_type__c;
                   system.debug('test');
                }
                else{
                    errorDesc +='Supplier not found in system. </br>';
                }
            
            }
            
            xP.SKU__c=(xP.SKU__c ==null || xP.SKU__c=='') ? '0' : xP.SKU__c;            
            if(xP.SKU__c.length()<1){
                errorDesc +='Product number(SKU) can not be empty. </br>';
            }else{
                
                if(mapProducts.get(xP.SKU__c)!=null){
                   xP.Product_Category__c = mapProducts.get(xP.SKU__c).Product_Category__c;
                   xP.Product_Name__c = mapProducts.get(xP.SKU__c).Product_Name__c;
                   xP.Product_Group__c = mapProducts.get(xP.SKU__c).Product_Group__c;
                   system.debug('test');
                }
                else{
                    errorDesc +='Product number(SKU) not found in system. </br>';
                }
            
            }
            
            xP.Non_compliance_reason_code__c=(xP.Non_compliance_reason_code__c==null) ? 0 : xP.Non_compliance_reason_code__c;
            if(mapLossTree.get(xP.Non_compliance_reason_code__c)!=null){
                xP.Loss_Level_2__c= mapLossTree.get(xP.Non_compliance_reason_code__c).Loss_L2__c;
                xP.loss_level_3__c = mapLossTree.get(xP.Non_compliance_reason_code__c).Loss_L3__c;
                xP.loss_level_4__c = mapLossTree.get(xP.Non_compliance_reason_code__c).Loss_L4__c;
            }
            else{
                errorDesc +='Loss Code not found in system. </br>';
            }
            
            xP.Number_of_Pallets_Per_SKU_Non_Compliant__c=(xP.Number_of_Pallets_Per_SKU_Non_Compliant__c==null) ? 0 : xP.Number_of_Pallets_Per_SKU_Non_Compliant__c;
            if(xP.Number_of_Pallets_Per_SKU_Non_Compliant__c==0){                
                errorDesc +='Number of Pallets should not be 0 and empty. </br>';
            }
            xP.Date_Pallet_Received__c =system.today();
            
            
            if(errorDesc.length()>0){
                xP.Error_Description__c=errorDesc;
                xP.Is_Error__c=true;
                
            }
        
        }
        system.debug(xPQNLIST);
        Database.UpsertResult[] SR = Database.Upsert(xPQNLIST, false);
        system.debug(SR);
        return SR;
    }
    
    @RemoteAction
    global static Map<String,Integer> getSheetStatus(String timeStamp) {

        Map<String,Integer> xMapStatus = new Map<String,Integer>();
        xMapStatus.put('Error',[Select Id from PQN_Pallet_Quality_Non_Conformance__c  where Is_Error__c=true and createdbyid=:userinfo.getuserid() and Multi_Timestamp__c=:timeStamp].size());
        xMapStatus.put('Success',[Select Id from PQN_Pallet_Quality_Non_Conformance__c  where Is_Error__c=false and createdbyid=:userinfo.getuserid() and Multi_Timestamp__c=:timeStamp].size());
       
        return xMapStatus;
    }
    
    @RemoteAction
    global static List<PQN_Pallet_Quality_Non_Conformance__c> sheetErrors(String timeStamp) {
      return [select id,Reporting_DC__c,Delivery_Note_Number__c,Description__c,SKU__c,Supplier__c,Supplier_Number__c, Non_compliance_reason_code__c,Number_of_Pallets_Per_SKU_Non_Compliant__c,Date_Pallet_Received__c,Comments__c,Error_Description__c,Account__c  From PQN_Pallet_Quality_Non_Conformance__c where Multi_Timestamp__c=:timeStamp AND Is_Error__c=true and createdbyid=:userinfo.getuserid()];
    }
    
    
}