src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>A rostered agency</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_BackupQuarter__c</fullName>
        <description>Used to hold the Quarters prior to raise new po</description>
        <label>AF_BackupQuarter</label>
        <picklist>
            <picklistValues>
                <fullName>Q1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>AF_Basefee_Estimate_Initial_Quarter__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Basefee Estimate in Initial Quarter</description>
        <label>Basefee Estimate Initial Quarter</label>
        <picklist>
            <picklistValues>
                <fullName>Q1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To the fiscal year details</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Pilot_Model__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check for Pilot model</description>
        <label>Pilot Model</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_RaiseNewPOQuarters__c</fullName>
        <description>This holds the quarters that were selected during the raise new po process</description>
        <label>AF_RaiseNewPOQuarters</label>
        <picklist>
            <picklistValues>
                <fullName>Q1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>AF_Status_Base_Fees__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Status for Base Fees</description>
        <label>Status Base Fees</label>
        <picklist>
            <picklistValues>
                <fullName>Initiate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency (Draft)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With CMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Controller Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Bonus Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store the Brands associated to Brand Estimate</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Category_Brand__c.object
<CustomObject>
    <description>Used to store Categories and associated brands related to Agency Fee Application.</description>
    <fields>
        <fullName>AF_Category_Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To associate brands to corresponding Categories</description>
        <label>Category</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Category-Brands</relationshipLabel>
        <relationshipName>Category_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Pilot_Model__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Not Used</description>
        <label>Pilot Model</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Super_category__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Super Catgeories</description>
        <label>Super category</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drinks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foods</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Category-Brands</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category-Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AF_AdjustQuater_Homepage_lightbox_Test.cls
@isTest(seeAllData=false)
public class AF_AdjustQuater_Homepage_lightbox_Test 
{  
    Private Static Integer IcurrYear = System.Today().year();
    Private Static string currYear=string.valueof(IcurrYear);
    private static String agencyFeesUserType = 'Agency';
    private static String Fyear = 'Year';
    Private static user usrforlightbox;
    Static testMethod void AF_adjustQuater_Homepage_lightbox()
    {
        Test.startTest();
        usrforlightbox = AF_TestFactory_Helper.createUserAdmin(true);
        User u=[SELECT id FROM user WHERE id=:usrforlightbox.id LIMIT 1];
        System.runAs(u)
        {
            
            //Insert Account
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,false);
            for(Account loopacc : acc){
                loopacc.published__c = true;
            }
            insert acc;
            List<Account> acctQuery = [SELECT id FROM account LIMIT 1];
            System.Assert(acctQuery[0].Id != null,AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,true);
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.CATEGORY_RECORD);
            List<AF_Brand_Estimate__c> BrandEst = AF_TestFactory_Helper.insertAFBrandEstList(1,true);
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c LIMIT 2]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRANDESTIMATE_RECORD);
            ApexPages.currentPage().getParameters().put('Category',AFCategoryBrand[0].id);
            ApexPages.currentPage().getParameters().put(Fyear,currYear);    
            AF_AdjustQuater_Homepage_lightbox adjHome=new AF_AdjustQuater_Homepage_lightbox();
            adjHome.saveBrandEstimate();
            adjHome.showPopup();
            adjHome.closePopup();
            Test.stopTest();
            
            
        }
    }
    Static testMethod void AF_adjustQuater_Homepage_lightbox1()
    {
        Test.startTest();
        usrforlightbox = AF_TestFactory_Helper.createUserAdmin(true);
        User u=[SELECT id FROM user WHERE id=:usrforlightbox.id LIMIT 1];
        System.runAs(u)
        {
            //insert Account.
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,false);
            for(Account loopacc : acc){
                loopacc.published__c = true;
            }
            insert acc;
            List<Account> acctQuery = [SELECT id FROM account LIMIT 1];
            System.Assert(acctQuery[0].Id != null,AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,false);
            for(AF_Category_Brand__c AFCate : Cb){
                AFCate.AF_Pilot_Model__c=false;
                AFCate.AF_Super_category__c = AF_Constants.TEST_SUPER_CATEGORY;
            }
            insert cb;
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.BRAND_RECORD);
            // Insert BrandEstimate.
            List<AF_Brand_Estimate__c> BrandEstList = AF_TestFactory_Helper.insertAFBrandEstList(1,false);
            List<AF_Brand_Estimate__c> BrandEstimateList = new List<AF_Brand_Estimate__c>();
            for(AF_Brand_Estimate__c BrandEst : BrandEstList){
                BrandEst.AF_Basefee_Estimate_Initial_Quarter__c='Q1;Q2;Q3;Q4';
                BrandEst.AF_Status_Base_Fees__c=AF_Constants.CATEGORY_FINANCE; 
                BrandEst.AF_Fiscal_Year__c=currYear;
                BrandEst.AF_Pilot_Model__c=false;
                BrandEstimateList.add(BrandEst);
            }
            insert BrandEstimateList;
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c LIMIT 2]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRANDESTIMATE_RECORD);
            
            List<AF_AdjustQuater_Homepage_lightbox.wrapChechbox> brandEstimateRecords=new List<AF_AdjustQuater_Homepage_lightbox.wrapChechbox>();
            ApexPages.currentPage().getParameters().put('Category',cb[0].id);
            ApexPages.currentPage().getParameters().put('brandEstimate',BrandEstList[0].id);
            ApexPages.currentPage().getParameters().put(Fyear,currYear);    
            AF_AdjustQuater_Homepage_lightbox adjHome=new AF_AdjustQuater_Homepage_lightbox();
            AF_AdjustQuater_Homepage_lightbox.wrapChechbox wr=new AF_AdjustQuater_Homepage_lightbox.wrapChechbox(BrandEstList[0],BrandEstList[0].Name,true,false,false,false);
            wr.Selected=true;
            brandEstimateRecords.add(wr);
            adjHome.QuarterEstimate=brandEstimateRecords;      
            adjHome.saveBrandEstimate();
            Test.stopTest();
        }
    }
    Static testMethod void AF_adjustQuater_Homepage_lightbox2()
    {
        Test.startTest();
        usrforlightbox = AF_TestFactory_Helper.createUserAdmin(true);
        User u=[SELECT id FROM user WHERE id=:usrforlightbox.id LIMIT 1];
        System.runAs(u)
        {
            //insert Account.
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,false);
            for(Account loopacc : acc){
                loopacc.published__c = true;
            }
            insert acc;
            List<Account> acctQuery = [SELECT id FROM account LIMIT 1];
            System.Assert(acctQuery[0].Id != null,AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,false);
            for(AF_Category_Brand__c AFCate : Cb){
                AFCate.AF_Pilot_Model__c=false;
                AFCate.AF_Super_category__c = AF_Constants.TEST_SUPER_CATEGORY;
            }
            insert cb;
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.BRAND_RECORD);
            // Insert BrandEstimate.
            List<AF_Brand_Estimate__c> BrandEstList = AF_TestFactory_Helper.insertAFBrandEstList(1,false);
            List<AF_Brand_Estimate__c> BrandEstimateList1 = new List<AF_Brand_Estimate__c>();
            for(AF_Brand_Estimate__c BrandEst : BrandEstList){
                BrandEst.AF_Basefee_Estimate_Initial_Quarter__c='Q1;Q2;Q3;Q4';
                //BrandEst.AF_RaiseNewPOQuarters__c=AF_Constants.QUARTER4;
                BrandEst.AF_Status_Base_Fees__c=AF_Constants.BASE_FEES_READYFORPO;
                BrandEst.AF_Fiscal_Year__c=currYear;
                BrandEst.AF_Pilot_Model__c=false;
                //BrandEst.AF_BackupQuarter__c='Q1; Q2; Q3; Q4';
                BrandEstimateList1.add(BrandEst);
            }
            insert BrandEstimateList1;
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c LIMIT 2]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRANDESTIMATE_RECORD);
            List<AF_AdjustQuater_Homepage_lightbox.wrapChechbox> brandEstimateRecords=new List<AF_AdjustQuater_Homepage_lightbox.wrapChechbox>();
            ApexPages.currentPage().getParameters().put('Category',cb[0].id);
            ApexPages.currentPage().getParameters().put(Fyear,currYear);    
            AF_AdjustQuater_Homepage_lightbox adjHome=new AF_AdjustQuater_Homepage_lightbox();
            AF_AdjustQuater_Homepage_lightbox.wrapChechbox wr=new AF_AdjustQuater_Homepage_lightbox.wrapChechbox(BrandEstList[0],BrandEstList[0].Name,true,true,true,true);
            wr.Selected=true;
            brandEstimateRecords.add(wr);
            adjHome.QuarterEstimate=brandEstimateRecords;      
            adjHome.showPopup();
            adjHome.saveBrandEstimate();
            Test.stopTest();
        }
    }
    Static testMethod void AF_adjustQuater_Homepage_lightbox3()
    {
        Test.startTest();
        usrforlightbox = AF_TestFactory_Helper.createUserAdmin(true);
        User u=[SELECT id FROM user WHERE id=:usrforlightbox.id LIMIT 1];
        System.runAs(u)
        {
            //insert Account.
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,false);
            for(Account loopacc : acc){
                loopacc.published__c = true;
            }
            insert acc;
            
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,false);
            for(AF_Category_Brand__c AFCate : Cb){
                AFCate.AF_Pilot_Model__c=false;
                AFCate.AF_Super_category__c = AF_Constants.TEST_SUPER_CATEGORY;
            }
            insert cb;
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.BRAND_RECORD);
            //insert BrandEstimate.
            List<AF_Brand_Estimate__c> BrandEstList = AF_TestFactory_Helper.insertAFBrandEstList(1,false);
            List<AF_Brand_Estimate__c> BrandEstimateList2 =new List<AF_Brand_Estimate__c>();
            for(AF_Brand_Estimate__c BrandEst : BrandEstList){
                //BrandEst.AF_Basefee_Estimate_Initial_Quarter__c='Q1;Q2;Q3;Q4';
                //BrandEst.AF_RaiseNewPOQuarters__c='3';
                BrandEst.AF_Fiscal_Year__c=currYear;
                BrandEst.AF_Pilot_Model__c=false;
                BrandEst.AF_Status_Base_Fees__c = AF_Constants.CATEGORY_FINANCE;
                BrandEstimateList2.add(BrandEst);
            }
            insert BrandEstimateList2;
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c LIMIT 2]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRAND_RECORD);
            List<AF_AdjustQuater_Homepage_lightbox.wrapChechbox> brandEstimateRecords=new List<AF_AdjustQuater_Homepage_lightbox.wrapChechbox>();
            ApexPages.currentPage().getParameters().put('Category',Cb[0].id);
            ApexPages.currentPage().getParameters().put(Fyear,currYear);    
            AF_AdjustQuater_Homepage_lightbox adjHome=new AF_AdjustQuater_Homepage_lightbox();
            AF_AdjustQuater_Homepage_lightbox.wrapChechbox wr = new AF_AdjustQuater_Homepage_lightbox.wrapChechbox(BrandEstList[0],BrandEstList[0].Name,true,true,true,true);
            list<AF_Brand_Estimate__c> brlist=new list<AF_Brand_Estimate__c>();
            wr.Selected=true;
            adjHome.displaypopquarter=false;
            brandEstimateRecords.add(wr);
            adjHome.QuarterEstimate=brandEstimateRecords;      
            adjHome.showPopup();
            adjHome.saveBrandEstimate();
            adjHome.displayPopup=false;
            Test.stoptest();
        }
    }
}