src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <fields>
        <fullName>UID_Region__c</fullName>
        <description>Region of where distributor or distributor&apos;s customer is located</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>SOUTH EAST ASIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MIDDLE EAST ASIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUROPE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NORTH ASIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH ASIA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UID_Segment__c</fullName>
        <description>Category of distributor given by Unilever</description>
        <label>Segment</label>
        <picklist>
            <picklistValues>
                <fullName>PI CUSTOMERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON PI CUSTOMERS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>UID_Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer of sales order</description>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>UID_Brand__c</fullName>
        <description>Brand of SKU</description>
        <formula>TEXT(PricebookEntry.Product2.UID_Brand__c)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UID_Category__c</fullName>
        <description>Category of SKU</description>
        <formula>TEXT(PricebookEntry.Product2.UID_Category__c)</formula>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UID_Material_ID__c</fullName>
        <formula>PricebookEntry.Product2.UID_Material_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>UID_Brand__c</fullName>
        <description>Brand of SKU</description>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>ALGIDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMORA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASTRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AXE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BALTIMOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BEN &amp; JERRY&apos;S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERTOLLI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BESTFOODS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLOCK &amp; WHITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLUE BAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLUE RIBBON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOVRIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRYLCREEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUAVITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUSHELLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAJOLINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALIPPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARTE D&apos;OR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLEAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSE UP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COLMANS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMFORT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEPSODENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UID_Category__c</fullName>
        <description>Category of SKU</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>BAKING COOKING AND SPREADING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COFFEE &amp; SNACKS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEODORANTS &amp; FRAGRANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRESSINGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAIR CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOUSEHOLD CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICE CREAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAUNDRY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON CORPORATE PERSONAL CARE CAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORAL CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER FOODS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAVOURY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SKIN CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SKIN CLEANSING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TEA AND SOY &amp; FRUIT BEVERAGES</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UID_Material_ID__c</fullName>
        <description>Material ID of SKU</description>
        <externalId>true</externalId>
        <label>Material ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Products</fullName>
        <active>true</active>
        <description>Standard products info.</description>
        <label>Products</label>
    </recordTypes>
</CustomObject>

src/objects/UID_Stocked_Product__c.object
<CustomObject>
    <fields>
        <fullName>UID_Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stocked Products</relationshipLabel>
        <relationshipName>Stocked_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UID_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UID_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UID_Stock_Cover_Calculation_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stock Cover Calculation Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Stocked Product</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Stocked Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocked Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UID_Stocked_Product_Summary__c.object
<CustomObject>
    <fields>
        <fullName>UID_Avail_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avail Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UID_Material_Id__c</fullName>
        <formula>UID_Material__r.UID_Material_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UID_Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Stocked Product Summary</relationshipLabel>
        <relationshipName>Stocked_Product_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UID_Stock_Cover_Calculation_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this will signifies that stock cover has been calculated.</description>
        <label>Stock Cover Calculation Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UID_Stock_Cover__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stock Cover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UID_Stocked_Product__c</fullName>
        <label>Stocked Product</label>
        <referenceTo>UID_Stocked_Product__c</referenceTo>
        <relationshipLabel>Stocked Product Summary</relationshipLabel>
        <relationshipName>Stocked_Product_Summary</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stocked Product Summary</label>
    <nameField>
        <displayFormat>SPS-{0000}</displayFormat>
        <label>Stocked Product Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocked Product Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UID_TriggerSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Trigger switch for UID project objects</description>
    <fields>
        <fullName>Inventory_Trigger_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Inventory Trigger Switch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Trigger_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Order Trigger Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>UID_TriggerSwitch</label>
</CustomObject>

src/classes/UID_StockCoverTriggerHelper_Test.cls
/**********************************************************************
 Name: UID_StockCoverTriggerHelper_Test() 
 Copyright © 2015 Salesforce 
 ====================================================== 
 ====================================================== 
 Purpose: 
 1. Test class of UID_InventoryTriggerHelper
 ====================================================== 
 ====================================================== 
 History 
 ------- 
 VERSION AUTHOR DATE DETAIL Description 
 1.0 Mangaoang 11/11/2015 INITIAL DEVELOPMENT Test inventory field population
 ***********************************************************************/
@isTest(seealldata=false)
public class UID_StockCoverTriggerHelper_Test{
    
    static Account testAccount00;
    static Account secondaryAccount00;
    
    static Id pricebookId;
    static Product2 testProduct00;
    static PricebookEntry productStandardPrice;
    
    static Order primaryOrderCurrentMonth;
    static Order secondaryOrderCurrentMonth;
    static Order secondaryOrderPrevMonth;
    static Order secondaryOrderPrev2Month;
    static Order secondaryOrderPrev3Month;
    
    /******************************************************************* 
    Purpose: test setReportMonthOnInsert
    Parameters: 
    Returns: void
    ********************************************************************/     
    static testMethod void setReportMonthOnInsertTest(){
        prepareData(10);
        Test.startTest();
        
        UID_Stocked_Product__c testStockedProduct00 = new UID_Stocked_Product__c();
            testStockedProduct00.UID_Start_Date__c = System.today().AddMonths(0);
            testStockedProduct00.UID_End_Date__c = System.today().AddMonths(0);
            testStockedProduct00.UID_Distributor__c = testAccount00.Id;
            testStockedProduct00.UID_Stock_Cover_Calculation_Flag__c = False;
        
        database.insert(testStockedProduct00, FALSE);
        
        UID_Stocked_Product_Summary__c testStockedSummary00 = new UID_Stocked_Product_Summary__c();
            testStockedSummary00.UID_Avail_Quantity__c = 100;
            testStockedSummary00.UID_Material__c = testProduct00.Id;
            testStockedSummary00.UID_Stocked_Product__c = testStockedProduct00.Id;
       
       database.insert(testStockedSummary00, FALSE);
       
          
       UID_Stocked_Product__c testStockedProduct01 = new UID_Stocked_Product__c();
            testStockedProduct01.UID_Start_Date__c = System.today().AddMonths(-1);
            testStockedProduct01.UID_End_Date__c = System.today().AddMonths(-1);
            testStockedProduct01.UID_Distributor__c = testAccount00.Id;
            testStockedProduct01.UID_Stock_Cover_Calculation_Flag__c = False;
        
        database.insert(testStockedProduct01, FALSE);
            
        UID_Stocked_Product_Summary__c testStockedSummary01 = new UID_Stocked_Product_Summary__c();
            testStockedSummary01.UID_Avail_Quantity__c = 200;
            testStockedSummary01.UID_Material__c = testProduct00.Id;
            testStockedSummary01.UID_Stocked_Product__c = testStockedProduct01.Id;
            
        database.insert(testStockedSummary01, FALSE);
          
        List <UID_Stocked_Product__c> testStockList = [Select ID, UID_Stock_Cover_Calculation_Flag__c From UID_Stocked_Product__c Where Id =: testStockedProduct00.id];
        for (UID_Stocked_Product__c t : testStockList) {
            t.UID_Stock_Cover_Calculation_Flag__c = True;
            
        }
        
        update testStockList;
        Test.stopTest();
        
        List <UID_Stocked_Product__c> testStockList1 = [Select ID, UID_Stock_Cover_Calculation_Flag__c, UID_Start_Date__c, UID_End_Date__c From UID_Stocked_Product__c Where Id =: testStockedProduct00.id];
        System.assertEquals(System.today().AddMonths(0), testStockList1[0].UID_Start_Date__c);
        System.assertEquals(System.today().AddMonths(0), testStockList1[0].UID_End_Date__c);
        
        List <UID_Stocked_Product__c> testStockList2 = [Select ID, UID_Stock_Cover_Calculation_Flag__c, UID_Start_Date__c, UID_End_Date__c From UID_Stocked_Product__c Where Id =: testStockedProduct01.id];
        System.assertEquals(System.today().AddMonths(-1), testStockList2[0].UID_Start_Date__c);
        System.assertEquals(System.today().AddMonths(-1), testStockList2[0].UID_End_Date__c);
        
        List<UID_Stocked_Product_Summary__c> testStockSummaryList1 = [Select ID, UID_Avail_Quantity__c, UID_Stock_Cover__c
                                                                     	From UID_Stocked_Product_Summary__c Where Id =: testStockedSummary00.id];
		
		
        //Check Stock Cover
        System.assertEquals(100, testStockSummaryList1[0].UID_Avail_Quantity__c);
        System.assertEquals(6000, testStockSummaryList1[0].UID_Stock_Cover__c);
        
        List<UID_Stocked_Product_Summary__c> testStockSummaryList2 = [Select ID, UID_Avail_Quantity__c, UID_Stock_Cover__c
                                                                     	From UID_Stocked_Product_Summary__c Where Id =: testStockedSummary01.id];
		
        //Check Stock Cover
        System.assertEquals(100, testStockSummaryList1[0].UID_Avail_Quantity__c);
        System.assertEquals(null, testStockSummaryList2[0].UID_Stock_Cover__c);
                
    }
    
    /******************************************************************* 
    Purpose: CalculationFlag is set to False
    Parameters: 
    Returns: void
    ********************************************************************/
    static testMethod void stockCoverIsNull(){
    	prepareData(5);
        Test.startTest();
        UID_Stocked_Product__c testStockedProduct00 = new UID_Stocked_Product__c();
            testStockedProduct00.UID_Start_Date__c = System.today().AddMonths(0);
            testStockedProduct00.UID_End_Date__c = System.today().AddMonths(0);
            testStockedProduct00.UID_Distributor__c = testAccount00.Id;
            testStockedProduct00.UID_Stock_Cover_Calculation_Flag__c = False;
        
        database.insert(testStockedProduct00, FALSE);
        
        UID_Stocked_Product_Summary__c testStockedSummary00 = new UID_Stocked_Product_Summary__c();
            testStockedSummary00.UID_Avail_Quantity__c = 100;
            testStockedSummary00.UID_Material__c = testProduct00.Id;
            testStockedSummary00.UID_Stocked_Product__c = testStockedProduct00.Id;
       
       database.insert(testStockedSummary00, FALSE);
        
        List <UID_Stocked_Product__c> testStockList = [Select ID, UID_Stock_Cover_Calculation_Flag__c From UID_Stocked_Product__c 
                                                       Where Id =: testStockedProduct00.id];
        
        for (UID_Stocked_Product__c t : testStockList) {
            t.UID_Stock_Cover_Calculation_Flag__c = False;
            
        }
        update testStockList;
        Test.stopTest();
        
        List<UID_Stocked_Product_Summary__c> testStockSummaryList1 = [Select ID, UID_Avail_Quantity__c, UID_Stock_Cover__c
                                                                     	From UID_Stocked_Product_Summary__c Where Id =: testStockedSummary00.id];
		
        //Check Stock Cover
        System.assertEquals(100, testStockSummaryList1[0].UID_Avail_Quantity__c);
        System.assertEquals(null, testStockSummaryList1[0].UID_Stock_Cover__c);
        
    }
    
    /******************************************************************* 
    Purpose: CalculationFlag is set to True
    Parameters: 
    Returns: void
    ********************************************************************/
    static testMethod void stockCoverIsNotNull(){
    	prepareData(15);
        Test.startTest();
        UID_Stocked_Product__c testStockedProduct00 = new UID_Stocked_Product__c();
            testStockedProduct00.UID_Start_Date__c = System.today().AddMonths(0);
            testStockedProduct00.UID_End_Date__c = System.today().AddMonths(0);
            testStockedProduct00.UID_Distributor__c = testAccount00.Id;
            testStockedProduct00.UID_Stock_Cover_Calculation_Flag__c = False;
        
        database.insert(testStockedProduct00, FALSE);
        
        UID_Stocked_Product_Summary__c testStockedSummary00 = new UID_Stocked_Product_Summary__c();
            testStockedSummary00.UID_Avail_Quantity__c = 100;
            testStockedSummary00.UID_Material__c = testProduct00.Id;
            testStockedSummary00.UID_Stocked_Product__c = testStockedProduct00.Id;
       
       database.insert(testStockedSummary00, FALSE);
       
       UID_Stocked_Product__c testStockedProduct01 = new UID_Stocked_Product__c();
            testStockedProduct01.UID_Start_Date__c = System.today().AddMonths(-1);
            testStockedProduct01.UID_End_Date__c = System.today().AddMonths(-1);
            testStockedProduct01.UID_Distributor__c = testAccount00.Id;
            testStockedProduct01.UID_Stock_Cover_Calculation_Flag__c = False;
        
        database.insert(testStockedProduct01, FALSE);
            
        UID_Stocked_Product_Summary__c testStockedSummary01 = new UID_Stocked_Product_Summary__c();
            testStockedSummary01.UID_Avail_Quantity__c = 200;
            testStockedSummary01.UID_Material__c = testProduct00.Id;
            testStockedSummary01.UID_Stocked_Product__c = testStockedProduct01.Id;
            
        database.insert(testStockedSummary01, FALSE);
        
        List <UID_Stocked_Product__c> testStockList = [Select ID, UID_Stock_Cover_Calculation_Flag__c From UID_Stocked_Product__c 
                                                       Where Id =: testStockedProduct00.id];
        
        for (UID_Stocked_Product__c t : testStockList) {
            t.UID_Stock_Cover_Calculation_Flag__c = True;
            
        }
        update testStockList;
        Test.stopTest();
        
        List<UID_Stocked_Product_Summary__c> testStockSummaryList1 = [Select ID, UID_Avail_Quantity__c, UID_Stock_Cover__c
                                                                     	From UID_Stocked_Product_Summary__c Where Id =: testStockedSummary00.id];
		
        //Check Stock Cover
        System.assertEquals(100, testStockSummaryList1[0].UID_Avail_Quantity__c);
        System.assertEquals(6000, testStockSummaryList1[0].UID_Stock_Cover__c);
        
        List<UID_Stocked_Product_Summary__c> testStockSummaryList2 = [Select ID, UID_Avail_Quantity__c, UID_Stock_Cover__c
                                                                     	From UID_Stocked_Product_Summary__c Where Id =: testStockedSummary01.id];
		
        //Check Stock Cover
        System.assertEquals(100, testStockSummaryList1[0].UID_Avail_Quantity__c);
        System.assertEquals(6000, testStockSummaryList1[0].UID_Stock_Cover__c);
        
        /*        
        List <UID_Stocked_Product__c> testStockList1 = [Select ID, UID_Stock_Cover_Calculation_Flag__c, UID_Start_Date__c, UID_End_Date__c 
                                                        From UID_Stocked_Product__c Where Id =: testStockedProduct00.id];
        System.assertEquals(FALSE, testStockList1[0].UID_Stock_Cover_Calculation_Flag__c);
        */
        
    }
    
    
    /******************************************************************* 
    Purpose: Ensure that the trigger does not fail at the max. batch size
    Parameters: 
    Returns: void
    ********************************************************************/
    static testMethod void bulkRecordTest(){
        prepareData(2);
        Test.startTest();
        
        boolean allStockedProductsSaved = true;
        boolean allStockedProductSummariesSaved = true;
        
        List<UID_Stocked_Product__c> stockedProducts = new List<UID_Stocked_Product__c>();
        List<UID_Stocked_Product_Summary__c> stockedProductSummaries = new List<UID_Stocked_Product_Summary__c>();
        
        for(Integer i=0; i< 200; i++) {
            UID_Stocked_Product__c stockedProduct = new UID_Stocked_Product__c();
            stockedProduct.UID_Start_Date__c = System.today().AddMonths(0);
            stockedProduct.UID_End_Date__c = System.today().AddMonths(0);
            stockedProduct.UID_Distributor__c = testAccount00.Id;
            stockedProduct.UID_Stock_Cover_Calculation_Flag__c = false;
            
            stockedProducts.add(stockedProduct);
        }
        
        insert(stockedProducts);

        for(UID_Stocked_Product__c sp: stockedProducts) {
            UID_Stocked_Product_Summary__c stockedProductSummary = new UID_Stocked_Product_Summary__c();
            stockedProductSummary.UID_Avail_Quantity__c = 100;
            stockedProductSummary.UID_Material__c = testProduct00.Id;
            stockedProductSummary.UID_Stocked_Product__c = sp.Id;   
            
            stockedProductSummaries.add(stockedProductSummary);  
            
            if(sp.id == null) { // If any of the records didn't save, flag it.
                allStockedProductsSaved = false;
            }
               
        }
        
        insert stockedProductSummaries;
        
        // Fire off the calculation
        for(UID_Stocked_Product__c sp: stockedProducts) {
            sp.UID_Stock_Cover_Calculation_Flag__c = true;
        }        
        
        update stockedProducts;
        
        for(UID_Stocked_Product_Summary__c sps: stockedProductSummaries) {
            if(sps.id == null) {
                allStockedProductSummariesSaved = false;
            }
        }

        Test.stopTest();
        
        System.assertEquals(allStockedProductsSaved, true, 'Bulk processing of StockedProducts did not complete.');
        System.assertEquals(allStockedProductSummariesSaved, true, 'Bulk processingof StockedProductSummaries did not complete.');        
        
    } 
    
    
    
    /******************************************************************* 
    Purpose: prepare account and product;create custom settings
    Parameters: 
    Returns: void
    ********************************************************************/  
    static void prepareData(Integer unitPrice){
        Id primaryAccountRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Primary Account').getRecordTypeId();
        Id secondaryAccountRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Secondary Account').getRecordTypeId();
        List<Account> newAccounts = new List<Account>();
        List<Order> newOrders = new List<Order>();
        List<OrderItem> newOrderItems = new List<OrderItem>();
        
        String STATUS_DRAFT = 'Draft';
        
        //create trigger switch(custom settings)
        UID_TriggerSwitch__c settingTriggerSwitch = UID_TriggerSwitch__c.getOrgDefaults();
            settingTriggerSwitch.Inventory_Trigger_Switch__c = TRUE;
            settingTriggerSwitch.Order_Trigger_Switch__c = TRUE;
        database.insert(settingTriggerSwitch, FALSE);
        //create products
        testProduct00 = new Product2();
            testProduct00.Name = 'testProduct00';
            testProduct00.UID_Material_ID__c = '920151111';
            testProduct00.UID_Brand__c = 'PEPSODENT';
            testProduct00.UID_Category__c = 'ORAL CARE';
        database.insert(testProduct00, FALSE);
        
        //create pricebook entry
        pricebookId = Test.getStandardPricebookId();
        productStandardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, 
            Product2Id = testProduct00.Id,
            UnitPrice = unitPrice, 
            IsActive = true);
        database.insert(productStandardPrice, FALSE);
       
        testAccount00 = new Account();
            testAccount00.RecordTypeId = primaryAccountRecordType;
            testAccount00.Name = 'testAccount00';
            testAccount00.UID_Region__c = 'SOUTH EAST ASIA';
            testAccount00.UID_Segment__c = 'PI CUSTOMERS';
            testAccount00.UID_Geography__c = 'OTHERS';
            testAccount00.AccountNumber = '915113204';
        database.insert(testAccount00, FALSE);
        
        //create account(type Secondary account)
        secondaryAccount00 = new Account();
            secondaryAccount00.RecordTypeId = secondaryAccountRecordType;
            secondaryAccount00.Name = 'secondaryAccount00';
            secondaryAccount00.UID_Region__c = 'SOUTH EAST ASIA';
            secondaryAccount00.UID_Segment__c = 'PI CUSTOMERS';
            secondaryAccount00.UID_Geography__c = 'OTHERS';
            secondaryAccount00.AccountNumber = '915113204';
        newAccounts.add(secondaryAccount00);
        
        database.insert(newAccounts, FALSE);
        
        primaryOrderCurrentMonth = new Order();
            primaryOrderCurrentMonth.AccountId = testAccount00.Id;
            primaryOrderCurrentMonth.UID_Distributor__c = testAccount00.Id;
            primaryOrderCurrentMonth.EffectiveDate = System.today();
            primaryOrderCurrentMonth.Status = STATUS_DRAFT;
            primaryOrderCurrentMonth.UID_Invoice_Number__c = '920151111';
            primaryOrderCurrentMonth.RecordTypeId = primaryAccountRecordType;
            primaryOrderCurrentMonth.Pricebook2Id =  pricebookId;       
        newOrders.add(primaryOrderCurrentMonth);
        
        secondaryOrderCurrentMonth = new Order();
            secondaryOrderCurrentMonth.AccountId = secondaryAccount00.Id;
            secondaryOrderCurrentMonth.UID_Distributor__c = testAccount00.Id;
            secondaryOrderCurrentMonth.EffectiveDate = System.today();
            secondaryOrderCurrentMonth.Status = STATUS_DRAFT;
            secondaryOrderCurrentMonth.UID_Invoice_Number__c = '11/18/2015/secondaryOrderCurrentMonth';
            secondaryOrderCurrentMonth.RecordTypeId = secondaryAccountRecordType;
            secondaryOrderCurrentMonth.Pricebook2Id =  pricebookId;  
        newOrders.add(secondaryOrderCurrentMonth);
        
        secondaryOrderPrevMonth = new Order();
            secondaryOrderPrevMonth.AccountId = secondaryAccount00.Id;
            secondaryOrderPrevMonth.UID_Distributor__c = testAccount00.Id;
            secondaryOrderPrevMonth.EffectiveDate = System.today().AddMonths(-1);
            secondaryOrderPrevMonth.Status = STATUS_DRAFT;
            secondaryOrderPrevMonth.UID_Invoice_Number__c = '11/18/2015/secondaryOrderPrevMonth';
            secondaryOrderPrevMonth.RecordTypeId = secondaryAccountRecordType;
            secondaryOrderPrevMonth.Pricebook2Id =  pricebookId;  
        newOrders.add(secondaryOrderPrevMonth);
        
        secondaryOrderPrev2Month = new Order();
            secondaryOrderPrev2Month.AccountId = secondaryAccount00.Id;
            secondaryOrderPrev2Month.UID_Distributor__c = testAccount00.Id;
            secondaryOrderPrev2Month.EffectiveDate = System.today().AddMonths(-2);
            secondaryOrderPrev2Month.Status = STATUS_DRAFT;
            secondaryOrderPrev2Month.UID_Invoice_Number__c = '11/18/2015/secondaryOrderPrev2Month';
            secondaryOrderPrev2Month.RecordTypeId = secondaryAccountRecordType;
            secondaryOrderPrev2Month.Pricebook2Id =  pricebookId;  
        newOrders.add(secondaryOrderPrev2Month);
        
        secondaryOrderPrev3Month = new Order();
            secondaryOrderPrev3Month.AccountId = secondaryAccount00.Id;
            secondaryOrderPrev3Month.UID_Distributor__c = testAccount00.Id;
            secondaryOrderPrev3Month.EffectiveDate = System.today().AddMonths(-3);
            secondaryOrderPrev3Month.Status = STATUS_DRAFT;
            secondaryOrderPrev3Month.UID_Invoice_Number__c = '11/18/2015/secondaryOrderPrev3Month';
            secondaryOrderPrev3Month.RecordTypeId = secondaryAccountRecordType;
            secondaryOrderPrev3Month.Pricebook2Id =  pricebookId;
        newOrders.add(secondaryOrderPrev3Month);
        
        database.insert(newOrders, FALSE);
        
        //create primary sales of the month
        OrderItem primarySaleCurrentMonth = new OrderItem();
            primarySaleCurrentMonth.UID_Order_Quantity__c = 60;
            primarySaleCurrentMonth.OrderId = primaryOrderCurrentMonth.Id;
            primarySaleCurrentMonth.Quantity = 1;
            primarySaleCurrentMonth.PricebookEntryId = productStandardPrice.Id;
            primarySaleCurrentMonth.UnitPrice = unitPrice;
        newOrderItems.add(primarySaleCurrentMonth);
        //create secondary sales of the month
        OrderItem secondarySaleCurrentMonth = new OrderItem();
            secondarySaleCurrentMonth.UID_Order_Quantity__c = 10;
            secondarySaleCurrentMonth.OrderId = secondaryOrderCurrentMonth.Id;
            secondarySaleCurrentMonth.Quantity = 1;
            secondarySaleCurrentMonth.PricebookEntryId = productStandardPrice.Id;
            secondarySaleCurrentMonth.UnitPrice = unitPrice;
        newOrderItems.add(secondarySaleCurrentMonth);
        //create secondary sales previous month
        OrderItem secondarySalePrevMonth = new OrderItem();
            secondarySalePrevMonth.UID_Order_Quantity__c = 10;
            secondarySalePrevMonth.OrderId = secondaryOrderPrevMonth.Id;
            secondarySalePrevMonth.Quantity = 1;
            secondarySalePrevMonth.PricebookEntryId = productStandardPrice.Id;
            secondarySalePrevMonth.UnitPrice = unitPrice;
        newOrderItems.add(secondarySalePrevMonth);
        //create secondary sales previous 2 month
        OrderItem secondarySalePrev2Month = new OrderItem();
            secondarySalePrev2Month.UID_Order_Quantity__c = 10;
            secondarySalePrev2Month.OrderId = secondaryOrderPrev2Month.Id;
            secondarySalePrev2Month.Quantity = 1;
            secondarySalePrev2Month.PricebookEntryId = productStandardPrice.Id;
            secondarySalePrev2Month.UnitPrice = unitPrice;
        newOrderItems.add(secondarySalePrev2Month);
        //create secondary sales previous 3 month
        OrderItem secondarySalePrev3Month = new OrderItem();
            secondarySalePrev3Month.UID_Order_Quantity__c = 10;
            secondarySalePrev3Month.OrderId = secondaryOrderPrev3Month.Id;
            secondarySalePrev3Month.Quantity = 1;
            secondarySalePrev3Month.PricebookEntryId = productStandardPrice.Id;
            secondarySalePrev3Month.UnitPrice = 1;
        newOrderItems.add(secondarySalePrev3Month);
        database.insert(newOrderItems,FALSE);
        
    }


}