src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <fields>
        <fullName>Local_Identifier__c</fullName>
        <description>CEC Local Identifier  will hold CPF (government issued ID) for consumers</description>
        <label>Local Identifier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CEC_E_Voucher_Details__c.object
<CustomObject>
    <description>CEC E-Voucher Details is used to issue voucher to a customer.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CEC Account Id Lookup to the Account object</description>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>E-Voucher Details</relationshipLabel>
        <relationshipName>E_Voucher_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Voucher_Value__c</fullName>
        <description>CEC Voucher Value will get populated with the voucher value that Advisor enters on the fulfilment</description>
        <label>Voucher Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>E-Voucher Detail</label>
    <nameField>
        <label>E-Voucher Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E-Voucher Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cec_Enclosure__c.object
<CustomObject>
    <description>CEC -</description>
    <fields>
        <fullName>ItemValue__c</fullName>
        <label>ItemValue</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Enclosure</label>
    <nameField>
        <label>Enclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enclosures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cec_Fulfilment__c.object
<CustomObject>
    <description>CEC -</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Case__r.AccountId</formula>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalEnclosureValue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Enclosure Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Approved__c</fullName>
        <description>CEC Date Approved is used to store the date when fulfilment was approved.</description>
        <label>Date Approved</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>CEC Date of Birth use to default the date of birth from person account</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>E_Voucher_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CEC E-Voucher Number is Lookup to the E-Voucher details.</description>
        <label>E-Voucher Number</label>
        <referenceTo>CEC_E_Voucher_Details__c</referenceTo>
        <relationshipLabel>Fulfilment</relationshipLabel>
        <relationshipName>Fulfilment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>E_Voucher_Value__c</fullName>
        <description>CEC E-Voucher Value is used to capture the E-Voucher  value.</description>
        <label>E-Voucher Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Enclosure1_Quantity__c</fullName>
        <description>CEC: To capture Enclosure1 Quantity</description>
        <label>Enclosure1 Quantity</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enclosure1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enclosure1</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>cec_Enclosure__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>cec_Enclosure__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>cec_Enclosure__c</referenceTo>
        <relationshipLabel>Fulfilment</relationshipLabel>
        <relationshipName>Fulfilment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enclosure2_Quantity__c</fullName>
        <description>CEC: To capture Enclosure2 Quantity</description>
        <label>Enclosure2 Quantity</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enclosure2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enclosure2</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>cec_Enclosure__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>cec_Enclosure__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>cec_Enclosure__c</referenceTo>
        <relationshipLabel>Fulfilment (Enclosure2)</relationshipLabel>
        <relationshipName>Fulfilment1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enclosure3_Quantity__c</fullName>
        <description>CEC: To capture Enclosure3 Quantity</description>
        <label>Enclosure3 Quantity</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enclosure3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enclosure3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>cec_Enclosure__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>cec_Enclosure__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>cec_Enclosure__c</referenceTo>
        <relationshipLabel>Fulfilment (Enclosure3)</relationshipLabel>
        <relationshipName>Fulfilment2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enclosure4_Quantity__c</fullName>
        <description>CEC: To capture Enclosure4 Quantity</description>
        <label>Enclosure4 Quantity</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enclosure4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enclosure4</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>cec_Enclosure__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>cec_Enclosure__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>cec_Enclosure__c</referenceTo>
        <relationshipLabel>Fulfilment (Enclosure4)</relationshipLabel>
        <relationshipName>Fulfilment3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enclosure5_Quantity__c</fullName>
        <description>CEC: To capture Enclosure5 Quantity</description>
        <label>Enclosure5 Quantity</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enclosure5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enclosure5</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>cec_Enclosure__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>cec_Enclosure__c.Country__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>cec_Enclosure__c</referenceTo>
        <relationshipLabel>Fulfilment (Enclosure5)</relationshipLabel>
        <relationshipName>Fulfilment4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Local_Identifier__c</fullName>
        <description>CEC Local Identifier is used to display the CPF number from the account.</description>
        <label>Local Identifier</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonEmail__c</fullName>
        <description>CEC PersonEmail  will hols email id of Account holder</description>
        <label>Person Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>QA_flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QA flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <label>Fulfilment</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Fulfilment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Max_Refund_Amount__c</fullName>
        <description>CEC: Max refund amount Advisors can provide</description>
        <formula>IF( ISPICKVAL(Refund_Authorization_Limit__c , &quot;Level 1&quot;) , $Setup.CEC_Cheque_Authorization_Limit__c.Level_1__c,
 IF( ISPICKVAL(Refund_Authorization_Limit__c , &quot;Level 2&quot;) , $Setup.CEC_Cheque_Authorization_Limit__c.Level_2__c,
 IF( ISPICKVAL(Refund_Authorization_Limit__c , &quot;Level 3&quot;) , $Setup.CEC_Cheque_Authorization_Limit__c.Level_3__c,
 IF( ISPICKVAL(Refund_Authorization_Limit__c , &quot;Level 4&quot;) , $Setup.CEC_Cheque_Authorization_Limit__c.Level_4__c,
 IF( ISPICKVAL(Refund_Authorization_Limit__c , &quot;Level 5&quot;) , $Setup.CEC_Cheque_Authorization_Limit__c.Level_5__c,
 IF( ISPICKVAL(Refund_Authorization_Limit__c , &quot;Level 6&quot;) , $Setup.CEC_Cheque_Authorization_Limit__c.Level_6__c,
 IF( ISPICKVAL(Refund_Authorization_Limit__c , &quot;Level 7&quot;) , $Setup.CEC_Cheque_Authorization_Limit__c.Level_7__c, null )))))) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max Refund Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quality_Check_Percentage__c</fullName>
        <inlineHelpText>CEC field, used to specify the level of emails randomly select for approval</inlineHelpText>
        <label>Quality Check Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CEC_FulfilmentHelperExtension.cls
/**********************************************************************
Name:  CEC_FulfilmentHelperExtension
Copyright Â© 2016  Unilever
======================================================================
=======================================================================
Purpose: This is the Helper class for cec_Fulfilment__c trigger
=======================================================================
=======================================================================
History
-------
VERSION  AUTHOR              DATE            DETAIL                        Description
1.0       mahesh konar       20th july 2016   CSC-4844                      Sonar Fixes

***********************************************************************/
public with sharing class  CEC_FulfilmentHelperExtension {
    
     /**
    This method is used to check quality and update QA flag
    @param : fulfilmentList - List of cec_Fulfilment__c objects that are to be inserted
    @return : void 
    **/
    public static void qualityCheck(List<cec_Fulfilment__c> fulfilmentList) {


        // try{
        //System.debug('~~~~In CEC_FulfilmentHelper');




        User loggedinuser = [select Quality_Check_Percentage__c, Max_Refund_Amount__c from User where id = :UserInfo.getUserId()];

        Double QualityPercent =  loggedinuser.Quality_Check_Percentage__c;

        //Double qualityMaxRefund = loggedinuser.Max_Refund_Amount__c;

        //System.debug('~~~~QualityPercent  ' + QualityPercent );
        //System.debug('~~~~loggedinuser.Quality_Check_Percentage__c ' + loggedinuser.Quality_Check_Percentage__c);

        Double randomnumber = Math.random() * 100;
        System.debug('~~~~randomnumber ' + randomnumber );

        if (Test.isRunningTest()) {
            randomnumber = 0.00;
            QualityPercent  = 1.00;
            //qualityMaxRefund = 1.00;
        }

        for (cec_Fulfilment__c fulfilmentObj : fulfilmentList) {



            if (randomnumber < QualityPercent) {

                fulfilmentObj.QA_flag__c = true;

            }


        }



        // }

        /* catch(Exception ex)
        {
        System.debug('Exception in CEC_FulfilmentHelper.qualityCheck() -> Exception :'  );

        }*/

    }

    /**
    This method is used to update Account details for DOB and Local Identifier
    @param :fulfilment List- List of new values from trigger context variable
    oldFulfilmentMap - Trigger context variable for old details
    */
    public static void updateAccountDetails(List<cec_Fulfilment__c> fulfilmentList, Map<Id, cec_Fulfilment__c> oldFulfilmentMap) {
        system.debug(' In updateDebitCardValue Method : fulfilmentList = ' + fulfilmentList);
        system.debug(' In updateDebitCardValue Method : oldFulfilmentMap = ' + oldFulfilmentMap);
        try {
            List<Account> accountList = new List<Account>();
            for (cec_Fulfilment__c fulfilment : fulfilmentList) {
                if ((fulfilment.Date_of_Birth__c != null &&
                        oldFulfilmentMap.get(fulfilment.Id).Date_of_Birth__c != fulfilment.Date_of_Birth__c) ||
                        (String.isNotBlank(fulfilment.Local_Identifier__c) &&
                         oldFulfilmentMap.get(fulfilment.Id).Local_Identifier__c != fulfilment.Local_Identifier__c) ||
                        (String.isNotBlank(fulfilment.PersonEmail__c) &&
                         oldFulfilmentMap.get(fulfilment.Id).PersonEmail__c != fulfilment.PersonEmail__c)) {

                    Account accountObj = new Account(   Id = fulfilment.Account_Id__c,
                                                        PersonBirthdate = fulfilment.Date_of_Birth__c,
                                                        Local_Identifier__c = fulfilment.Local_Identifier__c,
                                                        PersonEmail = fulfilment.PersonEmail__c);
                    accountList.add(accountObj);
                }
            }
            if (!accountList.isEmpty())
                update accountList;
        } catch (DmlException e) {
            for (cec_Fulfilment__c fulfilment : fulfilmentList) {
                if (e.getMessage().contains(CEC_Constants.LOCALIDENTIFIER_CPF)) {
                    fulfilment.addError(e.getDMLMessage(0));
                } else {
                    fulfilment.addError(e.getMessage());
                }
            }
        } catch (Exception e) {
            //throw e;
            System.debug('Exception in CEC_FulfilmentHelper.updateAccountDetails method ' + e.getMessage());
        }
    }
    
     /**
    This method is used to update E-Voucher value after fulfillment approval.
    @param : fulfilment List- List of new values from trigger context variable
    oldFulfilmentMap - Trigger context variable for old details
    */
    public static void updateEvoucherValue(List<cec_Fulfilment__c> fulfilmentList, Map<Id, cec_Fulfilment__c> oldFulfilmentMap) {

        system.debug(' In updateEvoucherValue Method : fulfilmentList = ' + fulfilmentList);
        system.debug(' In updateEvoucherValue Method : oldFulfilmentMap = ' + oldFulfilmentMap);

        List<CEC_E_Voucher_Details__c> eVoucherDetailToUpdate = new List<CEC_E_Voucher_Details__c>();
        CEC_E_Voucher_Details__c eVoucherDetailObj = new CEC_E_Voucher_Details__c();
        for (cec_Fulfilment__c fulfilment : fulfilmentList) {
            if (fulfilment.isApproved__c &&
                    oldFulfilmentMap.get(fulfilment.Id).isApproved__c != fulfilment.isApproved__c &&
                    fulfilment.E_Voucher_Number__c != null &&
                    fulfilment.E_Voucher_Value__c != null) {

                System.debug('@@@fulfilment.E_Voucher_Value__c ' + fulfilment.E_Voucher_Value__c);
                eVoucherDetailObj = new CEC_E_Voucher_Details__c(  Id = fulfilment.E_Voucher_Number__c ,
                        Voucher_Value__c =  fulfilment.E_Voucher_Value__c);
                System.debug('@@@eVoucherDetailObj ' + eVoucherDetailObj);
                eVoucherDetailToUpdate.add(eVoucherDetailObj);
            }
        }
        System.debug('@@eVoucherDetailToUpdate size' + eVoucherDetailToUpdate.size());
        if (!eVoucherDetailToUpdate.isEmpty()) {
            update eVoucherDetailToUpdate;
        }
    }
    /**
    This method is used to update Date Approved field on fulfilment object
    @param :fulfilment List- List of new values from trigger context variable
    oldFulfilmentMap - Trigger context variable for old details
    */
    public static void updateFulfilmentApprovedDate(List<cec_Fulfilment__c> fulfilmentList, Map<Id, cec_Fulfilment__c> oldFulfilmentMap) {
        try {
            for (cec_Fulfilment__c fulfilment : fulfilmentList) {
                if (fulfilment.isApproved__c &&
                        oldFulfilmentMap.get(fulfilment.Id).isApproved__c != fulfilment.isApproved__c) {
                    fulfilment.Date_Approved__c = System.now();
                }
            }
        } catch (Exception e) {
            System.debug('Exception in CEC_FulfilmentHelper.updateFulfilmentApprovedDate method ' + e.getMessage());
        }
    }

   
	 /*******************************************************************
    Purpose: To calculate Total Enclosure Value.
    Param: fulfilmentList
    ********************************************************************/

    public static void beforeInsUpdCalcEnclosure(List<cec_Fulfilment__c> fulfilmentList, Map<Id, cec_fulfilment__C> fulfilmentOldMap) {

        //2nd june 2016 - mahesh - To calculate Total Enclosure Value
        Set<Id> enclosureIds = new Set<Id>();

        for (cec_Fulfilment__c fulfilmentObj : fulfilmentList) {

            if (fulfilmentOldMap != null && (  fulfilmentObj.Enclosure1__c != fulfilmentOldMap.get(fulfilmentObj.Id).Enclosure1__c
                                               || fulfilmentObj.Enclosure2__c != fulfilmentOldMap.get(fulfilmentObj.Id).Enclosure2__c
                                               || fulfilmentObj.Enclosure3__c != fulfilmentOldMap.get(fulfilmentObj.Id).Enclosure3__c
                                               || fulfilmentObj.Enclosure4__c != fulfilmentOldMap.get(fulfilmentObj.Id).Enclosure4__c
                                               || fulfilmentObj.Enclosure5__c != fulfilmentOldMap.get(fulfilmentObj.Id).Enclosure5__c)) {

                enclosureIds.addAll(getEnclosureIds(fulfilmentObj));
            } else {

                enclosureIds.addAll(getEnclosureIds(fulfilmentObj));
            }

        }

        if (!enclosureIds.isEmpty()) {
            calcTotalEnclosure(enclosureIds, fulfilmentList);
        }
    }
	/*******************************************************************
    Purpose: To get all the enclosure Id on fulfillment.
    Param: fulfilmentObj
    Return: set<Id>
    ********************************************************************/
    public static set<Id> getEnclosureIds(cec_Fulfilment__c fulfilmentObj) {
		 //2nd june 2016 - mahesh - To calculate Total Enclosure Value
		 
        set<Id> enclosureIds = new set<Id>();
        if (fulfilmentObj.Enclosure1__c != null)
            enclosureIds.add(fulfilmentObj.Enclosure1__c);
        if (fulfilmentObj.Enclosure2__c != null)
            enclosureIds.add(fulfilmentObj.Enclosure2__c);
        if (fulfilmentObj.Enclosure3__c != null)
            enclosureIds.add(fulfilmentObj.Enclosure3__c);
        if (fulfilmentObj.Enclosure4__c != null)
            enclosureIds.add(fulfilmentObj.Enclosure4__c);
        if (fulfilmentObj.Enclosure5__c != null)
            enclosureIds.add(fulfilmentObj.Enclosure5__c);

        return enclosureIds;
    }
    
	/*******************************************************************
    Purpose: To calculate Total Enclosure Value.
    Param: fulfilmentList
    Param: enclosureIds
    ********************************************************************/
    public static void calcTotalEnclosure(set<Id> enclosureIds, List<cec_Fulfilment__c> fulfilmentList) {
		 //2nd june 2016 - mahesh - To calculate Total Enclosure Value
		 
        Map<Id, cec_Enclosure__c> enclosureById = new Map<Id, cec_Enclosure__c>([SELECT Id, ItemValue__c FROM cec_Enclosure__c WHERE Id IN:enclosureIds ]);

        System.debug('*********enclosureIds************' + enclosureIds);
        System.debug('*********enclosureById ************' + enclosureById );

        for (cec_Fulfilment__c fulfilmentObj : fulfilmentList) {

            fulfilmentObj.TotalEnclosureValue__c = 0;

            if (fulfilmentObj.Enclosure1__c != null && enclosureById.get(fulfilmentObj.Enclosure1__c).ItemValue__c != null
                    && String.isNotBlank(fulfilmentObj.Enclosure1_Quantity__c)) {
                fulfilmentObj.TotalEnclosureValue__c = enclosureById.get(fulfilmentObj.Enclosure1__c).ItemValue__c * Integer.valueOf(fulfilmentObj.Enclosure1_Quantity__c);

                System.debug('*********enclose1************' + fulfilmentObj.TotalEnclosureValue__c);
            } if (fulfilmentObj.Enclosure2__c != null && enclosureById.get(fulfilmentObj.Enclosure2__c).ItemValue__c != null
                    && String.isNotBlank(fulfilmentObj.Enclosure2_Quantity__c)) {
                fulfilmentObj.TotalEnclosureValue__c += enclosureById.get(fulfilmentObj.Enclosure2__c).ItemValue__c * Integer.valueOf(fulfilmentObj.Enclosure2_Quantity__c);

                System.debug('*********enclose2************' + fulfilmentObj.TotalEnclosureValue__c);
            } if (fulfilmentObj.Enclosure3__c != null && enclosureById.get(fulfilmentObj.Enclosure3__c).ItemValue__c != null
                    && String.isNotBlank(fulfilmentObj.Enclosure3_Quantity__c)) {
                fulfilmentObj.TotalEnclosureValue__c += enclosureById.get(fulfilmentObj.Enclosure3__c).ItemValue__c * Integer.valueOf(fulfilmentObj.Enclosure3_Quantity__c);

                System.debug('*********enclose3************' + fulfilmentObj.TotalEnclosureValue__c);
            } if (fulfilmentObj.Enclosure4__c != null && enclosureById.get(fulfilmentObj.Enclosure4__c).ItemValue__c != null
                    && String.isNotBlank(fulfilmentObj.Enclosure4_Quantity__c)) {
                fulfilmentObj.TotalEnclosureValue__c += enclosureById.get(fulfilmentObj.Enclosure4__c).ItemValue__c * Integer.valueOf(fulfilmentObj.Enclosure4_Quantity__c);

                System.debug('*********enclose4************' + fulfilmentObj.TotalEnclosureValue__c);
            } if (fulfilmentObj.Enclosure5__c != null && enclosureById.get(fulfilmentObj.Enclosure5__c).ItemValue__c != null
                    && String.isNotBlank(fulfilmentObj.Enclosure5_Quantity__c)) {
                fulfilmentObj.TotalEnclosureValue__c += enclosureById.get(fulfilmentObj.Enclosure5__c).ItemValue__c * Integer.valueOf(fulfilmentObj.Enclosure5_Quantity__c);

                System.debug('*********enclose5************' + fulfilmentObj.TotalEnclosureValue__c);
            }

        }
    }
}