src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <fields>
        <fullName>Region__c</fullName>
        <description>Purpose : Created to display region value from user object 
Data Source : SAP | Integration : Mule | Security Level : Restricted</description>
        <label>NFS Region</label>
        <picklist>
            <controllingField>Zone__c</controllingField>
            <picklistValues>
                <fullName>10007 Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10100 Non-Comm Region 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10200 Retail FS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10500 Redistribution - US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10600 Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10610 Club Stores - US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10620 Cash &amp; Carry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10800 C-Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53000 East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53010 Mid Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53015 Tri State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53020 New England</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54100 Obsolete/Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54200 Pepsi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55000 West Zone Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55005 Non-Comm Region 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55015 Midwest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55020 North central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55030 South Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55035 Mountain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55040 West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55045 West Client delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56005 Non-Comm Region 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56010 Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56015 Buying Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56020 Corporate Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56025 OCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59000 South CDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59005 East CDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59010 Redistribution - CA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Purpose : Created to display territory value from user object
Data Source : SAP | Integration : Mule | Security Level : Restricted</description>
        <label>NFS Territory</label>
        <picklist>
            <picklistValues>
                <fullName>55015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55030</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55035</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55045</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>89010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>89100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>82100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>82200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10610</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10620</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10600</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10800</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10200</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Purpose : Created to display user Zone value from user object
Data Source : SAP | Integration : Mule | Security Level : Restricted</description>
        <label>NFS Zone</label>
        <picklist>
            <picklistValues>
                <fullName>55 West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56 OCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>57 Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>58 South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59 East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80 Intercompany - FS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>81 Redistribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>82 Disposal/Exited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>83 Non-Comm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>84 Corp Accts/BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>85 Club, Cash &amp; Carry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>86 Specialty Channels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>87 Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>88 Retail Foodservice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FS_User_Territory__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>NAFS User Zone</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>FS User Territory</label>
</CustomObject>

src/objects/Territory__c.object
<CustomObject>
    <description>Store the territory code related with sales rep.</description>
    <label>Territory</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Territory</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FS_Utility.cls
/**********************************************************************
Purpose: Utility class for Food Solution (NAFS).
History :
VERSION AUTHOR         DATE         DETAIL Description
1.0     Accenture    11/May/2016     Utility class of NAFS project
                     10/June/2016    Updated to add test user creation method  
***********************************************************************/

public with sharing Class FS_Utility{
    private static boolean OppProduct= true;//Used in after update trigger - FS_OpportunityHelper
    private static boolean runaccPlan = true;
    private static boolean runobj = true;
    private static boolean ContractProduct= true;//Used in after update trigger - FS_ContractProductHelper
    public static boolean runOnceOppProduct(){
        if(OppProduct){
            OppProduct=false;
            return true;
        }else{
            return OppProduct;
        }
    }
    public static boolean runaccPlanOnce(){
        if(runaccPlan){
            runaccPlan=false;
            return true;
        }else{
            return runaccPlan;
        }
    }
    public static boolean runObjOnce(){
        if(runobj){
            runobj=false;
            return true;
        }else{
            return runobj;
        }
    } 
    public static boolean runOnceContractProduct(){
        if(ContractProduct){
            ContractProduct=false;
            return true;
        }else{
            return ContractProduct;
        }
    }
    
    Public Static map<String,String> recordTypewithName(String Name)
    {
        map<String,String> recordTypeWithName=new map<String,String>();
        List<RecordType> recordTypeWithNameList=[select id,DeveloperName from RecordType where sObjectType=:Name];
        for(RecordType varRecord:recordTypeWithNameList)
        {
        recordTypeWithName.put(varRecord.DeveloperName,varRecord.id);
        }
        return recordTypeWithName;
    }
    
    //This method is being called from FS Process Builder
    @InvocableMethod(label='Get Owners Custom Settings' description='')
    public static void getDefaults(List<Account> accounts) {
        list<Account> acts = new list<Account>();
        //list<ID> listOwner = new list<ID>();
        
        for(Account a : accounts){
           FS_User_Territory__c ut = FS_User_Territory__c.getInstance(a.ownerId);
           acts.add(new Account(Id=a.Id, Region__c = ut.Region__c,FS_CHD_Lock__c=true, Zone__c=ut.Zone__c, Territory__c=ut.Territory__c));//CurrencyIsoCode='CAD'
        }
        try{
            update acts;
        }catch(Exception e){
            system.debug(e);
        }
    }    
    
   }