src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>A rostered agency</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Matrix__c.object
<CustomObject>
    <description>Will represent an Agencies annual bonus results on an entity level</description>
    <fields>
        <fullName>AF_Bonus_Results__c</fullName>
        <description>AgencyFee#GLOBAL#To relate to  bonus results.</description>
        <label>Bonus Results</label>
        <referenceTo>AF_Bonus_Results__c</referenceTo>
        <relationshipLabel>Bonus Matrix</relationshipLabel>
        <relationshipName>Bonus_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Bonus_Summary__c</fullName>
        <description>Link to Parent Object for approval process and rollup summaries</description>
        <label>Bonus Summary</label>
        <referenceTo>AF_Bonus_Summary__c</referenceTo>
        <relationshipLabel>Bonus Matrix</relationshipLabel>
        <relationshipName>Bonus_Matrix</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store brand estimate.</description>
        <label>Brand Estimate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand Name</description>
        <formula>AF_Bonus_Results__r.AF_Bonus_Thresholds__r.AF_Brand_Estimate__r.Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <label>Bonus Matrix</label>
    <nameField>
        <label>Bonus Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Results__c.object
<CustomObject>
    <description>Will represent the quantitative and qualitative quarterly and annual bonus figures. There can be one or more bonus input records associated to one brand estimate</description>
    <fields>
        <fullName>AF_Bonus_Thresholds__c</fullName>
        <description>AgencyFee#GLOBAL#To store Bonus Thresholds values  associated to Bonus Thresholds Object</description>
        <label>Bonus Thresholds</label>
        <referenceTo>AF_Bonus_Threshold__c</referenceTo>
        <relationshipLabel>Bonus Results</relationshipLabel>
        <relationshipName>Bonus_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Bonus Results</label>
    <nameField>
        <displayFormat>BR-{00000000}</displayFormat>
        <label>Bonus Results Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bonus Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Summary__c.object
<CustomObject>
    <description>It Will represent a Unilever Bonus Fee estimate for a particular brand, fiscal year and agency combination.</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the Agency name / id</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bonus Summaries</relationshipLabel>
        <relationshipName>Bonus_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <formula>AF_Agency__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency Name</label>
        <type>Text</type>
    </fields>
    <label>Bonus Summary</label>
    <nameField>
        <label>Bonus Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Threshold__c.object
<CustomObject>
    <description>Will represent the threshold bonus targets for a brand estimate. There can be one or more thresholds per brand estimate, on a country by country basis.</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To Store the values for Brand Estimate</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Bonus Thresholds</relationshipLabel>
        <relationshipName>Bonus_Thresholds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores name of the Agency</description>
        <label>Agency Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bonus Thresholds</relationshipLabel>
        <relationshipName>Bonus_Thresholds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bonus Threshold</label>
    <nameField>
        <label>Bonus Threshold Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Thresholds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store Agencies associated to account</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Bonus_Threshold__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores Bonus Threshold Record</description>
        <label>Bonus Threshold</label>
        <referenceTo>AF_Bonus_Threshold__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store the Brands associated to Brand Estimate</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Category_Brand__c.object
<CustomObject>
    <description>Used to store Categories and associated brands related to Agency Fee Application.</description>
    <fields>
        <fullName>AF_Category_Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To associate brands to corresponding Categories</description>
        <label>Category</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Category-Brands</relationshipLabel>
        <relationshipName>Category_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Category-Brands</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category-Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AF_Currency__c.object
<CustomObject>
    <description>Will represent exchange and spot rate figures for all the world currencies</description>
    <label>Currency</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Currency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AF_Entity__c.object
<CustomObject>
    <description>Will represent the geographic working area where Unilever or an agency is operating. There will be 2 record types, one for Unilever Entities and one for Agency Entities</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate Entity with Agency</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entity</relationshipLabel>
        <relationshipName>Entity</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DummyUser__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains ID for Dummy user used in Approval process. This must be populated else you will see Error in Log when approval process fires - Exception no Manager specified</description>
    <label>AF_DummyUserID</label>
</CustomObject>

src/classes/AF_AfterUpdateBonusResHandler_Test1.cls
/*****************************************************************************************************************************
@Author :Cognizant
@name : Test_AF_AfterUpdateBonusResHandler
@CreateDate : 13/9/2014
@Description : This is a Test class for AF_AfterUpdateBonusResHandler class,       
@Version : 1.0
@reference : none
****************************************************************************************************************************/
@isTest
public class AF_AfterUpdateBonusResHandler_Test1
{
    Static Integer IcurrYear = System.Today().year();
    Static string currYear=string.valueof(IcurrYear);
    static user stdUserForResourceAllocation;
     /***********************************************************************************
*  @Description: this method will the test data
*  @name : AF_AfterUpdateBonusResHandler
*  @param : none.
*  @return: none.
*************************************************************************************/
    Static testMethod void AF_AfterUpdateBonusResHandler(){
        Test.startTest();
        stdUserForResourceAllocation=AF_TestFactory_Helper.createUserAdmin(true);
        User u=[SELECT id FROM user WHERE id=:stdUserForResourceAllocation.id LIMIT 1];
        System.runAs(u)
        { 
            //Insert Account
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,true);
            List<Account> acctQuery = [SELECT id FROM account LIMIT 1];
            System.Assert(acctQuery[0].Id != null, AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,true);
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE and Id IN:AFCategoryBrand LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.BRAND_RECORD);
            //Insert BrandEstimate
            List<AF_Brand_Estimate__c> BrandEst = AF_TestFactory_Helper.insertAFBrandEstList(1,true);
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c where Id IN:BrandEst LIMIT 1]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRANDESTIMATE_RECORD);
            //Insert Agency Entity
            List<AF_Entity__c> AFEntity = AF_TestFactory_Helper.insertAgencyEntityList(1,true);
            System.assertEquals(AFEntity[0].AF_Agency__c, acc[0].id,AF_TestFactory_Helper.AGENCY_ENTITY);
            List<AF_Entity__c> AFEntityQuery = [SELECT AF_Agency__c FROM AF_Entity__c where RecordTypeId=:AF_TestFactory_Helper.AF_AGENCY_ENTITY_RECTYPE and Id IN:AFEntity LIMIT 1];
            System.assertEquals(AFEntityQuery[0].AF_Agency__c, acc[0].id,AF_TestFactory_Helper.AGENCY_ENTITY);
            //Insert Unilever Entity
            List<AF_Entity__c> AFUnileverEntity = AF_TestFactory_Helper.insertUnileverEntityListRec(1,true);
            List<AF_Entity__c> AFUnileverEntityQuery = [SELECT Id FROM AF_Entity__c where RecordTypeId=:AF_TestFactory_Helper.AF_UNILIVER_ENTITY_RECTYPE and Id IN:AFUnileverEntity LIMIT 1];
            System.Assert(AFUnileverEntityQuery[0].Id != null,AF_TestFactory_Helper.UNILEVER_ENTITY);
            //Insert Currency
            List<AF_Currency__c> AFCurrency = AF_TestFactory_Helper.insertAFcurrencyList(1,true);
            List<AF_Currency__c> AFCurrencyQuery = [SELECT Id FROM AF_Currency__c where Id IN:AFCurrency LIMIT 1];
            System.Assert(AFCurrencyQuery[0].Id != null, AF_TestFactory_Helper.CURRENCY_RECORD);
            //Insert Dummyuser Custom settings
            List<DummyUser__c> duuser = AF_TestFactory_Helper.createDummyUser(true);
            System.Assert(duuser[0].Id != null, AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert Bonus Summary
            List<AF_Bonus_Summary__c> AFBonusSummary = AF_TestFactory_Helper.insertBonusSummary(1,true);
            List<AF_Bonus_Summary__c> AFBonusSummaryQuery = [Select AF_Agency__c from AF_Bonus_Summary__c where Id IN:AFBonusSummary LIMIT 1];
            System.assertEquals(AFBonusSummaryQuery[0].AF_Agency__c,acc[0].id,AF_TestFactory_Helper.BONUSSUMMARY_RECORD);
            //Insert Bonus Threshold
            List<AF_Bonus_Threshold__c> BonusThreshold =  AF_TestFactory_Helper.insertBonusThreshhold(1,true);
            List<AF_Bonus_Threshold__c> BonusThresholdQuery = [Select Agency_Name__c from AF_Bonus_Threshold__c where Id IN:BonusThreshold LIMIT 1];
            System.assertEquals(BonusThresholdQuery[0].Agency_Name__c,acc[0].id,AF_TestFactory_Helper.BONUSTHERSHOLD_RECORD);
            //Insert Bonus Results 
            List<AF_Bonus_Results__c> AFBonusRes = AF_TestFactory_Helper.insertBonusResults(1,true);
            List<AF_Bonus_Results__c> AFBonusResQuery = [Select AF_Bonus_Thresholds__c from AF_Bonus_Results__c where Id IN:AFBonusRes LIMIT 1];
            System.assertEquals(AFBonusResQuery[0].AF_Bonus_Thresholds__c,BonusThresholdQuery[0].id,AF_TestFactory_Helper.BONUSRESULT_RECORD);
            //Insert Bonus Matrix
            List<AF_Bonus_Matrix__c> AFBonusMat = AF_TestFactory_Helper.insertBonusMatrix(1,true);
            List<AF_Bonus_Matrix__c> AFBonusMatQuery = [Select AF_Bonus_Results__c from AF_Bonus_Matrix__c where Id IN:AFBonusMat LIMIT 1];
            System.assertEquals(AFBonusMatQuery[0].AF_Bonus_Results__c,AFBonusResQuery[0].id,AF_TestFactory_Helper.BONUSMATRIX_RECORD);
            AF_AfterUpdateBonusResHandler.AF_AfterUpdHandler(AFBonusRes);
            Test.stopTest();
        }
    }
}