src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>A rostered agency</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store Agencies associated to account</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Category__c</fullName>
        <description>Stores value of Category Used in Reporting</description>
        <formula>Brand__r.AF_Category_Brands__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Pilot_Model__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check for Pilot model</description>
        <label>Pilot Model</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Status_Base_Fees__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Status for Base Fees</description>
        <label>Status Base Fees</label>
        <picklist>
            <picklistValues>
                <fullName>Initiate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency (Draft)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With CMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Controller Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Bonus Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store the Brands associated to Brand Estimate</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Category_Brand__c.object
<CustomObject>
    <description>Used to store Categories and associated brands related to Agency Fee Application.</description>
    <fields>
        <fullName>AF_Category_Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To associate brands to corresponding Categories</description>
        <label>Category</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Category-Brands</relationshipLabel>
        <relationshipName>Category_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Category__c</fullName>
        <description>Not Used</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deodorants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HHC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ice Cream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laundry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savoury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCC &amp; Dressing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Cleansing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Pilot_Model__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Not Used</description>
        <label>Pilot Model</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Super_category__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Super Catgeories</description>
        <label>Super category</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drinks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foods</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Category-Brands</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category-Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AF_OOPS_Actual__c.object
<CustomObject>
    <description>Will represent the actual quarterly expenses recorded by an agency for a particular brand</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <description>AgencyFee#GLOBAL#Created for the sharing Rules, To share OOPs Actual related data to corresponding agency. Value will be populated using a trigger.</description>
        <label>Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Agency_lk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OOPS Actuals</relationshipLabel>
        <relationshipName>OOPS_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the Brand for the Oops record</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>OOPS Actuals</relationshipLabel>
        <relationshipName>OOPS_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Category__c</fullName>
        <description>Stores the Category - used in reporting</description>
        <formula>AF_Brand__r.AF_Category_Brands__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Status__c</fullName>
        <description>Status of Opps Actual</description>
        <label>AF_Status</label>
        <picklist>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>OOPS Actual</label>
    <nameField>
        <label>OOPS Actual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OOPS Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_OOPS_Estimate__c.object
<CustomObject>
    <description>Will represent the out of pocket expense estimation agreed upon between Unilever and an agency for a particular brand</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate OOPs Estimate to brand estimates</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>OOPS Estimates</relationshipLabel>
        <relationshipName>OOPS_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <formula>AF_OOPS_Actual__r.AF_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_OOPS_Actual__c</fullName>
        <description>Parent record of oops estimate</description>
        <label>OOPS Actual</label>
        <referenceTo>AF_OOPS_Actual__c</referenceTo>
        <relationshipLabel>OOPS Estimates</relationshipLabel>
        <relationshipName>OOPS_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Status__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Status for OOPS Estimate</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>with agency (draft)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>with category finance</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>with agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>with CMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for PO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>OOPS Estimate</label>
    <nameField>
        <label>OOPS Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OOPS Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AF_Agency_Fees_User_Type__c</fullName>
        <label>Agency Fees User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO Super User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Category Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <description>This represents Brands on the user level</description>
        <inlineHelpText>List of brands assigned to user</inlineHelpText>
        <label>Brand</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AF_Category__c</fullName>
        <description>This represents the categories</description>
        <inlineHelpText>List of Categories assigned to the user</inlineHelpText>
        <label>Category</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_AF_OOPSEstimateController.cls
/**
 * Test_AF_OOPSEstimateController : This Test class for AF_OOPSEstimateController apex class
 * @author 
 *
 */
@isTest(SeeAlldata=false)
public class Test_AF_OOPSEstimateController 
{    
    Static Integer IcurrYear = System.Today().year();
    Static string currYear=string.valueof(IcurrYear);
    Static testMethod void oopsEstimateController()
    {          
     Test.startTest();
     
     Profile p=[Select Id from Profile where Name='System Administrator'];       
     
     //Insert User 
     User u= new User(Alias = 'testoc', Email='standarduseroc@unilever.com', 
      EmailEncodingKey='UTF-8', LastName='Test Useroc', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = p.Id, 
      TimeZoneSidKey='Europe/London',AF_Agency_Fees_User_Type__c='Category Finance',isActive=true, 
      UserName='testuseroc@test123321.com',AF_Brand__c='Test Brandoc',AF_Category__c='Test Beveragesoc');
     insert u;        
      
     System.runAs(u)
     { 
     
     //Insert Account
     Account acc=new Account();
     acc.Name='Test Agencyoc';
     acc.published__c=true;
     insert acc;
     
     System.Assert(acc.Id != null, 'The account record not inserted');
     
     //Insert Category
     RecordType catRT = [select id,Name from RecordType where SobjectType='AF_Category_Brand__c' and Name='Category' Limit 1];
     AF_Category_Brand__c cat=new AF_Category_Brand__c();
     cat.RecordTypeId=catRT.Id;
     cat.Name='Test Beveragesoc';
     cat.AF_Pilot_Model__c=false;     
     cat.AF_Super_category__c='Drinks';
     insert cat;
     
     System.Assert(cat.Id != null, 'The Category record not inserted');
     
     //Insert Brand
     RecordType brandRT = [select id,Name from RecordType where SobjectType='AF_Category_Brand__c' and Name='Brand' Limit 1];
     AF_Category_Brand__c bran=new AF_Category_Brand__c();
     bran.RecordTypeId=brandRT.Id;
     bran.AF_Pilot_Model__c=false;    
     bran.Name='Test Brandoc';
     bran.AF_Category_Brands__c=cat.Id;
     insert bran;
     
     System.assertEquals(bran.AF_Category_Brands__c, cat.Id);
     
     //Insert Brand Estimate                  
     AF_Brand_Estimate__c brandEst=new AF_Brand_Estimate__c();
     brandEst.AF_Agency__c=acc.Id;               
     brandEst.Name='Test BrandEstimateoc';
     brandEst.AF_Status_Base_Fees__c='Initiate';  
     brandEst.Brand__c=bran.id;
     insert brandEst;
     
     System.assertEquals(brandEst.Brand__c, bran.id);

     
     //Insert OOPS Actual
     AF_OOPS_Actual__c oopsActual=new AF_OOPS_Actual__c();
     oopsActual.AF_Agency_lk__c=acc.Id;
     oopsActual.AF_Brand__c=bran.Id;
     oopsActual.AF_Agency__c=acc.Id;
     oopsActual.AF_Status__c='with agency';
     insert oopsActual;
     
     AF_Currency__c curr = new AF_Currency__c();
     curr.AF_Country__c = 'Ecuador';
     curr.AF_Currency_Code__c = 'USD';
     curr.Country_Currency__c = 'Eucador-USD';
     curr.AF_Fiscal_Year_new__c = currYear ;
     curr.Currency_Unit__c = 'US $';
     curr.AF_Fiscal_Year__c = system.today();
     curr.AF_Average_Exchange_Rate_To_EUR__c = 1.3253;
     curr.Ready_For_PO_Exchange_Rate_SGD_To_USD__c=1.0000;
     curr.Ready_For_PO_Exchange_Rate_To_EUR__c = 1.6112;
     insert curr;
     
     //Insert OOPS Estimate
     AF_OOPS_Estimate__c oopsEst=new AF_OOPS_Estimate__c();
     oopsEst.AF_Brand_Estimate__c=brandEst.Id;
     oopsEst.AF_OOPS_Actual__c=oopsActual.Id;
     oopsEst.AF_Estimate__c=75;
     oopsEst.AF_Status__c='Ready for PO';
     insert oopsEst; 
     
     ApexPages.currentPage().getParameters().put('id',oopsEst.id);         
     AF_OOPSEstimateController oopsEstCtrl=new AF_OOPSEstimateController();
     oopsEstCtrl.Save();
     oopsEstCtrl.SavePO();
     
     //Insert OOPS Actual
     AF_OOPS_Actual__c oopsActual1=new AF_OOPS_Actual__c();
     oopsActual1.AF_Agency_lk__c=acc.Id;
     oopsActual1.AF_Brand__c=bran.Id;
     oopsActual1.AF_Agency__c=acc.Id;
     oopsActual1.AF_Status__c='Ready For PO ';
     oopsActual1.Name = 'Axe-Q1-2015';
     oopsActual1.Quarter__c='Q1';
     insert oopsActual1;
     
     //Insert OOPS Estimate
     AF_OOPS_Estimate__c oopsEst1=new AF_OOPS_Estimate__c();
     oopsEst1.AF_Brand_Estimate__c=brandEst.Id;
     oopsEst1.AF_OOPS_Actual__c=oopsActual1.Id;
     oopsEst1.AF_Estimate__c=75;
     oopsEst1.AF_Status__c='Ready For PO';
     
     insert oopsEst1; 
     
     ApexPages.currentPage().getParameters().put('id',oopsEst1.id);         
     AF_OOPSEstimateController oopsEstCtrl1=new AF_OOPSEstimateController();
     oopsEstCtrl1.Save();
     oopsEstCtrl1.SavePO();
     
     delete oopsActual1;
     
     }
  }
}