src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>A rostered agency</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Agency_Estimate__c.object
<CustomObject>
    <description>Will represent an agency base fee estimate for a particular brand and agency combination</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store brand estimate.</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Agency Estimates</relationshipLabel>
        <relationshipName>Agency_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Category__c</fullName>
        <description>AgencyFee#GLOBAL#Created for the sharing Rules, To share agency estimates based on the category.Field Value will be populated using a trigger.</description>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_isComment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether a comment has been made against the record</description>
        <label>isComment</label>
        <type>Checkbox</type>
    </fields>
    <label>Agency Estimate</label>
    <nameField>
        <label>Agency Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Matrix__c.object
<CustomObject>
    <description>Will represent an Agencies annual bonus results on an entity level</description>
    <fields>
        <fullName>AF_Bonus_Summary__c</fullName>
        <description>Link to Parent Object for approval process and rollup summaries</description>
        <label>Bonus Summary</label>
        <referenceTo>AF_Bonus_Summary__c</referenceTo>
        <relationshipLabel>Bonus Matrix</relationshipLabel>
        <relationshipName>Bonus_Matrix</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store brand estimate.</description>
        <label>Brand Estimate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_isComment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether a comment has been made against the record</description>
        <label>isComment</label>
        <type>Checkbox</type>
    </fields>
    <label>Bonus Matrix</label>
    <nameField>
        <label>Bonus Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Summary__c.object
<CustomObject>
    <description>It Will represent a Unilever Bonus Fee estimate for a particular brand, fiscal year and agency combination.</description>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the brand id/name</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Bonus Summaries</relationshipLabel>
        <relationshipName>Bonus_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Category__c</fullName>
        <formula>AF_Brand__r.AF_Category_Brands__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <label>Bonus Summary</label>
    <nameField>
        <label>Bonus Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_Category__c</fullName>
        <description>Stores value of Category Used in Reporting</description>
        <formula>Brand__r.AF_Category_Brands__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_isComment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether a comment has been made against the record</description>
        <label>Is Comment</label>
        <type>Checkbox</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Comments__c.object
<CustomObject>
    <description>Will capture all comments posted by users and will allow reporting on these comments to be possible</description>
    <fields>
        <fullName>AF_Agency_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate Comments to Agency estimates.</description>
        <label>Agency Estimate</label>
        <referenceTo>AF_Agency_Estimate__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Bonus_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bonus Summary</label>
        <referenceTo>AF_Bonus_Summary__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Bonus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate comments to Bonus Matrix.</description>
        <label>Bonus</label>
        <referenceTo>AF_Bonus_Matrix__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate comments to brand estimates.</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Comments__c</fullName>
        <description>AgencyFee#GLOBAL#To enter the comments</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AF_OOPS_Actual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates comments to OOps Actual</description>
        <label>OOPS Actual</label>
        <referenceTo>AF_OOPS_Actual__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_OOPS_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate comments with OOPs estimates.</description>
        <label>OOPS Estimate</label>
        <referenceTo>AF_OOPS_Estimate__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Parent_Object_Type__c</fullName>
        <description>A literal value to allow us to perform casting in APEX to the object type the comment relates. This is not suited to being a pick list.</description>
        <label>AF_Parent_Object_Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Parent_Record_Id__c</fullName>
        <description>The parent record the comment belongs to.</description>
        <label>AF_Parent_Record_Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Public__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Used to show Comments to Both Internal and External Users
Unchecked - Comments only shown to Internal</inlineHelpText>
        <label>AF_Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Type__c</fullName>
        <description>AgencyFee#GLOBAL#To Store type.</description>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerName__c</fullName>
        <formula>CreatedBy.FirstName + &apos; &apos; +  CreatedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OwnerName</label>
        <type>Text</type>
    </fields>
    <label>Comments</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AF_OOPS_Actual__c.object
<CustomObject>
    <description>Will represent the actual quarterly expenses recorded by an agency for a particular brand</description>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the Brand for the Oops record</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>OOPS Actuals</relationshipLabel>
        <relationshipName>OOPS_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Category__c</fullName>
        <description>Stores the Category - used in reporting</description>
        <formula>AF_Brand__r.AF_Category_Brands__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_OOPS_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store the Roll up summary value of Estimates from OOPS Estimate object.</description>
        <label>OOPS Estimate</label>
        <summarizedField>AF_OOPS_Estimate__c.AF_Estimate__c</summarizedField>
        <summaryForeignKey>AF_OOPS_Estimate__c.AF_OOPS_Actual__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>OOPS Actual</label>
    <nameField>
        <label>OOPS Actual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OOPS Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_OOPS_Estimate__c.object
<CustomObject>
    <description>Will represent the out of pocket expense estimation agreed upon between Unilever and an agency for a particular brand</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate OOPs Estimate to brand estimates</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>OOPS Estimates</relationshipLabel>
        <relationshipName>OOPS_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <formula>AF_OOPS_Actual__r.AF_Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_OOPS_Actual__c</fullName>
        <description>Parent record of oops estimate</description>
        <label>OOPS Actual</label>
        <referenceTo>AF_OOPS_Actual__c</referenceTo>
        <relationshipLabel>OOPS Estimates</relationshipLabel>
        <relationshipName>OOPS_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_isComment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracks whether a comment has been created against the record</description>
        <label>isComment</label>
        <type>Checkbox</type>
    </fields>
    <label>OOPS Estimate</label>
    <nameField>
        <label>OOPS Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OOPS Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AF_Agency_Fees_User_Type__c</fullName>
        <label>Agency Fees User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO Super User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Category Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <description>This represents Brands on the user level</description>
        <inlineHelpText>List of brands assigned to user</inlineHelpText>
        <label>Brand</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AF_Category__c</fullName>
        <description>This represents the categories</description>
        <inlineHelpText>List of Categories assigned to the user</inlineHelpText>
        <label>Category</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AF_CommentsListCompController.cls
public with sharing class AF_CommentsListCompController{

    //Members
    public String ParentRecordId {get;set;}
    public String ParentObjectType {get;set;}
    public String brandvalue1{get;set;}
    public String category1{get;set;}
    public String year1{get;set;}
    public Boolean IsDisplayed {get;set;}
    public string IsViewAll{get;set;}
    public Boolean IsViewAllLink{get;set;}
    public string CommentId{get;set;}
    public string ReturnPageURL{get;set;}
    public string commentValue{get;set;}
    public boolean isAgencyFlag{get;set;} //to check wether logged in user is partner user or not
    public AF_Comments__c CommentRecord {get;set;}
    public List<CustomException> ErrorCollection {get;set;}
    public boolean isCMCOUser{get;set;}  
    public  List<AF_Comments__c> commentsList;
    public Id myCommentId{get;set;}
    public Id myCreateId{get;set;}
    public Boolean bCMCOSuperUser{get;set;}
    public Id LoggedId{get;set;}
    public AF_CommentsListCompController()
    
    {   
        isCMCOUser=false;
        bCMCOSuperUser=false;
        LoggedId = UserInfo.getUserId();
        User userObj = new User();
        userObj = [select Id,Contact.Account.Name, AF_Category__c, AF_Brand__c,Profile.Name, AF_Agency_Fees_User_Type__c from User where Id =:UserInfo.getUserId()];
        if(userObj.AF_Agency_Fees_User_Type__c=='Agency'){
            isAgencyFlag=true;
        }
        if(userObj.AF_Agency_Fees_User_Type__c=='CMCO User'){
            isCMCOUser=true;
        }  
        if(userObj.AF_Agency_Fees_User_Type__c=='CMCO Super User'){
            bCMCOSuperUser=true;
        }   
        IsDisplayed = false;        
        if(ApexPages.currentPage().getParameters().get('Id') != null)
        {
            CommentId = ApexPages.currentPage().getParameters().get('Id');          
        }
        ErrorCollection = new List<CustomException>();        
        CommentRecord = new AF_Comments__c();           
    }
    
    public List<AF_Comments__c> getCommentsList()
    {
        List<AF_Comments__c> comments;
        commentsList = new List<AF_Comments__c>();
        IsDisplayed = false;                                
        if(IsViewAll == 'true')
        {
            IsDisplayed = true;
            IsViewAllLink = false;
            comments = [select id, Name, AF_Type__c,AF_Public__c, AF_Parent_Record_Id__c, CreatedById, OwnerName__c, CreatedDate, AF_Comments__c from AF_Comments__c WHERE AF_Parent_Record_Id__c = : ParentRecordId ORDER BY CreatedDate DESC];    
        }
        else
        {
            IsViewAllLink = true;
            comments = [select id, Name, AF_Type__c, AF_Public__c,AF_Parent_Record_Id__c, CreatedById, OwnerName__c, CreatedDate, AF_Comments__c from AF_Comments__c WHERE AF_Parent_Record_Id__c = : ParentRecordId ORDER BY CreatedDate DESC LIMIT 5];    
        } 
        commentsList.addAll(comments);
        system.debug('myCommentId....'+myCommentId);
        return comments;
    }
    
    public PageReference EditComment()
    {
        ReturnPageURL = ParentRecordId;
        PageReference pageRef =  new PageReference('/apex/AF_EditComment');
        pageRef.getParameters().put('Id', CommentId);
        pageRef.getParameters().put('rp', ReturnPageURL);
        pageRef.setRedirect(true);  
       // return pageRef;
        return null;
    }
    public void SaveCommentEdit(){
    integer i=0;
    myCommentId=null;
    for(AF_Comments__c c:commentsList){
        if(c.AF_Comments__c.length() > 0){
            i++;
        }
    }
    if(i==commentsList.size()){
        system.debug('commentsList....'+commentsList);
        update commentsList;
    }
    
    }
    public void SaveComment()
    {
        //PageReference pageRef = new PageReference('/apex/AF_CloseAndRefresh?IsError=false');
        //pageRef.setRedirect(true); 
            //PageReference pageRef = new PageReference('/apex/AF_AgencyEstimate');
        List<Exception> exceptionCollection = new List<Exception>();
         
        try
        {
            if(CommentRecord.AF_Comments__c.length() > 0)
            {
                
                /*
                CommentRecord.AF_Parent_Record_Id__c = ParentId;
                CommentRecord.AF_Parent_Object_Type__c = ParentRecordType;
                System.debug('CommentRecord.AF_Parent_Record_Id__c : ' +  CommentRecord.AF_Parent_Record_Id__c);
                System.debug('CommentRecord.AF_Parent_Object_Type__c : ' +  CommentRecord.AF_Parent_Object_Type__c);
                */
                
                AF_Comments__c recordsToInsert = new AF_Comments__c();
                recordsToInsert.AF_Parent_Record_Id__c = ParentRecordId;
                recordsToInsert.AF_Parent_Object_Type__c = ParentObjectType;
                recordsToInsert.AF_Comments__c = CommentRecord.AF_Comments__c;
                //recordsToInsert.AF_OOPS_Actual__c = ParentRecordId;
                recordsToInsert.AF_Public__c = CommentRecord.AF_Public__c;
                System.debug('Comment Record was AF_Parent_Object_Type__c: ' +   recordsToInsert.AF_Parent_Object_Type__c);
                System.debug('Comment Record was AF_Parent_Record_Id__c: ' +   recordsToInsert.AF_Parent_Record_Id__c);
                System.debug('Comment Record was recordsToInsert.AF_Comments__c: ' +   recordsToInsert.AF_Comments__c);
                MapToLookups(recordsToInsert);
                insert recordsToInsert;                                
            }             
        }
        catch(Exception ex)
        {
                system.debug(ex);  
        }
        //return pageRef;
    }  
    
    private void MapToLookups(AF_Comments__c pCommentRecord) 
    {
        // this is a helper method that detects ParentObjectType and assign the id to specific looup fields
        if(ParentObjectType == 'AF_Brand_Estimate__c'){System.debug('ParentObjectType was AF_Brand_Estimate__c');pCommentRecord.AF_Brand_Estimate__c = ParentRecordId; UpdateIsCommentOnRecord('AF_Brand_Estimate__c', ParentRecordId);}
        if(ParentObjectType == 'AF_Agency_Estimate__c'){System.debug('ParentObjectType was AF_Agency_Estimate__c');pCommentRecord.AF_Agency_Estimate__c = ParentRecordId; UpdateIsCommentOnRecord('AF_Agency_Estimate__c', ParentRecordId);}
        if(ParentObjectType == 'AF_Bonus_Summary__c'){System.debug('ParentObjectType was AF_Bonus__c');pCommentRecord.AF_Bonus_Summary__c = ParentRecordId;}
        if(ParentObjectType == 'AF_Bonus_Matrix__c'){System.debug('ParentObjectType was AF_Bonus_Matrix__c');pCommentRecord.AF_Bonus__c = ParentRecordId;}
        if(ParentObjectType == 'AF_OOPS_Estimate__c'){System.debug('ParentObjectType was AF_OOPS_Estimate__c');pCommentRecord.AF_OOPS_Estimate__c = ParentRecordId;}        
        //add more here as these mapping are made with comments.         
    }
        
    private void UpdateIsCommentOnRecord(string pObjectType, Id pObjectId)
    {   
        System.debug('UpdateIsCommentOnRecord is running.');
        if(pObjectType == 'AF_Brand_Estimate__c'){try{AF_Brand_Estimate__c objBE    = [select Id, AF_isComment__c from AF_Brand_Estimate__c where Id = : pObjectId];if(objBE != null){objBE.AF_isComment__c = true; update objBE;}}catch(DMLException ex){System.debug(ex);}}
        if(pObjectType == 'AF_Agency_Estimate__c'){try{ AF_Agency_Estimate__c objAE = [select Id, AF_isComment__c from AF_Agency_Estimate__c where Id = : pObjectId];if(objAE != null){System.debug('UpdateIsCommentOnRecord: AF_Agency_Estimate__c.');objAE.AF_isComment__c = true; update objAE;}}catch(DMLException ex){System.debug(ex);}}
        //if(pObjectType == 'AF_Bonus__c'){try{Account obj  = [select Id, IsComment from [object] where Id = : pObjectId];if([obj] != null){obj.IsComment__c = true; update [obj];}}catch(DMLException ex){System.debug(ex);}}
        if(pObjectType == 'AF_OOPS_Estimate__c'){try{AF_OOPS_Estimate__c objOE  = [select Id, AF_isComment__c from AF_OOPS_Estimate__c where Id = : pObjectId];if(objOE != null){objOE.AF_isComment__c = true; update objOE;}}catch(DMLException ex){System.debug(ex);}}        
    }
       
    public class CustomException extends Exception {}
    
    public void editCommentByUsers(){
        system.debug('recordId..'+myCommentId);
        system.debug('myCreateId...'+myCreateId);
        system.debug('loggedin...'+UserInfo.getUserId());
        if(myCreateId!=UserInfo.getUserId() && bCMCOSuperUser==false){
            myCommentId=null;
             apexpages.addmessage(new apexpages.message(apexpages.severity.info,'Comment cannot be Changed')); 
        }
    }
 
}