src/objects/Account.object
<CustomObject>
<!-- TPM Components Start        -->
	
	
	
    <sharingModel>Private</sharingModel>

<!-- TPM Components End          -->
	<!---->
	
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Agency</fullName>
        <active>true</active>
        <description>A rostered agency</description>
        <label>Agency</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Agency_Estimate__c.object
<CustomObject>
    <description>Will represent an agency base fee estimate for a particular brand and agency combination</description>
    <fields>
        <fullName>AF_Adaptation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>AgencyFee#GLOBAL#To Store adaptive value.</description>
        <label>Adaptation</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <description>AgencyFee#GLOBAL#Created for the sharing Rules, To share Agency estimates related data to corresponding agency. Value will be populated using a trigger.</description>
        <label>Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store brand estimate.</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Agency Estimates</relationshipLabel>
        <relationshipName>Agency_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Controller_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AgencyFee#GLOBAL#To Store whether the controller flag is raised or not.</description>
        <label>Controller Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Digital_Local__c</fullName>
        <description>AgencyFee#GLOBAL#To Storedigital local.</description>
        <label>Digital Local</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AF_Digital__c</fullName>
        <defaultValue>0</defaultValue>
        <description>AgencyFee#GLOBAL#To Store Digital base fee.</description>
        <label>Digital</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Fiscal year.</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AgencyFee#GLOBAL#To know whether the record is locked or not.</description>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Traditional__c</fullName>
        <defaultValue>0</defaultValue>
        <description>AgencyFee#GLOBAL#To Store traditional.</description>
        <label>Traditional</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand Name</description>
        <formula>AF_Brand_Estimate__r.Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <label>Agency Estimate</label>
    <nameField>
        <label>Agency Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Bonus_Threshold__c.object
<CustomObject>
    <description>Will represent the threshold bonus targets for a brand estimate. There can be one or more thresholds per brand estimate, on a country by country basis.</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To Store the values for Brand Estimate</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Bonus Thresholds</relationshipLabel>
        <relationshipName>Bonus_Thresholds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Digital__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To include Digital in Bonus Calculation</description>
        <label>Digital</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Traditional__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To include Traditional in Bonus Calculation</description>
        <label>Traditional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Stores Fiscal Year</description>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Bonus Threshold</label>
    <nameField>
        <label>Bonus Threshold Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Thresholds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>AgencyFee#GLOBAL#To check state of Brand Estimate</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Adaptive__c</fullName>
        <defaultValue>0</defaultValue>
        <description>AgencyFee#GLOBAL#To store the adapatation related values</description>
        <label>Adaptive</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers1__c</fullName>
        <description>Holds Email address of agency user. Used for sending notifications to</description>
        <label>AF_AgencyUsers1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store Agencies associated to account</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_BackupQuarter__c</fullName>
        <description>Used to hold the Quarters prior to raise new po</description>
        <label>AF_BackupQuarter</label>
        <picklist>
            <picklistValues>
                <fullName>Q1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>AF_Controller_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AgencyFee#GLOBAL#To check the status of controller flag</description>
        <label>Controller Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Copied__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the base fee has been copied - Raise new PO / Batch Process or Created Manually</description>
        <label>Copied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Digital__c</fullName>
        <defaultValue>0</defaultValue>
        <description>AgencyFee#GLOBAL#To store the digital related values</description>
        <label>Digital</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To the fiscal year details</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Base fee is locked in approval process</description>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Status_Base_Fees__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Status for Base Fees</description>
        <label>Status Base Fees</label>
        <picklist>
            <picklistValues>
                <fullName>Initiate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency (Draft)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With CMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Controller Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Bonus Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Traditional__c</fullName>
        <defaultValue>0</defaultValue>
        <description>AgencyFee#GLOBAL#To store the Traditional related values</description>
        <label>Traditional</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Archived_BrandEstimate_Quarter__c</fullName>
        <description>Shows which quarters were selected prior to raise new po. Created the field for Reporting backup</description>
        <label>Archived BrandEstimate Quarter</label>
        <picklist>
            <picklistValues>
                <fullName>Q1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store the Brands associated to Brand Estimate</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Category_Brand__c.object
<CustomObject>
    <description>Used to store Categories and associated brands related to Agency Fee Application.</description>
    <fields>
        <fullName>AF_Category_Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To associate brands to corresponding Categories</description>
        <label>Category</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Category-Brands</relationshipLabel>
        <relationshipName>Category_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Category-Brands</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category-Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AF_Currency__c.object
<CustomObject>
    <description>Will represent exchange and spot rate figures for all the world currencies</description>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To Store the date when currency uploaded</description>
        <label>Upload Date</label>
        <type>Date</type>
    </fields>
    <label>Currency</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Currency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AF_Entity__c.object
<CustomObject>
    <description>Will represent the geographic working area where Unilever or an agency is operating. There will be 2 record types, one for Unilever Entities and one for Agency Entities</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate Entity with Agency</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entity</relationshipLabel>
        <relationshipName>Entity</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AF_Send_Email_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for Agency contact who will receive the notification after approval process.</description>
        <inlineHelpText>This field is for Agency contact who will receive the notification after approval process.</inlineHelpText>
        <label>Send Email Notifcation</label>
        <type>Checkbox</type>
    </fields>
    
    
    
    
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AF_Bonus_ThresholdHandler_Test.cls
/*****************************************************************************************************************************
@Author :Cognizant
@name : AF_Bonus_ThresholdHandler 
@CreateDate : 10/9/2014
@Description : This is a Test class for AF_Agency_EstimateHandler  class, 
@Version : 1.0
@reference : none
****************************************************************************************************************************/
@isTest(SeeAlldata=false)
public class AF_Bonus_ThresholdHandler_Test
{    
    Static Integer IcurrYear = System.Today().year();
    Static string currYear=string.valueof(IcurrYear);
    static user UserForAF_Bonus_ThresholdHandler ;
    /***********************************************************************************
*  @Description: this method will the test data
*  @name : AF_Bonus_ThresholdHandler
*  @param : none.
*  @return: none.
*************************************************************************************/
    Static testMethod void AF_Bonus_ThresholdHandler()
    {
        Test.startTest();
        UserForAF_Bonus_ThresholdHandler = AF_TestFactory_Helper.createUserAdmin(true);
        User u=[SELECT id,Email FROM user WHERE id=:UserForAF_Bonus_ThresholdHandler.id LIMIT 1];
        System.runAs(u)
        {
            //Insert Account
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,false);
               List<Account> accList = new List<Account>();
            for(Account loopacc : acc){
                loopacc.published__c = true;
                accList.add(loopacc);
            }
            insert acc;
            List<Account> acctQuery = [SELECT id FROM account LIMIT 1];
            System.Assert(acctQuery[0].Id != null, AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert contact.
            List<Contact> contactList = AF_TestFactory_Helper.AFInsertContact(1,false);
            List<Contact> contactList1=new List<Contact>();
            for(contact con : contactList){
                con.Email = 'test@test.com ';
                con.AF_Send_Email_Notification__c=true;
                contactList1.add(con);
            }
            insert contactList1;
            List<contact> conQuery = [SELECT id From Contact LIMIT 1];
            system.assert(conQuery[0].id!=null,AF_TestFactory_Helper.CONTACT_RECORD);
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,true);
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE and Id IN:AFCategoryBrand LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.BRAND_RECORD);
            List<AF_Brand_Estimate__c> BrandEst = AF_TestFactory_Helper.insertAFBrandEstList(1,false);
            List<AF_Brand_Estimate__c> BrandEstlist=new List<AF_Brand_Estimate__c>();
            for(AF_Brand_Estimate__c  loopBrandEst : BrandEst)
            {
                loopbrandEst.AF_Status_Base_Fees__c=AF_Constants.BASE_FEES_READYFORPO;  
                loopbrandEst.AF_Fiscal_Year__c=currYear;
                loopbrandEst.AF_Active__c = true;
                loopbrandEst.AF_Copied__c= false;
                loopbrandEst.AF_Locked__c = false; 
                loopbrandEst.AF_Controller_Flag__c=false;
                loopbrandEst.AF_AgencyUsers1__c=u.Email;
                loopbrandEst.AF_Traditional__c=23;
                loopbrandEst.AF_Digital__c=24;
                loopbrandEst.AF_Adaptive__c=44;
                loopbrandEst.AF_BackupQuarter__c = 'Q1;Q2;Q3';
                loopBrandEst.Archived_BrandEstimate_Quarter__c='Q1;Q2;Q3';
                BrandEstlist.add(loopbrandEst);
            }
            insert BrandEstlist;
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c LIMIT 2]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRANDESTIMATE_RECORD);
            //Insert Agency Entity
            List<AF_Entity__c> AFEntity = AF_TestFactory_Helper.insertAgencyEntityList(1,true);
            List<AF_Entity__c> AFEntityQuery = [SELECT AF_Agency__c FROM AF_Entity__c where RecordTypeId=:AF_TestFactory_Helper.AF_AGENCY_ENTITY_RECTYPE and Id IN:AFEntity LIMIT 1];
            System.assertEquals(AFEntityQuery[0].AF_Agency__c, acc[0].id,AF_TestFactory_Helper.AGENCY_ENTITY);
            List<AF_Entity__c> AFUnileverEntity = AF_TestFactory_Helper.insertUnileverEntityListRec(1,true);
            List<AF_Entity__c> AFUnileverEntityQuery = [SELECT Id FROM AF_Entity__c where RecordTypeId=:AF_TestFactory_Helper.AF_UNILIVER_ENTITY_RECTYPE and Id IN:AFUnileverEntity LIMIT 1];
            System.Assert(AFUnileverEntityQuery[0].Id != null, AF_TestFactory_Helper.UNILEVER_ENTITY);
             //inset Agency Estimate.           
           List<AF_Agency_Estimate__c> AgencyEsitmate = AF_TestFactory_Helper.insertAgencyEstimate(1,false);
            List<AF_Agency_Estimate__c> AgencyEsitmatelist=new List<AF_Agency_Estimate__c>();
            for(AF_Agency_Estimate__c agency : AgencyEsitmate){
                agency.AF_Fiscal_Year__c=currYear;
                agency.AF_Adaptation__c=22;
                agency.AF_Digital__c=22;
                agency.AF_Digital_Local__c=12;
                agency.AF_Traditional__c=22; 
                agency.AF_Status__c=AF_Constants.BASE_FEES_WITH_AGENCY;  
                AgencyEsitmatelist.add(agency);
            }
            insert AgencyEsitmatelist;
            List<AF_Agency_Estimate__c> AgencyQuery = [SELECT Id ,AF_Brand_Estimate__c FROM AF_Agency_Estimate__c WHERE ID IN : AgencyEsitmate limit 1];
            System.assertEquals(AgencyQuery[0].AF_Brand_Estimate__c, BrandEst[0].id,AF_TestFactory_Helper.AGENCYESTIMATE_RECORD);
            // insert currency.
            List<AF_Currency__c> AFCurrency = AF_TestFactory_Helper.insertAFcurrencyList(1,true);
            List<AF_Currency__c> AFCurrencyQuery = [SELECT Id FROM AF_Currency__c LIMIT 1];
            System.AssertEquals(AFCurrencyQuery[0].Id != null,AFCurrency!=null, AF_TestFactory_Helper.CURRENCY_RECORD);
            //Insert Bonus Threshold
            List<AF_Bonus_Threshold__c> BonusThreshold =  AF_TestFactory_Helper.insertBonusThreshhold(1,false);
              List<AF_Bonus_Threshold__c> BonusThresholdLSt = new   List<AF_Bonus_Threshold__c>();
              for(AF_Bonus_Threshold__c bonThres :BonusThreshold){
               bonThres.AF_Traditional__c=true;
                 bonThres.AF_Digital__c=true;
                 bonThres.Year__c=currYear;
                 bonThres.AF_Minimum__c=5;
                 bonThres.AF_Stretching__c=6;
                 bonThres.AF_Outstanding__c=7;
                 BonusThresholdLSt.add(bonThres);
              }
              insert BonusThresholdLSt;
            List<AF_Bonus_Threshold__c> BonusThresholdQuery = [Select Agency_Name__c from AF_Bonus_Threshold__c WHERE ID IN :BonusThresholdLSt LIMIT 1];
            System.assertEquals(BonusThresholdQuery[0].Agency_Name__c,acc[0].id, AF_TestFactory_Helper.BONUSTHERSHOLD_RECORD);
            AF_Bonus_ThresholdHandler threshhold =  new AF_Bonus_ThresholdHandler();
            AF_Bonus_Threshold__c so = new AF_Bonus_Threshold__c();
            AF_Bonus_Threshold__c oldso = new AF_Bonus_Threshold__c();
            threshhold.bulkBefore();
            threshhold.bulkAfter();
            threshhold.beforeInsert(so);
            threshhold.beforeUpdate(oldso,so);
            threshhold.beforeDelete(so);
            threshhold.afterInsert(so);
            threshhold.afterUpdate(oldso,so);
            threshhold.afterDelete(so);
            threshhold.andFinally();
        }
    }
}