src/objects/AF_Agency_Estimate__c.object
<CustomObject>
    <description>Will represent an agency base fee estimate for a particular brand and agency combination</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store brand estimate.</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Agency Estimates</relationshipLabel>
        <relationshipName>Agency_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Total__c</fullName>
        <description>Sum of Traditional , Digital and Adaptation</description>
        <formula>AF_Traditional__c +  AF_Digital__c +  AF_Adaptation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AF_Unilever_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To Store unilever entity.</description>
        <label>Unilever Entity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AF_Entity__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Unilever Entity</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AF_Entity__c</referenceTo>
        <relationshipLabel>Agency Estimates (Unilever entity)</relationshipLabel>
        <relationshipName>Agency_Estimates1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agency Estimate</label>
    <nameField>
        <label>Agency Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_Status_Base_Fees__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Status for Base Fees</description>
        <label>Status Base Fees</label>
        <picklist>
            <picklistValues>
                <fullName>Initiate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency (Draft)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With CMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Controller Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Bonus Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Total__c</fullName>
        <description>AgencyFee#GLOBAL#To store the related values for Total</description>
        <label>Total</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Controller_Review__c.object
<CustomObject>
    <description>To hold review by Controller groups for Brand Estimates</description>
    <fields>
        <fullName>Brand_Estimate__c</fullName>
        <description>Stores the Brand Estimate</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Controller Reviews</relationshipLabel>
        <relationshipName>Controller_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controller_Group__c</fullName>
        <description>Controller Group - comes from Unilever Entity - Controller Group</description>
        <label>Controller Group</label>
        <picklist>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oceania</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Review_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracks if Review is completed</description>
        <label>Review Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Controller Review</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>Controller Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controller Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Entity__c.object
<CustomObject>
    <description>Will represent the geographic working area where Unilever or an agency is operating. There will be 2 record types, one for Unilever Entities and one for Agency Entities</description>
    <fields>
        <fullName>Controller_Group__c</fullName>
        <description>Stores the Controller Group region for the entity. used for Controller Reviews</description>
        <label>Controller Group</label>
        <picklist>
            <picklistValues>
                <fullName>North Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAMETRUB</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AF_Brand_Controller_Review.cls
/*****************************************************************************************************************************
   @Author :Cognizant
   @name : AF_Brand_Controller_Review
   @CreateDate : 6/7/2014
   @Description : This is a controller class for AF_UL_AgencyMatrix Page, 
   @              this is used to query and update the controller review object.
   @Version : 1.0
   @reference : none
  ****************************************************************************************************************************/
public with sharing class AF_Brand_Controller_Review
{
    public static boolean BrandReview=true;
    Map<id,set<string>> mapgroups = new Map<id,set<string>>();
    list<AF_Controller_Review__c> lstReview=new list<AF_Controller_Review__c>();
    Map<id,set<string>> mapgroupCR = new Map<id,set<string>>();
    /***********************************************************************************
*  @Description: this method is used to query and check's the review for all
*  @              records in brandestimate and update it in controller review object
*  @name : Create_Review
*  @param : BrandId
*  @return: none.
*************************************************************************************/
    public void Create_Review(set<id> BrandId)
    {
        for(AF_Brand_Estimate__c AFB:[select id,(select id,Controller_Group__c from Controller_Reviews__r) from AF_Brand_Estimate__c where id in:BrandId])
        {
            if(mapgroupCR.containskey(AFB.id))
            {                
                set<string> setid=mapgroupCR.get(AFB.id);
                for(AF_Controller_Review__c ACR:AFB.Controller_Reviews__r)
                {
                    setid.add(ACR.Controller_Group__c);
                }
                mapgroupCR.put(AFB.id,setid);
            }
            Else
            {
                set<string> setid=new set<string>();
                for(AF_Controller_Review__c ACR:AFB.Controller_Reviews__r)
                {
                    setid.add(ACR.Controller_Group__c);
                }
                mapgroupCR.put(AFB.id,setid);
            }
        }
        for(AF_Agency_Estimate__c AgE:[select id,AF_Brand_Estimate__c,AF_Unilever_Entity__r.Controller_Group__c from AF_Agency_Estimate__c where AF_Total__c > 0 and AF_Brand_Estimate__c in:BrandId])
        {
            if(mapgroups.containskey(AgE.AF_Brand_Estimate__c))
            {
                set<string> setid=mapgroups.get(AgE.AF_Brand_Estimate__c);
                list<string> frontBack=new list<string>();
                if(AgE.AF_Unilever_Entity__r.Controller_Group__c!=null)
                frontBack = AgE.AF_Unilever_Entity__r.Controller_Group__c.split(';');
                for(string str:frontBack)
                {
                    if(!setid.contains(str))
                    {
                        setid.add(str);
                    }
                }
                mapgroups.put(AgE.AF_Brand_Estimate__c,setid);                             
            }
            Else
            {
                set<string> setid=new set<string>();
                list<string> frontBack=new list<string>();
                if(AgE.AF_Unilever_Entity__r.Controller_Group__c!=null)
                frontBack = AgE.AF_Unilever_Entity__r.Controller_Group__c.split(';');
                for(string str:frontBack)
                {
                    setid.add(str);
                }
                mapgroups.put(AgE.AF_Brand_Estimate__c,setid);
            }
        }
        if(!mapgroups.isempty())
        {
            for(id idval: mapgroups.keyset())
            {
                set<string> setCr=mapgroupCR.get(idval);                
                for(string setBr: mapgroups.get(idval))
                {
                    if(!setCr.contains(setBr))
                    {
                        AF_Controller_Review__c AFC=new AF_Controller_Review__c();
                        AFC.Brand_Estimate__c=idval;
                        AFC.Controller_Group__c=setBr;
                        lstReview.add(AFC);
                    }
                }
            }
        }
        if(!lstReview.isempty())
        {
            insert lstReview;
        }
        else
        {
            //Need to check if we have any review not completed - if so leave at current status
            List<AF_Controller_Review__c> exstReviews = new List<AF_Controller_Review__c>([select id from AF_Controller_Review__c where Brand_Estimate__c in:BrandId and Review_Completed__c=false]);
            if (exstReviews.isempty())
            {
                List<AF_Brand_Estimate__c> lstbrandestimates =new List<AF_Brand_Estimate__c>();
                for(AF_Brand_Estimate__c AFB:[select id,(select id,Controller_Group__c from Controller_Reviews__r) from AF_Brand_Estimate__c where id in:BrandId])
                {
                    AFB.AF_Status_Base_Fees__c = 'With CMCO';
                    lstbrandestimates.add(AFB);
                }
                if(!lstbrandestimates.IsEmpty())
                update lstbrandestimates;
                for(AF_Brand_Estimate__c bEstimates:lstbrandestimates){
                    Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();
                    request.setObjectId(bEstimates.Id);
                    request.setComments('Submitted for approval. Please approve.');
                    request.setNextApproverIds(new ID[]{UserInfo.getUserId()});
                    // submit the approval request for processing
                    Approval.ProcessResult result = Approval.process(request);
                }
            }
        }
        AF_CheckRecursive.run=false;
    }
}