src/objects/AF_Agency_Estimate__c.object
<CustomObject>
    <description>Will represent an agency base fee estimate for a particular brand and agency combination</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <description>AgencyFee#GLOBAL#Created for the sharing Rules, To share Agency estimates related data to corresponding agency. Value will be populated using a trigger.</description>
        <label>Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store brand estimate.</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Agency Estimates</relationshipLabel>
        <relationshipName>Agency_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Category_Finance_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to track changes by Cat Fin in approval process</description>
        <label>Category Finance Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Controller_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AgencyFee#GLOBAL#To Store whether the controller flag is raised or not.</description>
        <label>Controller Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Fiscal year.</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Sum_of_Percent__c</fullName>
        <description>Stores the sum of all % from entity exception - Country Breakdown</description>
        <label>Sum of Percent</label>
        <summarizedField>AF_Entity_Exception__c.AF_Value__c</summarizedField>
        <summaryForeignKey>AF_Entity_Exception__c.AF_Agency_Estimate__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand Name</description>
        <formula>AF_Brand_Estimate__r.Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Central_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Not Used</description>
        <label>Central Billing</label>
        <type>Checkbox</type>
    </fields>
    <label>Agency Estimate</label>
    <nameField>
        <label>Agency Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store Agencies associated to account</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Basefee_Estimate_Initial_Quarter__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Basefee Estimate in Initial Quarter</description>
        <label>Basefee Estimate Initial Quarter</label>
        <picklist>
            <picklistValues>
                <fullName>Q1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>AF_CMCO_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is set when CMCO Reject. Used in approval process to render approval buttons</description>
        <label>CMCO Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Category_Finance_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox sets to true when Category Finance users Approves the record.</description>
        <label>Category Finance Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Category_Finance_Flag__c</fullName>
        <description>Counts the Number of Agency Estimates that have been changed since last approval by Cat Fin</description>
        <label>Category Finance Flag</label>
        <summaryFilterItems>
            <field>AF_Agency_Estimate__c.AF_Category_Finance_Flag__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>AF_Agency_Estimate__c.AF_Brand_Estimate__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AF_Controller_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>AgencyFee#GLOBAL#To check the status of controller flag</description>
        <label>Controller Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To the fiscal year details</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_No_Bonus__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox says that there is No Bonus for this combination of Brand Estimate</description>
        <label>No Bonus</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_No_of_Central_Billing__c</fullName>
        <description>Counts the no of agency estimates where Unilever entity is Central Billing</description>
        <label>No of Central Billing</label>
        <summaryFilterItems>
            <field>AF_Agency_Estimate__c.Central_Billing__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>AF_Agency_Estimate__c.AF_Brand_Estimate__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AF_Pilot_Model__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check for Pilot model</description>
        <label>Pilot Model</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_Status_Base_Fees__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Status for Base Fees</description>
        <label>Status Base Fees</label>
        <picklist>
            <picklistValues>
                <fullName>Initiate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency (Draft)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With CMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Controller Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Bonus Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store the Brands associated to Brand Estimate</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExceptionsComplete__c</fullName>
        <description>Used in approval process to check if all country breakdown are at 100%</description>
        <formula>AF_SumofExceptionPercent__c / if(AF_TotalNoOfExceptions__c &gt;0,AF_TotalNoOfExceptions__c ,1)</formula>
        <label>ExceptionsComplete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Comments__c.object
<CustomObject>
    <description>Will capture all comments posted by users and will allow reporting on these comments to be possible</description>
    <fields>
        <fullName>AF_Agency_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate Comments to Agency estimates.</description>
        <label>Agency Estimate</label>
        <referenceTo>AF_Agency_Estimate__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate comments to brand estimates.</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Comments__c</fullName>
        <description>AgencyFee#GLOBAL#To enter the comments</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AF_Parent_Object_Type__c</fullName>
        <description>A literal value to allow us to perform casting in APEX to the object type the comment relates. This is not suited to being a pick list.</description>
        <label>AF_Parent_Object_Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Parent_Record_Id__c</fullName>
        <description>The parent record the comment belongs to.</description>
        <label>AF_Parent_Record_Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Public__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Used to show Comments to Both Internal and External Users
Unchecked - Comments only shown to Internal</inlineHelpText>
        <label>AF_Public</label>
        <type>Checkbox</type>
    </fields>
    <label>Comments</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AF_Controller_Review__c.object
<CustomObject>
    <description>To hold review by Controller groups for Brand Estimates</description>
    <fields>
        <fullName>Brand_Estimate__c</fullName>
        <description>Stores the Brand Estimate</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Controller Reviews</relationshipLabel>
        <relationshipName>Controller_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Review_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracks if Review is completed</description>
        <label>Review Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Controller Review</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>Controller Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controller Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AF_Agency_Fees_User_Type__c</fullName>
        <label>Agency Fees User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO Super User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Category Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <description>This represents Brands on the user level</description>
        <inlineHelpText>List of brands assigned to user</inlineHelpText>
        <label>Brand</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AF_ApprovalProcessForBrandEstController.cls
public Class AF_ApprovalProcessForBrandEstController
{
    public String brandEstimateId {get;set;}
    public String ParentId {get;set;}
    public String brandvalue1{get;set;}
    public String catageory1{get;set;}
    public String year1{get;set;}
    public String ParentRecordType {get;set;}
    Public Boolean Controllerflag{set;get;}
    public Boolean hasProcess {get; set;}
    public List<ProcessInstance> process {get; set;}
    public list<ProcessInstance> Targetprocess{set;get;}
    public List<ProcessInstanceHistory> stepOrWorkItem{get; set;}
    public Boolean hasStep {get; set;}
    Public user LoggedinUser{set;get;}
    Public AF_Brand_Estimate__c BrandEstRecord{set;get;}
    Public list<ProcessInstanceWorkitem> workItem=new list<ProcessInstanceWorkitem>();
    Public id workItemId{set;get;}
    public id NextActorid{set;get;}
    public set<id> Actoridset=new set<id>();
    Public string StatusofBrand{set;get;}
    public list<AF_Agency_Estimate__c>lstofAgencyEst=new list<AF_Agency_Estimate__c>();
    public boolean displayPopup {get; set;}
    public boolean displayPopupRej{set;get;}
    public boolean displayPopupRejComment{set;get;}
    public string RejectComment{set;get;}
    public string ApproveComment{set;get;}
    public boolean ButtonsDisplay{set;get;}
    public boolean Controllerflag1{set;get;}
    public boolean ApprovalButton{set;get;}
    Public boolean IsCatFinanceEdited{get;set;}
    Public boolean isAgency{get;set;}
    public void RejectBrandEstComment()
    {
        displayPopupRejComment=true;
    }
    
    public pagereference RejectBrandWithComments()
    {
        pagereference ref;
        try{
        if(RejectComment==''){
        ref=null;
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter the comments'));
        }
        else if(Actoridset.size()>0)
            {
                
                if(Actoridset.contains(Userinfo.getuserid()))
                {
               
                    Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                    req.setComments(RejectComment); //RejectComment
                    req.setAction('Reject');                    
                    req.setWorkitemId(workItemId);
                    // Submit the request for approval
                    Approval.ProcessResult result =  Approval.process(req);
                    //system.debug('@@@ Rejection Result='+result);
                    
                    AF_Comments__c AfC=new AF_Comments__c();
                    AfC.AF_Brand_Estimate__c=brandEstimateId;
                    AfC.AF_Comments__c=RejectComment;
                    AfC.AF_Parent_Record_Id__c=brandEstimateId;
                    AfC.AF_Public__c=true;
                    AfC.AF_Parent_Object_Type__c='AF_Brand_Estimate__c';
                    insert AfC;
                    
                    System.debug('@@@ Comments record inserted =='+AfC);
                    
                    TempConstructor();
                    displayPopupRejComment=false;
                    displayPopup=false;
                    displayPopUpRej=false;
                    Approvalpopup=false;
                    ref=new pagereference('/apex/AgencyHomePage?brandvalue='+brandvalue1+'category='+catageory1+'year='+year1);
                    ref.setRedirect(true);
                }
                else
                {
                    System.debug('@@@ Comments record not inserted ');
                    ref=null;
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You are not allowed to Approve the record'));
                }
            }    
        }Catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getmessage()));
            ref=null;
        }
        //return ref;
        
        return null;
    }
    
    public pagereference ApproveRecord()
    {
        pagereference ref;
        try{
            if(Actoridset.size()>0)
            {
                if(Actoridset.contains(Userinfo.getuserid()))
                {
                    Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                    req.setComments(''); //ApproveComment
                    req.setAction('Approve');        
                    req.setWorkitemId(workItemId);
                    // Submit the request for approval
                    Approval.ProcessResult result =  Approval.process(req);
                    
                    /*if((LoggedinUser.AF_Agency_Fees_User_Type__c=='Category Finance')) 
                    {
                        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                        req1.setComments('Submitting request for approval automatically ');
                        req1.setObjectId(brandEstimateId);
                        Approval.ProcessResult result1 = Approval.process(req1);                     
                        
                    }*/
                    
                    TempConstructor();
                    displayPopupRejComment=false;
                    displayPopup=false;
                    displayPopUpRej=false;
                    Approvalpopup=false;
                    ref=new pagereference('/apex/AgencyHomePage?brandvalue='+brandvalue1+'category='+catageory1+'year='+year1);
                    ref.setRedirect(true);
                }
                else
                {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You are not allowed to Approve the record'));
                    ref=null;
                }
            }
           }catch(exception e)
           {
               ref=null;
           }
          //  return ref;
          return null;
    }
    
    public pagereference RejectRecord()
    {
        pagereference ref;
        try{
            if(Actoridset.size()>0)
            {
                if(Actoridset.contains(Userinfo.getuserid()))
                {
               
                    Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                    req.setComments(''); //RejectComment
                    req.setAction('Reject');                    
                    req.setWorkitemId(workItemId);
                    // Submit the request for approval
                    Approval.ProcessResult result =  Approval.process(req);
                    //system.debug('@@@ Rejection Result='+result);
                    TempConstructor();
                    displayPopupRejComment=false;
                    displayPopup=false;
                    displayPopUpRej=false;
                    Approvalpopup=false;
                    ref=new pagereference('/apex/AgencyHomePage?brandvalue='+brandvalue1+'category='+catageory1+'year='+year1);
                    ref.setRedirect(true);
                }
                else
                {
                     ref=null;
                     ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You are not allowed to Approve the record'));
                }
            }    
        }Catch(Exception e)
        {
            ref=null;
        }
       // return ref;
         return null;
    }
    
    Public void closePopupReject()
    {
        displayPopupRej=false;
    }
    public void closePopup() {
        displayPopup = false;
    }
    
    public void closePopupRejComment()
    {
        displayPopupRejComment=false;
    }
 
    public void showPopup() {
        displayPopup = true;
    }
    public AF_ApprovalProcessForBrandEstController() 
    {
        
        
        brandEstimateId = ApexPages.currentPage().getParameters().get('id');
        isAgency = false;
        LoggedinUser=[select id,IsActive,Username,Name,AF_Brand__c,AF_Agency_Fees_User_Type__c  from  User  where id=:Userinfo.getuserid()   and IsActive=true  Order by CreatedDate Limit 50000];  
        TempConstructor();
         
    
    }
    
    Public Void TempConstructor()
    {
        IsCatFinanceEdited=false;
        if(brandEstimateId!=null && brandEstimateId!='')
        {    
            Targetprocess=[select Id, TargetObjectId, isDeleted, Status From ProcessInstance Where isDeleted = false and TargetObjectId =:brandEstimateId  and status='Pending' limit 1]; 
            System.debug('&&&&Targetprocess'+Targetprocess);
            BrandEstRecord=[select id,AF_Pilot_Model__c,AF_No_Bonus__c,AF_Basefee_Estimate_Initial_Quarter__c,AF_Category_Finance_Flag__c,Brand__c,AF_Fiscal_Year__c,AF_Category_Finance_Approved__c,AF_CMCO_Rejected__c,AF_Status_Base_Fees__c,AF_Agency__c,AF_Controller_Flag__c,ExceptionsComplete__c,AF_No_of_Central_Billing__c from AF_Brand_Estimate__c  where id=:brandEstimateId  limit 1 ];
           
            if(BrandEstRecord.AF_Category_Finance_Flag__c>0 && BrandEstRecord.AF_Status_Base_Fees__c=='With Agency' && LoggedinUser.AF_Agency_Fees_User_Type__c=='Agency'){
                lstofAgencyEst=[select id,AF_Category_Finance_Flag__c from AF_Agency_Estimate__c where AF_Brand_Estimate__r.id=:brandEstimateId];
            }
            StatusofBrand=BrandEstRecord.AF_Status_Base_Fees__c;
            workItem  =[Select p.Id,P.ActorId from ProcessInstanceWorkitem p where p.ProcessInstance.TargetObjectId =: brandEstimateId  limit 50000];
            if(workItem.size()>0)
            for(ProcessInstanceWorkitem  pis:workItem)
            {
                workItemId=pis.id;
                Actoridset.add(pis.ActorId) ;
            }   
        }
        if(LoggedinUser.AF_Agency_Fees_User_Type__c=='Category Finance' && BrandEstRecord.AF_Status_Base_Fees__c=='With Category Finance' &&  BrandEstRecord.AF_Category_Finance_Flag__c>0){
           IsCatFinanceEdited=true;
        }
        if(LoggedinUser.AF_Agency_Fees_User_Type__c=='Agency'){
            isAgency = true;
        }
        if((BrandEstRecord.AF_Status_Base_Fees__c=='With Agency' && LoggedinUser.AF_Agency_Fees_User_Type__c=='Agency') || 
           (BrandEstRecord.AF_Status_Base_Fees__c=='With CMCO' && LoggedinUser.AF_Agency_Fees_User_Type__c=='CMCO User'))
        {
            ApprovalButton=true;            
        }
        Else
        {
            ApprovalButton=false;
        }
        
        if(Actoridset.contains(LoggedinUser.id))
        {
            ButtonsDisplay=true;
        }
        Else
            ButtonsDisplay=false;
           /** list<AF_Controller_Review__c>lstreview=new list<AF_Controller_Review__c>();
            lstreview=[select id,name from AF_Controller_Review__c where Brand_Estimate__r.id=:brandEstimateId];
            system.debug('lstreview.....'+lstreview);
        if(lstreview.size()==0 && (BrandEstRecord.AF_Status_Base_Fees__c=='With CMCO' && LoggedinUser.AF_Agency_Fees_User_Type__c=='CMCO User')){
               Targetprocess=[select Id, TargetObjectId, isDeleted, Status From ProcessInstance Where isDeleted = false and TargetObjectId =:brandEstimateId  limit 1]; 
               system.debug('Targetprocess....'+Targetprocess);
               ButtonsDisplay=true;
            }**/
    }
    
    public boolean Approvalpopup{set;get;}
    
    public pagereference SubmitApprovalPopup()
    {
        /*if(BrandEstRecord.AF_Status_Base_Fees__c=='With Agency' && BrandEstRecord.ExceptionsComplete__c!=1&&BrandEstRecord.AF_No_of_Central_Billing__c >0)
        {
           // ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please check the country Breakdown percentage'));
            apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.ERROR,'Please indicate the country breakdown percentage within UK');
            apexpages.addmessage(msg); 
            return null;
        }
        Else*/
        // Check whether Country breakdown percentage value is exactly equal to 100, then only allow to Submit for approval else show an error message.
        /* Commented Out Martin O'connell - 12st September
        List<AF_Agency_Estimate__c> AgencyEstimates = new List<AF_Agency_Estimate__c>();
        Boolean ShowFlag = false;
        AgencyEstimates=[Select id,AF_Sum_of_Percent__c from AF_Agency_Estimate__c where AF_Brand_Estimate__r.id =:ParentId and Central_Billing__c=true];
        for(AF_Agency_Estimate__c AgncyEstms: AgencyEstimates)
        {
        
            if(AgncyEstms.AF_Sum_of_Percent__c <> 100)
            {
             ShowFlag=true;
             ApexPages.addMessage( new apexpages.message(apexpages.severity.error,'Country breakdown percentage value cannot less or more than 100 percent'));
            }
        }
        */
        AF_CountryBreakdownCheck mycheck = new AF_CountryBreakdownCheck();
        Boolean myresult = mycheck.CheckCountryBreakdown(ParentId);
        if((BrandEstRecord.AF_Status_Base_Fees__c=='With Agency' || BrandEstRecord.AF_Status_Base_Fees__c=='With Category Finance') && myresult )
        {
           // ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please check the country Breakdown percentage'));
            apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.ERROR,'Please indicate the country breakdown percentage within UK');
            apexpages.addmessage(msg); 
            return null;
        }
        Else
            Approvalpopup=true;
        return null;
        
        
        
        
           
        return null;
    }
     public pagereference Submit()
    {
        AF_CountryBreakdownCheck mycheck = new AF_CountryBreakdownCheck();
        Boolean myresult = mycheck.CheckCountryBreakdown(ParentId);
        if(BrandEstRecord.AF_Status_Base_Fees__c=='With Category Finance' && myresult )
        {
           // ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please check the country Breakdown percentage'));
            apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.ERROR,'Please indicate the country breakdown percentage within UK');
            apexpages.addmessage(msg); 
            return null;
        }
        
        AF_BonusRecordManager bonusRecordManager = new AF_BonusRecordManager();
        if(bonusRecordManager.BonusThresholdValidationCheck((BrandEstRecord))) {
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Bonus Thresholds are not created for all Unilever Entity Countries'));
            return null;
        }else{
         if(BrandEstRecord.AF_Category_Finance_Flag__c>0)
         {
         BrandEstRecord.AF_Status_Base_Fees__c='With Agency';
         update BrandEstRecord;
         list<AF_Controller_Review__c> ACR=new list<AF_Controller_Review__c>();
         for(AF_Controller_Review__c afc:[select id,Review_Completed__c from AF_Controller_Review__c where Brand_Estimate__c=:BrandEstRecord.id limit 50000])
         {
         afc.Review_Completed__c=false;
         ACR.add(afc);
         }
         if(ACR.size()>0)
         update ACR;
         }
         else if(BrandEstRecord.AF_Category_Finance_Flag__c==0)
         {
             BrandEstRecord.AF_Status_Base_Fees__c='With CMCO';
             update BrandEstRecord;
             Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for approval automatically ');
                req1.setObjectId(brandEstimateId);
                // Submit the approval request for the Brand Estimate
                System.debug('@@test'+brandEstimateId);
                Approval.ProcessResult result = Approval.process(req1);
               // ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Confirm,'Submitted for approval By Yamuna just sample'));
                 TempConstructor();
                displayPopupRejComment=false;
                displayPopup=false;
                displayPopUpRej=false;
                Approvalpopup=false;
         }
        pagereference ref= new pagereference('/apex/AgencyHomePage?brandvalue='+brandvalue1+'category='+catageory1+'year='+year1);
        ref.setredirect(true);
        //return ref;
        return null;
       }
    }
    public void closeApprovalPopup()
    {
        Approvalpopup=false;
    }   
    
    Public pagereference SubitforApproval()
    {
        pagereference ref;
            if(brandEstimateId!=null && brandEstimateId!='')
            if( (LoggedinUser.AF_Agency_Fees_User_Type__c=='Agency' && BrandEstRecord.AF_Status_Base_Fees__c=='With Agency')|| (LoggedinUser.AF_Agency_Fees_User_Type__c=='Category Finance' && BrandEstRecord.AF_Status_Base_Fees__c=='With Category Finance')|| (LoggedinUser.AF_Agency_Fees_User_Type__c=='CMCO Super User' && BrandEstRecord.AF_Status_Base_Fees__c=='With CMCO')) 
            {
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for approval automatically ');
                req1.setObjectId(brandEstimateId);
                // Submit the approval request for the Brand Estimate
                System.debug('@@test'+brandEstimateId);
                Approval.ProcessResult result = Approval.process(req1);
                //system.debug('@@@ Submit Approval Result='+result);
                if(lstofAgencyEst.size()>0){
                    list<AF_Agency_Estimate__c>updatedlist=new list<AF_Agency_Estimate__c>();
                    for(AF_Agency_Estimate__c resetflag:lstofAgencyEst){
                    resetflag.AF_Category_Finance_Flag__c=false;
                    updatedlist.add(resetflag);
                    }
                    update updatedlist;
                }
                TempConstructor();
                displayPopupRejComment=false;
                displayPopup=false;
                displayPopUpRej=false;
                Approvalpopup=false;
                ref=new pagereference('/apex/AgencyHomePage?brandvalue='+brandvalue1+'category='+catageory1+'year='+year1);
                ref.setredirect(true);
                //return null;
            } 
            else 
            {
                ref=null;
                 ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You Can not Submit Approval ,Beacuse your Agecy Fee user type  is Different with Brand Estimate status'));
            }
          //return ref;
         return null;
    }
    
    
    
    
    Public  void ApproveBrandEst()
    {
        System.debug('Here:');
        //reDirectHomePage=false;
        String errormsg = 'The Thresholds entered do not match the Unilever entity/entities in the Base Fees matrix. Please resolve the following mismatches by setting Bonus Threshold for Unilever entities:{';
        AF_BonusRecordManager bonusRecordManager = new AF_BonusRecordManager();
        AF_CountryBreakdownCheck mycheck = new AF_CountryBreakdownCheck();
        Boolean myresult = mycheck.CheckCountryBreakdown(ParentId);
        if(bonusRecordManager.BonusThresholdValidationCheck((BrandEstRecord))) {
        for(String countryNames:bonusRecordManager.ExceptionList){
            errormsg = errormsg+countryNames;
        }
        errormsg = errormsg+'}';
        system.debug('ExceptionList....'+bonusRecordManager.ExceptionList);
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,errormsg));
            }
        else if ((BrandEstRecord.AF_Status_Base_Fees__c=='With Category Finance'||BrandEstRecord.AF_Status_Base_Fees__c=='With CMCO') && myresult)    
        {
            apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.ERROR,'Please indicate the country breakdown percentage within UK');
            apexpages.addmessage(msg); 
            
        }
        else
        {
          displayPopup = true;
        }
    }
    
    Public Void  RejectBrandEst()
    {
        displayPopupRej=true;
   
    }
    
    Public void TrueControllerFlag()
    {
         system.debug('#######CheckBox functionality');
        try{
            if(LoggedinUser.AF_Agency_Fees_User_Type__c=='Controller' &&  Targetprocess.size()==0)
            {
              
                if(Controllerflag==true)
                {
                    if(BrandEstRecord!=null)
                    {
                        BrandEstRecord.AF_Controller_Flag__c=true;
                        update BrandEstRecord;
                    }    
                }      
            }
            else
            {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You cannot flag the record'));
                
            }
           }catch(exception e)
           {
           }
    
    }
    
    public pagereference RejectBrandestiamteFinance()
    {
      
         BrandEstRecord.AF_Status_Base_Fees__c='With Agency';
         system.debug(BrandEstRecord.AF_Status_Base_Fees__c+'BrandEstRecord.AF_Status_Base_Fees__c');
         update BrandEstRecord;
         list<AF_Controller_Review__c> ACR=new list<AF_Controller_Review__c>();
         for(AF_Controller_Review__c afc:[select id,Review_Completed__c from AF_Controller_Review__c where Brand_Estimate__c=:BrandEstRecord.id limit 50000])
         {
         afc.Review_Completed__c=false;
         ACR.add(afc);
         }
         if(ACR.size()>0)
         update ACR;
                   
          displayPopupRejComment=true;      
        pagereference ref= new pagereference('/apex/AgencyHomePage?brandvalue='+brandvalue1+'category='+catageory1+'year='+year1);
        ref.setredirect(true);
        return null;
    }
    
   
  
    
    public void changeBrandStatus()
    {
        try
        {
            /*if(StatusofBrand!='--None--')
            {
                if(BrandEstRecord!=null)
                {
                    BrandEstRecord.AF_Status_Base_Fees__c=StatusofBrand;*/
                    update BrandEstRecord;
               // }    
           // }      
        
        }
        catch(exception e)
        {
        
        }
    
    }
}