src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>AgencyFee#GLOBAL#To check state of Brand Estimate</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AF_AgencyBaseFees__c</fullName>
        <description>Sum of the agency estimate totals</description>
        <label>AgencyBaseFees</label>
        <summarizedField>AF_Agency_Estimate__c.AF_Total__c</summarizedField>
        <summaryForeignKey>AF_Agency_Estimate__c.AF_Brand_Estimate__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store Agencies associated to account</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To the fiscal year details</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store the Brands associated to Brand Estimate</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Category_Brand__c.object
<CustomObject>
    <description>Used to store Categories and associated brands related to Agency Fee Application.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Category-Brands</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category-Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AF_OOPS_Actual__c.object
<CustomObject>
    <description>Will represent the actual quarterly expenses recorded by an agency for a particular brand</description>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <description>AgencyFee#GLOBAL#Created for the sharing Rules, To share OOPs Actual related data to corresponding agency. Value will be populated using a trigger.</description>
        <label>Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Agency_lk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OOPS Actuals</relationshipLabel>
        <relationshipName>OOPS_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_year__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Fiscal year.</description>
        <label>Fiscal year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_No_Of_CrossBorder__c</fullName>
        <description>Calculates the total no of cross border transactions</description>
        <label>No Of CrossBorder</label>
        <summaryFilterItems>
            <field>AF_OOPS_Estimate__c.AF_Is_Crossborder_Wk__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>AF_OOPS_Estimate__c.AF_OOPS_Actual__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AF_OOPS_Estimate__c</fullName>
        <description>AgencyFee#GLOBAL#To Store the Roll up summary value of Estimates from OOPS Estimate object.</description>
        <label>OOPS Estimate</label>
        <summarizedField>AF_OOPS_Estimate__c.AF_Estimate__c</summarizedField>
        <summaryForeignKey>AF_OOPS_Estimate__c.AF_OOPS_Actual__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AF_Q1_Approval_Status__c</fullName>
        <description>Quarter Value of OOPS Actual status</description>
        <label>Q1 Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Q2_Approval_Status__c</fullName>
        <description>Quarter Value of OOPS Actual status</description>
        <label>Q2 Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Q3_Approval_Status__c</fullName>
        <description>Quarter Value of OOPS Actual status</description>
        <label>Q3 Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Q4_Approval_Status__c</fullName>
        <description>Quarter Value of OOPS Actual status</description>
        <label>Q4 Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Status_Q1__c</fullName>
        <description>Quarter Status</description>
        <label>Status Q1</label>
        <picklist>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Enter Actuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Status_Q2__c</fullName>
        <description>Quarter Status</description>
        <label>Status Q2</label>
        <picklist>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Enter Actuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Status_Q3__c</fullName>
        <description>Status of Q3 Actual</description>
        <label>AF_Status_Q3</label>
        <picklist>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Enter Actuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Status_Q4__c</fullName>
        <description>Quarter Status</description>
        <label>Status Q4</label>
        <picklist>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected - Enter Actuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Status__c</fullName>
        <description>Status of Opps Actual</description>
        <label>AF_Status</label>
        <picklist>
            <picklistValues>
                <fullName>With Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_iS_OOPS_Percentage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check for OOPS Percentage is locked or unlocked</description>
        <label>IS OOPS Percentage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Overall__c</fullName>
        <description>Tracks value of overall OOps %</description>
        <label>Overall %</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Quarter values.</description>
        <label>Quarter</label>
        <picklist>
            <picklistValues>
                <fullName>Q1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Total_Base_Fee__c</fullName>
        <description>Calculate the Total of Base Fee from oops estimmates</description>
        <label>Total Base Fee</label>
        <summarizedField>AF_OOPS_Estimate__c.AF_Agreed_Base_Fees__c</summarizedField>
        <summaryForeignKey>AF_OOPS_Estimate__c.AF_OOPS_Actual__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Crossborder__c</fullName>
        <description>Calculate the Total of value of cross border from oops estimmates</description>
        <label>Total Crossborder</label>
        <summarizedField>AF_OOPS_Estimate__c.AF_Estimate__c</summarizedField>
        <summaryFilterItems>
            <field>AF_OOPS_Estimate__c.AF_Is_Crossborder_Wk__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>AF_OOPS_Estimate__c.AF_OOPS_Actual__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>OOPS Actual</label>
    <nameField>
        <label>OOPS Actual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OOPS Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_OOPS_Estimate__c.object
<CustomObject>
    <description>Will represent the out of pocket expense estimation agreed upon between Unilever and an agency for a particular brand</description>
    <fields>
        <fullName>AF_Brand_Estimate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To relate OOPs Estimate to brand estimates</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>OOPS Estimates</relationshipLabel>
        <relationshipName>OOPS_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To store the fiscal year related values</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_OOPS_Actual__c</fullName>
        <description>Parent record of oops estimate</description>
        <label>OOPS Actual</label>
        <referenceTo>AF_OOPS_Actual__c</referenceTo>
        <relationshipLabel>OOPS Estimates</relationshipLabel>
        <relationshipName>OOPS_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AF_Status__c</fullName>
        <description>AgencyFee#GLOBAL#To store the Status for OOPS Estimate</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>with agency (draft)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>with category finance</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>with agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>with CMCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for PO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>OOPS Estimate</label>
    <nameField>
        <label>OOPS Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OOPS Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AF_UserTypeText__c</fullName>
        <externalId>true</externalId>
        <label>AF_UserTypeText</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AF_MatrixAgencySummary.cls
public  with sharing class AF_MatrixAgencySummary {

    /*** Variables for Summary Section ***/
    public Boolean isCMCO{get;set;}
                public Boolean isController{get;set;}
                public Boolean isProcurement{get;set;}
                public Boolean isFinanace{get;set;}
    public AF_OOPS_Actual__c oopsActObj{get;set;}
    public List<AF_OOPS_Actual__c> oopsActListObj{get;set;}
    public AF_Brand_Estimate__c brandEstimates{get;set;}
    public boolean q1Flag {get;set;}
    public boolean q2Flag {get;set;}
    public boolean q3Flag {get;set;}
    public boolean q4Flag {get;set;}
    public boolean isAgencyFlag{get;set;}
    public boolean ISCMCOSUAgency{get;set;}
    public Decimal currentOOPSPer {get;set;}
    public Integer oopsEstimate {get;set;}
    public Integer totalBaseFee {get;set;}
    public String overall{get;set;}
    public String agencyId {get;set;}
    public String fiscalYear {get;set;}
    public String brandId {get;set;}
    public Integer totalCrossBroder{get;set;}
    public Integer Q1{get;set;}
    public Integer Q2{get;set;}
    public Integer Q3{get;set;}
    public Integer Q4{get;set;}
    public String Q1ApprovalStatus{get;set;}
    public String Q2ApprovalStatus{get;set;}
    public String Q3ApprovalStatus{get;set;}
    public String Q4ApprovalStatus{get;set;}
    public AF_OOPS_Actual__c tempOopsRecord{get;set;}
    public String OOpsActualId;
    public list<AF_OOPS_Estimate__c>lst_OOPS_Estimate=new list<AF_OOPS_Estimate__c>();
    public Boolean IsCatFinance{get;set;}
    Public Boolean IsReadyforPO{get;set;}
    public List<String> quarterOops;
    public Integer ytgValue{get;set;}
    public String ytgColour{get;set;}
    public AF_MatrixAgencySummary(ApexPages.StandardController controller) {
      
      call_constructor();
      AF_ApproveActualsCtrl actConst = new AF_ApproveActualsCtrl();
      ytgValue = actConst.getTotalSum();
        if(ytgValue > oopsActObj.AF_OOPS_Estimate__c)
      {ytgColour='red';}else{ytgColour='black';}
       
    }
    public void call_constructor(){
     OOpsActualId = ApexPages.currentPage().getParameters().get('Id');
        brandId = ApexPages.currentPage().getParameters().get('bId');
        agencyId = ApexPages.currentPage().getParameters().get('aId');
        fiscalYear = ApexPages.currentPage().getParameters().get('fy');
        system.debug('OOpsActualId..'+OOpsActualId);
        system.debug('brandId..'+brandId);
        system.debug('agencyId..'+agencyId);
        system.debug('fiscalYear..'+fiscalYear);
        q1Flag=false;
        q2Flag=false;
        q3Flag=false;
        q4Flag=false;
        IsReadyforPO=false;
        isAgencyFlag=false;
        ISCMCOSUAgency=false;
        currentOOPSPer=0.0;
        oopsEstimate=0;
        totalBaseFee=0;
        overall = '';
        totalCrossBroder=0;
        Q1=0;
        Q2=0;
        Q3=0;
        Q4=0;
        Q1ApprovalStatus='';
        Q2ApprovalStatus='';
        Q3ApprovalStatus='';
        Q4ApprovalStatus='';
        quarterOops = new List<String>();
        lst_OOPS_Estimate=new list<AF_OOPS_Estimate__c>();
        tempOopsRecord = new AF_OOPS_Actual__c();
                                isCMCO = false;
                                isProcurement = false;
                                isController = false;
                                isFinanace = false;
        User userObj = new User();
        userObj = [Select id, AF_UserTypeText__c from User where id=:UserInfo.getUserId()];
        
        //check whether logged in User is Agency or CMCO User
        if(userObj.AF_UserTypeText__c=='Agency'){
            //if Agency User then make AgencyFlag true
            isAgencyFlag=true;
        }
        if(userObj.AF_UserTypeText__c=='CMCO Super User' || userObj.AF_UserTypeText__c=='Agency' ){
            //if Agency User then make AgencyFlag true
            ISCMCOSUAgency=true;
        }
                                
        if(userObj.AF_UserTypeText__c=='Category Finance'|| userObj.AF_UserTypeText__c=='CMCO Super User'){
            isFinanace = true;
        }
      
         system.debug('++++++'+userObj.AF_UserTypeText__c);
         system.debug('++++++'+ISCMCOSUAgency);
         
      /**  brandEstimates=new AF_Brand_Estimate__c();
        brandEstimates=[Select id,name,AF_AgencyBaseFees__c from AF_Brand_Estimate__c where Brand__c=:brandId and AF_Agency__c=:agencyId and AF_Fiscal_Year__c=:fiscalYear and AF_Active__c=true limit 1];
      **/
        //get OOPS Actual detail associated to this Brand and Agency
        oopsActObj = new AF_OOPS_Actual__c();
        oopsActListObj = new List<AF_OOPS_Actual__c>();
        oopsActListObj = [SELECT  AF_iS_OOPS_Percentage__c,Name,AF_Status__c,Quarter__c,AF_Status_Q1__c,
                                AF_Status_Q2__c,AF_Status_Q4__c,AF_Status_Q3__c,AF_Q1_Approval_Status__c,
                                AF_Q2_Approval_Status__c,AF_Q3_Approval_Status__c,AF_Q4_Approval_Status__c,
                                Total_Crossborder__c,Total_Base_Fee__c,AF_OOPS_Estimate__c,AF_No_Of_CrossBorder__c,
                                Overall__c,AF_Agency_lk__r.Name,AF_Brand__c,AF_Brand__r.name,AF_Q1__c,AF_Q2__c,AF_Q3__c,AF_Q4__c,
                                AF_Number_of_0_or_null_OOPS_estimates__c
                            FROM AF_OOPS_Actual__c 
                            WHERE AF_Brand__c = :brandId AND AF_Agency_lk__c = :agencyId AND AF_Fiscal_year__c = :fiscalYear];
       // oopsActListObj = [SELECT  Id,AF_iS_OOPS_Percentage__c,AF_Status__c,Quarter__c,AF_Q1_Approval_Status__c,AF_Q2_Approval_Status__c,AF_Q3_Approval_Status__c,AF_Q4_Approval_Status__c,Total_Crossborder__c,Total_Base_Fee__c,AF_OOPS_Estimate__c,AF_No_Of_CrossBorder__c,Overall__c,AF_Agency_lk__r.Name,AF_Brand__c,AF_Brand__r.name,AF_Q1__c,AF_Q2__c,AF_Q3__c,AF_Q4__c FROM AF_OOPS_Actual__c WHERE id=:OOpsActualId];
        system.debug('oopsActListObj...'+oopsActListObj);
        lst_OOPS_Estimate=[Select name,AF_Status__c from AF_OOPS_Estimate__c where AF_OOPS_Actual__r.id=:OOpsActualId];
        if(lst_OOPS_Estimate[0].AF_Status__c =='Ready For PO'){
            IsReadyforPO=true;
        }
        for(AF_OOPS_Actual__c oops: oopsActListObj){
            if(oops.Id == OOpsActualId){
                if(oops.Total_Base_Fee__c!=0){
                    currentOOPSPer=((oops.AF_OOPS_Estimate__c/oops.Total_Base_Fee__c)*100);
                    currentOOPSPer=currentOOPSPer.setScale(1);
                }
                oopsActObj = oops;
                String q = oopsActObj.Quarter__c;
                quarterOops = q.split(';');
                system.debug('oopsActObj...'+oopsActObj);           
                }
        }
        
        
         
        for(AF_OOPS_Actual__c oops:oopsActListObj){
            String quarterValue = oops.Quarter__c;
            if(quarterValue!=null){
                if(quarterValue.contains('Q1')){
                  //  if(oops.AF_Q1__c!=null){
                    tempOopsRecord.AF_Q1__c = oops.AF_Q1__c;
                    tempOopsRecord.AF_Q1_Approval_Status__c = oops.AF_Q1_Approval_Status__c;
                   // }
                }
                if(quarterValue.contains('Q2')){
                    //if(oops.AF_Q2__c!=null){
                    tempOopsRecord.AF_Q2__c = oops.AF_Q2__c;
                    tempOopsRecord.AF_Q2_Approval_Status__c = oops.AF_Q2_Approval_Status__c;
                   // }
                }
                if(quarterValue.contains('Q3')){
                   // if(oops.AF_Q3__c!=0){
                    tempOopsRecord.AF_Q3__c = oops.AF_Q3__c;
                    tempOopsRecord.AF_Q3_Approval_Status__c=oops.AF_Q3_Approval_Status__c;
                   // }
                }
                if(quarterValue.contains('Q4')){
                  //  if(oops.AF_Q4__c!=0){
                    tempOopsRecord.AF_Q4__c = oops.AF_Q4__c;
                    tempOopsRecord.AF_Q4_Approval_Status__c = oops.AF_Q4_Approval_Status__c;
                   // }
                }
            }
        }
        
        system.debug('Q1..'+tempOopsRecord.AF_Q1__c);
        system.debug('Q1ApprovalStatus..'+tempOopsRecord.AF_Q1_Approval_Status__c);
        system.debug('Q2..'+tempOopsRecord.AF_Q2__c);
        system.debug('Q2ApprovalStatus..'+tempOopsRecord.AF_Q2_Approval_Status__c);
        system.debug('Q3..'+tempOopsRecord.AF_Q3__c);
        system.debug('Q3ApprovalStatus..'+tempOopsRecord.AF_Q3_Approval_Status__c);
        system.debug('Q4..'+tempOopsRecord.AF_Q4__c);
        system.debug('Q4ApprovalStatus..'+tempOopsRecord.AF_Q4_Approval_Status__c);
        
    
    }
    
    public pagereference backToHomePage(){
        return null;
    }
              
    public pagereference backToChatter(){
        return null;
    }
              
    //to save entered values in OOPS Actual
     public void save(){
         try{
            String msg;
            AF_OOPSRecordManager OOPSRecordManager = new AF_OOPSRecordManager();
            OOPSRecordManager.OOPSActual = oopsActObj; 
            OOPSRecordManager.RecalculateOOPSEstimates();
            update oopsActObj;
            call_constructor();
            AF_OOPS_Actual__c oopsActObj1 = [SELECT AF_Number_of_0_or_null_OOPS_estimates__c
                                FROM AF_OOPS_Actual__c 
                                WHERE Id =:oopsActObj.Id];
            if(oopsActObj1.AF_Number_of_0_or_null_OOPS_estimates__c > 0) {
                msg = 'Successfully Refreshed';
            }else {
                msg = 'Successfully Refreshed, There are entities in the OOPS matrix that do not exist in the base fee.';
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, msg));
        }catch(DMLException dml){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.fatal,dml.getMessage()));
        }
     }
     
     //to submit data
     public pagereference submit(){
        
        List<AF_OOPS_Actual__c> updateOopsActual = new List<AF_OOPS_Actual__c>();
        set<String> oopsEstimateStatusUpdate = new set<String>();
        system.debug('inside submit1');
        for(AF_OOPS_Actual__c oops:oopsActListObj){
        integer i=0;
        system.debug('inside submit2');
            String quarterValue = oops.Quarter__c;
            if(quarterValue!=null){
            if(quarterValue.contains('Q1') && tempOopsRecord.AF_Q1__c!=oops.AF_Q1__c && tempOopsRecord.AF_Q1__c!=0 && tempOopsRecord.AF_Q1__c!=null){
                oops.AF_Q1__c = tempOopsRecord.AF_Q1__c ;
                oops.AF_Status__c='With Category Finance';
                oopsEstimateStatusUpdate.add(oops.Id);
                system.debug('tempOopsRecord.AF_Q1__c.....'+tempOopsRecord.AF_Q1__c);
                i++;
            }
            if(quarterValue.contains('Q2') && tempOopsRecord.AF_Q2__c!=oops.AF_Q2__c && tempOopsRecord.AF_Q2__c!=0 && tempOopsRecord.AF_Q2__c!=null){
                oops.AF_Q2__c = tempOopsRecord.AF_Q2__c ;
                oops.AF_Status__c='With Category Finance';
                oopsEstimateStatusUpdate.add(oops.Id);
                i++;
            }
            if(quarterValue.contains('Q3') && tempOopsRecord.AF_Q3__c!=oops.AF_Q3__c && tempOopsRecord.AF_Q3__c!=0 && tempOopsRecord.AF_Q3__c!=null){
                oops.AF_Q3__c = tempOopsRecord.AF_Q3__c ;
                oops.AF_Status__c='With Category Finance';
                oopsEstimateStatusUpdate.add(oops.Id);
                i++;
            }
            if(quarterValue.contains('Q4') && tempOopsRecord.AF_Q4__c!=oops.AF_Q4__c && tempOopsRecord.AF_Q4__c!=0 && tempOopsRecord.AF_Q4__c!=null){
                oops.AF_Q4__c = tempOopsRecord.AF_Q4__c ;
                oops.AF_Status__c='With Category Finance';
                oopsEstimateStatusUpdate.add(oops.Id);
                i++;
            }
            
            if(i>0){
            updateOopsActual.add(oops);
            }
            }
        }
        system.debug('updateOopsActual....'+updateOopsActual);
        system.debug('oopsEstimateStatusUpdate...'+oopsEstimateStatusUpdate);
        list<AF_OOPS_Estimate__c> submit_OOPS_Estimate = new list<AF_OOPS_Estimate__c>();
         submit_OOPS_Estimate=[Select name,AF_Status__c from AF_OOPS_Estimate__c where AF_OOPS_Actual__r.id IN :oopsEstimateStatusUpdate];
         system.debug('submit_OOPS_Estimate...'+submit_OOPS_Estimate);
            list<AF_OOPS_Estimate__c>updatedopps_est=new list<AF_OOPS_Estimate__c>();
            for(AF_OOPS_Estimate__c oops_est:submit_OOPS_Estimate){
                oops_est.AF_Status__c ='Ready for PO';
                updatedopps_est.add(oops_est);
            }
        system.debug('updateOopsActual...'+updateOopsActual);
        if(updateOopsActual.size()>0){
            try{
            update updateOopsActual;
            update updatedopps_est;
            }
            catch(Exception e){
            system.debug(e);
            }
         }
         
       
        // pagereference pf = new pagereference(Apexpages.currentpage().getUrl());
         //pf.setredirect(true);
        //return pf;
        
        return null;
    }
    
     public pagereference grApprove(){
     Boolean isAllApproved=false;
     List<AF_OOPS_Actual__c> updateOopsActual = new List<AF_OOPS_Actual__c>();
         for(AF_OOPS_Actual__c oops:oopsActListObj){
            
            String quarterValue = oops.Quarter__c;
            
            if(quarterValue!=null){
           
            if(quarterValue.contains('Q1')){
                if(q1Flag){
                    oops.AF_Q1_Approval_Status__c='Approved';
                    oops.AF_Status__c='Ready For PO';
                }
            }
            if(quarterValue.contains('Q2')){
                if(q2Flag){
                    oops.AF_Q2_Approval_Status__c='Approved';
                    oops.AF_Status__c='Ready For PO';
                }
            }
            if(quarterValue.contains('Q3')){
                if(q3Flag){
                    oops.AF_Q3_Approval_Status__c='Approved';
                    oops.AF_Status__c='Ready For PO';
                }
            }
            if(quarterValue.contains('Q4')){
                if(q4Flag){
                    oops.AF_Q4_Approval_Status__c='Approved';
                    oops.AF_Status__c='Ready For PO';
                }
            }
           
          
             
            
            updateOopsActual.add(oops);
            }
         }
         system.debug('updateOopsActual...'+updateOopsActual);
         if(updateOopsActual.size()>0){
            update updateOopsActual;
         }
        // pagereference pf = new pagereference(Apexpages.currentpage().getUrl());
        // pf.setredirect(true);
        // return pf;
          return null;
    }
    
     public pagereference grReject(){
        List<AF_OOPS_Actual__c> updateOopsActual = new List<AF_OOPS_Actual__c>();
         for(AF_OOPS_Actual__c oops:oopsActListObj){
            String quarterValue = oops.Quarter__c;
            if(quarterValue!=null){
            if(quarterValue.contains('Q1')){
                if(q1Flag){
                    oops.AF_Q1_Approval_Status__c='Rejected';
                    oops.AF_Status__c='With Agency';
                }
            }
            if(quarterValue.contains('Q2')){
                if(q2Flag){
                    oops.AF_Q2_Approval_Status__c='Rejected';
                    oops.AF_Status__c='With Agency';
                }
            }
            if(quarterValue.contains('Q3')){
                if(q3Flag){
                    oops.AF_Q3_Approval_Status__c='Rejected';
                    oops.AF_Status__c='With Agency';
                }
            }
            if(quarterValue.contains('Q4')){
                if(q4Flag){
                    oops.AF_Q4_Approval_Status__c='Rejected';
                    oops.AF_Status__c='With Agency';
                }
            }
            
            updateOopsActual.add(oops);
            }
         }
         system.debug('updateOopsActual...'+updateOopsActual);
         if(updateOopsActual.size()>0){
            update updateOopsActual;
         }
        // pagereference pf = new pagereference(Apexpages.currentpage().getUrl());
         //pf.setredirect(true);
         //return pf;
         return null;
    }
    
   public void SubmitOverall(){
         try{
            list<AF_OOPS_Estimate__c>updatedopps_est=new list<AF_OOPS_Estimate__c>();
            for(AF_OOPS_Estimate__c oops_est:lst_OOPS_Estimate){
                oops_est.AF_Status__c ='Ready For PO';
                updatedopps_est.add(oops_est);
            }
            system.debug('quarterOops....'+quarterOops);
            for(String s:quarterOops){
            if(s=='Q1'){
            oopsActObj.AF_Status_Q1__c='With Agency';
            }
            if(s=='Q2'){
            oopsActObj.AF_Status_Q2__c='With Agency';
            }
            if(s=='Q3'){
            oopsActObj.AF_Status_Q3__c='With Agency';
            }
            if(s=='Q4'){
            oopsActObj.AF_Status_Q4__c='With Agency';
            }
            }
            oopsActObj.AF_iS_OOPS_Percentage__c=True;
            oopsActObj.AF_Status__c='With Agency';
            update oopsActObj;
            update updatedopps_est;
             //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm,'Records successfully submitted'));
        }catch(DMLException dml){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.fatal,dml.getMessage()));
        }
     } 
    
}