src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_Fiscal_Year__c</fullName>
        <description>AgencyFee#GLOBAL#To the fiscal year details</description>
        <label>Fiscal Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AF_Pilot_Model__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check for Pilot model</description>
        <label>Pilot Model</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store the Brands associated to Brand Estimate</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Category_Brand__c.object
<CustomObject>
    <description>Used to store Categories and associated brands related to Agency Fee Application.</description>
    <fields>
        <fullName>AF_Category_Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To associate brands to corresponding Categories</description>
        <label>Category</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Category-Brands</relationshipLabel>
        <relationshipName>Category_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Pilot_Model__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Not Used</description>
        <label>Pilot Model</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Category-Brands</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category-Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/AF_Controller_Review__c.object
<CustomObject>
    <description>To hold review by Controller groups for Brand Estimates</description>
    <fields>
        <fullName>Brand_Estimate__c</fullName>
        <description>Stores the Brand Estimate</description>
        <label>Brand Estimate</label>
        <referenceTo>AF_Brand_Estimate__c</referenceTo>
        <relationshipLabel>Controller Reviews</relationshipLabel>
        <relationshipName>Controller_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Controller_Group__c</fullName>
        <description>Controller Group - comes from Unilever Entity - Controller Group</description>
        <label>Controller Group</label>
        <picklist>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oceania</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Review_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tracks if Review is completed</description>
        <label>Review Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Controller Review</label>
    <nameField>
        <displayFormat>CR-{000000000}</displayFormat>
        <label>Controller Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controller Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AF_AgencyReviewCommentsExtension_Test.cls
/*****************************************************************************************************************************
@Author :Cognizant
@name : AF_AgencyReviewCommentsExtension
@CreateDate : 20/9/2014
@Description : This is a Test class for AF_AgencyReviewCommentsExtension class, 
@Version : 1.0
@reference : none
****************************************************************************************************************************/
@isTest(SeeAlldata=false)
public class AF_AgencyReviewCommentsExtension_Test
{    
    Static Integer IcurrYear = System.Today().year()-1;
    Static string currYear=string.valueof(IcurrYear);
    static user AgencyReviewCommentsExtension;
    /***********************************************************************************
*  @Description: this method will the test data
*  @name : AFagencyReviewCommentsExtension
*  @param : none.
*  @return: none.
*************************************************************************************/
    Static testMethod void AFagencyReviewCommentsExtension()
    {
        Test.startTest();
        AgencyReviewCommentsExtension = AF_TestFactory_Helper.createUserAdmin(true);
        User u=[SELECT id FROM user WHERE id=:AgencyReviewCommentsExtension.id LIMIT 1];
        System.runAs(u)
        { 
            //Insert Account
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,true);
            List<Account> acctQuery = [SELECT id FROM account where id IN:acc LIMIT 1];
            System.Assert(acctQuery[0].Id != null, AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,true);
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE and Id IN:AFCategoryBrand LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.BRAND_RECORD);
            //Insert BrandEstimate
            List<AF_Brand_Estimate__c> BrandEst = AF_TestFactory_Helper.insertAFBrandEstList(1,false);
            List<AF_Brand_Estimate__c> BrandEstimate=new List<AF_Brand_Estimate__c>();
            for(AF_Brand_Estimate__c loopbrandEst : BrandEst){
                loopbrandEst.AF_Fiscal_Year__c=currYear;
                loopbrandEst.AF_Pilot_Model__c=true;
                BrandEstimate.add(loopbrandEst);
            }
            insert BrandEstimate;
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c where Id IN:BrandEst LIMIT 1]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRANDESTIMATE_RECORD);
            //Insert controller Review.
            List<AF_Controller_Review__c> ControllerReview = AF_TestFactory_Helper.AfcontrollerReview(1,false);
            List<AF_Controller_Review__c> ControllerReviewlist=new List<AF_Controller_Review__c>();
            for(AF_Controller_Review__c controll : ControllerReview){
                controll.Controller_Group__c='Europe';
                controll.Review_Completed__c=true;
                ControllerReviewlist.add(controll);
            }
            insert ControllerReviewlist;
            List<AF_Controller_Review__c> ControllerReviewQuery = [SELECT Id,Brand_Estimate__c FROM AF_Controller_Review__c WHERE ID IN :ControllerReview LIMIT 1];
            System.assertEquals(ControllerReviewQuery[0].Brand_Estimate__c, BrandEst[0].id,AF_TestFactory_Helper.CONTROLLERREVIEW_RECORD);
            ApexPages.currentPage().getParameters().put('id',brandEst[0].Id);   
            //Instantiating the class AF_AgencyReviewCommentsExtension 
            ApexPages.StandardController sc = new ApexPages.StandardController(brandEst[0]);
            AF_AgencyReviewCommentsExtension agencRevControl=new AF_AgencyReviewCommentsExtension (sc);
            agencRevControl.saveControllerReview();
            agencRevControl.checkReview=false;
            agencRevControl.saveControllerReview();
            Test.stopTest(); 
        }
    }
    /***********************************************************************************
*  @Description: this method will the test data
*  @name : AFagencyReviewCommentsExtension2
*  @param : none.
*  @return: none.
*************************************************************************************/
    Static testMethod void AFagencyReviewCommentsExtension2()
    {
        Test.startTest();
        AgencyReviewCommentsExtension = AF_TestFactory_Helper.createUserAdmin(true);
        User u=[SELECT id FROM user WHERE id=:AgencyReviewCommentsExtension.id LIMIT 1];
        System.runAs(u)
        { 
            //Insert Account
            List<Account> acc=AF_TestFactory_Helper.insertAFaccList(1,true);
            List<Account> acctQuery = [SELECT id FROM account where id IN:acc LIMIT 1];
            System.Assert(acctQuery[0].Id != null, AF_TestFactory_Helper.ACCOUNT_RECORD);
            //Insert category
            List<AF_Category_Brand__c> cb = AF_TestFactory_Helper.insertAFCBList(1,true);
            List<AF_Category_Brand__c> categoryQuery = [SELECT id FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_CATEGORY_RECTYPE and Id IN:cb LIMIT 1];
            System.Assert(categoryQuery[0].Id != null, AF_TestFactory_Helper.CATEGORY_RECORD);
            //Insert Brand
            List<AF_Category_Brand__c> AFCategoryBrand = AF_TestFactory_Helper.insertBrand(1,true);
            List<AF_Category_Brand__c> brandQuery = [SELECT AF_Category_Brands__c FROM AF_Category_Brand__c where RecordTypeId=:AF_TestFactory_Helper.AF_BRAND_RECTYPE and Id IN:AFCategoryBrand LIMIT 1];
            System.assertEquals(brandQuery[0].AF_Category_Brands__c,categoryQuery[0].Id, AF_TestFactory_Helper.BRAND_RECORD);
            //Insert BrandEstimate
            List<AF_Brand_Estimate__c> BrandEst = AF_TestFactory_Helper.insertAFBrandEstList(1,false);
            List<AF_Brand_Estimate__c> BrandEstlist=new List<AF_Brand_Estimate__c>();
            for(AF_Brand_Estimate__c loopbrandEst : BrandEst){
                loopbrandEst.AF_Fiscal_Year__c=currYear;
                loopbrandEst.AF_Pilot_Model__c=true;
                BrandEstlist.add(loopbrandEst);
            }
            insert BrandEstlist;
            List<AF_Brand_Estimate__c> BrandEstQuery =[SELECT Brand__c FROM AF_Brand_Estimate__c where Id IN:BrandEst LIMIT 1]; 
            System.assertEquals(BrandEstQuery[0].Brand__c, brandQuery[0].id,AF_TestFactory_Helper.BRANDESTIMATE_RECORD);
            //Insert controller Review.
            List<AF_Controller_Review__c> ControllerReview = AF_TestFactory_Helper.AfcontrollerReview(1,false);
            List<AF_Controller_Review__c> ControllerReviewlist=new List<AF_Controller_Review__c>();
            for(AF_Controller_Review__c controll : ControllerReview){
                controll.Controller_Group__c='Europe';
                controll.Review_Completed__c=false;
                ControllerReviewlist.add(controll);
            }
            insert ControllerReviewlist;
            List<AF_Controller_Review__c> ControllerReviewQuery = [SELECT Id,Brand_Estimate__c FROM AF_Controller_Review__c WHERE ID IN :ControllerReview LIMIT 1];
            System.assertEquals(ControllerReviewQuery[0].Brand_Estimate__c, BrandEst[0].id,AF_TestFactory_Helper.CONTROLLERREVIEW_RECORD);
            ApexPages.currentPage().getParameters().put('id',brandEst[0].Id);   
            //Instantiating the class AF_AgencyReviewCommentsExtension 
            ApexPages.StandardController sc = new ApexPages.StandardController(brandEst[0]);
            AF_AgencyReviewCommentsExtension agencRevControl=new AF_AgencyReviewCommentsExtension (sc);
            agencRevControl.saveControllerReview();
            agencRevControl.checkReview=false;
            agencRevControl.saveControllerReview();
            Test.stopTest(); 
        }
    }
}