src/objects/AF_Brand_Estimate__c.object
<CustomObject>
    <description>It Will represent a Unilever base fee estimate for a particular brand and agency combination.</description>
    <fields>
        <fullName>AF_AgencyUsers10__c</fullName>
        <label>AF_AgencyUsers10</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers1__c</fullName>
        <description>Holds Email address of agency user. Used for sending notifications to</description>
        <label>AF_AgencyUsers1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers2__c</fullName>
        <description>Holds Email address of agency user. Used for sending notifications to</description>
        <label>AF_AgencyUsers2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers3__c</fullName>
        <description>Holds Email address of agency user. Used for sending notifications to</description>
        <label>AF_AgencyUsers3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers4__c</fullName>
        <description>Holds Email address of agency user. Used for sending notifications to</description>
        <label>AF_AgencyUsers4</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers5__c</fullName>
        <description>Holds Email address of agency user. Used for sending notifications to</description>
        <label>AF_AgencyUsers5</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers6__c</fullName>
        <label>AF_AgencyUsers6</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers7__c</fullName>
        <label>AF_AgencyUsers7</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers8__c</fullName>
        <label>AF_AgencyUsers8</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_AgencyUsers9__c</fullName>
        <label>AF_AgencyUsers9</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AF_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store Agencies associated to account</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cat Finance Approver 10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the User id of the Cat Fin Approver</description>
        <label>Cat Finance Approver 1</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.AF_Agency_Fees_User_Type__c</field>
                <operation>equals</operation>
                <value>Category Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the User id of the Cat Fin Approver</description>
        <label>Cat Finance Approver 2</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.AF_Agency_Fees_User_Type__c</field>
                <operation>equals</operation>
                <value>Category Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the User id of the Cat Fin Approver</description>
        <label>Cat Finance Approver 3</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.AF_Agency_Fees_User_Type__c</field>
                <operation>equals</operation>
                <value>Category Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the User id of the Cat Fin Approver</description>
        <label>Cat Finance Approver 4</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.AF_Agency_Fees_User_Type__c</field>
                <operation>equals</operation>
                <value>Category Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the User id of the Cat Fin Approver</description>
        <label>Cat Finance Approver 5</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.AF_Agency_Fees_User_Type__c</field>
                <operation>equals</operation>
                <value>Category Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cat Finance Approver 6</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.AF_Agency_Fees_User_Type__c</field>
                <operation>equals</operation>
                <value>Category Finance</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cat Finance Approver 7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cat Finance Approver 8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Cat_Finance_Approver_9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cat Finance Approver 9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Brand_Estimates8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To store the Brands associated to Brand Estimate</description>
        <label>Brand</label>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Brand Estimates</relationshipLabel>
        <relationshipName>Brand_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Estimate</label>
    <nameField>
        <label>Brand Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AF_Category_Brand__c.object
<CustomObject>
    <description>Used to store Categories and associated brands related to Agency Fee Application.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Category-Brands</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category-Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AF_Send_Email_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for Agency contact who will receive the notification after approval process.</description>
        <inlineHelpText>This field is for Agency contact who will receive the notification after approval process.</inlineHelpText>
        <label>Send Email Notifcation</label>
        <type>Checkbox</type>
    </fields>
    
    
    
    
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DummyUser__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains ID for Dummy user used in Approval process. This must be populated else you will see Error in Log when approval process fires - Exception no Manager specified</description>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AF_DummyUserID</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AF_Agency_Fees_User_Type__c</fullName>
        <label>Agency Fees User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO Super User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Category Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <description>This represents Brands on the user level</description>
        <inlineHelpText>List of brands assigned to user</inlineHelpText>
        <label>Brand</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AF_UserTypeText__c</fullName>
        <externalId>true</externalId>
        <label>AF_UserTypeText</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UpdateBrandEstimateCatApproverValues.cls
public class UpdateBrandEstimateCatApproverValues
{

    public Static void UpdateBrandingEstimates(List<AF_Brand_Estimate__c> BrandRecords)
    {
    
        list<AF_Brand_Estimate__c>  afBrands=new list<AF_Brand_Estimate__c>();
        List<user> Userlist=new List<user>();
        Map<id,List<String>> usermap=new Map<id,List<String>>();
        List<string> BrandStrings=new list<String>();
        list<id> userids=new list<id>();
        String DummyUserid;
        set<id> brandids=new set<id>();
        Map<id,string> brandMap=new Map<id,String>();
        List<AF_Category_Brand__c> CatBrands=new  List<AF_Category_Brand__c>();
        DummyUser__c Dummy = DummyUser__c.getOrgDefaults();
        DummyUserid=Dummy.User_id__c;
        System.debug('!!!!!!!!!!!!!!!!!!!!!!!!'+DummyUserid);
        if(BrandRecords.size()>0)
        for(AF_Brand_Estimate__c br:BrandRecords)
        {
            if(br.Brand__c!=null)
            brandids.add(br.Brand__c); 
        }
        
        CatBrands=[select id,Name From AF_Category_Brand__c  where id IN:brandids ];
        if(CatBrands.size()>0)
        for(AF_Category_Brand__c cb:CatBrands)
        {
            brandMap.put(cb.id,cb.Name);
        }
        
        List<User> users=[select id,IsActive,Username,Name,AF_Brand__c,AF_Agency_Fees_User_Type__c  from  User  where  AF_UserTypeText__c=:'Category Finance'  and IsActive=true  Order by CreatedDate Limit 50000];
        if(BrandRecords.size()>0)
        for( AF_Brand_Estimate__c Brandest:BrandRecords)
        {  
            userids=new list<id>();
            String Brandname;
            if(Brandest.Brand__c!=null)
            {
                Brandname=brandMap.get(Brandest.Brand__c);
            }
            system.debug('&&&&&&&&&&&&&&&Brandname='+Brandname);
            if(users.size()>0)
            for(user u:users)
            {  
                system.debug('%%%%%%%%%%%%'+u.AF_Brand__c);
                BrandStrings=new list<String>();
                if(u.AF_Brand__c!=null && u.AF_Brand__c!='' )
                {
                   
                    String Brandvalue=u.AF_Brand__c;
                    BrandStrings=Brandvalue.split(';');          
                }
                if(BrandStrings.size()>0)
                For(String s:BrandStrings)
                {
                    if(s==Brandname)
                    {
                        userids.add(u.id);
                    }
                }    
            } 
            System.debug('^^^^^^^^^^^^^^^^^user id  size'+userids.size());  
            System.debug('^^^^^^^^^^^^^^^^^userids=='+userids);
            //if(userids.size()==0)
            //Brandest.addError('There are no user records with this Brand');
            if(userids.size()==1)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_3__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_4__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_5__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_6__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_7__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_8__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_9__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_10__c=DummyUserid;
            }
            else if(userids.size()==2)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=userids[1];
                Brandest.AF_Cat_Finance_Approver_3__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_4__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_5__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_6__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_7__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_8__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_9__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_10__c=DummyUserid;
            }
            else if(userids.size()==3)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=userids[1];
                Brandest.AF_Cat_Finance_Approver_3__c=userids[2];
                Brandest.AF_Cat_Finance_Approver_4__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_5__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_6__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_7__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_8__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_9__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_10__c=DummyUserid;
            }
            else if(userids.size()==4)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=userids[1];
                Brandest.AF_Cat_Finance_Approver_3__c=userids[2];
                Brandest.AF_Cat_Finance_Approver_4__c=userids[3];
                Brandest.AF_Cat_Finance_Approver_5__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_6__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_7__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_8__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_9__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_10__c=DummyUserid;
            }
            else if(userids.size()==5)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=userids[1];
                Brandest.AF_Cat_Finance_Approver_3__c=userids[2];
                Brandest.AF_Cat_Finance_Approver_4__c=userids[3];
                Brandest.AF_Cat_Finance_Approver_5__c=userids[4];
                Brandest.AF_Cat_Finance_Approver_6__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_7__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_8__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_9__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_10__c=DummyUserid;
            }
            else if(userids.size()==6)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=userids[1];
                Brandest.AF_Cat_Finance_Approver_3__c=userids[2];
                Brandest.AF_Cat_Finance_Approver_4__c=userids[3];
                Brandest.AF_Cat_Finance_Approver_5__c=userids[4];
                Brandest.AF_Cat_Finance_Approver_6__c=userids[5];
                Brandest.AF_Cat_Finance_Approver_7__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_8__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_9__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_10__c=DummyUserid;
            }
            else if(userids.size()==7)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=userids[1];
                Brandest.AF_Cat_Finance_Approver_3__c=userids[2];
                Brandest.AF_Cat_Finance_Approver_4__c=userids[3];
                Brandest.AF_Cat_Finance_Approver_5__c=userids[4];
                Brandest.AF_Cat_Finance_Approver_6__c=userids[5];
                Brandest.AF_Cat_Finance_Approver_7__c=userids[6];
                Brandest.AF_Cat_Finance_Approver_8__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_9__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_10__c=DummyUserid;
                }
            else if(userids.size()==8)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=userids[1];
                Brandest.AF_Cat_Finance_Approver_3__c=userids[2];
                Brandest.AF_Cat_Finance_Approver_4__c=userids[3];
                Brandest.AF_Cat_Finance_Approver_5__c=userids[4];
                Brandest.AF_Cat_Finance_Approver_5__c=userids[5];
                Brandest.AF_Cat_Finance_Approver_6__c=userids[6];
                Brandest.AF_Cat_Finance_Approver_8__c=userids[7];
                Brandest.AF_Cat_Finance_Approver_9__c=DummyUserid;
                Brandest.AF_Cat_Finance_Approver_10__c=DummyUserid;
            }
            else if(userids.size()==9)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=userids[1];
                Brandest.AF_Cat_Finance_Approver_3__c=userids[2];
                Brandest.AF_Cat_Finance_Approver_4__c=userids[3];
                Brandest.AF_Cat_Finance_Approver_5__c=userids[4];
                Brandest.AF_Cat_Finance_Approver_6__c=userids[5];
                Brandest.AF_Cat_Finance_Approver_7__c=userids[6];
                Brandest.AF_Cat_Finance_Approver_8__c=userids[7];
                Brandest.AF_Cat_Finance_Approver_9__c=userids[8];
                Brandest.AF_Cat_Finance_Approver_10__c=DummyUserid;
            }
            else if(userids.size()>=10)
            {
                Brandest.AF_Cat_Finance_Approver_1__c=userids[0];
                Brandest.AF_Cat_Finance_Approver_2__c=userids[1];
                Brandest.AF_Cat_Finance_Approver_3__c=userids[2];
                Brandest.AF_Cat_Finance_Approver_4__c=userids[3];
                Brandest.AF_Cat_Finance_Approver_5__c=userids[4];
                Brandest.AF_Cat_Finance_Approver_6__c=userids[5];
                Brandest.AF_Cat_Finance_Approver_7__c=userids[6];
                Brandest.AF_Cat_Finance_Approver_8__c=userids[7];
                Brandest.AF_Cat_Finance_Approver_9__c=userids[8];
                Brandest.AF_Cat_Finance_Approver_10__c=userids[9];
            }
  
            
        }
        
        
    }
    
    public Static void UpdateOopsagency(AF_Brand_Estimate__c BrandRecords)
    {
         
         AF_Brand_Estimate__c ao = BrandRecords;
         if(ao.AF_Agency__c!= null)
         {
             list<contact> clist = new list<contact>();
             for(contact c : [select id,name,email,accountid from contact where accountid =: ao.AF_Agency__c and AF_Send_Email_Notification__c =: true])
             {
                 clist.add(c);
             }
             if(clist.size() > 0 && clist.size()==1)
             {
                 if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
             }
             if(clist.size() > 0 && clist.size()==2)
             {
                 if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
                 if(clist[1].email != null && clist[1].email != '')
                    ao.AF_AgencyUsers2__c = clist[1].email;
             }
             if(clist.size() > 0 && clist.size()==3)
             {
                 if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
                 if(clist[1].email != null && clist[1].email != '')
                    ao.AF_AgencyUsers2__c = clist[1].email;
                 if(clist[2].email != null && clist[2].email != '')
                    ao.AF_AgencyUsers3__c = clist[2].email;
             }
             if(clist.size() > 0 && clist.size()==4)
             {
                 if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
                 if(clist[1].email != null && clist[1].email != '')
                    ao.AF_AgencyUsers2__c = clist[1].email;
                 if(clist[2].email != null && clist[2].email != '')
                    ao.AF_AgencyUsers3__c = clist[2].email;
                 if(clist[3].email != null && clist[3].email != '')
                    ao.AF_AgencyUsers4__c = clist[3].email;
            }
            if(clist.size() > 0 && clist.size()==5)
            {
                if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
                 if(clist[1].email != null && clist[1].email != '')
                    ao.AF_AgencyUsers2__c = clist[1].email;
                 if(clist[2].email != null && clist[2].email != '')
                    ao.AF_AgencyUsers3__c = clist[2].email;
                  if(clist[3].email != null && clist[3].email != '')
                    ao.AF_AgencyUsers4__c = clist[3].email;
                  if(clist[4].email != null && clist[4].email != '')
                    ao.AF_AgencyUsers5__c = clist[4].email;
            }
            if(clist.size() > 0 && clist.size()==6)
            {
                if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
                if(clist[1].email != null && clist[1].email != '')
                    ao.AF_AgencyUsers2__c = clist[1].email;
                if(clist[2].email != null && clist[2].email != '')
                    ao.AF_AgencyUsers3__c = clist[2].email;
                if(clist[3].email != null && clist[3].email != '')
                    ao.AF_AgencyUsers4__c = clist[3].email;
                if(clist[4].email != null && clist[4].email != '')
                    ao.AF_AgencyUsers5__c = clist[4].email;
                if(clist[5].email != null && clist[5].email != '')
                    ao.AF_AgencyUsers6__c = clist[5].email;
            }
            if(clist.size() > 0 && clist.size()==7)
            {
                if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
                if(clist[1].email != null && clist[1].email != '')
                    ao.AF_AgencyUsers2__c = clist[1].email;
                if(clist[2].email != null && clist[2].email != '')
                    ao.AF_AgencyUsers3__c = clist[2].email;
                if(clist[3].email != null && clist[3].email != '')
                    ao.AF_AgencyUsers4__c = clist[3].email;
                if(clist[4].email != null && clist[4].email != '')
                    ao.AF_AgencyUsers5__c = clist[4].email;
                if(clist[5].email != null && clist[5].email != '')
                    ao.AF_AgencyUsers6__c = clist[5].email;
                if(clist[6].email != null && clist[6].email != '')
                    ao.AF_AgencyUsers7__c = clist[6].email;
            }
            if(clist.size() > 0 && clist.size()==8)
            {
                if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
                if(clist[1].email != null && clist[1].email != '')
                    ao.AF_AgencyUsers2__c = clist[1].email;
                if(clist[2].email != null && clist[2].email != '')
                    ao.AF_AgencyUsers3__c = clist[2].email;
                if(clist[3].email != null && clist[3].email != '')
                    ao.AF_AgencyUsers4__c = clist[3].email;
                if(clist[4].email != null && clist[4].email != '')
                    ao.AF_AgencyUsers5__c = clist[4].email;
                if(clist[5].email != null && clist[5].email != '')
                    ao.AF_AgencyUsers6__c = clist[5].email;
                if(clist[6].email != null && clist[6].email != '')
                    ao.AF_AgencyUsers7__c = clist[6].email;
                if(clist[7].email != null && clist[7].email != '')
                    ao.AF_AgencyUsers8__c = clist[7].email;         
            }
            if(clist.size() > 0 && clist.size()==9)
            {
                if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
                if(clist[1].email != null && clist[1].email != '')
                    ao.AF_AgencyUsers2__c = clist[1].email;
                if(clist[2].email != null && clist[2].email != '')
                    ao.AF_AgencyUsers3__c = clist[2].email;
                if(clist[3].email != null && clist[3].email != '')
                    ao.AF_AgencyUsers4__c = clist[3].email;
                if(clist[4].email != null && clist[4].email != '')
                    ao.AF_AgencyUsers5__c = clist[4].email;
                if(clist[5].email != null && clist[5].email != '')
                    ao.AF_AgencyUsers6__c = clist[5].email;
                if(clist[6].email != null && clist[6].email != '')
                    ao.AF_AgencyUsers7__c = clist[6].email;
                if(clist[7].email != null && clist[7].email != '')
                    ao.AF_AgencyUsers8__c = clist[7].email;
                if(clist[8].email != null && clist[8].email != '')
                    ao.AF_AgencyUsers9__c = clist[8].email;
            }
            if(clist.size() > 0 && clist.size()>=10)
            {
                if(clist[0].email != null && clist[0].email != '')
                    ao.AF_AgencyUsers1__c = clist[0].email;
                if(clist[1].email != null && clist[1].email != '')
                    ao.AF_AgencyUsers2__c = clist[1].email;
                if(clist[2].email != null && clist[2].email != '')
                    ao.AF_AgencyUsers3__c = clist[2].email;
                if(clist[3].email != null && clist[3].email != '')
                    ao.AF_AgencyUsers4__c = clist[3].email;
                if(clist[4].email != null && clist[4].email != '')
                    ao.AF_AgencyUsers5__c = clist[4].email;
                if(clist[5].email != null && clist[5].email != '')
                    ao.AF_AgencyUsers6__c = clist[5].email;
                if(clist[6].email != null && clist[6].email != '')
                    ao.AF_AgencyUsers7__c = clist[6].email;
                if(clist[7].email != null && clist[7].email != '')
                    ao.AF_AgencyUsers8__c = clist[7].email;
                if(clist[8].email != null && clist[8].email != '')
                    ao.AF_AgencyUsers9__c = clist[8].email;
                if(clist[9].email != null && clist[9].email != '')
                    ao.AF_AgencyUsers10__c = clist[9].email;
            }
        }
    }
}