src/objects/AF_CatFinanceThreshold__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is used to input the dates which the category Finance user should input the Bonus Threshold values</description>
    <fields>
        <fullName>AF_Date__c</fullName>
        <label>AF_Date</label>
        <type>Date</type>
    </fields>
    <label>AF_CatFinanceThreshold</label>
</CustomObject>

src/classes/Test_AF_SendEmailToCatFinance.cls
/*****************************************************************************************************************************
@Author :Cognizant
@name : Test_AF_SendEmailToCatFinance
@Created Date : 08/08/2014.
@Description : This Test class for  AF_SendEmailToCatFinance apex class.
@Version : 1.0
@reference : none
****************************************************************************************************************************/
@isTest(SeeAlldata=false)
public class Test_AF_SendEmailToCatFinance
{  
	/**********************************************************************
*  @Description: This method will have Test data.
*  @name : AFCallingSchedulable
*  @param : none
*  @return : none
*************************************************************************/  
	Static testMethod void AFCallingSchedulable()
	{
		Test.StartTest();
		AF_CatFinanceThreshold__c customList = new AF_CatFinanceThreshold__c();
		customList.AF_Date__c = system.today();
		insert customList;
		System.Assert(customList.Id != null, 'The customsetting record not inserted');
		AF_SendEmailToCatFinance obj = new AF_SendEmailToCatFinance();
		//obj.query=null;
		Datetime dt = Datetime.now().addMinutes(1);
		String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
		String jobId = System.schedule('Sample_Heading', CRON_EXP, obj); 
		Database.BatchableContext BC ;
		obj.finish(BC);
		Test.stopTest();
	}
}