src/objects/AF_Category_Brand__c.object
<CustomObject>
    <description>Used to store Categories and associated brands related to Agency Fee Application.</description>
    <fields>
        <fullName>AF_Brand_Logo__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Brand Logo Image
Created as per requirement A5.1 inRTM</description>
        <label>Brand Logo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>AF_Category_Brands__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AgencyFee#GLOBAL#To associate brands to corresponding Categories</description>
        <label>Category</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AF_Category_Brand__c</referenceTo>
        <relationshipLabel>Category-Brands</relationshipLabel>
        <relationshipName>Category_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AF_Super_category__c</fullName>
        <description>AgencyFee#GLOBAL#To Store Super Catgeories</description>
        <label>Super category</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drinks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foods</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Stores the Brand</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Category-Brands</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category-Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Category_Brands.cls
public class Category_Brands 
{
   /* List<SelectOption> options = new List<SelectOption>();
    public Category_Brands(ApexPages.StandardController controller) 
    {
        category =new AF_Category_Brand__c();
        maprectype=new map<string,string>();        
        for(Recordtype rec:[select id,name from Recordtype where SobjectType=:'AF_Category_Brand__c' and IsActive=:true])
           {
               if(RecTypeValue==null)
                   RecTypeValue=rec.name;
               options.add(new SelectOption(rec.name,rec.name));
               maprectype.put(rec.name,string.valueof(rec.id));
           }
    }

    public AF_Category_Brand__c category{set;get;}
    public string CategoryValue{set;get;}
    public string BrandValue{set;get;}
    public string RecTypeValue{set;get;}
    public Category_Brands()
    {
       category =new AF_Category_Brand__c();
       
    }
    public map<string,string> maprectype{set;get;}
    public List<SelectOption> getRecTypes() 
    {
        
        return options;
    }
    
    public void OnchangeType()
    {}
    
    public pagereference Save_Record()
    {
        try
        {     
            pagereference ref;
            category.recordtypeid=maprectype.get(RecTypeValue);
            if(RecTypeValue=='Brand')
            {
                if(BrandValue!=null && BrandValue!='')
                {
                    
                    category.name=BrandValue;
                    category.Brand__c=BrandValue;
                    category.AF_Super_category__c=null;
                    upsert category;
                    ref=new pagereference('/'+category.id);
                    
                
                }    
                else
                {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error,'Please Enter Brand value'));
                    
                }
            }
            Else if(RecTypeValue=='Category')
            {
               if(CategoryValue!=null && CategoryValue!='')
               {
                    
                    category.name=CategoryValue;
                    category.Brand__c=null;
                    category.AF_Category_Brands__c=null;
                    category.AF_Brand_Logo__c=null;
                    upsert category;
                    ref=new pagereference('/'+category.id);
                    
                    
               }    
               else
               {
                   ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error,'Please Enter Category Value '));
                }           
            }
            
            
           
            return ref;
        }
        Catch(Exception ex)
        {
            apexpages.addmessages(ex);
            return null; 
        }
    }*/
}