src/objects/Amr_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Is_PC_part_of_the_Roster__c</fullName>
        <label>Is PC part of the Roster ?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_the_PPC_part_of_the_Roster__c</fullName>
        <label>Is PPC part of the Roster?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Amount_of_PC__c</fullName>
        <label>Local Amount of PC</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Local_Amount_of_PPC__c</fullName>
        <label>Local Amount of PPC</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Local_Currency_of_PC_Costs__c</fullName>
        <label>Local Currency of PC Costs</label>
        <picklist>
            <picklistValues>
                <fullName>Euro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>£</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A Guilder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algerian Dinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baht</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balboa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ber $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boliviano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Can $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cedi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFA Franc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congo Franc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dirham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D Krone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fiji $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuerte (Parallel)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Cordoba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK $</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Currency_of_PPC_Costs__c</fullName>
        <label>Local Currency of PPC Costs</label>
        <picklist>
            <picklistValues>
                <fullName>Euro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>£</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A Guilder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algerian Dinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baht</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balboa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ber $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boliviano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Can $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cedi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFA Franc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congo Franc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dirham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D Krone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fiji $</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuerte (Parallel)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Cordoba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HK $</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PC_Costs_Euro_Amount__c</fullName>
        <label>PC Costs (Euro Amount)</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Country__c</fullName>
        <label>PC Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PC_name__c</fullName>
        <label>PC name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PPC_Country__c</fullName>
        <label>PPC Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PPC_Name__c</fullName>
        <label>PPC Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Company_Name__c</fullName>
        <label>Service Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Amr Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amr Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Amr_QuotePageController.cls
public class Amr_QuotePageController {
        
        public String savingId{get;set;}
        public List<Amr_Quote__c> quoteOldList{get;set;}
        
        public List<Amr_Quote__c> quoteNewRow{
        get{
             if(quoteNewRow == null)
                    quoteNewRow = new List<Amr_Quote__c>();     
                return quoteNewRow;
        }set;
    }
        
        public  Document document {
        get {
          if (document == null)
             document = new Document();
             return document;
        }
        set;
   }
        
        public Amr_QuotePageController(){
                
                savingId = ApexPages.currentPage().getParameters().get('id');
            system.debug('savingId========>'+savingId);
            
            quoteOldList = [select Is_PC_part_of_the_Roster__c,PC_name__c,PC_Country__c,Service_Company_Name__c,
                                   Local_Currency_of_PC_Costs__c,Local_Amount_of_PC__c,PC_Costs_Euro_Amount__c,
                                   Is_the_PPC_part_of_the_Roster__c,PPC_Name__c,PPC_Country__c,
                                   Local_Currency_of_PPC_Costs__c,Local_Amount_of_PPC__c,
                                   PPC_Costs_Euro_Amount__c,CA_Additional_agency_Name__c,CA_Location__c,
                                   Local_Currency_of_CA_Costs__c,Local_Amount_of_CA__c,CA_Costs_Euro_Amount__c,
                                   Total_Costs__c from Amr_Quote__c where Saving__c = :savingId];
            system.debug('----------quote list'+quoteOldList);
            
            Amr_Quote__c quoteObj = new Amr_Quote__c(Saving__c = savingId);
            quoteNewRow.add(quoteObj);
        }
        
        public PageReference addRowQuote(){
                system.debug('new Quote entered===>'+quoteNewRow);
            system.debug('new Quote entered===>'+document);
            insert quoteNewRow;
            for(Amr_Quote__c quoteObj: quoteNewRow){
              quoteOldList.add(quoteObj);
            }
            
            quoteNewRow.clear();
        quoteNewRow.add(new Amr_Quote__c(Saving__c = savingId));
            return null;
        }
        
}