src/objects/Amr_Job_Details__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Contact_Account_Director_Email__c</fullName>
        <inlineHelpText>The Agency person managing this project/activity</inlineHelpText>
        <label>Agency Contact Account Director Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Any_other_agencies_involved__c</fullName>
        <inlineHelpText>List the names of any other agencies that will be working on this activity. Add other agency name with comma separated value</inlineHelpText>
        <label>Any other agencies involved ?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Budget_Allocated_Input_Value__c</fullName>
        <inlineHelpText>The money set aside in your budget for completing this project/activity</inlineHelpText>
        <label>Budget Allocated Input Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <inlineHelpText>Campaign name and/or creative idea created by the agency (e.g. Nothing beats an astronaut)</inlineHelpText>
        <label>Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Digital_Agency_Name__c</fullName>
        <inlineHelpText>The name of the Digital Agency managing this project/activity</inlineHelpText>
        <label>Digital Agency Name (if applicable)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Approver_Of_Material_Email__c</fullName>
        <inlineHelpText>The senior manager who has overall responsibility for this material</inlineHelpText>
        <label>Final Approver Of Material Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Target_Air_Date__c</fullName>
        <inlineHelpText>The date when the material will first be put to use</inlineHelpText>
        <label>Target Air Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unilever_Finance_Member_Email__c</fullName>
        <inlineHelpText>The person who has financial approval on this project/activity</inlineHelpText>
        <label>Unilever finance member email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Your_Email_Address__c</fullName>
        <inlineHelpText>The person completing this registration</inlineHelpText>
        <label>Your Email Address</label>
        <type>Email</type>
    </fields>
    <label>Amr Job Details</label>
    <nameField>
        <label>Job Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amr Job Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Amr_Saving__c.object
<CustomObject>
    <fields>
        <fullName>Duration_of_Additional_Films__c</fullName>
        <label>Duration of Additional Films</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration_of_Masters__c</fullName>
        <label>Duration of Masters</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder_Name__c</fullName>
        <label>Folder Name</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted Quotes and Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Quotes and Documents</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Details__c</fullName>
        <label>Job Details</label>
        <referenceTo>Amr_Job_Details__c</referenceTo>
        <relationshipName>AM_Savings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Monthly_Submitted__c</fullName>
        <label>Monthly Submitted</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Amr Saving</label>
    <nameField>
        <label>AM_Saving Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amr Savings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Amr_UploadSavingFilesController_Test.cls
@isTest
public class Amr_UploadSavingFilesController_Test {
     
        static testMethod void testMethod1() {
        Amr_Job_Details__c jobDetailsObj = new Amr_Job_Details__c(name = 'test1',Agency_Contact_Account_Director_Email__c = 'test@gmail.com',
                                            Digital_Agency_Name__c = 'test',Target_Air_Date__c = Date.Today(),Your_Email_Address__c = 'abc@gmail.com',
                                            Any_other_agencies_involved__c = 'abc',Budget_Allocated_Input_Value__c = 5,Campaign_Name__c = 'xyz',
                                            Final_Approver_Of_Material_Email__c = 'xas@gmail.com',Unilever_Finance_Member_Email__c = 'pqe@gmail.com'
                                            );
        insert jobDetailsObj;
        
        Amr_Saving__c savingObj = new Amr_Saving__c(Duration_of_Additional_Films__c = '12.4',Duration_of_Masters__c = '5',Job_Details__c = jobDetailsObj.id,
                                  Monthly_Submitted__c = 'January',Folder_Name__c = 'Brief');
                                  
        insert savingObj;
        
        Document documentObj = new Document(body = Blob.valueOf('test'),name = 'test1');
        
        
        Amr_UploadSavingFilesController_CC.MultipleDocumentInner innerObj  = new Amr_UploadSavingFilesController_CC.MultipleDocumentInner();
        innerObj.document = documentObj;
        innerObj.savingObj = savingObj;
        
        ApexPages.currentPage().getParameters().put('id',savingObj.id);
        
        Amr_UploadSavingFilesController_CC controller = new Amr_UploadSavingFilesController_CC();
        controller.FileCount = '1';
        
        controller.ChangeCount();
        controller.allFileList.add(innerObj);
        controller.SaveAttachments();
        system.assert(controller!= null);
    }
     
}