src/objects/ar_Agency_Portal_CMS__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accessibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Privacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T&amp;C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Card Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency List</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agency Portal CMS</label>
    <nameField>
        <displayFormat>CMS-{000}</displayFormat>
        <label>Agency Portal CMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Portal CMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AR_Test_LandingPage.cls
@isTest 
public with sharing class AR_Test_LandingPage {
	static testmethod void Test_LandingPage()
	{
		Test.startTest();
		
		ar_Agency_Portal_CMS__c testCMS = new ar_Agency_Portal_CMS__c();
		testCMS.title__c = 'test';
		testCMS.body__c = 'test';
		testCMS.order__c = 1;
		testCMS.Type__c = 'Landing Page' ;
		testCMS.Published__c = true;
		insert testCMS;
		
		AR_LandingPage testcon = new AR_LandingPage();
		testcon.init();

		System.assertEquals(testCMS.title__c,testcon.content.title__c,'No Data');
		
		Test.stopTest();
	}
}