src/objects/Article__c.object
<CustomObject>
    <customHelpPage>bc_help_pop_up_combined2</customHelpPage>
    <description>Force.com Sites &quot;Article&quot;. Used by content authors to create content to be displayed on the website.</description>
    <fields>
        <fullName>Image_Caption__c</fullName>
        <inlineHelpText>Optional caption for images. Displayed underneath an image when clicked</inlineHelpText>
        <label>Image Caption</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <inlineHelpText>References an external URL e.g. Sharepoint etc.</inlineHelpText>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Ordinal__c</fullName>
        <inlineHelpText>The sequence in which the articles should be displayed</inlineHelpText>
        <label>Ordinal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture_ID__c</fullName>
        <inlineHelpText>Please select Manage Content Library, Select an image from a library and copy the ID from the CMS_ID field. Ideal size of the image is 290 x 290 pixels.</inlineHelpText>
        <label>Article Image ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publish_Date__c</fullName>
        <inlineHelpText>Used to sort the content (most recent is always at the top) and is displayed on the full view of an article</inlineHelpText>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Workflow controls if this is set or not. Only Published articles will appear on the site.</description>
        <inlineHelpText>Tick this box to have the article appear on the site</inlineHelpText>
        <label>Display?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <inlineHelpText>This is the article summary that appears on the News Stories page</inlineHelpText>
        <label>Summary</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>uw_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>uw_Brand__c</referenceTo>
        <relationshipLabel>Articles</relationshipLabel>
        <relationshipName>Articles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Article</label>
    <nameField>
        <label>Article Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Category__c.object
<CustomObject>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/uw_Brand__c.object
<CustomObject>
    <customHelpPage>bc_help_pop_up_combined1</customHelpPage>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dressings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hair, Skin Cleansing, Deo, skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ice Cream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laundry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lipton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savoury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Cleansing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Brand Centre Old</label>
    <nameField>
        <label>Brands Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Centre Old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/uw_Links__c.object
<CustomObject>
    <customHelpPage>bc_help_pop_up6</customHelpPage>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>uw_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>uw_Brand__c</referenceTo>
        <relationshipLabel>Whos Who Links</relationshipLabel>
        <relationshipName>B_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Links</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Brand Links Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrandCentreExtension.cls
public class BrandCentreExtension {
        
        public string position {get;set;}
    public string Ordinal {get;set;}
    public string SectionImage {get;set;}
    public string Styleclass {get;set;}
    public string name {get;set;}
    public string Photolink{get;set;}
    public string Profilename{get;set;} 
     public string Profileid{get;set;}
    public string recordtypename{get;set;}
    public string linktype{get;set;}
        List<uw_Links__c> whoswholinks = new List<uw_Links__c>();
        List<uw_Links__c> brandlinks = new List<uw_Links__c>();
        List<Sub_Category__c> brandsubcategory = new List<Sub_Category__c>();
        
        uw_Links__c uwlink = new uw_Links__c();
    public uw_Links__c getUWLink() { return uwlink; }
        
        public BrandCentreExtension(ApexPages.StandardController controller) {
    
    ApexPages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=EmulateIE8');  
     articleImageCounter = 0;         
    recordtypename = ApexPages.currentPage().getParameters().get('retURL');
    linktype = ApexPages.currentPage().getParameters().get('type');
    User u = [Select u.SmallPhotoUrl, u.FullPhotoUrl, u.FirstName, u.LastName, u.id From User u where u.id=:Userinfo.getUserid()];
    Photolink = u.smallPhotoUrl;
    Profilename = u.FirstName + ' ' + u.LastName;
    Profileid = u.id;
    }
          
        private static Integer articleImageCounter {get {
    if (articleImageCounter == null) {
    articleImageCounter = 0;
    }
    return articleImageCounter;
    } set;}
    
    private static final Integer ARTICLE_POSITIONS = 3;

    private void advancePosition() {
    }
    public Integer articleImagePosition {get {
    advancePosition();
    return articleImagePosition;
    } private set;
    }
        
    public Boolean pos0 {get {
    articleImagePosition = math.mod(articleImageCounter,ARTICLE_POSITIONS);
    pos0 = (articleImagePosition == 0);
        return pos0;
        } private set;
        }
        public Boolean pos1 {get {
                    
        articleImagePosition = math.mod(articleImageCounter,ARTICLE_POSITIONS);
        pos1 = (articleImagePosition == 1);
        return pos1;
        } private set;
        }
        public Boolean pos2 {get {
        articleImagePosition = math.mod(articleImageCounter,ARTICLE_POSITIONS);
        pos2 = (articleImagePosition == 2);
        articleImageCounter++;          
        return pos2;
        } private set;
        }
    
        
        
        public List<Article__c> articles {get {
    if (articles == null) {
    articles = new List<Article__c>();
    }
    return articles;
    } private set;
    }
    
    
    
    list <article__c> articlelist;
    
    public list <article__c> getarticlelist()
    {        
    articlelist =  [Select Picture_ID__c, Link__c, Image_Caption__c, Id, Name, Summary__c, Publish_Date__c, Ordinal__c From Article__c  WHERE Published__c = true and uw_brand__c = :ApexPages.currentPage().getParameters().get('id') ORDER BY Ordinal__c];
    return articlelist;
    }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

}