src/objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If an asset belongs to an innovation or repeatable model, it must be part of an asset group. The asset group it relates to will be displayed here.</description>
        <inlineHelpText>If an asset belongs to an innovation or repeatable model, it must be part of an asset group. The asset group it relates to will be displayed here.</inlineHelpText>
        <label>Asset Group</label>
        <referenceTo>Asset_Group__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Brand the asset belongs to.</description>
        <inlineHelpText>Brand the asset belongs to.</inlineHelpText>
        <label>Brand</label>
        <referenceTo>Brand_Master__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Category the asset belongs to.</description>
        <inlineHelpText>Category the asset belongs to.</inlineHelpText>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POS_Asset_Type__c</fullName>
        <description>Determines the asset type and where it belongs to.</description>
        <inlineHelpText>Determines the asset type and where it belongs to.</inlineHelpText>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>Masterbrand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repeatable Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call To Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best Practices</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset_Group__c.object
<CustomObject>
    <description>Check with BET to see if this link can be made using the BET ID. Does this need to be a separate object?</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Brand the asset group belongs to.</description>
        <inlineHelpText>Brand the asset group belongs to.</inlineHelpText>
        <label>Brand</label>
        <referenceTo>Brand_Master__c</referenceTo>
        <relationshipLabel>Asset Groups</relationshipLabel>
        <relationshipName>Asset_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Category the asset group belongs to.</description>
        <inlineHelpText>Category the asset group belongs to.</inlineHelpText>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Asset Groups</relationshipLabel>
        <relationshipName>Asset_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Asset Groups can be created for Innovation (Guidelines) and Repeatable Models. In Addition can be created for In-Store Execution and Masterbrand .</description>
        <inlineHelpText>Asset Groups can be created for Innovation (Guidelines) and Repeatable Models. In Addition can be created for In-Store Execution and Masterbrand .</inlineHelpText>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>Masterbrand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repeatable Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call To Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best Practices</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Asset Group</label>
    <nameField>
        <label>Asset Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Segment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/File__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If an asset belongs to an innovation or repeatable model, it must be part of an asset group. If the file is related to an asset group, it is shown here.</description>
        <inlineHelpText>If an asset belongs to an innovation or repeatable model, it must be part of an asset group. If the file is related to an asset group, it is shown here.</inlineHelpText>
        <label>Asset Group</label>
        <referenceTo>Asset_Group__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>Uploads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Brand the file belongs to. Prepopulated depending on the source the file is created from.</description>
        <inlineHelpText>Brand the file belongs to. Prepopulated depending on the source the file is created from.</inlineHelpText>
        <label>Brand</label>
        <referenceTo>Brand_Master__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Category the asset belongs to. Prepopulated depending on the source the file is created from.</description>
        <inlineHelpText>Category the asset belongs to. Prepopulated depending on the source the file is created from.</inlineHelpText>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>CategoryUploads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feed_ID__c</fullName>
        <label>Feed ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feed_Thumbnail_URL__c</fullName>
        <label>Feed Thumbnail URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feed_URL__c</fullName>
        <label>Feed URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Primary_Image__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tickbox this if the file contains the image which should be used as the thumbnail representing the underlaying asset (if the file belongs to an asset).</description>
        <inlineHelpText>Tickbox this if the file contains the image which should be used as the thumbnail representing the underlaying asset (if the file belongs to an asset).</inlineHelpText>
        <label>Is Primary Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>POS_File_Type__c</fullName>
        <description>The file relates to a category, brand, asset group or asset. The asset type information is copied from the origin.</description>
        <inlineHelpText>The file relates to a category, brand, asset group or asset. The asset type information is copied from the origin.</inlineHelpText>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>Masterbrand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Store Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repeatable Model</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>The order in which the files will be displayed in the WIN@POS user interface</description>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <description>The file type will determine which icon will be shown in the front-end to the user for this file.</description>
        <inlineHelpText>The file type will determine which icon will be shown in the front-end to the user for this file.</inlineHelpText>
        <label>File Type</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Artwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Download Image</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Download</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toolkit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>File</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WINatPOSUploadController.cls
/*===========================================================================
  Name:  WINatPOSUploadController                                                       
  Copyright notice:                                                          
  ===========================================================================
  ===========================================================================
   Purpose: Controller for WINatPOSUpload page                                                                  
  -------                                                                    
  ===========================================================================
  ===========================================================================
  History                                                                   
  -------                                                                   
  VERSION  AUTHOR           DATE              DETAIL          RELEASE/CSR   
   1.0 -  Darren Sabey   22/10/2013      INITIAL DEVELOPMENT               
  ===========================================================================*/

public with sharing class WINatPOSUploadController {

    public File__c f {get; set;}
    public Document d {get; set;}
    
    public WINatPOSUploadController(ApexPages.StandardController sc) {
        f = (File__c) sc.getRecord();
        if (f.Id == null) {
        	if (f.Asset__c != null) {
        		// Set the POS file type
        		Asset__c a = [Select Id, POS_Asset_Type__c
        		              From Asset__c 
        		              Where Id = :f.Asset__c];
                f.POS_File_Type__c = a.POS_Asset_Type__c; 
            } 
        } else {
        	f = [Select Id, Name, Asset__c, Brand__c, Category__c, Asset_Group__c, Feed_ID__c, Feed_URL__c,
        	            Feed_Thumbnail_URL__c, Type__c, Is_Primary_Image__c, Sub_Type__c, POS_File_Type__c, Sort_Order__c 
        	     From File__c 
        	     Where Id = :f.Id];
        }
        d = new Document();
    }
    
    public PageReference saveAndUpload() {
    	
    	// Start transaction control
        Savepoint sp = Database.setSavepoint();
    	    
    	try {
    		
    		// Upsert the existing record
    		upsert f;
            
            if (d.Name != null && d.Body != null) {
                // Create the Chatter feed items and link to the file record
            	FeedItem post = new FeedItem();
                post.ParentId = f.Id; 
                post.Body = d.Name;
                post.ContentData = d.Body;
                post.ContentFileName = d.Name;
                post.Title = d.Name;
                insert post;
            
                // Link the file record to the Chatter feed item
                f.Feed_ID__c = post.Id;
                upsert f;            
            }
    	} catch (Exception e) {
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, e.getMessage()));
        	// Rollback any changes
            Database.rollback(sp);
            // Remove the file record id from the sobject 
            f = f.clone(false, true, true, true);
            // Clear the viewstate
            d.Body = null;
            d = new Document();
    		return null;
    	} finally {
    		// Clear the viewstate
            d.body = null; 
            d = new Document();
        }
        
        // Navigate user to the asset record
        String retURL = ApexPages.currentPage().getParameters().get('retURL');
        if (retURL != null) {
            return new PageReference(retURL);        	
        } else {
            return new ApexPages.StandardController(f).view(); 
        }        
    }
    
}