src/objects/BET_Category__c.object
<CustomObject>
    <label>BET Category</label>
    <nameField>
        <label>BET Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BET Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDO_Brand__c.object
<CustomObject>
    <description>mdo master object to store brands</description>
    <fields>
        <fullName>status__c</fullName>
        <description>store status of the brand</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MDO_BrandPositions__c.object
<CustomObject>
    <description>Store brand positions details</description>
    <fields>
        <fullName>brand_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to brand</description>
        <label>Brand Id</label>
        <referenceTo>MDO_Brand__c</referenceTo>
        <relationshipLabel>BrandPositions</relationshipLabel>
        <relationshipName>BrandPositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>brand_position_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to brand position</description>
        <label>Brand Position Id</label>
        <referenceTo>MDO_BrandPosition__c</referenceTo>
        <relationshipLabel>BrandPositions</relationshipLabel>
        <relationshipName>BrandPositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product_category_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to mdm_category</description>
        <label>Product Category Id</label>
        <referenceTo>MDO_Category__c</referenceTo>
        <relationshipLabel>BrandPositions</relationshipLabel>
        <relationshipName>BrandPositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>store status of brand positions</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BrandPositions</label>
    <nameField>
        <displayFormat>BPS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BrandPositions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MDO_Category__c.object
<CustomObject>
    <description>Store mdo product category master data</description>
    <fields>
        <fullName>parent_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent ID</label>
        <referenceTo>MDO_Category__c</referenceTo>
        <relationshipLabel>ProductCategory</relationshipLabel>
        <relationshipName>ProductCategory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>store mdm product category status</description>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ProductCategory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductCategory</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Sub_Category__c.object
<CustomObject>
    <label>Sub Category</label>
    <nameField>
        <label>Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/uw_BET__c.object
<CustomObject>
    <customHelpPage>be_help_pop_up</customHelpPage>
    <description>Custom object for Brand Experience Toolkit</description>
    <fields>
        <fullName>Brand_Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Positioning</label>
        <referenceTo>MDO_BrandPosition__c</referenceTo>
        <relationshipLabel>Brand Experience List</relationshipLabel>
        <relationshipName>Brand_Experience_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category Group</label>
        <referenceTo>MDO_Category__c</referenceTo>
        <relationshipLabel>Brand Experience List</relationshipLabel>
        <relationshipName>Brand_Experience_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BET_Category__c.BET_Parent_Category__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BET_Category__c</referenceTo>
        <relationshipLabel>Brand Experience (BET Division)</relationshipLabel>
        <relationshipName>Brand_Experience1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>MDO_Brand__c</referenceTo>
        <relationshipLabel>Brand Experience List</relationshipLabel>
        <relationshipName>Brand_Experience_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>MDO_Category__c</referenceTo>
        <relationshipLabel>Brand Experience List (Product Category)</relationshipLabel>
        <relationshipName>Brand_Experience_List1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>In Progress - when BET is still being built
Published - Once the BET is complete
Expired - when the BET and its associated assets have expired.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>First release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Releasing assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release to refresh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unreleased</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BET_Category__c.BET_Parent_Category__c</field>
                <operation>equals</operation>
                <valueField>$Source.Category__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BET_Category__c</referenceTo>
        <relationshipLabel>Brand Experience</relationshipLabel>
        <relationshipName>Brand_Experience</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>uw_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Search and select your Brand, which includes &apos;Cross-Brand&apos; if your BET is cross brand. 
Note: If you cannot find your brand then you can select any brand and uncheck &apos;Inherit branding&apos;.</inlineHelpText>
        <label>Brand</label>
        <referenceTo>uw_Brand__c</referenceTo>
        <relationshipLabel>Brand Experience</relationshipLabel>
        <relationshipName>BETs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Experience</label>
    <nameField>
        <label>Toolkit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Experience List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/uw_Brand__c.object
<CustomObject>
    <customHelpPage>bc_help_pop_up_combined1</customHelpPage>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Foods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HomeCare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refreshments</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Brand</label>
        <referenceTo>uw_Brand__c</referenceTo>
        <relationshipName>uw_Brand</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dressings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hair, Skin Cleansing, Deo, skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ice Cream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laundry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lipton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savoury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Cleansing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Brand Centre Old</label>
    <nameField>
        <label>Brands Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Centre Old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BET_MDODataMigrationAndTransformBatch.cls
/*****************************************************************************************************************************
Name: BET_MDODataMigrationAndTransformBatch
Copyright © 2015 Unilever. 

Purpose: One  off  update  in  BET  to  update  all  BET records  to refer  to  the  new
master data reference tables

History
-------
VERSION AUTHOR                  		DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   m.bluj@polsource.com            02/09/2015      INITIAL DEVELOPMENT
*******************************************************************************************************************************/
global class BET_MDODataMigrationAndTransformBatch implements Database.Batchable<sObject> {
	
	String query = 'SELECT id,uw_Brand__c,uw_Brand__r.name,Product_Brand__c,Category__c,Category__r.name,Category_Group__c,Sub_Category__c,Sub_Category__r.name,Product_Category__c,Brand_Position__c '+
				   'FROM uw_Bet__c '+
				   'WHERE Brand_Position__c == null';

	global Map<String,MDO_Category__c> categoryGroups = new Map<String,MDO_Category__c>();
	global Map<Id,List<MDO_Category__c>> categoryGroupRelatedCategories = new Map<Id,List<MDO_Category__c>>();
	global Map<String,MDO_Brand__c> brands = new Map<String,MDO_Brand__c>();

	global BET_MDODataMigrationAndTransformBatch() {
		for(MDO_Category__c categoryGroup : (List<MDO_Category__c>)BET_MasterDataService.getBETCategoryGroups()){
			categoryGroups.put(categoryGroup.name, categoryGroup);
		}

		for(MDO_Category__c category : BET_MasterDataService.getAllAvailableCategories()){
			if(categoryGroupRelatedCategories.keySet().contains(category.parent_id__r.parent_id__c)){
				categoryGroupRelatedCategories.get(category.parent_id__r.parent_id__c).add(category);
			} else {
				categoryGroupRelatedCategories.put(category.parent_id__r.parent_id__c, new List<MDO_Category__c>{category});
			}
		}

		for(MDO_Brand__c brand : [select id,name from MDO_Brand__c where status__c = 'Active']){
			brands.put(brand.name, brand);
		}
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		update proceedWithDataTransormation((List<uw_Bet__c>)scope);
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}

	global List<uw_Bet__c> proceedWithDataTransormation(List<uw_Bet__c> scope){
		System.debug('Entering proceedWithDataTransormation : ' + scope);
		List<uw_Bet__c> betsForUpdate = new List<uw_Bet__c>();
		List<uw_Bet__c> betsForErrors = new List<uw_Bet__c>();
		for(uw_Bet__c bet : scope) {
			MDO_Category__c categoryGroup = categoryGroups.get(bet.Category__r.name);
			MDO_Brand__c brand = brands.get(bet.uw_Brand__r.name);
			bet.Category_Group__c = categoryGroup == null ? null : categoryGroup.id;
			bet.Product_Brand__c = brand == null ? null : brand.id;
			if(categoryGroup != null) {
				for(MDO_Category__c category : categoryGroupRelatedCategories.get(categoryGroup.id)){
					if(category.name == bet.Sub_Category__r.name){
						bet.Product_Category__c = category.id;
					}
				}
			}
			if(bet.Product_Category__c != null && bet.Product_Brand__c != null){
				bet.Brand_Position__c = getBrandPosition(bet.Product_Brand__c,bet.Product_Category__c);
			}
			if(validateBet(bet)){
				betsForUpdate.add(bet);
			} else {
				betsForErrors.add(bet);
			}
		}
		System.debug('Exit proceedWithDataTransormation : ' + betsForUpdate + ', ' + betsForErrors);
		logErrors(betsForErrors);
		return betsForUpdate;
	}

	global Id getBrandPosition(Id brandId,Id categoryId){
		List<MDO_BrandPositions__c> bpositions = [select id,brand_position_id__c from MDO_BrandPositions__c where 
														brand_id__c =: brandId 
														and product_category_id__c in (select id from MDO_Category__c where parent_id__c =: categoryId or id =: categoryId)];	

		return bpositions.isEmpty() ? null : bpositions.get(0).brand_position_id__c;
	}

	global Boolean validateBet(uw_Bet__c bet){
		System.debug('Entering validateBet : ' + bet);
		return bet.Product_Brand__c != null && bet.Category__c != null && bet.Product_Category__c != null && bet.Brand_Position__c != null;
	}

	global void logErrors(List<uw_Bet__c> betsForErrors){
		for(uw_Bet__c betRecord : betsForErrors){
			system.debug('Invalid MDO matching for BET : ' + betRecord);
		}
	}
	
}