src/objects/BET_Follow_Request__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Experience_Toolkit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand  Experience   Toolkit</label>
        <referenceTo>uw_BET__c</referenceTo>
        <relationshipLabel>BET Follow Requests</relationshipLabel>
        <relationshipName>BET_Follow_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BET Follow Request</label>
    <nameField>
        <displayFormat>BFR-{000000}</displayFormat>
        <label>BET Follow Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BET Follow Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BET_Member_Request__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Experience_Toolkit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Experience Toolkit</label>
        <referenceTo>uw_BET__c</referenceTo>
        <relationshipLabel>BET Member Requests</relationshipLabel>
        <relationshipName>BET_Member_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Follow BET Request</label>
        <referenceTo>BET_Follow_Request__c</referenceTo>
        <relationshipLabel>BET Member Requests</relationshipLabel>
        <relationshipName>BET_Member_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BET_Member_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BET Member Request</label>
    <nameField>
        <displayFormat>BMR-{000000}</displayFormat>
        <label>BET Member Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BET Member Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/uw_BET__c.object
<CustomObject>
    <customHelpPage>be_help_pop_up</customHelpPage>
    <description>Custom object for Brand Experience Toolkit</description>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Inoplan_Project__r.Project_Id__c</formula>
        <label>Inoplan ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>In Progress - when BET is still being built
Published - Once the BET is complete
Expired - when the BET and its associated assets have expired.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>First release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Releasing assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release to refresh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unreleased</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Brand Experience</label>
    <nameField>
        <label>Toolkit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Experience List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BET_MemberRequestHandlerClsTest.cls
/*****************************************************************************************************************************
Name: BET_MemberRequestHandlerClsTest
Copyright © 2015 Unilever. 

Purpose: BET_MemberRequestHandlerClsTest is test class for BET_MemberRequestHandlerCls

History
-------
VERSION AUTHOR                  		DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   k.szepietowski@polsource.com            28/07/2015      INITIAL DEVELOPMENT
*******************************************************************************************************************************/
@isTest
private class BET_MemberRequestHandlerClsTest {
	
    @isTest static void testPreventMemberRequestDuplicatesWhileInsertWithInvalidProjectId(){
        Test.startTest();
        //check for owner
        uw_BET__c betObject = BET_TestUtils.getTestBet();
        insert betObject;
        String invalidProjectID = BET_TestUtils.createIPMProject('Unit Test IPM Project Name').id;
        BET_Follow_Request__c followRequest = BET_TestUtils.createBetFollowRequest(betObject.id,invalidProjectID);
        insert followRequest;
        //create test member request data
        List<BET_Member_Request__c> betMembersToInsert = new List<BET_Member_Request__c>();
        for(User u : [Select id FROM User Limit 10]){
            BET_Member_Request__c betMemeberItem = new BET_Member_Request__c();
            betMemeberItem.Brand_Experience_Toolkit__c = betObject.id;
            betMemeberItem.ProjectRequest__c = followRequest.id;
            betMemeberItem.UserId__c = u.id;
            betMemeberItem.Project_Id__c = invalidProjectID;
			betMemeberItem.Status__c = Label.BETTeamMemberRequestNewStatus;
            betMemeberItem.Role__c = Label.BetTeamMemberRoleMember;
            betMembersToInsert.add(betMemeberItem);
        }
        //BET_CustomBETException should occure for invailid ProjectID wrong format
        insert betMembersToInsert;
        Test.stopTest();
        System.assertEquals(betMembersToInsert.size(),10,'There should be 10 elements in list');
    }
    
    
    @isTest static void testPreventMemberRequestDuplicatesWhileInsertWithVailidProjectId(){
        Test.startTest();
        //check for owner
        uw_BET__c betObject = BET_TestUtils.getTestBet();
        insert betObject;
        String invalidProjectID = betObject.id;
        BET_Follow_Request__c followRequest = BET_TestUtils.createBetFollowRequest(betObject.id,invalidProjectID);
        insert followRequest;
        //create test member request data
        List<BET_Member_Request__c> betMembersToInsert = new List<BET_Member_Request__c>();
        List<BET_Member_Request__c> betMembersToInsert1 = new List<BET_Member_Request__c>();
        List<User> usedUsers = new List<User>();
        for(User u : [Select id FROM User Limit 10]){
            BET_Member_Request__c betMemeberItem = new BET_Member_Request__c();
            betMemeberItem.Brand_Experience_Toolkit__c = betObject.id;
            betMemeberItem.ProjectRequest__c = followRequest.id;
            betMemeberItem.UserId__c = u.id;
            betMemeberItem.Project_Id__c = invalidProjectID;
			betMemeberItem.Status__c = Label.BETTeamMemberRequestNewStatus;
            betMemeberItem.Role__c = Label.BetTeamMemberRoleMember;
            betMembersToInsert.add(betMemeberItem);
            usedUsers.add(u);
        }
        
        //BET_CustomBETException should occure for invailid ProjectID wrong format    
        insert betMembersToInsert;
        for(BET_Member_Request__c memeberToClone : betMembersToInsert){
            betMembersToInsert1.add(memeberToClone.clone(false,true));
        }
        
        //try to insert one more time the sampe collection
        try{
            insert betMembersToInsert1;
            //system.assertEquals(0, 1, 'Exception should be thrown so this code instruction should not be executed in test');
        }catch(System.DmlException ex){
            system.assertEquals(true,ex.getMessage().containsIgnoreCase('is already defined'),'Exception message should contain given text');
            
        }
        Test.stopTest();
    }
	
}