src/objects/BET_Member_Request__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Experience_Toolkit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Experience Toolkit</label>
        <referenceTo>uw_BET__c</referenceTo>
        <relationshipLabel>BET Member Requests</relationshipLabel>
        <relationshipName>BET_Member_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BET_Member_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BET Member Request</label>
    <nameField>
        <displayFormat>BMR-{000000}</displayFormat>
        <label>BET Member Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BET Member Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/uw_BET__c.object
<CustomObject>
    <customHelpPage>be_help_pop_up</customHelpPage>
    <description>Custom object for Brand Experience Toolkit</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>In Progress - when BET is still being built
Published - Once the BET is complete
Expired - when the BET and its associated assets have expired.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>First release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Releasing assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release to refresh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unreleased</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Studio_Chatter_Group__c</fullName>
        <label>Studio Chatter Group</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Brand Experience</label>
    <nameField>
        <label>Toolkit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Experience List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/uw_BET_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BET_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BET Team Member</label>
    <nameField>
        <displayFormat>BTM-{0000}</displayFormat>
        <label>BET Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BET Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BET_ManageMembersService.cls
/* service class without sharing */
public without sharing class BET_ManageMembersService {

	private BET_ManageMembersService() {}

	/************************************************************
        Purpose: Method deletes team members
        Parameters: List<uw_BET_Team_Member__c> members
        Returns: -
        Throws: -
    *************************************************************/
	public static void deleteTeamMembers(List<uw_BET_Team_Member__c> members){
		delete members;
	}
	
	public static PageReference doMassApproveDeny(String status,List<BET_ManageMembersController.MemberRequestWrapper> memberRequests,Id betId){
        System.debug('Entering doMassApproveDeny ' + status + ', ' + memberRequests + ', ' + betId);
        List<BET_Member_Request__c> requests = new List<BET_Member_Request__c>();
        for(BET_ManageMembersController.MemberRequestWrapper memberRequest : memberRequests){
            if(memberRequest.isSelected){
                memberRequest.obj.Status__c = status;
                requests.add(memberRequest.obj);
            }
        }
        try{
            if(requests.isEmpty()){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.BET_Member_Requests_Not_Marked));  
                return null;
            } else {
                update requests;
            }
        }catch (Exception e){
            System.debug('Exception in doApprove : ' + e.getMessage());
            return null;
        }
        PageReference pr = BET_ManageMembersService.forward(betId);
        System.debug('Exit doMassApproveDeny : ' + pr);
        return pr;
    }

	/************************************************************
        Purpose: Method deletes related member requests
        Parameters: List<uw_BET_Team_Member__c> deletedMembers
        Returns: -
        Throws: -
    *************************************************************/
    public static void deleteRelatedMemberRequests(List<uw_BET_Team_Member__c> deletedMembers, Id betId){
        System.debug('Entering deleteRelatedMemberRequests : ' + deletedMembers);
        Set<Id> usersIds = new Set<Id>();
        for(uw_BET_Team_Member__c teamMember : deletedMembers){
            usersIds.add(teamMember.Team_Member__c);
        }
        delete [select id from BET_Member_Request__c where Brand_Experience_Toolkit__c =: betId and UserId__c in :usersIds];
        System.debug('Entering deleteRelatedMemberRequests');
    }

    /************************************************************
        Purpose: Method cleans up after removed tem members
        Parameters: -
        Returns: -
        Throws: -
    *************************************************************/
    public static void cleanUpSharesGroupsSubscriptions(List<uw_BET_Team_Member__c> deletedMembers, uw_BET__c bet){
        System.debug('Entering cleanUpSharesGroupsSubscriptions : ' + deletedMembers);
        Set<Id> usersIds = new Set<Id>();
        for(uw_BET_Team_Member__c teamMember : deletedMembers){
            usersIds.add(teamMember.Team_Member__c);
        }
        delete [SELECT Id FROM uw_BET__Share WHERE parentId = :bet.id AND userOrGroupId in:usersIds]; 
        delete [SELECT Id FROM CollaborationGroupMember WHERE CollaborationGroupId =: bet.Studio_Chatter_Group__c AND memberId in : usersIds];
        delete [Select Id,SubscriberId,ParentId from EntitySubscription where SubscriberId in:usersIds and ParentId=:bet.id limit 1000];
        System.debug('Exit cleanUpSharesGroupsSubscriptions');
    }


    /************************************************************
        Purpose: Method retrieves picklist value for given fieldresult
        Parameters: Schema.DescribeFieldResult fieldResult
        Returns: List<selectOption>
        Throws: -
    *************************************************************/
    public static List<selectOption> getRoles(Schema.DescribeFieldResult fieldResult,Boolean isBetOwnerOrManager){
        List<selectOption> options = new List<selectOption>();           
        List<Schema.PicklistEntry> picklistEntryList = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry picklistEntry : picklistEntryList){
            if(!isBetOwnerOrManager && picklistEntry.getLabel() != 'Manager') {
                options.add(new SelectOption(picklistEntry.getLabel(), picklistEntry.getValue()));
            } else if (isBetOwnerOrManager) {
                options.add(new SelectOption(picklistEntry.getLabel(), picklistEntry.getValue()));
            }
        }       
        return options;
    }

    /************************************************************
        Purpose: Method refreshes page
        Parameters: -
        Returns: PageReference
        Throws: -
    *************************************************************/
    public static PageReference forward(Id betId){
        System.debug('Entering forward');
        PageReference pr = new PageReference('/apex/BET_ManageMembers?bet='+betId);
        pr.setRedirect(true);
        System.debug('Exit forward ' + pr);
        return pr;
    }
}