src/objects/BFM_Debit_Note__c.object
<CustomObject>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DN_Company_Code_check_status__c</fullName>
        <label>DN Company Code check status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DN_Date_check_status__c</fullName>
        <label>DN Date check status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DN_Emission_date_time__c</fullName>
        <label>DN Emission date &amp; time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DN_Link_Check_Status__c</fullName>
        <label>DN Link Check Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DN_Vendor_Code_Check_Status__c</fullName>
        <label>DN Vendor Code Check Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Debit_Note_Status__c</fullName>
        <label>Debit Note Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occurrence__c</fullName>
        <label>Occurrence</label>
        <referenceTo>BFM_Occurrence__c</referenceTo>
        <relationshipLabel>Debit Notes</relationshipLabel>
        <relationshipName>Debit_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Request_For_Cancellation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request For Cancellation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <label>Vendor Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Debit Note</label>
    <nameField>
        <displayFormat>DN-{00000000}</displayFormat>
        <label>DN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_Occurrence__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Date_1__c</fullName>
        <label>Approval Date 1</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Date_2__c</fullName>
        <label>Approval Date 2</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Date_3__c</fullName>
        <label>Approval Date 3</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Date_4__c</fullName>
        <label>Approval Date 4</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Date_5__c</fullName>
        <label>Approval Date 5</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Date_6__c</fullName>
        <label>Approval Date 6</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occurrence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Occurrence</label>
        <referenceTo>BFM_Occurrence__c</referenceTo>
        <relationshipName>Occurrences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>Occ-{000}</displayFormat>
        <label>BFM Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_SES__c.object
<CustomObject>
    <fields>
        <fullName>Occurrence__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Occurrence</label>
        <referenceTo>BFM_Occurrence__c</referenceTo>
        <relationshipLabel>SESs</relationshipLabel>
        <relationshipName>SESOccs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unilever_company_code__c</fullName>
        <formula>Stage__r.Unilever_Account__r.Company_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unilever company code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Code__c</fullName>
        <formula>Stage__r.Shipment__r.Carrier_Account__r.Vendor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vendor Code</label>
        <type>Text</type>
    </fields>
    <label>SES</label>
    <nameField>
        <displayFormat>SES-{0000}</displayFormat>
        <label>SES Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SESs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BFM_DebitNote_CodeValidations.cls
public class BFM_DebitNote_CodeValidations{
    public static void debitNoteCheck(List<BFM_Debit_Note__c> dnRecords,set<id> setdebitnote,boolean isinsert){
        List<BFM_Debit_Note__c> dnTRecords = new List<BFM_Debit_Note__c>();
        List<BFM_Occurrence__c> occTRecords = new List<BFM_Occurrence__c>();
       // dnTRecords = [select id,Occurrence__c from BFM_Debit_Note__c where id in : dnRecords];
        map<id,BFM_Occurrence__c> mapocc = new map<id,BFM_Occurrence__c>();
        set<id> setoccurenceids = new set<id>();
        for(BFM_Debit_Note__c dn: dnRecords){
            setoccurenceids.add(dn.Occurrence__c);
        }
        if(!setoccurenceids.isEmpty()){
            occTRecords = [select id,(select id,Vendor_Code__c,Unilever_company_code__c from SESOccs__r),Approval_Date_1__c,Approval_Date_2__c,Approval_Date_3__c,Approval_Date_4__c,Approval_Date_5__c,Approval_Date_6__c from BFM_Occurrence__c where id in:setoccurenceids];
        }
        for(BFM_Occurrence__c occ: occTRecords){
            mapocc.put(occ.id,occ);
        }
        for(BFM_Debit_Note__c dn: dnRecords){
            if(isinsert == true || !setdebitnote.contains(dn.id)){
            if(dn.Request_For_Cancellation__c == false && dn.Debit_Note_Status__c!='Cancelled'){
            if(mapocc.containskey(dn.Occurrence__c) && !mapocc.get(dn.Occurrence__c).SESOccs__r.isEmpty()){
                dn.DN_Link_Check_Status__c = 'Link Ok';
                dn.Debit_Note_Status__c = 'Link Ok';
            }
            else{
                dn.DN_Link_Check_Status__c = 'Pending Link';
                dn.Debit_Note_Status__c = 'Pending Link';
            }
            }
            if(dn.DN_Link_Check_Status__c == 'Link Ok' && dn.Request_For_Cancellation__c == false && dn.Debit_Note_Status__c!='Cancelled'){
                integer codecount=0,vendorcount=0,datecount=0;
                if(!mapocc.get(dn.Occurrence__c).SESOccs__r.isEmpty()){
                    for(BFM_SES__c ses: mapocc.get(dn.Occurrence__c).SESOccs__r){
                        if(dn.Company_Code__c!=null && dn.Company_Code__c==ses.Unilever_company_code__c){
                            codecount++;
                        }
                        if(dn.Vendor_Code__c!=ses.Vendor_Code__c){
                            vendorcount++;
                        }                                                                
                    }
                    if(codecount>0){
                        dn.DN_Company_Code_Check_Status__c = 'Company Code Ok';
                        dn.Debit_Note_Status__c = 'Company Code Ok';
                    }
                    else{
                        dn.DN_Company_Code_Check_Status__c = 'Wrong Company Code';
                        dn.Debit_Note_Status__c = 'Wrong Company Code';
                    }
                    if(dn.DN_Company_Code_Check_Status__c == 'Company Code Ok'){
                    if(vendorcount==0){
                        dn.DN_Vendor_Code_Check_Status__c = 'Vendor Ok';
                        dn.Debit_Note_Status__c = 'Vendor Ok';
                    }
                    else{
                        dn.DN_Vendor_Code_Check_Status__c = 'Wrong Vendor';
                        dn.Debit_Note_Status__c = 'Wrong Vendor';
                    }
                    }
                }
                if(mapocc.containskey(dn.Occurrence__c) && dn.DN_Emission_date_time__c!=null && (date.valueof(dn.DN_Emission_date_time__c)>mapocc.get(dn.Occurrence__c).Approval_Date_1__c)){
                    datecount++;
                }
                if(dn.DN_Vendor_Code_Check_Status__c == 'Vendor Ok'){
                if(datecount>0){
                    dn.DN_Date_Check_Status__c = 'Date Ok';
                    dn.Debit_Note_Status__c = 'Date Ok';
                }
                else{
                    dn.DN_Date_Check_Status__c = 'Date Not Ok';
                    dn.Debit_Note_Status__c = 'Date Not Ok';
                }
                }
                
                }
            }
            }
                
            
        
    }
}