src/objects/BFM_NF_e__c.object
<CustomObject>
    <fields>
        <fullName>NFS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFS</label>
        <referenceTo>BFM_NFS__c</referenceTo>
        <relationshipLabel>NF-es</relationshipLabel>
        <relationshipName>NF_es</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NF_e_access_key__c</fullName>
        <externalId>true</externalId>
        <label>NF-e access key</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taker_CNPJ__c</fullName>
        <label>Taker CNPJ</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <label>NF-e</label>
    <nameField>
        <displayFormat>NF-e{00000}</displayFormat>
        <label>BFM NF-e Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NF-es</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BFM_NFS__c.object
<CustomObject>
    <fields>
        <fullName>NFS_Link_Check_Status__c</fullName>
        <label>NFS Link Check Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFS_Number__c</fullName>
        <label>NFS Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFS_Series__c</fullName>
        <label>NFS Series</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Taker_Company_UF__c</fullName>
        <formula>Service_Taker__r.Region__c</formula>
        <label>Service Taker Company UF</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_s_CNPJ_or_CPF__c</fullName>
        <label>Vendor´s CNPJ or CPF</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <label>NFS</label>
    <nameField>
        <displayFormat>NFS-{000000000}</displayFormat>
        <label>BFM NFS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NFS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_POD__c.object
<CustomObject>
    <fields>
        <fullName>NF_e_Access_Key__c</fullName>
        <externalId>true</externalId>
        <label>NF-e Access Key</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NF_e__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NF-e</label>
        <referenceTo>BFM_NF_e__c</referenceTo>
        <relationshipName>PODs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POD_Date__c</fullName>
        <label>POD Date</label>
        <type>Date</type>
    </fields>
    <label>POD</label>
    <nameField>
        <displayFormat>POD-{00000000}</displayFormat>
        <label>POD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PODs</pluralLabel>
    <recordTypes>
        <fullName>POD</fullName>
        <active>true</active>
        <label>POD</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BFM_POD_DateAdjustment_CC_Test.cls
@isTest
public class BFM_POD_DateAdjustment_CC_Test{
    private static testMethod void testBFM_POD_DateAdjustment_CC(){
    test.startTest();
    list<BFM_POD__c> podlst = new list<BFM_POD__c>();
    BFM_POD__c pod = new BFM_POD__c();          
    pod.POD_Date__c=Date.newInstance(2016,9,20);
    podlst.add(pod);    
    insert podlst;
        
    list<BFM_NFS__c>nfslst=new list<BFM_NFS__c>();

    BFM_NFS__c nfs=new BFM_NFS__c();
    nfs.Name='test';
    nfs.NFS_Number__c='1234';
    nfs.NFS_Series__c='123';
    nfs.Vendor_s_CNPJ_or_CPF__c='12345678900000';
    nfs.NFS_Link_Check_Status__c='Link Ok';
   // nfs.Service_Taker_Company_UF__c='12';
    //insert nfs;
    nfslst.add(nfs);
    
    insert nfslst; 
    system.assertEquals('test',nfs.Name); 
    
    BFM_NF_e__c nfe=new BFM_NF_e__c();
    nfe.NF_e_access_key__c='1234567890';
    nfe.Taker_CNPJ__c='12345678900000';
        
    nfe.NFS__c=nfs.id;
        
    insert nfe;
        
    pod.NF_e__c=nfe.id;
    update pod;
        
    BFM_POD_DateAdjustment_CC podHandler = new BFM_POD_DateAdjustment_CC();
    podHandler.podUpdate();
    podHandler.back(); 
    test.stopTest();
    }
}