src/objects/BFM_AbsoluteConsideration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>AbsoluteConsideration_Value__c</fullName>
        <label>AbsoluteConsideration Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BFM AbsoluteConsideration</label>
</CustomObject>

src/objects/BFM_CT_e__c.object
<CustomObject>
    <fields>
        <fullName>Cte_Status__c</fullName>
        <label>Cte Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DEFINITIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DEFINITIVE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ICMS_Tax_Rate__c</fullName>
        <label>ICMS Tax Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ICMS_Value__c</fullName>
        <label>ICMS Value</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Value__c</fullName>
        <formula>Receivable_Amount__c - ( ((Receivable_Amount__c * COFINS_Aliquot__c) + ( Receivable_Amount__c * PIS_Aliquot__c ))- ( Receivable_Amount__c * ICMS_Tax_Rate__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Status__c</fullName>
        <label>Tax Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>CT-e</label>
    <nameField>
        <displayFormat>CTE-{0000000}</displayFormat>
        <label>BFM CT-e Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CT-es</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>BFM_CT_e__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CT-e</label>
        <referenceTo>BFM_CT_e__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BFM_SES__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SES</label>
        <referenceTo>BFM_SES__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{0000000}</displayFormat>
        <label>BFM_Error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BFM_SES__c.object
<CustomObject>
    <fields>
        <fullName>CT_E__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CT-e</label>
        <referenceTo>BFM_CT_e__c</referenceTo>
        <relationshipLabel>SESs</relationshipLabel>
        <relationshipName>SESs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gross_Value_net_tax__c</fullName>
        <label>Gross Value (net+tax)</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ICMS_Calculation_Base__c</fullName>
        <label>ICMS Calculation Base</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ICMS_Value__c</fullName>
        <label>ICMS Value</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Value__c</fullName>
        <label>Net Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>SES</label>
    <nameField>
        <displayFormat>SES-{0000}</displayFormat>
        <label>SES Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SESs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BFM_ToleranceMargin__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Tolence Margin value is set for value validation and Tax validation.</description>
    <fields>
        <fullName>Tolerance_Percentage_Value__c</fullName>
        <label>Tolerance Percentage Value</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>BFM Tolerance Margin</label>
</CustomObject>

src/classes/BFM_TotalValueValidation.cls
Public Class BFM_TotalValueValidation{
    
    Private static Decimal  grossValue=0;
    @invocableMethod()
    Public static void CteTotalValueValidation(list<BFM_CT_e__c> CTeRecord){
        set<Id> recId=New set<Id>();
        Decimal SESTaxvalue;
        Decimal tolerancValue;
        Decimal toleranceMargin;
        Decimal taxValue;
        Decimal absoluteConsiderationValue;
        list<BFM_CT_e__c> listCTeTaxUpdate = new  list<BFM_CT_e__c>();
        If(BFM_CheckRecursive.firstRun==true){
            BFM_CheckRecursive.firstRun=false;
            for(BFM_CT_e__c cte: CTeRecord){
                recId.add(cte.id);
            }
            system.debug('recID--->'+recId);    
            list<BFM_CT_e__c> CTeRecordList = [SELECT Id,DEFINITIVE__c,Tax_Status__c,Cte_Status__c,ICMS_Value__c,
                                               ICMS_Tax_Rate__c,
                                               (select Net_Value__c,Gross_Value_net_tax__c,ICMS_Calculation_Base__c from SESs__r) FROM BFM_CT_e__c where id IN:recId];
            system.debug('CTeRecordList---->'+CTeRecordList);
            
            for(BFM_CT_e__c cte: CTeRecordList){
                // IF CT-e is definitive and has a SES linked to it...
                if(cte.DEFINITIVE__c==true && cte.SESs__r.size()>0){
                    system.debug('perform Validation---->');
                    system.debug('Number of attached SES---->'+cte.SESs__r.size());
                    
                    // Rewritten using for-each
                    for(BFM_SES__c ses : cte.SESs__r){
                        if(ses.gross_value_net_tax__c != null && ses.net_value__c != null){
                    		grossValue += ses.gross_value_net_tax__c;
                            //tax value calculated as : Tax= GrossValue -NetValue
                            taxValue += ses.gross_value_net_tax__c - ses.net_value__c;
                        }
                    }
                    /**
                    for(integer i=0;i<cte.SESs__r.size();i++){                           
                        if(cte.SESs__r[i].Gross_Value_net_tax__c!=null && cte.SESs__r[i].Net_Value__c!=null){                                        
                            grossValue= grossValue+ (cte.SESs__r[i].Gross_Value_net_tax__c);
                            //tax value calculated as : Tax= GrossValue -NetValue
                            taxValue=taxValue+ (cte.SESs__r[i].Gross_Value_net_tax__c - cte.SESs__r[i].Net_Value__c);
                        }                           
                    }   
					*/
                    toleranceMargin = grossValue*((BFM_ToleranceMargin__c.getValues('Value').Tolerance_Percentage_Value__c)/100);
                    tolerancValue = grossValue+toleranceMargin;
                    SESTaxvalue=taxValue;
                    absoluteConsiderationValue=BFM_AbsoluteConsideration__c.getValues('Value').AbsoluteConsideration_Value__c;
                    system.debug('grossValue---->'+grossValue);
                    system.debug('toleranceMargin----->'+toleranceMargin);                                   
                    
                    if(cte.ICMS_Value__c >grossValue && cte.ICMS_Value__c<=tolerancValue){
                        system.debug('Passes Tolerance check----->');
                        system.debug('cte.ICMS_Value__c--->'+cte.ICMS_Value__c);
                        system.debug('grossValue----->'+grossValue);
                        system.debug('absoluteConsiderationValue----->'+absoluteConsiderationValue);
                        if(cte.ICMS_Value__c!=Null && math.abs(cte.ICMS_Value__c-grossValue)<=absoluteConsiderationValue){
                            system.debug('Passes Absolute Considertation check----->');
                            system.debug('SESTaxvalue------>'+SESTaxvalue);
                            system.debug('tax value'+(cte.ICMS_Value__c*(cte.ICMS_Tax_Rate__c)/100));
                            
                            if(cte.ICMS_Tax_Rate__c!=null && (cte.ICMS_Value__c*(cte.ICMS_Tax_Rate__c)/100)==SESTaxvalue){
                                system.debug('Passes Tax percentage check----->');
                                cte.Tax_Status__c='Tax Validation Ok';
                                listCTeTaxUpdate.add(cte);
                                if(!Approval.isLocked(cte.Id)){
                                    Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                                    req.setComments('Submitting Request Tax calculation');
                                    req.setObjectId(cte.id);
                                    Approval.ProcessResult result = Approval.process(req);
                                    System.debug('Submitted for approval successfully: '+result.isSuccess());
                                }
                            }
                            else{
                                cte.Tax_Status__c='Tax value Error';
                                listCTeTaxUpdate.add(cte);
                                BFM_Error_Log__c newError = new BFM_Error_Log__c();          
                                newError.Reason__c = 'Tax value is not matching';
                                newError.BFM_CT_e__c = cte.id;
                                insert newError;
                            }
                        }
                        else{
                            cte.Tax_Status__c='Absolute Consideration value Error';
                            listCTeTaxUpdate.add(cte);
                            BFM_Error_Log__c newError = new BFM_Error_Log__c();          
                            newError.Reason__c = 'Obsolute Consideration value is not matching';
                            newError.BFM_CT_e__c = cte.id;
                            insert newError;
                        }
                    }
                    else{
                        cte.Tax_Status__c='Tolerance Margin Error';
                        listCTeTaxUpdate.add(cte);
                        //Initiate approval process 
                        if(!Approval.isLocked(cte.Id)){             
                            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                            req.setComments('Submitting Request for Total Value Validation');
                            req.setObjectId(cte.id);
                            Approval.ProcessResult result = Approval.process(req);
                            System.debug('Submitted for approval successfully: '+result.isSuccess());
                        }
                        BFM_Error_Log__c newError = new BFM_Error_Log__c();          
                        newError.Reason__c = 'Out of Tolerance value';
                        newError.BFM_CT_e__c = cte.id;
                        insert newError;                            
                    }
                    if(listCTeTaxUpdate != null){
                        Database.SaveResult[] updateRec = Database.update(listCTeTaxUpdate,false);
                    }
                }                               
            }
        }
    }
}