src/objects/BFM_UserCreationRequest__c.object
<CustomObject>
    <description>Represents one request for a new Carrier User.</description>
    <fields>
        <fullName>Created_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that was created by approval of this User Creation Request.</description>
        <label>Created User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BFM_User_Creation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Creation Request</label>
    <nameField>
        <displayFormat>REQ-{0000000}</displayFormat>
        <label>BFM User Creation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Creation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BFM_UpdateUserRequestQueueable.cls
public with sharing class BFM_UpdateUserRequestQueueable implements Queueable {
  Id userCreationRequestId;
    Id userId;
    public BFM_UpdateUserRequestQueueable(Id userCreationRequestId, Id userId){
        this.userCreationRequestId = userCreationRequestId;
        this.userId = userId;
    }
    
    public void execute(QueueableContext SC){
        BFM_UserCreationRequest__c creationRequest = [SELECT Created_User__c FROM BFM_UserCreationRequest__c WHERE Id =:this.userCreationRequestId LIMIT 1];
        creationRequest.Created_User__c = this.userId;
        update creationRequest;
    }
}