src/objects/BFM_CC_e__c.object
<CustomObject>
    <fields>
        <fullName>CC_e_Duplicate_Record_Status__c</fullName>
        <label>CC-e Duplicate Check Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_e_Key__c</fullName>
        <externalId>true</externalId>
        <label>CC-e Key</label>
        <length>52</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_e_Status__c</fullName>
        <label>CC-e Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_e_Valid_CNPJ_Status__c</fullName>
        <label>CC-e CNPJ Check Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CNPJ_Issuer__c</fullName>
        <label>CNPJ Issuer</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CNPJ_Service_Taker__c</fullName>
        <label>CNPJ Service Taker</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC-es</relationshipLabel>
        <relationshipName>CC_es</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Taker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Taker</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC-es (Service Taker)</relationshipLabel>
        <relationshipName>CC_es1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC-e</label>
    <nameField>
        <displayFormat>CCE-{000000}</displayFormat>
        <label>CC-e Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC-es</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BFM_CT_e__c.object
<CustomObject>
    <fields>
        <fullName>CC_e_Key__c</fullName>
        <externalId>true</externalId>
        <label>CC-e Key</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_e_Status__c</fullName>
        <label>CC-e Status</label>
        <picklist>
            <picklistValues>
                <fullName>File Ok</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>File Not Ok</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CNPJ_Service_Taker__c</fullName>
        <description>CNPJ Service Taker</description>
        <label>CNPJ Service Taker</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CNPJ_issuer__c</fullName>
        <description>CNPJ issuer</description>
        <label>CNPJ issuer</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CT_e_Duplicate_Record_Status__c</fullName>
        <label>CT-e Duplicate Record Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CT_e_Valid_CNPJ_Status__c</fullName>
        <label>CT-e Valid CNPJ Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CT_e_key__c</fullName>
        <externalId>true</externalId>
        <label>CT-e key</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <label>Carrier Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CT-es (Carrier Account)</relationshipLabel>
        <relationshipName>CT_es</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cte_Status__c</fullName>
        <label>Cte Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unilever_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unilever Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>BFM_CT_es</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CT-e</label>
    <nameField>
        <displayFormat>CTE-{0000000}</displayFormat>
        <label>BFM CT-e Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CT-es</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_Debit_Note__c.object
<CustomObject>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Debit Notes (Carrier Account)</relationshipLabel>
        <relationshipName>Debit_Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Taker_CNPJ__c</fullName>
        <label>Service Taker CNPJ</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unilever_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unilever Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Debit Notes</relationshipLabel>
        <relationshipName>Debit_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_s_CNPJ_or_CPF__c</fullName>
        <label>Vendor´s CNPJ or CPF</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <label>Debit Note</label>
    <nameField>
        <displayFormat>DN-{00000000}</displayFormat>
        <label>DN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>BFM_CC_e__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC-e</label>
        <referenceTo>BFM_CC_e__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BFM_CT_e__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CT-e</label>
        <referenceTo>BFM_CT_e__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BFM_MDF_e__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MDF-e</label>
        <referenceTo>BFM_MDF_e__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BFM_NFS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFS</label>
        <referenceTo>BFM_NFS__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{0000000}</displayFormat>
        <label>BFM_Error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BFM_MDF_e__c.object
<CustomObject>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <label>Carrier Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MDF-e</relationshipLabel>
        <relationshipName>MDF_e</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Issuer_CNPJ__c</fullName>
        <label>Issuer CNPJ</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDFE_Access_Key__c</fullName>
        <externalId>true</externalId>
        <label>MDFE Access Key</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_e_Duplicate_Record_Status__c</fullName>
        <label>MDF-e Duplicate Record Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_e_Status__c</fullName>
        <label>MDF-e Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDF_e_Valid_CNPJ_Status__c</fullName>
        <label>MDF-e Valid CNPJ Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taker_CNPJ__c</fullName>
        <label>Taker CNPJ</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unilever_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unilever Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MDF-e (Unilever Account)</relationshipLabel>
        <relationshipName>MDF_e1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MDF-e</label>
    <nameField>
        <displayFormat>MDFE-{0000000000}</displayFormat>
        <label>MDF-e Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDF-e</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_NF_e__c.object
<CustomObject>
    <fields>
        <fullName>Taker_CNPJ__c</fullName>
        <label>Taker CNPJ</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <label>NF-e</label>
    <nameField>
        <displayFormat>NF-e{00000}</displayFormat>
        <label>BFM NF-e Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NF-es</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BFM_NFS__c.object
<CustomObject>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NFS</relationshipLabel>
        <relationshipName>NFS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>NFS_CNPJ_Check_Status__c</fullName>
        <label>NFS CNPJ Check Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFS_Duplicate_Check_Status__c</fullName>
        <label>NFS Duplicate Check Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFS_Emission_Date_Time__c</fullName>
        <label>NFS Emission Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NFS_Mandatory_Field_Status__c</fullName>
        <label>NFS Mandatory Field Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFS_Number__c</fullName>
        <label>NFS Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFS_Series__c</fullName>
        <label>NFS Series</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFS_Status__c</fullName>
        <label>NFS Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Taker_CNPJ__c</fullName>
        <label>Service Taker CNPJ</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Taker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Taker</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NFS (Service Taker)</relationshipLabel>
        <relationshipName>NFS1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_UF_State__c</fullName>
        <formula>Carrier__r.Vendor_UF_State__c</formula>
        <label>Vendor UF (State)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_s_CNPJ_or_CPF__c</fullName>
        <label>Vendor´s CNPJ or CPF</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <label>NFS</label>
    <nameField>
        <displayFormat>NFS-{000000000}</displayFormat>
        <label>BFM NFS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NFS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_POD__c.object
<CustomObject>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>BFM_Carrier</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>BFM_PODs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>POD</label>
    <nameField>
        <displayFormat>POD-{00000000}</displayFormat>
        <label>POD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PODs</pluralLabel>
    <recordTypes>
        <fullName>POD</fullName>
        <active>true</active>
        <label>POD</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BFM_RecordutilityController.cls
public class BFM_RecordutilityController {
    public void cceCheck(Map<string,id> OldKeyMap,Map<string,id> NewRecordMap, string FileType , List<BFM_CC_e__c> CCeRecord ,set<string> CNPJId){
        List<BFM_Error_Log__c> errlist= New List<BFM_Error_Log__c>();
        set<string> accCNPJ = new set<string>();
        List<BFM_CT_e__c> CT_eUpdateRecordList= New List<BFM_CT_e__c>();
        List<BFM_CC_e__c> CC_eUpdateRecordList=New List<BFM_CC_e__c>();
        List<Account> acclist=[Select id,CNPJ__c from Account where CNPJ__c IN:CNPJId];
        for(Account ac : acclist){
            accCNPJ.add(ac.CNPJ__c);
        }
        if(FileType == 'CC-e'){
            for(BFM_CC_e__c cce : CCeRecord){
                if(OldKeyMap.containsKey(cce.CC_e_Key__c)){
                    cce.CC_e_Duplicate_Record_Status__c = Label.BFM_Validation_Error; 
                    cce.CC_e_Status__c =  Label.BFM_Validation_Error;             
                }else{
                    cce.CC_e_Duplicate_Record_Status__c = Label.BFM_Validation_OK;
                    cce.CC_e_Status__c =  Label.BFM_Validation_OK;  
                } 
                
                if(cce.CC_e_Duplicate_Record_Status__c!='Validation Error'){
                    if((cce.CNPJ_Issuer__c!=null && accCNPJ.contains(cce.CNPJ_Issuer__c)) && (cce.CNPJ_Service_Taker__c!=null && accCNPJ.contains(cce.CNPJ_Service_Taker__c)) ){
                        cce.CC_e_Valid_CNPJ_Status__c = Label.BFM_Valid_CNPJ;
                        cce.CC_e_Status__c =  Label.BFM_Valid_CNPJ;  
                    } else{
                        cce.CC_e_Valid_CNPJ_Status__c = 'Invalid CNPJ';
                        cce.CC_e_Status__c =  'Invalid CNPJ';  
                    }
                }
                system.debug('sssssssssssssssssssss'+cce.CC_e_Status__c);
            }
            BFM_Link_CCECTE.linkCCECTE(CCeRecord);
        }
    }
    
    
    public void cteCheck(Map<string,id> OldKeyMap,Map<string,id> NewRecordMap, string FileType , List<BFM_CT_e__c> CTeRecord ,set<string> CNPJId){
        List<BFM_Error_Log__c> errlist= New List<BFM_Error_Log__c>();
        set<string> accCNPJ = new set<string>();
        List<BFM_CT_e__c> CT_eUpdateRecordList=New List<BFM_CT_e__c>();
        List<Account> acclist=[Select id,CNPJ__c from Account where CNPJ__c IN:CNPJId];
        for(Account ac : acclist){
            accCNPJ.add(ac.CNPJ__c);
        }
        if(FileType == 'CT-e'){
            for(BFM_CT_e__c cte : CTeRecord){
                if(OldKeyMap.containsKey(cte.CT_e_Key__c)){
                    cte.CT_e_Duplicate_Record_Status__c = Label.BFM_Validation_Error; 
                    cte.Cte_Status__c = Label.BFM_Validation_Error;             
                }else{
                    cte.CT_e_Duplicate_Record_Status__c = Label.BFM_Validation_OK;
                    cte.Cte_Status__c = Label.BFM_Validation_OK;   
                } 
                
                if(cte.CT_e_Duplicate_Record_Status__c!='Validation Error'){
                    if((cte.CNPJ_Issuer__c!=null && accCNPJ.contains(cte.CNPJ_Issuer__c)) || (cte.CNPJ_Service_Taker__c!=null && accCNPJ.contains(cte.CNPJ_Service_Taker__c)) ){
                        cte.CT_e_Valid_CNPJ_Status__c = Label.BFM_Valid_CNPJ;
                        cte.Cte_Status__c = Label.BFM_Valid_CNPJ;   
                    } else{
                        cte.CT_e_Valid_CNPJ_Status__c = 'Invalid CNPJ';
                        cte.Cte_Status__c = 'Invalid CNPJ';   
                    }
                }
            }
        }
    }
    
    public void mdfeCheck(Map<string,id> OldKeyMap,Map<string,id> NewRecordMap, string FileType , List<BFM_MDF_e__c> mdfeRecord ,set<string> CNPJId){
        set<string> accCNPJ = new set<string>();
        map<string,account> mapacc = new map<string,account>();
        List<Account> acclist=[Select id,CNPJ__c from Account where CNPJ__c IN:CNPJId];
        for(Account ac : acclist){
            accCNPJ.add(ac.CNPJ__c);
            mapacc.put(ac.CNPJ__c,ac);
        }
        for(BFM_MDF_e__c mdfe : mdfeRecord){
            if(mapacc.containskey(mdfe.Issuer_CNPJ__c) && mapacc.get(mdfe.Issuer_CNPJ__c)!=null){
                //      mdfe.Carrier_Account__c = mapacc.get(mdfe.Issuer_CNPJ__c).id;
            }
            if(mapacc.containskey(mdfe.Taker_CNPJ__c) && mapacc.get(mdfe.Taker_CNPJ__c)!=null){
                //      mdfe.Unilever_Account__c = mapacc.get(mdfe.Taker_CNPJ__c).id;
            }
            if(OldKeyMap.containsKey(mdfe.MDFE_Access_Key__c)){
                mdfe.MDF_e_Duplicate_Record_Status__c= Label.BFM_Validation_Error; 
                mdfe.MDF_e_Status__c = Label.BFM_Validation_Error;             
            } else{
                mdfe.MDF_e_Duplicate_Record_Status__c= Label.BFM_Validation_Ok;
                mdfe.MDF_e_Status__c = Label.BFM_Validation_Ok;
            }
            if(mdfe.MDF_e_Duplicate_Record_Status__c!=Label.BFM_Validation_Error){
                if((mdfe.Issuer_CNPJ__c!=null && accCNPJ.contains(mdfe.Issuer_CNPJ__c)) || (mdfe.Taker_CNPJ__c!=null && accCNPJ.contains(mdfe.Taker_CNPJ__c)) ){
                    mdfe.MDF_e_Valid_CNPJ_Status__c= 'Valid CNPJ';
                    mdfe.MDF_e_Status__c = 'Valid CNPJ';
                } else{
                    mdfe.MDF_e_Valid_CNPJ_Status__c= 'Invalid CNPJ';
                    mdfe.MDF_e_Status__c = 'Invalid CNPJ';
                }
            }
        }
        
    }
    public void nfsCheck(Map<string,id> OldKeyMap,Map<string,id> NewRecordMap, string FileType , List<BFM_NFS__c> nfsRecord ,set<string> CNPJId){
        set<string> accCNPJ = new set<string>();
        Map<string,Account> mapacc = new Map<string,Account>();
        List<Account> acclist=[Select id,CNPJ__c,Vendor__c,Company_Code__c,Vendor_UF_State__c from Account where CNPJ__c IN:CNPJId];
        for(Account ac : acclist){
            accCNPJ.add(ac.CNPJ__c);
            mapacc.put(ac.CNPJ__c, ac);
        }
        for(BFM_NFS__c nfs : nfsRecord){
            if(mapacc.containskey(nfs.Vendor_s_CNPJ_or_CPF__c)){
                nfs.Carrier__c = mapacc.get(nfs.Vendor_s_CNPJ_or_CPF__c).id;
            }
            if(mapacc.containskey(nfs.Service_Taker_CNPJ__c)){
                nfs.Service_Taker__c= mapacc.get(nfs.Service_Taker_CNPJ__c).id;
            }
            if(nfs.NFS_Number__c!=null && nfs.NFS_Series__c!=null && nfs.Vendor_s_CNPJ_or_CPF__c!=null && nfs.NFS_Emission_Date_Time__c!=null){
                nfs.NFS_Mandatory_Field_Status__c = Label.BFM_Validation_Ok;
                nfs.NFS_Status__c = Label.BFM_Validation_Ok;
            }
            else{
                nfs.NFS_Mandatory_Field_Status__c = Label.BFM_Validation_Error;
                nfs.NFS_Status__c = Label.BFM_Validation_Error;
            }
            if(nfs.NFS_Mandatory_Field_Status__c != Label.BFM_Validation_Error){
                if(OldKeyMap.containsKey(nfs.NFS_Number__c+nfs.NFS_Series__c+nfs.Vendor_s_CNPJ_or_CPF__c+nfs.NFS_Emission_Date_Time__c.year())){
                    nfs.NFS_Duplicate_Check_Status__c= Label.BFM_Validation_Error;   
                    nfs.NFS_Status__c = Label.BFM_Validation_Error;            
                } else{
                    nfs.NFS_Duplicate_Check_Status__c= Label.BFM_Validation_Ok;
                    nfs.NFS_Status__c = Label.BFM_Validation_Ok;
                }
            }
            if(nfs.NFS_Duplicate_Check_Status__c!=null && nfs.NFS_Duplicate_Check_Status__c!=Label.BFM_Validation_Error){
                if((nfs.Vendor_s_CNPJ_or_CPF__c!=null && accCNPJ.contains(nfs.Vendor_s_CNPJ_or_CPF__c)) && (nfs.Service_Taker_CNPJ__c!=null && accCNPJ.contains(nfs.Service_Taker_CNPJ__c)) ){
                    nfs.NFS_CNPJ_Check_Status__c= 'Valid CNPJ';
                    nfs.NFS_Status__c = 'Valid CNPJ';
                    if(nfs.NFS_Link_Check_Status__c == null){
                        nfs.NFS_Link_Check_Status__c = 'Pending Link';
                        nfs.NFS_Status__c = 'Pending Link';
                    }
                } else{
                    nfs.NFS_CNPJ_Check_Status__c= 'Invalid CNPJ';
                    nfs.NFS_Status__c = 'Invalid CNPJ';
                }
            }
        }
        
    }
    
    //Debit Note
    public void debitnoteCheck(Map<string,id> OldKeyMap,Map<string,id> NewRecordMap, string FileType , List<BFM_Debit_Note__c> dnRecord ,set<string> CNPJId){
        set<string> accCNPJ = new set<string>();
        map<string,account> mapAccount = new map<string,account>();
        List<Account> acclist=[Select id,CNPJ__c,Vendor__c,Company_Code__c from Account where CNPJ__c IN:CNPJId];
        for(Account ac : acclist){
            accCNPJ.add(ac.CNPJ__c);
            mapAccount.put(ac.CNPJ__c,ac);
        }
        for(BFM_Debit_Note__c dn : dnRecord){
            if(mapAccount.containsKey(dn.Vendor_s_CNPJ_or_CPF__c)){
                dn.carrier_account__c = mapAccount.get(dn.Vendor_s_CNPJ_or_CPF__c).id;
                dn.Vendor_Code__c = mapAccount.get(dn.Vendor_s_CNPJ_or_CPF__c).Vendor__c;                              
            }
            if(mapAccount.containsKey(dn.Service_Taker_CNPJ__c)){
                dn.Unilever_Account__c = mapAccount.get(dn.Service_Taker_CNPJ__c).id;  
                dn.Company_Code__c = mapAccount.get(dn.Service_Taker_CNPJ__c).Company_Code__c;                            
            }
            if(OldKeyMap.containsKey(dn.DN_Number__c)){
                dn.DN_duplicate_check_status__c= Label.BFM_Validation_Error;
                dn.Debit_Note_Status__c = Label.BFM_Validation_Error;               
            } else{
                dn.DN_duplicate_check_status__c= Label.BFM_Validation_Ok;
                dn.Debit_Note_Status__c = Label.BFM_Validation_Ok;
            }
            if(dn.DN_duplicate_check_status__c!=Label.BFM_Validation_Error){
                if((dn.Vendor_s_CNPJ_or_CPF__c!=null && accCNPJ.contains(dn.Vendor_s_CNPJ_or_CPF__c)) && (dn.Service_Taker_CNPJ__c!=null && accCNPJ.contains(dn.Service_Taker_CNPJ__c)) ){
                    dn.DN_cnpj_check_status__c = 'Valid CNPJ';
                    dn.Debit_Note_Status__c = 'Valid CNPJ';
                } else{
                    dn.DN_cnpj_check_status__c = 'Invalid CNPJ';
                    dn.Debit_Note_Status__c = 'Invalid CNPJ';
                }
            }
        }
        
    }
    
    
    //POD
    public void podCheck(Map<string,id> OldKeyMap,Map<string,BFM_NF_e__c> nferecordmap, string FileType , List<BFM_POD__c> podRecord ,set<string> CNPJId){
        set<string> accCNPJ = new set<string>();
        //map<string,account> mapAccount = new map<string,account>();
        system.debug('OldKeyMap:'+OldKeyMap);
        system.debug('nferecordmap:'+nferecordmap);
        system.debug('FileType:'+FileType);
        system.debug('podRecord:'+podRecord);
        system.debug('CNPJId:'+CNPJId);
        
        
        List<Account> acclist=[Select id,CNPJ__c,Vendor__c,Company_Code__c from Account where CNPJ__c IN:CNPJId];
        for(Account ac : acclist){
            accCNPJ.add(ac.CNPJ__c);
            // mapAccount.put(ac.CNPJ__c,ac);
        }
        
        for(BFM_POD__c pod : podRecord){
            system.debug('Pod inside for loop:'+pod);
            system.debug('Podnfekey:'+pod.NF_e_Access_Key__c);
            // if(pod.POD_Status__c== 'In Progress'){
            if(pod.NF_e__c==null && nferecordmap.containskey(pod.NF_e_Access_Key__c)){
                pod.NF_e__c = nferecordmap.get(pod.NF_e_Access_Key__c).id;
            }  
            if(OldKeyMap.containsKey(pod.NF_e_Access_Key__c ) && !nferecordmap.containskey(pod.NF_e_Access_Key__c)){
                pod.POD_Duplicate_Check_Status__c= Label.BFM_Validation_Error;
                //pod.POD_Status__c= Label.BFM_Validation_Error;               
            } else{
                pod.POD_Duplicate_Check_Status__c= Label.BFM_Validation_Ok;
                //pod.POD_Status__c= Label.BFM_Validation_Ok;
            }
            system.debug('pod.POD_Duplicate_Check_Status__c:'+pod.POD_Duplicate_Check_Status__c+'~~~~~pod.POD_Status__c:'+pod.POD_Status__c);
            if(pod.POD_Duplicate_Check_Status__c==Label.BFM_Validation_Ok && pod.POD_Duplicate_Check_Status__c!=null){
                //system.debug(nferecordmap.get(pod.NF_e_Access_Key__c).CNPJ_destination__c);
                //if((nferecordmap.get(pod.NF_e_Access_Key__c).CNPJ_destination__c!=null && accCNPJ.contains(nferecordmap.get(pod.NF_e_Access_Key__c).CNPJ_destination__c))){
                if(nferecordmap.get(pod.NF_e_Access_Key__c)!=null){
                    if(nferecordmap.get(pod.NF_e_Access_Key__c).CNPJ_destination__c!=null){
                        pod.POD_CNPJ_Check_Status__c = 'Valid CNPJ';
                        //pod.POD_Status__c = 'Valid CNPJ';
                    } else{
                        pod.POD_CNPJ_Check_Status__c= 'Invalid CNPJ';
                        //pod.POD_Status__c = 'Invalid CNPJ';
                    }
                }
            }
            system.debug('cnpjcheck'+pod.POD_CNPJ_Check_Status__c);
            if(pod.POD_CNPJ_Check_Status__c=='Valid CNPJ' && pod.POD_CNPJ_Check_Status__c!=null){           
                if(pod.Upload_date__c!=null && pod.Upload_date__c.date()==Date.valueOf(nferecordmap.get(pod.NF_e_Access_Key__c).NF_e_creation_date__c)){                   
                    pod.POD_Date__c= pod.Upload_date__c.date();
                } 
                if(pod.POD_Date__c>=Date.valueOf(nferecordmap.get(pod.NF_e_Access_Key__c).NF_e_creation_date__c)){
                    pod.POD_Date_Check_Status__c = 'Date Ok';
                    //pod.POD_Status__c = 'Date Ok';                   
                }
                else{
                    pod.POD_Date_Check_Status__c = 'Date Not Ok';
                    //pod.POD_Status__c = 'Date Not Ok';
                }
            }
            system.debug('datecheck'+pod.POD_Date_Check_Status__c+'statuscheck'+pod.POD_Status__c);
            if(pod.POD_Date_Check_Status__c =='Date Ok' && pod.POD_Status__c!=null){           
                
                if(nferecordmap.containskey(pod.NF_e_Access_Key__c) && nferecordmap.get(pod.NF_e_Access_Key__c).SES__c!=null){
                    pod.POD_Link_Check_Status__c = 'Link Ok';
                    //pod.POD_Status__c = 'Link Ok';
                    
                }
                else{
                    pod.POD_Link_Check_Status__c = 'Pending Link';
                    //pod.POD_Status__c = 'Pending Link';
                }
            }
            
            // }
        }
        
    }
}