src/objects/BFM_AccountAccessRequest__c.object
<CustomObject>
    <description>Represents Access Requests a User makes to gain access to Accounts.</description>
    <label>Account Access Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>BFM Account Access Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Access Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_UserCreationRequest__c.object
<CustomObject>
    <description>Represents one request for a new Carrier User.</description>
    <fields>
        <fullName>CommunityNickname__c</fullName>
        <description>Nickname of the User that will be created if this request is approved.</description>
        <label>Community Nickname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Creation Request</label>
    <nameField>
        <displayFormat>REQ-{0000000}</displayFormat>
        <label>BFM User Creation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Creation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BFM_CreateCarrierUser_Test.cls
@isTest
private class BFM_CreateCarrierUser_Test {
    private static testMethod void myTest(){
        BFM_UserCreationRequest__c userCreationRequest = BFM_TestUtils.createUserCreationRequest();
        insert userCreationRequest;
        
        BFM_UserCreationRequest__c userCreationRequestDuplicatedNickname = BFM_TestUtils.createUserCreationRequest();
        userCreationRequestDuplicatedNickname.communityNickname__c = userCreationRequest.CommunityNickname__c;
        insert userCreationRequestDuplicatedNickname;
        
        Account carrierAccount = BFM_TestUtils.createCarrierAccount();
        insert carrierAccount;
        
        BFM_AccountAccessRequest__c accessRequest = BFM_TestUtils.createAccountAccessRequest(userCreationRequest.Id, 
                                                                                             carrierAccount.Id);
        insert accessRequest;
        system.assertEquals('userCreationRequest.Id','userCreationRequest.Id');
        
        BFM_AccountAccessRequest__c accessRequestDuplicatedNickname = BFM_TestUtils.createAccountAccessRequest(userCreationRequestDuplicatedNickname.Id, 
                                                                                             carrierAccount.Id);
        insert accessRequestDuplicatedNickname;
        
        Test.startTest();
        BFM_CreateCarrierUser.createUserShareAccounts(new List<BFM_UserCreationRequest__c>{userCreationRequest});
        BFM_CreateCarrierUser.createUserShareAccounts(new List<BFM_UserCreationRequest__c>{userCreationRequestDuplicatedNickname});
        
        Test.stopTest();
    }
}