src/objects/BFM_NF_e__c.object
<CustomObject>
    <fields>
        <fullName>NF_e_access_key__c</fullName>
        <externalId>true</externalId>
        <label>NF-e access key</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>NF-e</label>
    <nameField>
        <displayFormat>NF-e{00000}</displayFormat>
        <label>BFM NF-e Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NF-es</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BFM_Occurrence__c.object
<CustomObject>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <label>Carrier Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Occurrences</relationshipLabel>
        <relationshipName>Occurrences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Occurrence</label>
    <nameField>
        <displayFormat>Occ-{000}</displayFormat>
        <label>BFM Occurrence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_Shipment__c.object
<CustomObject>
    <description>A Shipment represents one delivery transaction a Carrier company performs for an Unilever Company.</description>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <description>The Carrier delivering this Shipment.</description>
        <label>Carrier Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Carrier Account)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Number__c</fullName>
        <externalId>true</externalId>
        <label>Shipment Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>DT-{000000}</displayFormat>
        <label>Shipment Internal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_UserCreationRequest__c.object
<CustomObject>
    <description>Represents one request for a new Carrier User.</description>
    <fields>
        <fullName>CNPJ__c</fullName>
        <label>CNPJ</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>User Creation Request</label>
    <nameField>
        <displayFormat>REQ-{0000000}</displayFormat>
        <label>BFM User Creation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Creation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BFM_TriggerFactory_Test.cls
@isTest
public class BFM_TriggerFactory_Test {
    private static testMethod void bfm_TriggerTestMethod(){
        Test.startTest();       
        Account acc = new Account();
        acc.Name ='TestAccount';
        insert acc;
        
        BFM_Shipment__c ship = new BFM_Shipment__c();
        ship.Carrier_Account__c = acc.Id;
        ship.Shipment_Number__c = '11111';
        insert ship;
        ship.Company_Code__c = '333';
        update ship;

        BFM_Occurrence__c occ = new BFM_Occurrence__c();
        occ.Carrier_Account__c = acc.Id;
        insert occ;
        occ.Plant__c = '22';
        update occ;
        
        BFM_UserCreationRequest__c uc = new BFM_UserCreationRequest__c();
        uc.CNPJ__c = '122222';
        insert uc;
        uc.CNPJ__c = '3333';
        update uc;
        BFM_NF_e__c nfe = new BFM_NF_e__c();
        nfe.NF_e_access_key__c = '3322234';
        insert nfe;
        nfe.NF_e_access_key__c = '3343';
        update nfe;        
        Test.stopTest();
    }
}