src/objects/BFM_Email_Information__c.object
<CustomObject>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <label>Carrier Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Email_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <label>Remark</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SF_Approver__c</fullName>
        <formula>CONTAINS( UPPER(Remark__c), &apos;SF_APPROVAL&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SF Approver</label>
        <type>Checkbox</type>
    </fields>
    <label>Email Information</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Informations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BFM_CreateContactFromEmail_Test.cls
@isTest
public class BFM_CreateContactFromEmail_Test {
  private static testMethod void BFM_CreateContactFromEmail_TestMethod(){
      	Account acc = new Account();
      	acc.Name = 'TestAccount';
      	Insert acc;  
		BFM_Email_Information__c emailinfo = new BFM_Email_Information__c();
        emailinfo.email__c = 'test@test.com';
        emailinfo.Carrier_Account__c = acc.Id;
        emailinfo.Remark__c = 'SF_APPROVAL';
      	insert emailinfo;
      	List<BFM_Email_Information__c> emailsInserted = [select id,Name,email__c,Carrier_Account__c,Remark__c,SF_Approver__c from BFM_Email_Information__c where id=:emailinfo.id ];
      	BFM_CreateContactFromEmailInformation.createContactsFromEmails(emailsInserted);
	}
}