src/objects/BFM_CT_e__c.object
<CustomObject>
    <fields>
        <fullName>CT_e_Number__c</fullName>
        <label>CT-e Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CT_e_key__c</fullName>
        <externalId>true</externalId>
        <label>CT-e key</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <label>CT-e</label>
    <nameField>
        <displayFormat>CTE-{0000000}</displayFormat>
        <label>BFM CT-e Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CT-es</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BFM_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>BFM_CT_e__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CT-e</label>
        <referenceTo>BFM_CT_e__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{0000000}</displayFormat>
        <label>BFM_Error</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BFM_ValidateFiscalDocuments_Test.cls
@isTest
private class BFM_ValidateFiscalDocuments_Test {
    static testMethod void FiscalDocuments(){
    BFM_CT_e__c cte=new BFM_CT_e__c();
    cte.CT_e_key__c='123456';
    cte.CT_e_Number__c='6456';
    insert cte;
    system.assertEquals('123456', cte.CT_e_key__c);
    
    BFM_Error_Log__c errolog = new BFM_Error_Log__c();
    errolog.BFM_CT_e__c = cte.id;
    insert errolog;
    system.assertEquals(cte.id, errolog.BFM_CT_e__c);
        
    Set<Id> cteids = new Set<Id>();
    Test.startTest(); 
    BFM_ValidateFiscalDocuments fiscaldocs = new BFM_ValidateFiscalDocuments(cteids);
    BFM_ValidateFiscalDocumentsResponse fiscalres = new BFM_ValidateFiscalDocumentsResponse();
    BFM_GeneralServiceCalls servicecall = new BFM_GeneralServiceCalls();
    Test.setMock(HttpCalloutMock.class, new BFM_MockHttpResponse());
    //BFM_ValidateFiscalDocuments.callValidateFiscalDocuments();
    fiscaldocs.generateIntegrationFailureErrorLogs(200,'status');
    Test.stopTest();
    }
}