src/objects/Brand_USLP_Progress__c.object
<CustomObject>
    <description>isll  list of brands that have started their USLP ambition showing their progress</description>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Brand USLP Progress</label>
    <nameField>
        <label>Brand USLP Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand USLP Progress</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Carousel__c.object
<CustomObject>
    <description>isll</description>
    <label>Carousel</label>
    <nameField>
        <label>Carousel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carousel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chatter_History__c.object
<CustomObject>
    <description>isll - keeps a record of all deleted posts on the isll group.</description>
    <fields>
        <fullName>Deleting_Moderator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deleting Moderator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Chatter_History1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feed_Contents__c</fullName>
        <label>Feed Contents</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Feed_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feed Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Chatter_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chatter History</label>
    <nameField>
        <label>Chatter History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CMS_Article__c.object
<CustomObject>
    <description>isll</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CMS Article</label>
    <nameField>
        <label>CMS Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CMS_Article_Link__c.object
<CustomObject>
    <description>isll
junction object for CMS Article and CMS Content with type Link</description>
    <fields>
        <fullName>CMS_Article__c</fullName>
        <label>CMS Article</label>
        <referenceTo>CMS_Article__c</referenceTo>
        <relationshipLabel>CMS Article Links</relationshipLabel>
        <relationshipName>CMS_Article_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CMS_Link__c</fullName>
        <label>CMS Link</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CMS_Content__c.Type__c</field>
                <operation>equals</operation>
                <value>Link</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CMS_Content__c</referenceTo>
        <relationshipLabel>CMS Article Links</relationshipLabel>
        <relationshipName>CMS_Article_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CMS Article Link</label>
    <nameField>
        <displayFormat>CAL-{00000}</displayFormat>
        <label>CMS Article Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CMS Article Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMS_Content__c.object
<CustomObject>
    <description>isll</description>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>CMS Contents</relationshipLabel>
        <relationshipName>CMS_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextLink</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CMS Content</label>
    <nameField>
        <label>CMS Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CMS_ContentToCarousel__c.object
<CustomObject>
    <description>isll</description>
    <fields>
        <fullName>CMS_Content__c</fullName>
        <label>CMS Content</label>
        <referenceTo>CMS_Content__c</referenceTo>
        <relationshipLabel>CMS Contents to Carousel</relationshipLabel>
        <relationshipName>CMS_Contents_to_Carousel</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Carousel__c</fullName>
        <label>Carousel</label>
        <referenceTo>Carousel__c</referenceTo>
        <relationshipLabel>CMS Contents to Carousel</relationshipLabel>
        <relationshipName>CMS_Contents_to_Carousel</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CMS Content to Carousel</label>
    <nameField>
        <displayFormat>CTC-{0}</displayFormat>
        <label>CMS Content to Carousel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CMS Contents to Carousel</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMS_Page_Article__c.object
<CustomObject>
    <description>isll
object contain page name and lookup to Article.</description>
    <fields>
        <fullName>CMS_Article__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CMS Article</label>
        <referenceTo>CMS_Article__c</referenceTo>
        <relationshipLabel>CMS Page Articles</relationshipLabel>
        <relationshipName>CMS_Page_Articles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CMS Page Article</label>
    <nameField>
        <displayFormat>CPAN-{0000000}</displayFormat>
        <label>CMS Page Article Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CMS Page Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <description>isll events</description>
    <fields>
        <fullName>Chatter_Group_Name__c</fullName>
        <label>Chatter Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Description__c</fullName>
        <label>Event Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Event Start date time</description>
        <label>Start Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event_Member__c.object
<CustomObject>
    <description>ISLL</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Members</relationshipLabel>
        <relationshipName>Event_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Event_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Member</label>
    <nameField>
        <label>Event Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ISLL_Custom_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>isll custom settings</description>
    <label>ISLL Custom Settings</label>
</CustomObject>

src/objects/isllBrainResultsSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>NumericValue__c</fullName>
        <label>NumericValue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>isllBrainResultsSettings</label>
</CustomObject>

src/classes/isll_TestData.cls
/**
*
* Author:       Carmine Barbuto
* Date:         07/03/2014
* Description:  ISLL Project - Utility Class for Test Data.
* Version:      1.0
*
* --------------------------
* Copyright © 2014  Unilever
* --------------------------
**/
@isTest
public class isll_TestData {
    
    //******************* CONSTANT VALUES
    
    public static String CHATTER_GROUP          = 'ISLL Chatter Group';
    public static String FILE_INDICATOR         = 'New File Indicator';
    public static String ISLL_NAME              = 'Internal Sustainable Living Lab';
    public static String PARAM_CONTENTVERSIONID = 'contentVersionID';
    public static String PARAM_LIBRARYPAGESIZE  = 'fullLibrariesPageSize';
    public static String PARAM_OFFSETMAX        = 'offsetMaxLimit';         

    //******************* CMS Article

    public static CMS_Article__c createCMSArticle() {
        CMS_Article__c art  = new CMS_Article__c();
        art.Name            = 'Test Article';
        art.Title__c        = 'Test Title';
        art.Body__c         = 'Test Body';
        
        return art;
    }
    
    public static CMS_Page_Article__c createCMSPageArticle(String pageName, Id articleId) {
        CMS_Page_Article__c pge     = new CMS_Page_Article__c();
        pge.Page_Name__c            = pageName;
        pge.CMS_Article__c          = articleId;
        pge.Order__c                = 0;
        
        return pge;
    }

    public static CMS_Content__c createCMSContent(String cType) {
        CMS_Content__c cnt  = new CMS_Content__c();
        cnt.Name            = 'Content';
        cnt.Content__c      = 'Test Content';
        cnt.Type__c         = cType;

        return cnt;
    }

    public static CMS_Article_Link__c createCMSArticleLink(Id articleId, Id contentId) {
        CMS_Article_Link__c alk = new CMS_Article_Link__c();
        alk.CMS_Article__c      = articleId;
        alk.CMS_Link__c         = contentId;

        return alk;
    }

    //******************* EVENT

    public static Event__c createEvent() {
        Event__c evt                = createEvent(Datetime.now(), Datetime.now());

        return evt;
    }
    public static Event__c createEvent(DateTime startDate, DateTime endDate) {
        Event__c evt                = new Event__c();
        evt.Name                    = 'Test Event';
        evt.Event_Description__c    = 'Test Description';
        evt.Start_Date_Time__c      = startDate;
        evt.End_Date_Time__c        = endDate;

        // Create a group with random name - errors were caused for a group name that is used in repeated tests.
        CollaborationGroup testGroup = createChatterGroup(
            (string.valueOf(system.now()) + Math.random()).left(40)
        );
        insert testGroup;

        evt.Chatter_Group_Name__c   = testGroup.Id;

        return evt;
    }

    public static Event_Member__c createEventMember(Id userId, Id eventId, String memberName) {
        Event_Member__c evm = new Event_Member__c();
        evm.Name            = memberName;  
        evm.User__c         = userId; 
        evm.Event__c        = eventId;

        return evm;
    }

    //******************* CAROUSEL

    public static Carousel__c createCarousel(String name) {
        Carousel__c crs = new Carousel__c();
        crs.Name        = name;

        return crs;
    }

    public static CMS_ContentToCarousel__c createCMSContentCarousel(Id contentId, Id carouselId) {
        CMS_ContentToCarousel__c ctc    = new CMS_ContentToCarousel__c();
        ctc.Carousel__c                 = carouselId;
        ctc.CMS_Content__c              = contentId;

        return ctc;
    }

    //******************* BRAND

    public static Brand_USLP_Progress__c createBrandProgress(String name, Decimal orderNumber) {
        Brand_USLP_Progress__c bup  = new Brand_USLP_Progress__c();
        bup.Name                    = name;
        bup.Order_Number__c         = orderNumber;

        return bup;
    }

    //******************* CUSTOM SETTINGS

    public static isllBrainResultsSettings__c createBrainResultSetting(String name, Integer value) {
        isllBrainResultsSettings__c brs = new isllBrainResultsSettings__c();
        brs.Name                        = name;
        brs.NumericValue__c             = value;

        return brs;
    }

    public static ISLL_Custom_Settings__c createISLLCustomSetting(String name) {
        ISLL_Custom_Settings__c stg = new ISLL_Custom_Settings__c();
        stg.Name                    = name;
        
        return stg;
    }

    //******************* CHATTER

    public static Chatter_History__c createChatterHistory() {
        Chatter_History__c cht      = new Chatter_History__c();
        cht.Feed_Contents__c        = 'Content'; 
        cht.Feed_Owner__c           = System.Userinfo.getUserId();
        cht.Deleting_Moderator__c   = System.Userinfo.getUserId();

        return cht;
    }

    public static CollaborationGroup createChatterGroup(String groupName) {
        CollaborationGroup cgr  = new CollaborationGroup();
        cgr.Name                = groupName;   
        cgr.CollaborationType   = 'Public';  

        return cgr; 
    }

    public static CollaborationGroupMember createCollaborationGroupMember(Id memberId, Id groupId) {
        CollaborationGroupMember cgm    = new CollaborationGroupMember();
        cgm.Memberid                    = memberId;
        cgm.CollaborationGroupId        = groupId;

        return cgm;
    }

    public static FeedItem createFeedItem(Id groupId, String body) {
        FeedItem fdi    = new FeedItem();
        fdi.ParentId    = groupId;
        fdi.Type        = 'TextPost';
        fdi.Body        = body;

        return fdi;
    }

    public static FeedComment createFeedComment(Id feedId) {
        FeedComment fdc = new FeedComment();
        fdc.CommentBody = 'Test Comment';
        fdc.FeedItemId  = feedId;
        
        return fdc;
    }

    //******************* DOCUMENTS

    public static ContentVersion createContentVersion() {
        ContentVersion cnv  = createContentVersion('Test File');

        return cnv;
    }
    public static ContentVersion createContentVersion(String title) {
        ContentVersion cnv  = new ContentVersion();
        cnv.VersionData     = Blob.valueof(title);
        cnv.Title           = title;
        cnv.PathOnClient    = 'filePath';
        
        return cnv;
    }

    public static Attachment createAttachment(Id parentId) {
        Attachment att  = new Attachment();
        att.OwnerId     = UserInfo.getUserId();
        att.ParentId    = parentId;
        att.Name        = 'Attachment Test';
        att.Body        =  Blob.valueOf('Attachment Body');

        return att;
    }

    //******************* USER

    public static User createUser(Id profileId) {
        User usr                        = new User();
        usr.Username                    = 'name.name@company.com' + Datetime.now().millisecond();
        usr.Email                       = 'name.name@company.com';
        usr.Lastname                    = 'LastName';
        usr.Firstname                   = 'FirstName';
        usr.Alias                       = 'test';
        usr.CommunityNickname           = 'nickname';
        usr.ProfileId                   = profileId;
        usr.TimeZoneSidKey              = 'GMT';
        usr.LocaleSidKey                = 'en_US';
        usr.EmailEncodingKey            = 'ISO-8859-1';
        usr.LanguageLocaleKey           = 'en_US';
        usr.UserPermissionsMobileUser   = false;

        return usr;
    }

    public static List<User> createBulkUser(Id profileId, Integer maxNumber) {
        List<User> userList = new List<User>();
        for(integer i = 0; i < maxNumber; i++){ 
            User usr                        = new User();
            usr.Username                    = 'name.name@company.com' + Datetime.now().millisecond() + i;
            usr.Email                       = 'name.name@company.com' + i;
            usr.Lastname                    = 'LastName' + i;
            usr.Firstname                   = 'FirstName' + i;
            usr.Alias                       = 'test' + i;
            usr.CommunityNickname           = 'nickname' + i;
            usr.ProfileId                   = profileId;
            usr.TimeZoneSidKey              = 'GMT';
            usr.LocaleSidKey                = 'en_US';
            usr.EmailEncodingKey            = 'ISO-8859-1';
            usr.LanguageLocaleKey           = 'en_US';
            usr.UserPermissionsMobileUser   = false;
            userList.add(usr);
        }

        return userList;
    }


}