src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PBS_Profile__c.object
<CustomObject>
    <description>Object holds user profiles for Plancraft app</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Categories</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Personal Care</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Home Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refreshments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross Category</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Guest</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia / Africa / NAMET (U2K2)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia (Fusion)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User - profile owner</description>
        <inlineHelpText>User - profile owner</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PBS_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Level__c</fullName>
        <label>Work Level</label>
        <picklist>
            <picklistValues>
                <fullName>Guest</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>user_role__c</fullName>
        <description>User role</description>
        <inlineHelpText>User role</inlineHelpText>
        <label>User Role</label>
        <referenceTo>PBS_Standard_Job_Profile__c</referenceTo>
        <relationshipName>PBS_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Plancraft Profile</label>
    <nameField>
        <displayFormat>PBS-P-{000000}</displayFormat>
        <label>PBS Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plancraft Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PBS_Standard_Job_Profile__c.object
<CustomObject>
    <description>Objects holds list of defined Standard Job Profiles</description>
    <label>PBS Standard Job Profile</label>
    <nameField>
        <label>PBS Standard Job Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS Standard Job Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PBS_Training_Plan_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Completed_On__c</fullName>
        <inlineHelpText>Date this assignment was completed</inlineHelpText>
        <label>Completed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Course completion duration</description>
        <formula>(Completed_On__c -  DATEVALUE( CreatedDate ))+1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Completion_Date__c</fullName>
        <description>Expected Completion Date of a Training Plan</description>
        <formula>DATEVALUE(CreatedDate ) +30</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Thirty_Days_Completed__c</fullName>
        <formula>Duration__c &lt;=30</formula>
        <label>Thirty Days Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Training Plan</label>
        <referenceTo>PBS_Training_Plan__c</referenceTo>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PBS_Training Plan Assignment</label>
    <nameField>
        <displayFormat>TPAS-{0000000}</displayFormat>
        <label>Training Plan Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS_Training Plan Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PBS_Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <label>Geography</label>
        <picklist>
            <picklistValues>
                <fullName>Guest</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia / Africa / NAMET (U2K2)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia (Fusion)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PBS_Standard_Job_Profile__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>User Role</label>
        <referenceTo>PBS_Standard_Job_Profile__c</referenceTo>
        <relationshipName>Training_Track</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Training tracks are not available to end users until they are &quot;Active&quot;</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Level__c</fullName>
        <label>Work Level</label>
        <picklist>
            <picklistValues>
                <fullName>Guest</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PBS_Training Track</label>
    <nameField>
        <label>Training Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS_Training Track</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PBS_Training_Track_Level__c.object
<CustomObject>
    <fields>
        <fullName>Training_Track__c</fullName>
        <label>Training Track</label>
        <referenceTo>PBS_Training_Track__c</referenceTo>
        <relationshipName>Training_Track_Levels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>PBS_Training Track Level</label>
    <nameField>
        <label>Training Track Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBS_Training Track Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PBS_Training_Track_Level_Item__c.object
<CustomObject>
    <fields>
        <fullName>Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Plan</label>
        <referenceTo>PBS_Training_Plan__c</referenceTo>
        <relationshipName>Training_Track_Level_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Track_Level__c</fullName>
        <label>Training Track Level</label>
        <referenceTo>PBS_Training_Track_Level__c</referenceTo>
        <relationshipName>Training_Track_Level_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>PBS_Training Track Level Item</label>
    <nameField>
        <displayFormat>TTLI-{0000000}</displayFormat>
        <label>Training Track Level Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PBS_Training Track Level Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <label>Geography</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Role__c</fullName>
        <label>User Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Level__c</fullName>
        <label>Work Level</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PBS_CustomReport.cls
public class PBS_CustomReport {
    public  Map<String,Map<String,PBS_Profile__c>> reportDataMap {get;set;}
    public  Map<String,Map<String, PBS_Training_Track_Level_Item__c>> reportTrackDataMap {get;set;}
    public  Map<String,PBS_Training_Plan_Assignment__c> tpAssignmentMap {get;set;}
    public  Map<String, PBS_Training_Track_Level_Item__c>  ttlavelitemMap {get;set;}
    public  Map<String, PBS_Training_Track_Level_Item__c>  ttlavelitemMap2 {get;set;}
    public PBS_CustomReport(){
        reportDataMap = new Map<String,Map<String,PBS_Profile__c>>();
        tpAssignmentMap = new Map<String,PBS_Training_Plan_Assignment__c>();
        ttlavelitemMap = new Map<String,PBS_Training_Track_Level_Item__c>();
        ttlavelitemMap2 = new Map<String,PBS_Training_Track_Level_Item__c>();
        getTrainingPlanAssignment();        
    }
    
    private void getTrainingPlanAssignment(){
        Map<String,PBS_Profile__c> profileMap = new Map<String,PBS_Profile__c>();
        
        for(PBS_Training_Plan_Assignment__c tpa : [Select Id,name, CreatedDate, Completed_On__c,Duration__c,Expected_Completion_Date__c,Status__c,Thirty_Days_Completed__c,Training_Plan__c,User__c From PBS_Training_Plan_Assignment__c]){
            tpAssignmentMap.put(tpa.Training_Plan__c, tpa);
        }      
        
        for(PBS_Profile__c p : [Select Id,name,Category__c,Geography__c,user_role__r.Name,Work_Level__c,User__c,User__r.Manager.Name,User__r.Country From PBS_Profile__c]){
            profileMap.put(p.User__c, p);
        }
        
        for(PBS_Training_Track_Level_Item__c ttl : [SELECT name, Training_Track_Level__r.Training_Track__r.name, Training_Track_Level__r.Training_Track__r.CreatedDate, Training_Plan__c FROM PBS_Training_Track_Level_Item__c]){
            ttlavelitemMap.put(ttl.Training_Plan__c, ttl);
        }
        
        Map<String,PBS_Profile__c> profile = new Map<String,PBS_Profile__c>();
        PBS_Training_Track_Level_Item__c ttlival2 = new PBS_Training_Track_Level_Item__c(); 
        
        for(PBS_Training_Plan_Assignment__c tpaVal : tpAssignmentMap.values()){
            for(PBS_Profile__c profileVal : profileMap.values()){
               //if 2nd map does not have that key
               if(profileMap.keyset().contains(tpaVal.User__c)){
                    profile.put(profileVal.User__c,profileVal);
                    reportDataMap.put(tpaVal.Training_Plan__c,profile);
               }else{
                    profile.put(tpaVal.User__c,profileVal);
                    reportDataMap.put(tpaVal.Training_Plan__c,profile);                   
               }
            }
            
            for(PBS_Training_Track_Level_Item__c ttliVal : ttlavelitemMap.values()){
               //if 2nd map does not have that key
               if(ttlavelitemMap.keyset().contains(tpaVal.Training_Plan__c)){
                    ttlavelitemMap2.put(tpaVal.Training_Plan__c, ttliVal);
               }else{
                    ttlavelitemMap2.put(tpaVal.Training_Plan__c, ttlival2);                   
               }
            }
            
        }        
        system.debug('reportdata map---->'+reportDataMap);
    }    
}