src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPMProject_Span__c</fullName>
        <description>To capture the span of project.</description>
        <label>Project Span</label>
        <picklist>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Brand_Positioning__c</fullName>
        <description>To capture the brand of product for the project.</description>
        <label>Brand Positioning</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Brand__c</fullName>
        <description>To capture the brand.</description>
        <label>IPM_Brand</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Category_Icon__c</fullName>
        <description>To store the category icon details.</description>
        <formula>IF(IPM_Category_Text__c = &apos;Tea and Soy &amp; Fruit Beverages&apos; || IPM_Category_Text__c = &apos;BEVERAGES&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_beverages.png&apos;,&apos;BEVERAGES&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Deodorants &amp; Fragrances&apos; || IPM_Category_Text__c = &apos;Deodorants &amp; Fragrances&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_deo.png&apos;,&apos;DEO&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Dressings&apos; || IPM_Category_Text__c = &apos;DRESSINGS&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_dressings.png&apos;,&apos;DRESSINGS&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Hair Care&apos; || IPM_Category_Text__c = &apos;HAIR CARE&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_hair.png&apos;,&apos;HAIR&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Home Care&apos; || IPM_Category_Text__c = &apos;HOME CARE&apos; , 
IMAGE(&apos;/resource/IPM_Resource/images/category_homecare.png&apos;,&apos;HOMECARE&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Ice Cream&apos; || IPM_Category_Text__c = &apos;ICE CREAM&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_icecream.png&apos;,&apos;ICECREAM&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Laundry&apos; || IPM_Category_Text__c = &apos;LAUNDRY&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_laundry.png&apos;,&apos;LAUNDRY&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;ORAL CARE&apos; || IPM_Category_Text__c = &apos;Oral Care&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_oral.png&apos;,&apos;ORAL&apos;,21,21), 
IF( IPM_Category_Text__c = &apos;Savoury&apos; || IPM_Category_Text__c = &apos;Savoury&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_savoury.png&apos;,&apos;SAVOURY&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Skin Care&apos; || IPM_Category_Text__c = &apos;SKIN CARE&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_skincare.png&apos;,&apos;SKINCARE&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Skin Cleansing&apos; || IPM_Category_Text__c = &apos;SKIN CLEANSING&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_skincleansing.png&apos;,&apos;SKINCLEANSING&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Spreads&apos; || IPM_Category_Text__c = &apos;SPREADS&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_spreads.png&apos;,&apos;SPREADS&apos;,21,21), 
IF(IPM_Category_Text__c = &apos;Household Care&apos; || IPM_Category_Text__c = &apos;HOUSEHOLD CARE&apos; || IPM_Category_Text__c = &apos;HHC&apos;, 
IMAGE(&apos;/resource/IPM_Resource/images/category_HHC.png&apos;,&apos;HOUSEHOLD CARE&apos;,21,21),
&apos;&apos;)))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IPM Category Icon</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Category_Text__c</fullName>
        <description>To store the category text.</description>
        <label>IPM Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related category.</description>
        <label>IPM_Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>To capture the GK model</description>
        <label>IPM GateKeeping Model</label>
        <picklist>
            <picklistValues>
                <fullName>CCVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCLT Leader &amp; CCVP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Description__c</fullName>
        <description>To capture the description of the project.</description>
        <label>Project Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Logo__c</fullName>
        <description>To capture the logo of the project.</description>
        <label>Project Logo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Name__c</fullName>
        <description>To store the name of the project.</description>
        <externalId>true</externalId>
        <inlineHelpText>Project Name is mandatory</inlineHelpText>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IPM_Project_Type__c</fullName>
        <description>To capture the type of project.</description>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Target_Launch_Date__c</fullName>
        <description>The target launch date of the project.</description>
        <label>Target Launch Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>Gate Keeping Model for IPM project</description>
        <label>GateKeeping Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>project phase</description>
        <label>Phase</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Type__c</fullName>
        <description>Project Type i.e. rollout ,global</description>
        <label>Project Type</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IPM Project Type</label>
</CustomObject>

src/classes/IPMProjectIntermediateController.cls
/* Type Name: ipmProjectIntermediateController 
Author: 
Created Date:
Reason: Redirecting to Core Parameters, Task Generation, Project Scope, Team Members Pages
Change History:Added to fields to query. To be used in vf component "ipmProjectDetails" Removed Standard Controller
Author: Samrat Chakraborty
Modified Date: 15-10-2014  */
public with sharing class IPMProjectIntermediateController {
    
    //Initializing Variables
  
    public IPM_Project__c project {get; set;}
    public String projectId;
    public Boolean isImage{get; set;}
    public Boolean isDescVisible{get; set;}
    public String projectType;
    public string isBossID{get;set;}
    public list<IPM_Project__c>ProjectCoreParemeters=new list<IPM_Project__c>();
    public boolean isCoreParameter{get;set;}
    public boolean isPLeader{get;set;}
    public ipmProjectIntermediateController(){
      Apexpages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=9');
        isBossID='';
        projectId=ApexPages.currentPage().getParameters().get('Id');
        if(projectId=='' || projectId==null)
        {
        projectId=ApexPages.currentPage().getParameters().get('Pid');
        }
        isBossID=ApexPages.currentPage().getParameters().get('IsBossID');
        projectType=ApexPages.currentPage().getParameters().get('isProject');
        if(projectType=='true')
            isDescVisible=true;
        if(projectId!=null)

        project=[Select Id,IPM_Gatekeeping_Model__c,IPM_Project_Name__c,IPM_Project_Description__c,IPM_Category_Text__c,IPM_Brand__c,IPM_Project_Logo__c,IPM_Brand_Positioning__c,IPM_Category__r.Name,IPM_Category_Icon__c,IPM_Target_Launch_Date__c,IPM_Phase__c,IPM_Project_Type__c,IPMProject_Span__c from IPM_Project__c where Id=:projectId];
     
     System.debug('Number of Queries used in this Apex code so far: ' + Limits.getQueries());        
    }
      
     
  
}