src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vep_Factory__c.object
<CustomObject>
    <description>Factories details across all locations are stored</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Factory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Factory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Vep_Factories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vep Factory</label>
    <nameField>
        <label>Factory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vep Factories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/VEP_FactoryVisit__c.object
<CustomObject>
    <fields>
        <fullName>Lodging_Desk_Email__c</fullName>
        <label>Lodging Desk Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Travel_Desk_Email__c</fullName>
        <label>Travel Desk Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

src/objects/Vep_Visitor__c.object
<CustomObject>
    <description>Factory Visitor details are stored in this object</description>
    <fields>
        <fullName>Factory_to_Visit__c</fullName>
        <label>Factory to Visit</label>
        <picklist>
            <picklistValues>
                <fullName>Amli Factory Silvassa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barotiwala Foods Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barotiwala HPC Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chhindwara Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiplun Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cochin Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cochin Exports Factory Marine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daman Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi Exports Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diamond Harbour Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Etah Beverages Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Etah Exports Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gandhidham LLPL Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goa Personal Wash Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haldia Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haridwar HPC Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosur Beverages Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kalwa Foods Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kandla Exports Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Khamgaon Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kolkata Beverages Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kolkata Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mangalore Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mysore Beverages Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nalagarh Factory - Ice Creams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nasik Ice Cream Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orai Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pondicherry Beverages Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pondicherry Detergents Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pondicherry Exports Factory</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lodging_Desk_Email__c</fullName>
        <label>Lodging Desk Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lodging__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lodging</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pickup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pickup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Travel_Desk_Email__c</fullName>
        <label>Travel Desk Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Travel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Travel</label>
        <type>Checkbox</type>
    </fields>
    <label>Vep Visitor</label>
    <nameField>
        <label>Visitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vep Visitors</pluralLabel>
    <recordTypes>
        <fullName>Request</fullName>
        <active>true</active>
        <label>Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vep_Visitor_Pass__c.object
<CustomObject>
    <fields>
        <fullName>Factory_to_Visit__c</fullName>
        <formula>Text(Visitor__r.Factory_to_Visit__c)</formula>
        <label>Factory to Visit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Text(Visitor__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor__c</fullName>
        <label>Visitor</label>
        <referenceTo>Vep_Visitor__c</referenceTo>
        <relationshipLabel>Vep Visitor Passes</relationshipLabel>
        <relationshipName>Visitor_Passes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vep Visitor Pass</label>
    <nameField>
        <displayFormat>VEP-{0000000}</displayFormat>
        <label>Visitor Pass Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vep Visitor Passes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VEP_Visitor_Trigger_Test.cls
@isTest
private class VEP_Visitor_Trigger_Test{
    static testMethod void test_VEP_Visitor_Trigger(){
        VEP_Factory__c fact= new VEP_Factory__c();
        fact.name='Factory1';
        fact.category__c ='Category1';
        fact.Factory_Manager__c =userinfo.getuserid();
        insert fact;
        
        VEP_FactoryVisit__c Fsetting = new VEP_FactoryVisit__c();
        Fsetting.Name = 'Factory1';
        Fsetting.Travel_Desk_Email__c='test@xyz.com';
        Fsetting.Lodging_Desk_Email__c='test@xyz.com';
        insert Fsetting;
        
        List<VEP_Visitor__c> listVisitor = new List<VEP_Visitor__c>();
        VEP_Visitor__c visitor = new VEP_Visitor__c();
        Id robRecordTypeId = Schema.SObjectType.VEP_Visitor__c.getRecordTypeInfosByName().get('Request on Behalf').getRecordTypeId();
        Id rRecordTypeId = Schema.SObjectType.VEP_Visitor__c.getRecordTypeInfosByName().get('Request').getRecordTypeId();
        
        System.assert(rRecordTypeId != null);
        
        visitor.name='Test Visitor'; 
        visitor.Travel__c=true;
        visitor.lodging__c=true;
        visitor.pickup__c=true;
        visitor.recordtypeid = rRecordTypeId;
        visitor.status__c= 'Pending Approval';
        visitor.Factory_to_visit__c='Factory1';
        listVisitor.add(visitor); 
        
        System.assert(robRecordTypeId != null);
        VEP_Visitor__c visitor1 = new VEP_Visitor__c();
        visitor1.name='Test Visitor1'; 
        visitor1.status__c='Approved';
        visitor1.recordtypeid = robRecordTypeId;
        visitor1.Travel__c=true; 
        visitor1.lodging__c=true; 
        visitor1.pickup__c=true;
        visitor1.Factory_to_visit__c='Factory1';
        listVisitor.add(visitor1);    
        insert listVisitor;
        List<VEP_Visitor__c> listvepins = new List<VEP_Visitor__c>();
        listvepins = [select id from VEP_Visitor__c where id=:visitor.id or id=:visitor1.id];
        System.assertEquals(listVisitor.size(),listvepins.size());
        Test.startTest();        
        VEP_Visitor_TriggerHandler.vep_UpdateFactory(listVisitor);
        VEP_Visitor_TriggerHandler.vep_generatePassOnBehalf(listVisitor);
        Test.stopTest();
        VEP_Visitor__c lv = [select id,factory_manager__c from VEP_Visitor__c where id=:visitor.id];
        
        System.assertEquals(lv.factory_manager__c,fact.Factory_Manager__c);
        
        
      
        VEP_Visitor_Pass__c vp = [select id,Visitor__c from VEP_Visitor_Pass__c where Visitor__c=: visitor1.id limit 1];
        System.assertEquals(visitor1.id,vp.Visitor__c);
        
        
        
    }
}