src/objects/CEC_Exception_Log__c.object
<CustomObject>
    <description>CEC: To capture the exception handling for CEC</description>
    <fields>
        <fullName>Error_Description__c</fullName>
        <description>CEC: Captures the error description</description>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>CEC: Captures the origin record id</description>
        <label>Reference Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Component_Name__c</fullName>
        <description>CEC: capture the apex class name where this exception has occurred</description>
        <label>Source Component Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Method_Name__c</fullName>
        <description>CEC: capture the apex method name where this exception has occurred</description>
        <label>Source Method Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <description>CEC:  capture the original component type from where this method got invoked</description>
        <label>Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Trigger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduler</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CEC:  Capture the user id in whose instance error has happened</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Exception_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>CEC-{0000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CEC_ExceptionHandling.cls
/**********************************************************************
Name:  CEC_ExceptionHandling
Copyright @ 2016  Unilever
======================================================================
=======================================================================
Purpose: To log exception in a custom object CEC_Exception_Log.
=======================================================================
=======================================================================
History                                                            
-------                                                            
VERSION    AUTHOR            DATE            DETAIL                   
1.0        Mahesh           Nov-2016        INITIAL DEVELOPMENT   
***********************************************************************/
public with sharing class CEC_ExceptionHandling {
	
    /****************************************************************************************************
    @Name CreateExceptionLog
    @param srcType to pass type of component.
	@param methodName to pass name of method.
	@param compName to pass name of class.
	@param RefID to pass record Id.
	@param prntCompName to pass name of parent class.
	@param errDesc to pass Exception message.
    @Description: Insert CEC_Exception_Log__c.
    
    ****************************************************************************************************/
    public static void CreateExceptionLog(String srcType, String methodName,String compName, String RefID,
                                          String errDesc){
                                             
      if(String.isNotBlank(methodName) && String.isNotBlank(compName) && String.isNotBlank(errDesc)){
              CEC_Exception_Log__c excep = new CEC_Exception_Log__c(User__c = userinfo.getUserId(),
        							 Source_Type__c =srcType,Source_Method_Name__c =methodName,
                                     Source_Component_Name__c = compName,Reference_Id__c = RefID,
                                      Error_Description__c = errDesc);
        	  insert excep;                                   
          }
        
        
    }
}