src/objects/CI_SMS_Weekly_Update__c.object
<CustomObject>
    <customHelpPage>CI_R2R_SME_Weekly_Update_Help_Page</customHelpPage>
    <fields>
        <fullName>Comments__c</fullName>
        <label>SME Weekly Comments</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
     <fields>
        <fullName>RAG__c</fullName>
        <inlineHelpText>Updates/changes of this field will be reflected in CI_R2R Innovation</inlineHelpText>
        <label>RAG</label>
        <picklist>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CI_SME Weekly Update</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>CI_SMS Weekly Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI_SME Weekly Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CI_R2R_SME_GetHistory_Test.cls
@isTest
private class CI_R2R_SME_GetHistory_Test{
    static testMethod void myUnitTest() {
        Test.startTest(); 
        CI_SMS_Weekly_Update__c CISME = new CI_SMS_Weekly_Update__c();        
        //CISME.Project_Category__c= 'Continuous Improvements';
        CISME.RAG__c = 'Green';
        CISME.Comments__c = 'testcomments';
        insert CISME;
        system.assertEquals('Green', CISME.RAG__c);
        
        
        List<CI_SMS_Weekly_Update__History> inHistory = new List<CI_SMS_Weekly_Update__History>();               
        
        PageReference pageRef = Page.CI_R2R_Comments_Section_for_SME;            
        test.setcurrentpage(pageRef);       
        
               
        ApexPages.StandardController sc = new ApexPages.standardController(CISME);        
        CI_R2R_SME_GetHistory Historycls = new CI_R2R_SME_GetHistory(sc);
        CI_R2R_SME_GetHistory.wrapper R2Rwrap = new CI_R2R_SME_GetHistory.wrapper('name','name1','changedby','cDate');
        Historycls.getWrappervalues();
        
        Historycls.changedby = 'test1';   
        
        Test.stopTest();
    } 
}