src/objects/Core_Approver_Details__c.object
<CustomObject>
    <customHelpPage>Core_CA_IPHelp</customHelpPage>
    <fields>
        <fullName>Approval_Header__c</fullName>
        <label>Request Id</label>
        <referenceTo>Core_Approval_Header__c</referenceTo>
        <relationshipLabel>Approval Status</relationshipLabel>
        <relationshipName>Core_Approver_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approval Status</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Core_CA_MiniPageView_Override_Controller.cls
public with sharing class Core_CA_MiniPageView_Override_Controller{
    
    public String customPageURL {get;set;}
    public Core_CA_MiniPageView_Override_Controller(ApexPages.StandardController controller) {
        String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();   
        string urlId = ApexPages.currentPage().getParameters().get('id'); 
        List<Core_Approver_Details__c> lstApprover = [SELECT Id FROM Core_Approver_Details__c WHERE Approval_Header__c =: urlId];           
        if(!lstApprover.isEmpty())
            customPageURL = baseUrl+'/apex/Core_CA_ApprovalHomePage#/MyApprovalsHome?headerId='+urlId+'&ipId='+lstApprover[0].Id;
        else
           customPageURL = baseUrl+'/apex/Core_CA_ApprovalHomePage#/MyApprovalsHome?headerId='+urlId+'&ipId='+urlId; 
    }
}