src/objects/Core_Approval_Header__c.object
<CustomObject>
    <customHelpPage>Core_CA_SocialBusinessHelp</customHelpPage>
    <fields>
        <fullName>Ariba_Company_Code__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fully_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fully Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reminder_Alert_Days__c</fullName>
        <label>Reminder Alert Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requested_For_Details__c</fullName>
        <label>Requester</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>GTES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ariba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remedy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clarity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent for Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Approval Console</label>
    <nameField>
        <label>Request ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Console</pluralLabel>
    <recordTypes>
        <fullName>Ariba</fullName>
        <active>true</active>
        <label>Ariba</label>
    </recordTypes>
    <recordTypes>
        <fullName>Clarity</fullName>
        <active>true</active>
        <label>Clarity</label>
    </recordTypes>
    <recordTypes>
        <fullName>GTES</fullName>
        <active>true</active>
        <label>GTES</label>
    </recordTypes>
    <recordTypes>
        <fullName>Invoice</fullName>
        <active>true</active>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Core_Approver_Details__c.object
<CustomObject>
    <customHelpPage>Core_CA_IPHelp</customHelpPage>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>ACTV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COPY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PREP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REWO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QUER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approval_Header__c</fullName>
        <label>Request Id</label>
        <referenceTo>Core_Approval_Header__c</referenceTo>
        <relationshipLabel>Approval Status</relationshipLabel>
        <relationshipName>Core_Approver_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interested_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interested Party</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Core_Approver_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine if the approver is currently active in the business flow of Ariba.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>EMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>END</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <picklist>
            <picklistValues>
                <fullName>Ariba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GTES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remedy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clarity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query With Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to AP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Approval Status</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Status</pluralLabel>
    <recordTypes>
        <fullName>Ariba</fullName>
        <active>true</active>
        <label>Ariba</label>
    </recordTypes>
    <recordTypes>
        <fullName>Clarity</fullName>
        <active>true</active>
        <label>Clarity</label>
    </recordTypes>
    <recordTypes>
        <fullName>GTES</fullName>
        <active>true</active>
        <label>GTES</label>
    </recordTypes>
    <recordTypes>
        <fullName>Invoice</fullName>
        <active>true</active>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CORE_Chatter_Approval__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ReminderAlertDays__c</fullName>
        <label>ReminderAlertDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CORE Chatter Approval</label>
</CustomObject>

src/classes/CORE_CA_ReminderAlert_Batch.cls
/*
   Class Name              : CORE_CA_ReminderAlert
   Date                    : 17/09/2014
   Requirement/Project Name: Chatter Approvals
   Requirement/Description : Send the reminder alert(Chatter notification) to the approver.
       Reminder should be sent on the day depending on.
       1. Ariba: 'Reminder_Alert_Days__c' field of the Chatter approval object.
       2. GTES : 'Core_CA_GTES_ReminderDays__c' custom setting.
*/

global with sharing class CORE_CA_ReminderAlert_Batch implements Database.Batchable<SObject>{

    global Database.QueryLocator start (Database.BatchableContext BC){
        // Retrive all the records which are not 'approved' or 'rejected' from the Interested Party object.
        return Database.getQueryLocator('SELECT Id,Source_System__c,Interested_Party__c,Approval_Header__c,CreatedDate,Is_Active__c FROM Core_Approver_Details__c WHERE ( Status__c != \'Approved\' AND Status__c != \'Rejected\' AND Action__c !=\'APPR\'AND Action__c !=\'REJC\' AND Role__c = \'APP\' AND (Source_System__c=\'Ariba\' OR Source_System__c=\'GTES\')) OR ( Status__c != \'Approved\' AND Status__c != \'Rejected\' AND Status__c!=\'Rework\' AND Action__c !=\'APPR\' AND Action__c !=\'REJC\' AND Action__c !=\'REWO\' AND (Role__c = \'APP\' OR Role__c = \'END\') AND Source_System__c=\'Clarity\') OR ( Status__c != \'Approved\' AND Status__c != \'Return to AP\' AND Status__c!=\'Query With Vendor\' AND Action__c !=\'APPR\' AND Action__c !=\'REJC\' AND Action__c !=\'QUER\' AND (Role__c = \'APP\') AND Source_System__c=\'Invoice\')' );
    }

    global void execute(Database.BatchableContext BC,List<sObject> scope){   
        List<Core_Approver_Details__c> lstApproverDetail=scope;
        List<FeedItem> feedItemsToInsert = new List<FeedItem>();
        Decimal intReminderAlertDays;
        String strBody;
        String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        Set<Id> setUserId = new Set<Id>();
        for(Core_Approver_Details__c approverDetail :lstApproverDetail){
            setUserId.add(approverDetail.Interested_Party__c);
        }
        
        //map of user
        Map<Id,User> mapUser = new Map<Id,User>([Select Name FROM User WHERE IsActive= true and Id IN : setUserId]);
             
        // Loop through the retrived record.
        for(Core_Approver_Details__c approverDetail :lstApproverDetail){
            List<Core_Approval_Header__c> lstApprovalHeader = [Select Id,Reminder_Alert_Days__c,Name,Status__c,Fully_Approved__c,Requested_For_Details__c, Ariba_Company_Code__c from Core_Approval_Header__c where id =: approverDetail.Approval_Header__c];  
            
            if(approverDetail.Interested_Party__c != null ){          
                
                //Send reminder alert to ariba system
                if(approverDetail.Source_System__c == 'Ariba' && lstApprovalHeader[0].Status__c =='Submitted' && CORE_Chatter_Approval__c.getinstance('Ariba_Notification').Text_Value__c == 'Yes' && approverDetail.Is_Active__c ){ 
                    intReminderAlertDays = lstApprovalHeader[0].Reminder_Alert_Days__c;  
                    if(intReminderAlertDays == approverDetail.CreatedDate.date().daysBetween(System.now().date())){
                        strBody = CORE_Chatter_Approval__c.getinstance('Ariba-ApprovalOverdue').Text_Value__c;
                        strBody = strBody.replace('YYY',lstApprovalHeader[0].Name); 
                        strBody = strBody.replace('XXX',mapUser.get(approverDetail.Interested_Party__c).Name);                  
                       feedItemsToInsert.add(new FeedItem( Type = 'LinkPost', Body = strBody , ParentId = approverDetail.Approval_Header__c,
                                                             LinkURL =baseUrl+'/'+lstApprovalHeader[0].Id , Title = lstApprovalHeader[0].Name, CreatedById = CORE_Chatter_Approval__c.getinstance('Ariba').Text_Value__c ));
                        /* feedItemsToInsert.add(new FeedItem( Type = 'LinkPost', Body = strBody , ParentId = approverDetail.Approval_Header__c,
                                                             LinkURL = baseUrl+'/apex/Core_CA_ApprovalHomePage#/MyApprovalsHome?headerId='+lstApprovalHeader[0].Id+'&ipId='+approverDetail.Id , Title = lstApprovalHeader[0].Name, CreatedById = CORE_Chatter_Approval__c.getinstance('Ariba').Text_Value__c )); */
                    }
                }
                
                //Send reminder alert to GTES system
                if(approverDetail.Source_System__c == 'GTES' && CORE_Chatter_Approval__c.getinstance('GTES_Notification').Text_Value__c == 'Yes' && !lstApprovalHeader[0].Fully_Approved__c  ){ 
                    intReminderAlertDays = integer.valueOf(CORE_Chatter_Approval__c.getinstance('GTES').ReminderAlertDays__c);                   
                    if(intReminderAlertDays == approverDetail.CreatedDate.date().daysBetween(System.now().date())){
                         strBody = CORE_Chatter_Approval__c.getinstance('GTES-ApprovalOverdue').Text_Value__c;
                         strBody = strBody.replace('YYY',lstApprovalHeader[0].Name);
                         strBody = strBody.replace('XXX',mapUser.get(approverDetail.Interested_Party__c).Name);                      
                        feedItemsToInsert.add(new FeedItem( Type = 'LinkPost', Body = strBody , ParentId = approverDetail.Approval_Header__c,
                                                            LinkURL =baseUrl+'/'+lstApprovalHeader[0].Id , Title =lstApprovalHeader[0].Name, CreatedById = CORE_Chatter_Approval__c.getinstance('GTES').Text_Value__c )); 
                        /*feedItemsToInsert.add(new FeedItem( Type = 'LinkPost', Body = strBody , ParentId = approverDetail.Approval_Header__c,
                                                            LinkURL =baseUrl+'/apex/Core_CA_ApprovalHomePage#/MyApprovalsHome?headerId='+lstApprovalHeader[0].Id+'&ipId='+approverDetail.Id , Title =lstApprovalHeader[0].Name, CreatedById = CORE_Chatter_Approval__c.getinstance('GTES').Text_Value__c ));*/
                    }
                }   
                
                //Send reminder alert to Clarity system
                if(approverDetail.Source_System__c == 'Clarity' && CORE_Chatter_Approval__c.getinstance('Clarity_Notification').Text_Value__c == 'Yes'){ 
                    intReminderAlertDays = integer.valueOf(CORE_Chatter_Approval__c.getinstance('Clarity').ReminderAlertDays__c);                   
                    if(intReminderAlertDays == approverDetail.CreatedDate.date().daysBetween(System.now().date())){
                         strBody = CORE_Chatter_Approval__c.getinstance('Clarity_ApprovalOverdue').Text_Value__c;
                         strBody = strBody.replace('YYY',lstApprovalHeader[0].Name);
                         strBody = strBody.replace('XXX',mapUser.get(approverDetail.Interested_Party__c).Name);                      
                        feedItemsToInsert.add(new FeedItem( Type = 'LinkPost', Body = strBody , ParentId = approverDetail.Approval_Header__c,
                                                            LinkURL =baseUrl+'/'+lstApprovalHeader[0].Id , Title =lstApprovalHeader[0].Name, CreatedById = CORE_Chatter_Approval__c.getinstance('GTES').Text_Value__c )); 
                    }
                }  
                
                //Send reminder alert to Invoice system
                if(approverDetail.Source_System__c == 'Invoice' && CORE_Chatter_Approval__c.getinstance('Invoice_Notification').Text_Value__c == 'Yes'){ 
                    intReminderAlertDays = integer.valueOf(CORE_Chatter_Approval__c.getinstance('Invoice').ReminderAlertDays__c);                   
                    if(intReminderAlertDays == approverDetail.CreatedDate.date().daysBetween(System.now().date())){
                         strBody = CORE_Chatter_Approval__c.getinstance('Invoice_ApprovalOverdue').Text_Value__c;
                         strBody = strBody.replace('YYY',lstApprovalHeader[0].Requested_For_Details__c);
                         strBody = strBody.replace('XXX',mapUser.get(approverDetail.Interested_Party__c).Name);
                         strBody = strBody.replace('ZZZ',lstApprovalHeader[0].Ariba_Company_Code__c);
                        feedItemsToInsert.add(new FeedItem( Type = 'LinkPost', Body = strBody , ParentId = approverDetail.Approval_Header__c,
                                                            LinkURL =baseUrl+'/'+lstApprovalHeader[0].Id , Title =lstApprovalHeader[0].Requested_For_Details__c, CreatedById = CORE_Chatter_Approval__c.getinstance('Invoice').Text_Value__c )); 
                    }
                }                         
            } 
        }            
        
        //Insert the FeedItem. 
        if(!feedItemsToInsert.isEmpty())
            Database.insert(feedItemsToInsert, false);
 
    }

    global void finish(Database.BatchableContext BC){
    
    }
}