src/objects/cp_Event__c.object
<CustomObject>
    <description>CP - Information about the event is stored here, and displayed on the Planner &amp; Plan on a page</description>
    <fields>
        <fullName>Activity_Status__c</fullName>
        <label>Submission Status</label>
        <picklist>
            <picklistValues>
                <fullName>Offline</fullName>
                <color>#DDDDDD</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#FF99FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Tentative</fullName>
                <color>#CC9933</color>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#66FF99</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Are_Dates_Guarenteed__c</fullName>
        <inlineHelpText>Are these dates set in stone?</inlineHelpText>
        <label>Are the dates confirmed?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Planner Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planner Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cp_Planner__c.object
<CustomObject>
    <label>Planner</label>
    <nameField>
        <label>Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cp_PlannerLocation__c.object
<CustomObject>
    <fields>
        <fullName>Planner__c</fullName>
        <label>Planner</label>
        <referenceTo>cp_Planner__c</referenceTo>
        <relationshipLabel>Planner Locations</relationshipLabel>
        <relationshipName>Planner_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Planner Location</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planner Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cp_PlannerPreference__c.object
<CustomObject>
    <description>CP - Custom object to store default planner preferences for each user. All fields are free text as a visualforce page will be used to override this object.</description>
    <fields>
        <fullName>Planner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planner</label>
        <referenceTo>cp_Planner__c</referenceTo>
        <relationshipLabel>Default Preferences</relationshipLabel>
        <relationshipName>Planner_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Planner Preference</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Preference Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planner Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cp_EventApprovalTest.cls
/**
*
* Author:	Radoslava Radkova
* Date:		04/06/2014
* Description:	Test class for cp_EventApproval class.
*
* -------------------
* COVERAGE:  	  87%
* -------------------
*
**/
@isTest
private class cp_EventApprovalTest
{
	static testmethod void testApproveGlobalEvent()
	{
		User testUser = cp_TestData.getTestUser('System Administrator','Event');
        insert testUser;

		List<cp_Planner__c> planners = new List<cp_Planner__c>();
        cp_Planner__c cluster = cp_TestData.getTestPlanner(cp_PlannerUtility.CLUSTER,'Europe',testUser.Id);
        planners.add(cluster);
        insert planners;

        // Planner Preference
        cp_PlannerPreference__c defaults = new cp_PlannerPreference__c();
        defaults.Planner__c = cluster.Id;
        insert defaults;

        // Event
        cp_Event__c e = cp_TestData.getTestPlannerEvent();
        insert e;

        cp_EventApproval.approveEvent(e.Id);

        List<cp_Event__c> event = [SELECT Id, Activity_Status__c FROM cp_Event__c WHERE Id =: e.id];
        System.assertEquals(event.get(0).Activity_Status__c, cp_EventTriggerHandler.EVENT_STATUS_OFFLINE);

        cp_EventApproval.saveToPlanner(e.Id);

	}

	static testmethod void testApproveLocalEvent()
	{
		User testUser = cp_TestData.getTestUser('System Administrator','Event');
        insert testUser;

		List<cp_Planner__c> planners = new List<cp_Planner__c>();
        cp_Planner__c cluster = cp_TestData.getTestPlanner(cp_PlannerUtility.CLUSTER,'Europe',testUser.Id);
        planners.add(cluster);
        insert planners;

        // Planner Preference
        cp_PlannerPreference__c defaults = new cp_PlannerPreference__c();
        defaults.Planner__c = cluster.Id;
        insert defaults;

        // Event
        cp_Event__c e = cp_TestData.getTestPlannerEvent('Local');
        e.Are_Dates_Guarenteed__c = 'Yes';
        insert e;

        // Planner Locations
        List<cp_PlannerLocation__c> locs = new List<cp_PlannerLocation__c>();
        locs.add(cp_TestData.getTestPlannerLocation(e.Id, cluster.Id));
        insert locs;

        cp_EventApproval.saveToPlanner(e.Id);

        List<cp_Event__c> event = [SELECT Id, Activity_Status__c FROM cp_Event__c WHERE Id =: e.id];
        System.assertEquals(event.get(0).Activity_Status__c, cp_PlannerUtility.CONFIRMED);

        cp_EventApproval.approveEvent(e.Id);
	}

	static testmethod void testApproveGlobalEventWithPlannerLocation()
	{
		User testUser = cp_TestData.getTestUser('System Administrator','Event');
        insert testUser;

		List<cp_Planner__c> planners = new List<cp_Planner__c>();
        cp_Planner__c cluster = cp_TestData.getTestPlanner(cp_PlannerUtility.CLUSTER,'Europe',testUser.Id);
        planners.add(cluster);
        insert planners;

        // Planner Preference
        cp_PlannerPreference__c defaults = new cp_PlannerPreference__c();
        defaults.Planner__c = cluster.Id;
        insert defaults;

        // Event
        cp_Event__c e = cp_TestData.getTestPlannerEvent();
        e.Are_Dates_Guarenteed__c = 'Yes';
        insert e;

        // Planner Locations
        List<cp_PlannerLocation__c> locs = new List<cp_PlannerLocation__c>();
        locs.add(cp_TestData.getTestPlannerLocation(e.Id, cluster.Id));
        insert locs;

        cp_EventApproval.approveEvent(e.Id);

        List<cp_Event__c> event = [SELECT Id, Activity_Status__c FROM cp_Event__c WHERE Id =: e.id];
       	System.assertEquals(cp_EventTriggerHandler.EVENT_STATUS_DRAFT, event.get(0).Activity_Status__c);

        cp_EventApproval.saveToPlanner(e.Id);
	}
	
}