src/objects/CPA_PWORF__c.object
<CustomObject>
    <description>This object holds Project Work Order Request Form (PWORF) details which is used for supplier/vendor management.

It displays PWORF requests received from Project Services / Delivery Teams at Unilever.</description>
    <fields>
        <fullName>mpkl_Project_Phases__c</fullName>
        <description>Phases of the project that are covered in the PWORF</description>
        <label>Project Phases*</label>
        <picklist>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analyse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deploy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>pkl_Status__c</fullName>
        <description>Auto generated based on user actions</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmitted</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Withhold</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Accepted</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Answered</fullName>
                <color>#B6E32E</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PWORF</label>
    <nameField>
        <label>PWORF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PWORF</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPA_PWORF_Ageing__c.object
<CustomObject>
    <description>This object will be used for persisting the pworf ageing only with help of Apex Scheduler/Triggers.</description>
    <fields>
        <fullName>PWORF_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PWORF ID</label>
        <referenceTo>CPA_PWORF__c</referenceTo>
        <relationshipLabel>CPA PWORF Ageing</relationshipLabel>
        <relationshipName>CPA_PWORF_Ageing</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CPA PWORF Ageing</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>CPA PWORF Aging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA PWORF Ageing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CPA_Trigger_Pattern__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This custom setting is used for PWORF,PWO, LOI and CR trigger</description>
    <label>CPA For Trigger Pattern</label>
</CustomObject>

src/classes/CPA_batchProrfAgeUpdate_test.cls
/**********************************************************************
Name: CPA_batchProrfAgeUpdate_test()
Copyright © 2015 Salesforce
======================================================
======================================================
Purpose: This is the batch class of PWORF Age
-------
======================================================
======================================================
History
-------
VERSION     AUTHOR       DATE            DETAIL Description
1.0         Name      20/04/2016     INITIAL DEVELOPMENT CSR:
***********************************************************************/
@isTest
private class CPA_batchProrfAgeUpdate_test {

    static testmethod void test() {
        
        CPA_Trigger_Pattern__c PWORFTriggerPattern = CPA_testCustomSettingClass_util.createTest_PWORFTriggerPattern();
        insert PWORFTriggerPattern; 
                        
        CPA_PWORF__c objPworf1 = CPA_testPWORFClass_util.createTest_other_PWORF();
            objPworf1.Name = 'PWORF-'+system.Now()+1;
            objPworf1.mpkl_Project_Phases__c = 'Design; Build; Test; Deploy';
            objPworf1.pkl_Status__c = CPA_ConstantsForContractingAppClasses.SAVED;
            insert objPworf1;
			objPworf1.pkl_Status__c = CPA_ConstantsForContractingAppClasses.SUBMITTED;
            update objPworf1;

       CPA_PWORF_Ageing__c[] ml = new List<CPA_PWORF_Ageing__c>();
       for (Integer i=0;i<10;i++) {
           CPA_PWORF_Ageing__c m = new CPA_PWORF_Ageing__c(
               PWORF_ID__c=objPworf1.id);
               
           ml.add(m);
       }
       insert ml;

       Test.startTest();
       CPA_batchProrfAgeUpdate batchProrfAgeUpdate = new CPA_batchProrfAgeUpdate ();

	   Database.executebatch(batchProrfAgeUpdate);
       Test.stopTest();
	   System.assert (CPA_ConstantsForContractingAppClasses.SUBMITTED == objPworf1.pkl_Status__c);
    }
}