src/objects/CPA_HLE_Request__c.object
<CustomObject>
    <description>HLE Request Object</description>
    <fields>
        <fullName>pkl_Status__c</fullName>
        <description>Auto generated based on user actions</description>
        <inlineHelpText>Auto generated based on user actions</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>txta_Reason_for_Cancellation__c</fullName>
        <label>Reason for Cancellation</label>
        <type>TextArea</type>
    </fields>
    <label>HLE Request</label>
    <nameField>
        <label>HLE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HLE Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CPA_HLE_CancelReasonController.cls
Public Class CPA_HLE_CancelReasonController{
 Public id hleId;
     Public CPA_HLE_Request__c hleRecord;
     Public string strReason{get;set;}  

    public CPA_HLE_CancelReasonController(ApexPages.StandardController controller) {
        
        if(ApexPages.currentPage().getParameters().get('id') != null) {      
              hleId= ApexPages.currentPage().getParameters().get('id');
            getRecord(hleId);     
        }
      }
      
    public void getRecord(ID hleId){
       hleRecord = [select id,  txta_Reason_for_Cancellation__c,pkl_Status__c  from CPA_HLE_Request__c where id =:hleId];
       strReason = hleRecord.txta_Reason_for_Cancellation__c;
      }
      
    public PageReference  SaveCancelReason(){
        hleRecord.txta_Reason_for_Cancellation__c = strReason;
        hleRecord.pkl_Status__c= 'Cancelled';
        //Approval.unLockResult lrList = Approval.unlock(hleRecord.id, true);           
        update hleRecord;  
        PageReference ReturnPage = new PageReference('/' + hleRecord.id); 
        ReturnPage.setRedirect(true); 
        return ReturnPage;
    }
    public PageReference  CancelReason(){
        PageReference ReturnPage = new PageReference('/' + hleRecord.id); 
        ReturnPage.setRedirect(true); 
        return ReturnPage;  
    }
}