src/objects/Download_Statistics__c.object
<CustomObject>
    <label>WINatPOS Download Statistics</label>
    <nameField>
        <label>Download Statistics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WINatPOS Download Statistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Search_Statistics__c.object
<CustomObject>
    <label>WINatPOS Search Statistics</label>
    <nameField>
        <label>Search Statistics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WINatPOS Search Statistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WinatPOSPurgeStatistics__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>WinatPOS configuration parameters to purge statistics records that are gathered for reporting</description>
    <fields>
        <fullName>Download_Statistics__c</fullName>
        <description>How many days are kept in the database for Download_Statistics object (LAST_N_DAYS:n)</description>
        <label>Download_Statistics</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Search_Statistics__c</fullName>
        <description>How many days are kept in Search Statistics object (LAST_N_DAYS:n)</description>
        <label>Search Statistics</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WinatPOSPurgeStatistics</label>
</CustomObject>

src/classes/WINatPOS_SCH_PurgeStats_Test.cls
/**********************************************************************
Name: WINatPOS_SCH_PurgeStats_Test
Copyright © 2014 Unilever.
=======================================================
=======================================================
Purpose: Test class for WINatPOS_SCH_PurgeStats
=======================================================
=======================================================
History
-------
VERSION AUTHOR                  DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   Istvan Szegedi          18/09/2014      INITIAL DEVELOPMENT
***********************************************************************/

@isTest
public class WINatPOS_SCH_PurgeStats_Test {     
    public static string CRON_EXP = '0 0 0 15 3 ? 2022';

  /*******************************************************************
    Purpose: Method to test scheduling Apex class for purging stats
    Parameters: Void
    Returns: Void
    Throws [Exceptions]: [optional]
    ********************************************************************/
    static testmethod void testScheduledJob(){
        // create test data for custom settings
        WinatPOSPurgeStatistics__c purgeStatsCustomSettings = new WinatPOSPurgeStatistics__c();
        purgeStatsCustomSettings.Name = 'PurgeConfig';
        purgeStatsCustomSettings.Search_Statistics__c = 180;
        purgeStatsCustomSettings.Download_Statistics__c = 365;
        insert purgeStatsCustomSettings;
        
        Test.startTest();
    
        // schedule the test job
        String jobId = System.schedule('Scheduled Job to Purge WINatPOS stats', 
                                        CRON_EXP, new WINatPOS_SCH_PurgeStats());  
        // get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                          FROM CronTrigger WHERE id =: jobId];
        
        Test.stopTest();
        
           // Verify the expressions are the same
        System.assertEquals(CRON_EXP,ct.CronExpression);
    
        // Verify the job has not run 
        System.assertEquals(0,ct.TimesTriggered);
    
        // Verify the next time the job will run
        System.assertEquals('2022-03-15 00:00:00', String.valueOf(ct.NextFireTime));
    
    }   
}