src/objects/EA_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Due_Date__c</fullName>
        <label>Activity_Due_Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Everyday_Activity__c</fullName>
        <label>Everyday Activity</label>
        <referenceTo>Everyday_Activity__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invitation_Status__c</fullName>
        <label>Invitation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{DD}{MM}{YY}-{00000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Everyday_Activity__c.object
<CustomObject>
    <label>Everyday Activity</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Everyday Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EA_FeedbackNotificationBatch.cls
/*
Class Name: EA_Feedback_Controller.cls
Author : Mindtree
Date: 27th Nov 2015
Requirement/Project Name: Unilever Salesforce Engagement
Requirement/Description: Batch apex to send scheduled feedback reminders.
*/
global class EA_FeedbackNotificationBatch implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext BC){           
        String status = 'Self';
        dateTime whenDay = system.today()-1;
        String q = 'SELECT Activity_Due_Date__c,Id,Invitation_Status__c,Participant__c,Everyday_Activity__c FROM EA_Team_Member__c WHERE Invitation_Status__c =: status AND Activity_Due_Date__c >:whenDay';      
        return Database.getQueryLocator(q);
    }      
    global void execute(Database.BatchableContext BC, List<sObject>scope){            
        if(scope != null && scope.size()>0){               
            EA_Feedback_Controller.sendFeedbackReminder(scope);
        }                    
    }    
    global void finish(Database.BatchableContext BC){
        // Logic to be Executed at finish
    }
}