src/objects/Global_Object_Ownership__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Records ownership and details for each object with a prefix as well as the Enterprise Archtect Responsible</description>
    <fields>
        <fullName>Enterprise_Architect__c</fullName>
        <label>Enterprise Architect Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Object Ownership</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>TODAY() -  DATEVALUE(CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Enterprise_Architect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enterprise Architect</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Users_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <defaultValue>&apos;What is your Suggestion?&apos;</defaultValue>
        <inlineHelpText>What are you trying to do?</inlineHelpText>
        <label>Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prototype</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Suggestion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idea</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Feedback</label>
    <nameField>
        <displayFormat>R-{0}</displayFormat>
        <label>Response Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/userFeedbackCTRL.cls
public with sharing class userFeedbackCTRL {
    @auraEnabled
    public static USER getUserInfo(string userId){
		return [select id, name from user where id = :userId];
    }
    
    @auraEnabled
    public static list<User_Feedback__c> history(string userId){
        
        list<User_Feedback__c> feedback = new List<User_Feedback__c>();
        //try{
            feedback = [select id, name, feedback__c, Status__c, type__c, Age__c, Enterprise_Architect__c,Object_Type__c, Project__c, createddate from User_Feedback__c where createdById = :userId order by createdDate DESC];
        //}catch(exception e){
            //nothing
        //}
        
        return feedback;
    }
    
    
    private static void getProjectDetails(User_Feedback__c uf){
        id recId = (Id)uf.Record_id__c;
        
        Schema.SObjectType sobjectType = recId.getSObjectType();
        
        string obname = sobjectType.getDescribe().getName();
        uf.Object_Type__c = obname;
        
        
    }
    
    private static void getEADetails(User_Feedback__c uf){
        
        //return if there is no associated object
        
        if(uf.Object_Type__c == null || uf.Object_Type__c==''){
            return;
        }
            
        string obname = uf.Object_Type__c;
        
        //strip out custom object identifier
        
        if(obname.contains('__c')){
            obname.replace('__c', '');
        }
        
        //Standard Objects or those without Prefix probably dont have an owner
        //so ignore standard objects?!
        
        if(obname.contains('_')){
            string[] items = obname.split('_');
            //take the prefix
            string prefix = items[0];
            
            //Check there is a mapping to the prefix in custom settings
            Global_Object_Ownership__c prefixVal = Global_Object_Ownership__c.getInstance(prefix);
            
            //Copy the project prefix mapping
            if(prefixVal!=null){
                uf.Project__c = prefixVal.Project__c;
                //Try and Match the EA based on full name - not entirely happy with this join as might be two people with same name in Unilever
                
                try{
                    uf.Enterprise_Architect__c = [select id from user where email = :prefixVal.Enterprise_Architect__c limit 1].id;
                }catch(exception e){
                    
                }
                                
            }
        }
    }
    
    //Void Method because publisher action closes on save
    @auraEnabled
    public static void insertFeedback(User_Feedback__c uf){
        
        
        if(uf.Record_id__c !=null && uf.Record_id__c!=''){
            
           userFeedbackCTRL.getProjectDetails(uf);
           userFeedbackCTRL.getEADetails(uf);
            
            
        }
            
		
        
        insert uf;
        
    }
    
    
}