src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/uw_BET__c.object
<CustomObject>
    <customHelpPage>be_help_pop_up</customHelpPage>
    <description>Custom object for Brand Experience Toolkit</description>
    <fields>
        <fullName>Brand_Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand Positioning</label>
        <referenceTo>MDO_BrandPosition__c</referenceTo>
        <relationshipLabel>Brand Experience List</relationshipLabel>
        <relationshipName>Brand_Experience_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category Group</label>
        <referenceTo>MDO_Category__c</referenceTo>
        <relationshipLabel>Brand Experience List</relationshipLabel>
        <relationshipName>Brand_Experience_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>Brand Experience List</relationshipLabel>
        <relationshipName>Brand_Experience_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inoplan_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Please select the Inoplan project your BET should be linked to for reporting purposes. Where possible use the ORIGINAL project name and not a rollout.</inlineHelpText>
        <label>Inoplan Project</label>
        <referenceTo>uw_Inoplan_Project__c</referenceTo>
        <relationshipLabel>Brand Experience</relationshipLabel>
        <relationshipName>Brand_Experience</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>MDO_Brand__c</referenceTo>
        <relationshipLabel>Brand Experience List</relationshipLabel>
        <relationshipName>Brand_Experience_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>MDO_Category__c</referenceTo>
        <relationshipLabel>Brand Experience List (Product Category)</relationshipLabel>
        <relationshipName>Brand_Experience_List1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand Experience</label>
    <nameField>
        <label>Toolkit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Experience List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CategoryComponentData.cls
/*************************************************************************************
Name : CategoryComponentData

Purpose : Class used for comunication between visualforce page and category brand selection component

History

VERSION  AUTHOR                DATE        DETAIL   Description
1.0      m.bluj@polsource.com  17-07-2015  Initial
*************************************************************************************/
public class CategoryComponentData {

	public String categoryGroup {get;set;}
	public String category {get;set;}
	public String brandpositioning {get;set;}
	public String brand {get;set;}
	public String impProject {get;set;}
	public String inoplanProject {get;set;}
	public Boolean categoryMigrated {get;set;}
	public Boolean categoryNotMigrated {get;set;}
	public Boolean leadIPM {get;set;}

	public CategoryComponentData() {}

	public CategoryComponentData (uw_BET__c bet){
		impProject = bet.IPM_Project__c;
		inoplanProject = bet.Inoplan_Project__c;
		categoryGroup = bet.Category_Group__c; 
		category = bet.Product_category__c;
		brandpositioning = bet.Brand_Position__c;
		brand = bet.Product_Brand__c;
		leadIPM = bet.IPM_Project__c !=null ? true : false;
	}
}