src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>To capture the GK model</description>
        <label>IPM GateKeeping Model</label>
        <picklist>
            <picklistValues>
                <fullName>CCVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCLT Leader &amp; CCVP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document__c.object
<CustomObject>
    <description>THis is used in IPM to store Project documents</description>
    <fields>
        <fullName>IPM_GateDocuments__c</fullName>
        <description>To capture gate document name</description>
        <label>IPM_GateDocuments</label>
        <picklist>
            <picklistValues>
                <fullName>Charter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Design Lock</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>Relation to the Project Object</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Documents</relationshipLabel>
        <relationshipName>Project_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Project Document</label>
    <nameField>
        <label>Project Document Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IPM_Updatetasks_Test.cls
/*****************************************************************************
*@Author:Cognizant
*@Date:01/02/2015
*@Description : To test IPM_Updatetasks class functionalities
*/
@isTest
public class IPM_Updatetasks_Test {
    public static IPM_Project__c project;
    public static IPM_Project_Document__c proDoc; //=new IPM_Project_Document__c();
    public static Map<Id, IPM_Project_Document__c> newPDocumentsMap=new Map<Id, IPM_Project_Document__c>();
    
    /**************************************************************
    *@Description :create a project and project document
    */
    static testMethod void initializeData(){
        //project=new IPM_Project__c();
    	
        project = IPM_TestFactory_Helper.createIPMProject(false);
        project.IPM_GateKeeping_Model__c='Both'; 
        insert project;
        system.assertNotEquals(project.id, null);
        
        proDoc = IPM_TestFactory_Helper.createIPMProjectDocument(false);
        proDoc.IPM_GateDocuments__c= IPM_ConstantUtils.CHARTER_GATE; 
        proDoc.IPM_Project__c=project.ID;
        insert proDoc;
            
        system.assertNotEquals(proDoc.id, null);
        system.assertEquals(proDoc.IPM_GateDocuments__c,  IPM_ConstantUtils.CHARTER_GATE, 'IPM_GateDocuments__c Not Matched');
        newPDocumentsMap.put(proDoc.Id,proDoc);
        system.assert(newPDocumentsMap != null && !newPDocumentsMap.isEmpty(), 'newPDocumentsMap map should contain atleast 1 item.');
        
        
    }
    
    /**************************************************************
    *@Description :get project id from initiliazedata method
    */
    static testMethod void dotest(){ 
        initializeData();
        
        Test.startTest();
        PageReference pRef = new PageReference('/apex/IPM_UniqueProjectName?id='+project.Id);
        Test.setCurrentPage(pRef);
        system.assert(pRef!=null, 'pRef should not be null.');
        Test.stopTest();
    }
}