src/objects/IPM_Company_Card__c.object
<CustomObject>
    <description>This object store company cards details</description>
    <fields>
        <fullName>IPM_Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>to store business partner user name</description>
        <label>Business Partner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Company_Card</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Company Card</label>
    <nameField>
        <label>IPM Company Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Company Card</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Milestone__c.object
<CustomObject>
    <description>This object is used to capture Milestone Dates</description>
    <fields>
        <fullName>IPM_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to identify milestone is completed.</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Deputy_Project_Leader_Email__c</fullName>
        <description>Field to store deputy project leader&apos;s email.</description>
        <label>IPM Deputy Project Leader Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IPM_Due_Date__c</fullName>
        <description>Due date of milestone</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Gatekeeper_Email__c</fullName>
        <description>Formula field to store Gatekeeper&apos;s email.</description>
        <label>IPM Gatekeeper Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IPM_Milestone_Due_Date_In_Past__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send a mail when the milestone due date in the past</description>
        <label>IPM Milestone Due Date In Past</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent master milestone lookup.</description>
        <label>IPM Milestone</label>
        <referenceTo>IPM_Milestone__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Name__c</fullName>
        <description>Milestone name</description>
        <label>Milestone Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>phase of milestone.</description>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Launch Evaluation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Leader_Email__c</fullName>
        <description>Field to store Project leader&apos;s email.</description>
        <label>IPM Project Leader Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Name__c</fullName>
        <description>Formula field to store project name.</description>
        <formula>IPM_Project__r.IPM_Project_Name__c</formula>
        <label>IPM Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Type__c</fullName>
        <description>Project type will be stored at each milestone level.</description>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollout</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>IPM Project Master data</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Type_of_gate__c</fullName>
        <description>Type of the gate will be identified based on this field.</description>
        <label>Type of Gate</label>
        <picklist>
            <picklistValues>
                <fullName>Charter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Milestone</label>
    <nameField>
        <label>IPM Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>Deputy_Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user.</description>
        <label>Deputy Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPMProject_Span__c</fullName>
        <description>To capture the span of project.</description>
        <label>Project Span</label>
        <picklist>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_CompanyCardText__c</fullName>
        <description>To capture the Company Card Text.</description>
        <label>Source Company Card</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related company card.</description>
        <label>IPM Company Card</label>
        <referenceTo>IPM_Company_Card__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Finance_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the finance related user.</description>
        <label>Finance Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>To capture the GK model</description>
        <label>IPM GateKeeping Model</label>
        <picklist>
            <picklistValues>
                <fullName>CCVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCLT Leader &amp; CCVP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Gatekeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user in this case the gatekeeper.</description>
        <label>Project Gatekeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user in this case the project leader.</description>
        <label>Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Name__c</fullName>
        <description>To store the name of the project.</description>
        <externalId>true</externalId>
        <inlineHelpText>Project Name is mandatory</inlineHelpText>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IPM_Project_Type__c</fullName>
        <description>To capture the type of project.</description>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Temporary_Phase__c</fullName>
        <description>To capture the temporary phase of the project.</description>
        <label>Temporary Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Resource__c.object
<CustomObject>
    <description>To store the IPM Project Team Members</description>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <description>Project&apos;s company card value will be populated in this field.</description>
        <formula>IPM_Project__r.IPM_Company_Card__c</formula>
        <label>Company Card</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>lookup for IPM project</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Resources</relationshipLabel>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Role_Type__c</fullName>
        <description>Store role type</description>
        <label>IPM Role Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to IPM User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resource Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>Gate Keeping Model for IPM project</description>
        <label>GateKeeping Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>project phase</description>
        <label>Phase</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Type__c</fullName>
        <description>Project Type i.e. rollout ,global</description>
        <label>Project Type</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Independent_Project__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check for independent project</description>
        <label>Independent Project?</label>
        <type>Checkbox</type>
    </fields>
    <label>IPM Project Type</label>
</CustomObject>

src/classes/IPM_DueDateNotification_Batch.cls
/******************************************** 
*@Author:Cognizant
*@Date:September 2015
*@Description : Sends chatter notification and mail when Milestone Due Date is today or passed or 21 days in the future 
* This class is set as Without Sharing as the Batch class needs to send Notifications to all
* eligible users irrespective of who schedules batch class. Ideally the bacth class wil be 
* scheduled by an Admin user.
* This class has been declared as global as it implements Database.Batchable interface.
*********************************************/

global without sharing class IPM_DueDateNotification_Batch implements Database.Batchable<sObject> {


    public static String response ;
    private static final String CLASS_NAME = IPM_DueDateNotification_Batch.class.getName();
    private static Map<Id,String> projIdchatterMessageMap = new Map<Id,String>();
    private static Set<Id> projIdNewProjectsSet = new Set<Id>();
    private static Map<Id,Set<Id>> subjectIdMentionIdSetMap = new Map<Id,Set<Id>>();
    private static List<IPM_Milestone__c> milestonesUpdated= new List<IPM_Milestone__c>();
    
    global Database.QueryLocator start(Database.BatchableContext bC) {
        
        Date dueIntwentyOneDays = system.today().addDays(21); // Milestones approaching due date in next 21 days
        Date todayDate = System.today();//Milestones having due date today
        String query = 'SELECT IPM_Due_Date__c,IPM_Completed__c,IPM_Project__r.IPM_Project_Gatekeeper__r.Email,IPM_Project__r.Deputy_Project_Leader__r.Name,IPM_Deputy_Project_Leader_Email__c, ';
                   query+='IPM_Project__r.IPM_Project_Leader__r.Name,IPM_Project__r.IPM_Project_Leader__r.Email,IPM_Milestone_Due_Date_In_Past__c,IPM_Project_Leader_Email__c, ' ;
                   query+='IPM_Project__r.Deputy_Project_Leader__r.Email,IPM_Project__r.IPM_Project_Name__c,IPM_Project__r.IPM_Project_Gatekeeper__r.Name,IPM_Gatekeeper_Email__c,';
                   query+='IPM_Project__c,IPM_Name__c,IPM_Type_of_gate__c,IPM_Phase__c,IPM_Project__r.IPM_Project_Leader__c,IPM_Project__r.IPM_Finance_Member__c, ';
                   query+='IPM_Project__r.Deputy_Project_Leader__c,IPM_Project__r.IPM_Company_Card__r.IPM_Business_Partner__c,IPM_Project__r.IPM_Phase__c, IPM_Project__r.IPM_Temporary_Phase__c ';
                   query+='FROM IPM_Milestone__c';
                   query +=' where (IPM_Due_Date__c <= :todayDate or IPM_Due_Date__c = :dueIntwentyOneDays) AND IPM_Completed__c = false'; 
        return Database.getQueryLocator(query);
    } 
    
    global void execute(Database.BatchableContext bC, List<IPM_Milestone__c> milestoneList) {
        Integer dateValue;
        String projectPhase;
        response = IPM_ConstantUtils.BLANK;
        Set<Id> milestoneProjSet = new Set<Id>();
        for(IPM_Milestone__c milestoneProj:milestoneList)
        {
            milestoneProjSet.add(milestoneProj.IPM_Project__c);
        }
        
        Map<Id, IPM_Project__c> mapProjects = new Map<Id, IPM_Project__c>([
        																	SELECT Name,Id, IPM_Project_Type__c, IPM_GateKeeping_Model__c, IPMProject_Span__c,IPM_Phase__c, IPM_CompanyCardText__c 
        																	FROM IPM_Project__c 
        																	where Id IN : milestoneProjSet LIMIT 50000]);
        List<IPM_Project_Resource__c> resourceList = [Select IPM_User__c,IPM_Project__c from IPM_Project_Resource__c 
        where IPM_Role_Type__c =: IPM_ConstantUtils.FUNCTIONAL_ROLE_FINANCE and IPM_Project__c IN: milestoneProjSet LIMIT 50000];
        
        for(IPM_Milestone__c eachMilestone:milestoneList)
        {
	          //Check if milestone is current active milestone of the project 
	          if(Test.isRunningTest()){
	              projectPhase = eachMilestone.IPM_Project__r.IPM_Temporary_Phase__c;
	          } 
	          else {
	              projectPhase = eachMilestone.IPM_Project__r.IPM_Phase__c;
	          }
	          if(projectPhase == eachMilestone.IPM_Phase__c && String.IsNotBlank(String.valueOf(eachMilestone.IPM_Due_Date__c)))
	          {
	             dateValue=Date.valueOf(System.today()).daysBetween(Date.valueOf(eachMilestone.IPM_Due_Date__c));
	              //If milestone due date is today
	              if(dateValue==0)
	               { 
	               		milestoneDueDateToday(eachMilestone,resourceList);  
	               }
	               //If milestone due date is approaching 21 days
	              if(dateValue==IPM_ConstantUtils.maxDueDaysDiffrence && dateValue >IPM_ConstantUtils.minDueDaysDiffrence)
	              {
	             		milestoneDueDateApproaching(eachMilestone,resourceList);
	              }
	              //if the project is driving the milestone, then only send the notification, else ignore.
	            if(IPM_Utils.retrieveProjectType(mapProjects.get(eachMilestone.IPM_Project__c))!=null && IPM_Utils.retrieveProjectType(mapProjects.get(eachMilestone.IPM_Project__c)).Independent_Project__c)
	        	  {
	        	  	  milestoneDueDateIsPassed(eachMilestone,dateValue);
	        	 
		          }
        	}  
        }
        
        try
        {
           update milestonesUpdated; 
           IPM_ChatterUtils.postChatterFeedWithMention(projIdNewProjectsSet, projIdchatterMessageMap, subjectIdMentionIdSetMap );
           response = IPM_ConstantUtils.MAIL_SENT_RESPONSE;
          }catch(System.Exception ex){ // Generalized exception
                    response = ex.getMessage();
                    ExceptionLoggingHelper.createErrorLog(UserInfo.getUserId(),CLASS_NAME,IPM_ConstantUtils.EXECUTE_METHOD,response,ex, IPM_ConstantUtils.ERROR_STR, null, null, null,null);
          }     
    }   

	private static void milestoneDueDateToday(IPM_Milestone__c eachMilestone,List<IPM_Project_Resource__c> resourceList)
	{
		Set<Id> projLeadSet = createProjLeadSet(eachMilestone,resourceList);
	    
	    projIdNewProjectsSet.add(eachMilestone.IPM_Project__c);
	    subjectIdMentionIdSetMap.put(eachMilestone.IPM_Project__c,projLeadSet);
	    projIdchatterMessageMap.put(eachMilestone.IPM_Project__c,IPM_ConstantUtils.IPM_SPACE + IPM_ConstantUtils.PLANNED+eachMilestone.IPM_Name__c+IPM_ConstantUtils.IPM_SPACE+System.Label.IPM_DUE_ON_TODAY+System.Label.IPM_Remember_To_Update);
	              
	}
	
	private static void milestoneDueDateApproaching(IPM_Milestone__c eachMilestone,List<IPM_Project_Resource__c> resourceList)
	{
		Set<Id> projLeadSet = createProjLeadSet(eachMilestone,resourceList);
			
	    projIdNewProjectsSet.add(eachMilestone.IPM_Project__c);
	    subjectIdMentionIdSetMap.put(eachMilestone.IPM_Project__c,projLeadSet);
	    projIdchatterMessageMap.put(eachMilestone.IPM_Project__c,IPM_ConstantUtils.IPM_SPACE+IPM_ConstantUtils.PLANNED+eachMilestone.IPM_Type_of_gate__c+IPM_ConstantUtils.IPM_SPACE+IPM_ConstantUtils.GATE+IPM_ConstantUtils.IPM_SPACE+System.Label.IPM_Due_Date_In_21_days+IPM_ConstantUtils.DUE_DATE_STR2);
	             
	} 
	
	private static void milestoneDueDateIsPassed(IPM_Milestone__c eachMilestone,Integer dateValue)
	{
		//If milestone due date is passed
		if(eachMilestone.IPM_Due_Date__c < System.today() &&  ( dateValue == -1 || math.mod(dateValue,7) == 0 ) && !eachMilestone.IPM_Completed__c )
	      {
	        eachMilestone.IPM_Milestone_Due_Date_In_Past__c = true;
	        eachMilestone.IPM_Project_Leader_Email__c = eachMilestone.IPM_Project__r.IPM_Project_Leader__r.Email;
	        eachMilestone.IPM_Deputy_Project_Leader_Email__c = eachMilestone.IPM_Project__r.Deputy_Project_Leader__r.Email;
	        eachMilestone.IPM_Gatekeeper_Email__c = eachMilestone.IPM_Project__r.IPM_Project_Gatekeeper__r.Email;
	        milestonesUpdated.add(eachMilestone);
	       }
       else if(eachMilestone.IPM_Milestone_Due_Date_In_Past__c)
	       {
	        eachMilestone.IPM_Milestone_Due_Date_In_Past__c = false;
	        milestonesUpdated.add(eachMilestone);
	       }
	}
	
	private static Set<Id> createProjLeadSet(IPM_Milestone__c eachMilestone ,List<IPM_Project_Resource__c> resourceList){
	   
	    Set<Id>projLeadSet = new Set<Id>();
        if(eachMilestone.IPM_Project__r.IPM_Project_Leader__c != null)
        {
              projLeadSet.add(eachMilestone.IPM_Project__r.IPM_Project_Leader__c);
        }
        if(eachMilestone.IPM_Project__r.Deputy_Project_Leader__c != null )      
        {
              projLeadSet.add(eachMilestone.IPM_Project__r.Deputy_Project_Leader__c);
        }
        if(eachMilestone.IPM_Project__r.IPM_Finance_Member__c != null )      
        {
              projLeadSet.add(eachMilestone.IPM_Project__r.IPM_Finance_Member__c);
        }
        if(eachMilestone.IPM_Project__r.IPM_Company_Card__c != NULL && eachMilestone.IPM_Project__r.IPM_Company_Card__r.IPM_Business_Partner__c != null )      
        {
              projLeadSet.add(eachMilestone.IPM_Project__r.IPM_Company_Card__r.IPM_Business_Partner__c);
        }
        for(IPM_Project_Resource__c eachResource:resourceList)
        {   
            if(eachMilestone.IPM_Project__c == eachResource.IPM_Project__c && eachResource.IPM_User__c != null)
            {
                  projLeadSet.add(eachResource.IPM_User__c);
            }
        }     
        
        return projLeadSet;	
	}
	
    global void finish(Database.BatchableContext bC) {
        //sends an email for job status, after the job is completed.
        IPM_Utils.sendApexJobStatusMail(bC);
    }
    
}