src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Resource__c.object
<CustomObject>
    <description>To store the IPM Project Team Members</description>
    <fields>
        <fullName>IPM_Project_Role_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to capture the owner of role in team member</description>
        <label>Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>lookup for IPM project</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Resources</relationshipLabel>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Role__c</fullName>
        <description>Displaying from user record</description>
        <formula>(text(IPM_User__r.IPM_Role__c))</formula>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to IPM User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resource Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IPM_Role__c</fullName>
        <description>to stroe role from AD</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Project Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gate Keeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Leader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IPM_ProjectResourceTriggerHandler.cls
public without sharing class IPM_ProjectResourceTriggerHandler {
    
    private boolean m_isExecuting = false;

    public IPM_ProjectResourceTriggerHandler(boolean isExecuting){
        m_isExecuting = isExecuting;
    }
    
    public void onAfterInsert(IPM_Project_Resource__c[] newProjectResources) {
        
        list<IPM_Project_Resource__c> newPRList = new list<IPM_Project_Resource__c>();
        for(IPM_Project_Resource__c eachPResource : newProjectResources) {
            if(eachPResource.IPM_Project_Role_Owner__c) {
                newPRList.add(eachPResource);
            }
        }
        if(IPM_CheckRecursive.runOnce() && newPRList.size() > 0) {
            IPM_TaskHelper.reAssignFunctionalWiseTasks(newPRList);
        }
        IPM_ChatterFeedHelper.autoFollowTeamMembers(newProjectResources);
    }
    
    public void OnAfterUpdate(IPM_Project_Resource__c[] newProjectResources, Map<Id, IPM_Project_Resource__c> newProjectResourcesMap, 
                                Map<Id, IPM_Project_Resource__c> oldProjectResources) {
        
        list<IPM_Project_Resource__c> newPRList = new list<IPM_Project_Resource__c>();
        for(IPM_Project_Resource__c eachPResource : newProjectResources) {
            IPM_Project_Resource__c oldPR = oldProjectResources.get(eachPResource.Id);
            if(eachPResource.IPM_Project_Role_Owner__c && 
                (eachPResource.IPM_User__c != oldPR.IPM_User__c || eachPResource.IPM_Project_Role_Owner__c != oldPR.IPM_Project_Role_Owner__c)) {
                newPRList.add(eachPResource);
            }
        }
        if(newPRList.size() > 0) {
            IPM_TaskHelper.reAssignFunctionalWiseTasks(newPRList);
        }
    }
    
     @future
    public static void notifyRoleChangeToPLs(Set<Id> userIds) {
        
        IPM_Project_Resource__c[] pResourceList = [SELECT IPM_Project__c, IPM_Role__c, IPM_User__c 
                                                       FROM IPM_Project_Resource__c
                                                       WHERE IPM_User__c IN :userIds];
        memberChangingRole(pResourceList);
    }
    
    public static void memberChangingRole(IPM_Project_Resource__c[] newProjectResources) {
                                        
        Map<Id, IPM_Project_Resource__c[]> pResourceRoleChangedMap = new Map<Id, IPM_Project_Resource__c[]>();
        Set<Id> userIds = new Set<Id>();
        for(IPM_Project_Resource__c eachPResource : newProjectResources) {
            if(!pResourceRoleChangedMap.containsKey(eachPResource.IPM_Project__c)) {
                IPM_Project_Resource__c[] tmpLst = new List<IPM_Project_Resource__c>();
                tmpLst.add(eachPResource);
                pResourceRoleChangedMap.put(eachPResource.IPM_Project__c, tmpLst);
            }else {
                pResourceRoleChangedMap.get(eachPResource.IPM_Project__c).add(eachPResource);
            }
            userIds.add(eachPResource.IPM_User__c);
        }
        system.debug('** pResourceRoleChangedMap : ' + pResourceRoleChangedMap);
        Map<Id, IPM_Project__c> projectMap = IPM_Utils.getProjectDetails(pResourceRoleChangedMap.keySet());
        Map<Id, User> userDetailsMap = IPM_Utils.getUserDetailsMap(userIds);
        Map<Id, String> pResourceDetailsMap = new Map<Id, String>();
        for(Id eachProject : pResourceRoleChangedMap.keySet()) {
            Set<String> contextMsgList = new Set<String>();
            for(IPM_Project_Resource__c eachPResource : pResourceRoleChangedMap.get(eachProject)) {
                String str = ' User : ' + userDetailsMap.get(eachPResource.IPM_User__c).Name + ' New Role : ' + eachPResource.IPM_Role__c;
                contextMsgList.add(str);
            }
            system.debug('** contextMsgList : ' + contextMsgList);
            pResourceDetailsMap.put(eachProject, IPM_Utils.convertSetToString(contextMsgList));
        }
        system.debug('** pResourceDetailsMap : ' + pResourceDetailsMap);
        system.debug('** projectMap : ' + projectMap);
        IPM_ChatterFeedHelper.postChatterUpdateToUser(projectMap, pResourceDetailsMap);
    }
    
    public void onAfterUnDelete(IPM_Project_Resource__c[] newProjectResources) {
        IPM_ChatterFeedHelper.autoFollowTeamMembers(newProjectResources);
    }
    
    public void OnAfterDelete(IPM_Project_Resource__c[] oldProjectResources) {
        IPM_ChatterFeedHelper.autoUnFollowTeamMembers(oldProjectResources);
    }
}