src/objects/IPM_Financial__c.object
<CustomObject>
    <fields>
        <fullName>Financial_External_ID__c</fullName>
        <description>Financial External Id.</description>
        <externalId>true</externalId>
        <label>Financial External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Global_External_Id__c</fullName>
        <description>This field is used to store the Global project external id.</description>
        <formula>IF(NOT(ISBLANK(Parent_Project__c)), Parent_Project__r.IPM_Project_Name__c, IF(NOT(ISBLANK(Regional_Project__c)), Regional_Project__r.IPM_Parent_Project__r.IPM_Project_Name__c, IPM_Project_Rollout__r.IPM_Project__r.IPM_Project_Name__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Global External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_External_Id__c</fullName>
        <description>Regional Project External Id associated with the financial.</description>
        <formula>IF(NOT(ISBLANK(Regional_Project__c)),  Regional_Project__r.IPM_Project_Name__c ,  IPM_Project_Rollout__r.IPM_Rollout_Project__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Regional External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Launch_Date__c</fullName>
        <description>Project Target Launch date.</description>
        <label>Target Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>IPM Financial</label>
    <nameField>
        <displayFormat>FIN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Financials</pluralLabel>
    <recordTypes>
        <fullName>Consolidated</fullName>
        <active>true</active>
        <description>Consolidated Financials</description>
        <label>Consolidated</label>
    </recordTypes>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Financial_Year__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Stores external system record id</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_External_Id__c</fullName>
        <description>Stores related financial record external id</description>
        <formula>IPM_Financial__r.Financial_External_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Financial External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_RecordtypeId__c</fullName>
        <description>Stores related financial record type id</description>
        <formula>IPM_Financial__r.RecordTypeId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Financial RecordtypeId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_External_Id__c</fullName>
        <description>Stores related financial record&apos;s Global project external id.</description>
        <formula>IPM_Financial__r.Global_External_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Global External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Financial__c</fullName>
        <description>Associated financial record</description>
        <label>IPM Financial</label>
        <referenceTo>IPM_Financial__c</referenceTo>
        <relationshipLabel>IPM Financial Years</relationshipLabel>
        <relationshipName>IPM_Financial_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PL_Type__c</fullName>
        <description>To store P &amp; L type</description>
        <label>P&amp;L Type</label>
        <picklist>
            <picklistValues>
                <fullName>Gross</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incremental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Regional_External_Id__c</fullName>
        <description>Stores related financial record&apos;s regional external id</description>
        <formula>IPM_Financial__r.Regional_External_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Regional External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Launch_Date__c</fullName>
        <description>Stores related financial record&apos;s Target Launch date</description>
        <formula>IPM_Financial__r.Target_Launch_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year_Type__c</fullName>
        <description>Stores year type</description>
        <label>Year Type</label>
        <picklist>
            <picklistValues>
                <fullName>Innovation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Calendar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Stores year value</description>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Financial Year</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Financial Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IPMFinancialYearTriggerHandler.cls
public without sharing class IPMFinancialYearTriggerHandler{

    private transient Map<String, IPM_Financial_Year__c> mapUpsertFY;
    private Map<String, IPM_Financial_Year__c> mapAllConsolidatedFinancialYears;

    private Map<String, String> mapGlobalConsolidatedFY;
    private Map<String, String> mapRegionalConsolidatedFY;

    private static String DEFAULT_FINANCIAL_RECORDTYPE;
    private static String CONSOLIDATED_FINANCIAL_RECORDTYPE;

    private static String VOLUME_UNIT_TONS = 'Total Tons';
    private static String VOLUME_UNIT_000_UNITS = 'Total \'000 Units';

    private static String PL_TYPE_GROSS = 'Gross';
    private static String PL_TYPE_INCREMENTAL = 'Incremental';
    private static String YEAR_TYPE_INNOVATION = 'Innovation';
    private static String YEAR_TYPE_CALENDAR = 'Calendar';
    
    private static String TYPE_GLOBAL = 'Global';
    private static String TYPE_REGIONAL = 'Regional';
    private static String TYPE_LOCAL = 'Local';
    
    public void onAfterUpdate(Map<Id, IPM_Financial_Year__c> mapNewFinancialYears, Map<Id, IPM_Financial_Year__c> mapOldFinancialYears){
        DEFAULT_FINANCIAL_RECORDTYPE = Schema.SObjectType.IPM_Financial__c.getRecordTypeInfosByName().get('Default').getRecordTypeId();
        CONSOLIDATED_FINANCIAL_RECORDTYPE = Schema.SObjectType.IPM_Financial__c.getRecordTypeInfosByName().get('Consolidated').getRecordTypeId();
        
        if(DEFAULT_FINANCIAL_RECORDTYPE.length() > 15)
            DEFAULT_FINANCIAL_RECORDTYPE = DEFAULT_FINANCIAL_RECORDTYPE.subString(0,15);

        if(CONSOLIDATED_FINANCIAL_RECORDTYPE.length() > 15)
            CONSOLIDATED_FINANCIAL_RECORDTYPE = CONSOLIDATED_FINANCIAL_RECORDTYPE.subString(0,15);

        mapGlobalConsolidatedFY = new Map<String, String>();
        mapRegionalConsolidatedFY = new Map<String, String>();

        Set<String> setFinancialExternalIds = new Set<String>();

        For(IPM_Financial_Year__c financialYear : mapNewFinancialYears.values()){
            String globalExternalId = financialYear.Global_External_Id__c + '_CONSOLIDATED';
            mapGlobalConsolidatedFY.put(financialYear.Id, globalExternalId);
            setFinancialExternalIds.add(globalExternalId);

            String regionalExternalId = financialYear.Regional_External_Id__c + '_CONSOLIDATED';
            mapRegionalConsolidatedFY.put(financialYear.Id, regionalExternalId);
            setFinancialExternalIds.add(regionalExternalId);
        }

        //Consolidate Financials
        getConsolidatedFinancialYears(setFinancialExternalIds);
        mapUpsertFY = new Map<String, IPM_Financial_Year__c>();
        for(IPM_Financial_Year__c financialYear : mapNewFinancialYears.values()){
            if(financialYear.Financial_RecordtypeId__c == DEFAULT_FINANCIAL_RECORDTYPE){
                consolidateFinancials(financialYear, mapOldFinancialYears.get(financialYear.Id), TYPE_GLOBAL);
                consolidateFinancials(financialYear, mapOldFinancialYears.get(financialYear.Id), TYPE_REGIONAL);
            }
        }

        if(mapUpsertFY.size() > 0)
            Database.upsert(mapUpsertFY.values(), IPM_Financial_Year__c.External_ID__c, false);

    }

    private void getConsolidatedFinancialYears(Set<String> setFinancialExternalIds){
        String queryString = 'SELECT ';
        //IPM Financial
        For (String field : Schema.SObjectType.IPM_Financial_Year__c.fields.getMap().KeySet()){
            if (field != 'Id')
                queryString+= field + ', ';
        }
        queryString+= 'Id FROM IPM_Financial_Year__c WHERE Financial_External_ID__c IN: setFinancialExternalIds';
        
        mapAllConsolidatedFinancialYears = new Map<String, IPM_Financial_Year__c>();
        For(IPM_Financial_Year__c consollidatedFinancialYear : Database.query(queryString))
            mapAllConsolidatedFinancialYears.put(consollidatedFinancialYear.External_ID__c, consollidatedFinancialYear);

    }

    private void consolidateFinancials(IPM_Financial_Year__c newFinancialYear, IPM_Financial_Year__c oldFinancialYear, String consolidationType){
        String newConsolidatedFinExtId;
        String oldConsolidatedFinExtId;
        if(consolidationType == TYPE_GLOBAL){
            newConsolidatedFinExtId = mapGlobalConsolidatedFY.get(newFinancialYear.Id);
            oldConsolidatedFinExtId = mapGlobalConsolidatedFY.get(oldFinancialYear.Id);
        
        } else if(consolidationType == TYPE_REGIONAL){
            newConsolidatedFinExtId = mapRegionalConsolidatedFY.get(newFinancialYear.Id);
            oldConsolidatedFinExtId = mapRegionalConsolidatedFY.get(oldFinancialYear.Id);

        }

        String newConsolidatedFYExtId = getFinancialYearExternalId(newConsolidatedFinExtId, newFinancialYear.Name, newFinancialYear.Year_Type__c, newFinancialYear.PL_Type__c);
        String oldConsolidatedFYExtId = getFinancialYearExternalId(oldConsolidatedFinExtId, oldFinancialYear.Name, oldFinancialYear.Year_Type__c, oldFinancialYear.PL_Type__c);

        IPM_Financial_Year__c newConsolidatedFY = mapAllConsolidatedFinancialYears.get(newConsolidatedFYExtId);
        IPM_Financial_Year__c oldConsolidatedFY = mapAllConsolidatedFinancialYears.get(oldConsolidatedFYExtId);

        if(mapUpsertFY.containsKey(newConsolidatedFYExtId))
            newConsolidatedFY = mapUpsertFY.get(newConsolidatedFYExtId);

        if(mapUpsertFY.containsKey(oldConsolidatedFYExtId))
            oldConsolidatedFY = mapUpsertFY.get(oldConsolidatedFYExtId);
        
        if(newConsolidatedFY == null && newFinancialYear.Year_Type__c == YEAR_TYPE_CALENDAR){
            //Create new Financial Year
            Integer index = Integer.valueOf(newFinancialYear.Name) - oldFinancialYear.Target_Launch_Date__c.year() + 1;
            newConsolidatedFY = new IPM_Financial_Year__c(
                IPM_Financial__r = new IPM_Financial__c(Financial_External_ID__c = newConsolidatedFinExtId),
                External_Id__c = newConsolidatedFYExtId,
                Name = newFinancialYear.Name,
                Year__c = '' + index,
                Year_Type__c = newFinancialYear.Year_Type__c,
                PL_Type__c = newFinancialYear.PL_Type__c
            );
        }

        consolidateFinancialRecord(newFinancialYear, newConsolidatedFY, oldFinancialYear, oldConsolidatedFY);
    }
    
    private void consolidateFinancialRecord(IPM_Financial_Year__c newFinancialYear, IPM_Financial_Year__c newConsolidatedFY, IPM_Financial_Year__c oldFinancialYear, IPM_Financial_Year__c oldConsolidatedFY){
        processConsolidation(newFinancialYear, newConsolidatedFY, oldFinancialYear, oldConsolidatedFY, 'Advertising_Promotions');
        processConsolidation(newFinancialYear, newConsolidatedFY, oldFinancialYear, oldConsolidatedFY, 'Gross_Profit');
        processConsolidation(newFinancialYear, newConsolidatedFY, oldFinancialYear, oldConsolidatedFY, 'Turnover');
        processConsolidation(newFinancialYear, newConsolidatedFY, oldFinancialYear, oldConsolidatedFY, 'Profit_Before_Overheads');
        processVolumeConsolidation(newFinancialYear, newConsolidatedFY, oldFinancialYear, oldConsolidatedFY);
    }

    private void processConsolidation(IPM_Financial_Year__c newFinancialYear, IPM_Financial_Year__c newConsolidatedFY, IPM_Financial_Year__c oldFinancialYear, IPM_Financial_Year__c oldConsolidatedFY, String fieldName){
        Set<String> fieldSufixes = new Set<String>{TYPE_GLOBAL, TYPE_REGIONAL, TYPE_LOCAL};
        Decimal value;
        For(String suffix : fieldSufixes){
            //NEW Consolidated Financial Year
            if(mapUpsertFY.containsKey(newConsolidatedFY.External_ID__c))
                newConsolidatedFY = mapUpsertFY.get(newConsolidatedFY.External_ID__c);
            Object newValueObject = newConsolidatedFY.get(fieldname + '_' + suffix + '__c');
            if(newValueObject == null)
                value = (Decimal) newFinancialYear.get(fieldname + '_' + suffix + '__c');
            else
                value = (Decimal) newConsolidatedFY.get(fieldname + '_' + suffix + '__c') + (Decimal) newFinancialYear.get(fieldname + '_' + suffix + '__c');

            newConsolidatedFY.put(fieldname + '_' + suffix + '__c', value);
            mapUpsertFY.put(newConsolidatedFY.External_ID__c, newConsolidatedFY);

            //OLD Consolidated Financial Year
            if(mapUpsertFY.containsKey(oldConsolidatedFY.External_ID__c))
                oldConsolidatedFY = mapUpsertFY.get(oldConsolidatedFY.External_ID__c);
            value = (Decimal) oldConsolidatedFY.get(fieldname + '_' + suffix + '__c') - (Decimal) oldFinancialYear.get(fieldname + '_' + suffix + '__c');
            oldConsolidatedFY.put(fieldname + '_' + suffix + '__c', value);
            
            mapUpsertFY.put(oldConsolidatedFY.External_ID__c, oldConsolidatedFY);
        }
    }

    private void processVolumeConsolidation(IPM_Financial_Year__c newFinancialYear, IPM_Financial_Year__c newConsolidatedFY, IPM_Financial_Year__c oldFinancialYear, IPM_Financial_Year__c oldConsolidatedFY){
        Set<String> fieldSufixes = new Set<String>{TYPE_GLOBAL, TYPE_REGIONAL, TYPE_LOCAL};
        Decimal value;
        For(String suffix : fieldSufixes){
            String newVolumeUnit = (String) newFinancialYear.get('Volume_Unit_' + suffix + '__c');
            String oldVolumeUnit = (String) oldFinancialYear.get('Volume_Unit_' + suffix + '__c');

            //NEW Consolidated Financial Year
            if(mapUpsertFY.containsKey(newConsolidatedFY.External_ID__c))
                newConsolidatedFY = mapUpsertFY.get(newConsolidatedFY.External_ID__c);
            Object newValueObject = newConsolidatedFY.get('Volume_' + suffix + '__c');
            if(newValueObject == null){
                if((newVolumeUnit == VOLUME_UNIT_TONS) && (oldVolumeUnit == VOLUME_UNIT_TONS)){
                    value = (Decimal) newFinancialYear.get('Volume_' + suffix + '__c');
                    newConsolidatedFY.put('Volume_Tons_' + suffix + '__c', value);
                
                } else if((newVolumeUnit == VOLUME_UNIT_000_UNITS) && (oldVolumeUnit == VOLUME_UNIT_000_UNITS)){
                    value = (Decimal) newFinancialYear.get('Volume_' + suffix + '__c');
                    newConsolidatedFY.put('Volume_' + suffix + '__c', value);

                }else if((newVolumeUnit == VOLUME_UNIT_TONS) && (oldVolumeUnit == VOLUME_UNIT_000_UNITS)){
                    value = (Decimal) newFinancialYear.get('Volume_' + suffix + '__c');
                    newConsolidatedFY.put('Volume_Tons_' + suffix + '__c', value);

                }else if((newVolumeUnit == VOLUME_UNIT_000_UNITS) && (oldVolumeUnit == VOLUME_UNIT_TONS)){
                    value = (Decimal) newFinancialYear.get('Volume_' + suffix + '__c');
                    newConsolidatedFY.put('Volume_' + suffix + '__c', value);

                }
                
            } else {

                if((newVolumeUnit == VOLUME_UNIT_TONS) && (oldVolumeUnit == VOLUME_UNIT_TONS)){
                    value = (Decimal) newConsolidatedFY.get('Volume_Tons_' + suffix + '__c') + (Decimal) newFinancialYear.get('Volume_' + suffix + '__c');
                    newConsolidatedFY.put('Volume_Tons_' + suffix + '__c', value);
                
                }else if((newVolumeUnit == VOLUME_UNIT_000_UNITS) && (oldVolumeUnit == VOLUME_UNIT_000_UNITS)){
                    value = (Decimal) newConsolidatedFY.get('Volume_' + suffix + '__c') + (Decimal) newFinancialYear.get('Volume_' + suffix + '__c');
                    newConsolidatedFY.put('Volume_' + suffix + '__c', value);

                }else if((newVolumeUnit == VOLUME_UNIT_TONS) && (oldVolumeUnit == VOLUME_UNIT_000_UNITS)){
                    value = (Decimal) newConsolidatedFY.get('Volume_Tons_' + suffix + '__c') + (Decimal) newFinancialYear.get('Volume_' + suffix + '__c');
                    newConsolidatedFY.put('Volume_Tons_' + suffix + '__c', value);

                }else if((newVolumeUnit == VOLUME_UNIT_000_UNITS) && (oldVolumeUnit == VOLUME_UNIT_TONS)){
                    value = (Decimal) newConsolidatedFY.get('Volume_' + suffix + '__c') + (Decimal) newFinancialYear.get('Volume_' + suffix + '__c');
                    newConsolidatedFY.put('Volume_' + suffix + '__c', value);

                }
                
            }

            mapUpsertFY.put(newConsolidatedFY.External_ID__c, newConsolidatedFY);

            //OLD Consolidated Financial Year
            if(mapUpsertFY.containsKey(oldConsolidatedFY.External_ID__c))
                oldConsolidatedFY = mapUpsertFY.get(oldConsolidatedFY.External_ID__c);

            if((newVolumeUnit == VOLUME_UNIT_TONS) && (oldVolumeUnit == VOLUME_UNIT_TONS)){
                value = (Decimal) oldConsolidatedFY.get('Volume_Tons_' + suffix + '__c') - (Decimal) oldFinancialYear.get('Volume_' + suffix + '__c');
                oldConsolidatedFY.put('Volume_Tons_' + suffix + '__c', value);

            }else if((newVolumeUnit == VOLUME_UNIT_000_UNITS) && (oldVolumeUnit == VOLUME_UNIT_000_UNITS)){
                value = (Decimal) oldConsolidatedFY.get('Volume_' + suffix + '__c') - (Decimal) oldFinancialYear.get('Volume_' + suffix + '__c');
                oldConsolidatedFY.put('Volume_' + suffix + '__c', value);

            }else if((newVolumeUnit == VOLUME_UNIT_TONS) && (oldVolumeUnit == VOLUME_UNIT_000_UNITS)){
                value = (Decimal) oldConsolidatedFY.get('Volume_' + suffix + '__c') - (Decimal) oldFinancialYear.get('Volume_' + suffix + '__c');
                oldConsolidatedFY.put('Volume_' + suffix + '__c', value);

            }else if((newVolumeUnit == VOLUME_UNIT_000_UNITS) && (oldVolumeUnit == VOLUME_UNIT_TONS)){
                value = (Decimal) oldConsolidatedFY.get('Volume_Tons_' + suffix + '__c') - (Decimal) oldFinancialYear.get('Volume_' + suffix + '__c');
                oldConsolidatedFY.put('Volume_Tons_' + suffix + '__c', value);

            }
            
            mapUpsertFY.put(oldConsolidatedFY.External_ID__c, oldConsolidatedFY);
        }
    }
    
    private String getFinancialYearExternalId(String financialExternalId, String yearName, String yearType, String plType){
        return financialExternalId + '_' + yearName + '_' + yearType + '_' + plType;
    }
}