src/objects/IPM_Bosscard__c.object
<CustomObject>
    <description>This object is created to hold the Bosscard Details</description>
    <fields>
        <fullName>IPM_Assumptions__c</fullName>
        <description>This field is used to capture  the assumption content entered by users on the BOSSCARD creation screen.</description>
        <label>Assumptions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Background__c</fullName>
        <description>This field is used to capture  the Background content entered by users on the BOSSCARD creation screen.</description>
        <label>Background</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_BosscardIdea__c</fullName>
        <description>To Be Deleted</description>
        <label>Idea</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IPM_BosscardName__c</fullName>
        <description>To store the name of the BOSSCARD.</description>
        <label>Name</label>
        <length>14</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IPM_Bosscard_Logo_Id__c</fullName>
        <description>To store the id from standard  document object for the logo.</description>
        <label>Bosscard Logo Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Bosscard_Logo__c</fullName>
        <description>To store the logo of BOSSCARD</description>
        <label>Bosscard Logo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Brand_Positioning__c</fullName>
        <description>To store the brand positioning value</description>
        <label>Brand Positioning</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Brand__c</fullName>
        <description>To be Deleted.</description>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Constraints__c</fullName>
        <description>This field is used to capture the  Constraints content entered by users on the BOSSCARD creation screen.</description>
        <label>Constraints</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Consumer_Need__c</fullName>
        <description>This field is used to capture the  Consumer Need content entered by users on the BOSSCARD creation screen.</description>
        <label>Consumer Need</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Deliverables__c</fullName>
        <description>This field is used to capture the deliverables content entered by users on the BOSSCARD creation screen.</description>
        <label>Deliverables</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Gate_Keeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To capture the gate keeper user name</description>
        <label>Gate Keeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Bosscard</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Opportunity__c</fullName>
        <description>This field is used to capture the Opportunity content entered by users on the BOSSCARD creation screen.</description>
        <inlineHelpText>Opportunity Information</inlineHelpText>
        <label>Opportunity</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Potential_Business_Opportunity__c</fullName>
        <description>This field is used to capture the Potential Business Opportunity content entered by users on the BOSSCARD creation screen.</description>
        <label>Potential Business Opportunity</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Resources__c</fullName>
        <description>This field is used to capture the Resources content entered by users on the BOSSCARD creation screen.</description>
        <label>Resources</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Scope__c</fullName>
        <description>This field is used to capture the Scope content entered by users on the BOSSCARD creation screen.</description>
        <label>Scope</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Sustainibility__c</fullName>
        <description>This field is used to capture the Sustainability content entered by users on the BOSSCARD creation screen.</description>
        <label>Sustainability</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Target_Launch_Date__c</fullName>
        <description>to specify the target launch date by Project Leaders during the time of BOSSCARD creation.</description>
        <label>Target Launch Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>IPM Bosscard</label>
    <nameField>
        <label>IPM Bosscard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Bosscard</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_Bosscard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Bosscard.</description>
        <label>Bosscard</label>
        <referenceTo>IPM_Bosscard__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Brand_Positioning__c</fullName>
        <description>To capture the brand of product for the project.</description>
        <label>Brand Positioning</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Brand__c</fullName>
        <description>To capture the brand.</description>
        <label>IPM_Brand</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Complexity__c</fullName>
        <description>To capture the complexity of the project.</description>
        <label>Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>To capture the GK model</description>
        <label>IPM GateKeeping Model</label>
        <picklist>
            <picklistValues>
                <fullName>CCVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCLT Leader &amp; CCVP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Target_Launch_Date__c</fullName>
        <description>The target launch date of the project.</description>
        <label>Target Launch Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IPM_Brand_Positioning__c</fullName>
        <label>Brand Positioning</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IPM_PrintBosscardPDFController_Test.cls
@isTest
public class IPM_PrintBosscardPDFController_Test {
public static IPM_Project__c project;
public static IPM_Bosscard__c boss=new IPM_Bosscard__c();
static testMethod void initializeData(){
project=new IPM_Project__c();


project.Name='TestComments45';
project.IPM_Phase__c='Ideas';
project.IPM_Complexity__c='Full';
project.IPM_GateKeeping_Model__c='Both'; 
insert project;

//boss.Name='abc';
         boss.IPM_BosscardName__c='abc';
         //boss.IPM_Bosscard_Logo_Id__c=
         boss.IPM_Target_Launch_Date__c='06/06/2015';
         boss.IPM_Bosscard_Logo__c='sf';
         boss.IPM_BosscardIdea__c='dfdsf';
         //boss.IPM_Gate_Keeper__c='''
         //boss.IPM_Gate_Keeper__r.Name
         boss.IPM_Brand__c='sdf';
         boss.IPM_Assumptions__c='df';
         boss.IPM_Background__c='dfd';
         boss.IPM_Constraints__c='fdf';
         boss.IPM_Deliverables__c='fdfg';
         boss.IPM_Opportunity__c='gdfg';
         boss.IPM_Potential_Business_Opportunity__c='dfg';
         boss.IPM_Consumer_Need__c='fgfd';
         boss.IPM_Resources__c='gfd';
         boss.IPM_Brand_Positioning__c='fgfdg';
         boss.IPM_Scope__c='fgf';
         boss.IPM_Sustainibility__c='3';
          insert boss;

      

}


 
     
     static testMethod void dotest()
     {
     initializeData();
          PageReference pRef = new PageReference('/apex/IPM_PDocumentTriggerHandler?id='+boss.Id);
         Test.setCurrentPage(pRef);
         
        
         IPM_PrintBosscardPDFController ipmPD=new IPM_PrintBosscardPDFController();
        
         
     }
}