src/objects/IPM_Financial__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Parent associated with financial</description>
        <label>Parent Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Financials (Consolidated)</relationshipLabel>
        <relationshipName>IPM_Financials_Consolidated</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Financial</label>
    <nameField>
        <displayFormat>FIN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Financials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Milestone__c.object
<CustomObject>
    <description>This object is used to capture Milestone Dates</description>
    <fields>
        <fullName>IPM_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent master milestone lookup.</description>
        <label>IPM Milestone</label>
        <referenceTo>IPM_Milestone__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>phase of milestone.</description>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Launch Evaluation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>IPM Project Master data</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Milestone</label>
    <nameField>
        <label>IPM Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related company card.</description>
        <label>IPM Company Card</label>
        <referenceTo>IPM_Company_Card__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Complexity__c</fullName>
        <description>To capture the complexity of the project.</description>
        <label>Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>To capture the GK model</description>
        <label>IPM GateKeeping Model</label>
        <picklist>
            <picklistValues>
                <fullName>CCVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCLT Leader &amp; CCVP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document__c.object
<CustomObject>
    <description>THis is used in IPM to store Project documents</description>
    <fields>
        <fullName>IPM_GateDocuments__c</fullName>
        <description>To capture gate document name</description>
        <label>IPM_GateDocuments</label>
        <picklist>
            <picklistValues>
                <fullName>Charter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Design Lock</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>Relation to the Project Object</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Documents</relationshipLabel>
        <relationshipName>Project_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Project Document</label>
    <nameField>
        <label>Project Document Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document_Section__c.object
<CustomObject>
    <description>To be used in IPM project to store Gate Document Sections. It refers to the IPM Section object to pick what section/subsection it needs.</description>
    <fields>
        <fullName>IPM_Project_Document__c</fullName>
        <description>Relationship to Project Document</description>
        <label>IPM Project Document</label>
        <referenceTo>IPM_Project_Document__c</referenceTo>
        <relationshipLabel>IPM Project Document Sections</relationshipLabel>
        <relationshipName>IPM_Project_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Name__c</fullName>
        <description>Contains section name</description>
        <label>Section Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Sequence__c</fullName>
        <description>To display section sequence number</description>
        <formula>IPM_Section__r.IPM_Section_Sequence__c</formula>
        <label>IPM_Section_Sequence</label>
        <type>Text</type>
    </fields>
    <label>IPM Project Document Section</label>
    <nameField>
        <label>Section Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Document Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Questionnaire__c.object
<CustomObject>
    <description>Object to store all questions related to POS and RQS</description>
    <fields>
        <fullName>IPM_Active_RQS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Based on the POS score capture which RQS question to be active for a Project</description>
        <label>IPM Active RQS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Is_Added_Question__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To capture if the Questions are added</description>
        <label>IPM Is Added Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Document_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To capture the corresponding section name for the Risk and OTIF based questions</description>
        <label>IPM Project Document Section</label>
        <referenceTo>IPM_Project_Document_Section__c</referenceTo>
        <relationshipLabel>IPM Questionnaires</relationshipLabel>
        <relationshipName>IPM_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>Detail to to the related Project</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Questionnaires</relationshipLabel>
        <relationshipName>IPM_Questionnaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_RQS_Gate_Type__c</fullName>
        <description>To choose the gate type for the questions. Will be used in mapping the active questions from the custom settings</description>
        <label>IPM RQS Gate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Charter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Score__c</fullName>
        <description>To capture the score against each question for both POS and RQS</description>
        <label>IPM Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IPM_Sequence_Number__c</fullName>
        <description>To capture the sequence Number of a Question</description>
        <label>IPM Sequence Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IPM Questionnaire</label>
    <nameField>
        <displayFormat>IQ-{0000}</displayFormat>
        <label>IPM Questionnaire Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Task__c.object
<CustomObject>
    <fields>
        <fullName>IPM_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User to whom the task is assigned</description>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>Field for the phase of the task</description>
        <label>Phase</label>
        <picklist>
            <controllingField>IPM_Type_of_Gate__c</controllingField>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Launch Evaluation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Document_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The project document section for which the task is created</description>
        <label>IPM Project Document Section</label>
        <referenceTo>IPM_Project_Document_Section__c</referenceTo>
        <relationshipLabel>IPM Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>The project for which the task is created</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Task_Complexity__c</fullName>
        <description>The complexity of the task</description>
        <label>Task Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Task</label>
    <nameField>
        <label>Task ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IPM_GateDocumentRiskManagement_Test.cls
/**
* @author       Cognizant 
* @date         11/08/2015
* @description  This class is used to test the functionality of IPM_GateDocumentRiskManagement class 
*/
@isTest
public class IPM_GateDocumentRiskManagement_Test{

    public static IPM_Project__c project;// Project object initialization
    public static IPM_Project_Document__c projDoc;
    public static List<IPM_Project_Document__c> projDocList=new List<IPM_Project_Document__c>();
    private static List<IPM_Project__c>projectList=new list<IPM_Project__c>();
    public static IPM_GateDocumentRiskManagement ipm_gateRiskManage;
    public static List<IPM_Questionnaire__c> quesList;
    private static final string TEST_COMMENTS_STR='TestComments1';
    private static final string PROJECT_DOC_CREATED_STR='Project Document created';
    public static PageReference  pRef;
    public static List<IPM_Project__c>projectListObj=new List<IPM_Project__c>();
    public static List<IPM_Project__c> projlList=new List<IPM_Project__c>();
    public static List<IPM_Project_Document_Section__c>projectDocSecListObj=new List<IPM_Project_Document_Section__c>();
    public static User globalUser;
    public static User stdUserForRiskMang;

    /*************************************************************************************************************************
    * @description Test Data
    */
    @testSetup static void initializeData(){
        
        System.runAs(IPM_TestFactory_Helper.createUserAdmin(true))
        {
            // user has to be created as system admin 
            stdUserForRiskMang= IPM_TestFactory_Helper.createIPMPlatformProfileUser('');
        }       
        
        List<User>userLists=[SELECT id FROM user WHERE id=:stdUserForRiskMang.id LIMIT 1];
        System.AssertEquals(userLists[0].id, stdUserForRiskMang.id,'user id is:'+userLists[0].id);//positive test
        
        // Create Company Card information 
        IPM_Company_Card__c globalCompanyCard = IPM_TestFactory_Helper.createGlobalCompanyCard(false);
        IPM_Company_Card__c regionalCompanyCard = IPM_TestFactory_Helper.createRegionalCompanyCard(false);
        IPM_Company_Card__c localCompanyCard = IPM_TestFactory_Helper.createLocalCompanyCard(false);
        
        List<IPM_Company_Card__c> companyCardList = new List<IPM_Company_Card__c>{globalCompanyCard,regionalCompanyCard,localCompanyCard};
        insert companyCardList;
        List<IPM_Company_Card__c>comList=[select Id from IPM_Company_Card__c where Id=:companyCardList[0].Id limit 1];
        System.assertEquals(comList[0].Id,companyCardList[0].Id,'company card inserted');
        
        IPM_TestFactory_Helper.getProjectMasterData();
        projectList = IPM_TestFactory_Helper.projectSetUp(1,stdUserForRiskMang);
        System.runAs(stdUserForRiskMang) {
            insert projectList;
            
            project=projectList[0];
            List<IPM_Project__c> projlList1=[SELECT ID,Name,IPM_Phase__c,IPM_Complexity__c,IPM_GateKeeping_Model__c FROM IPM_Project__c WHERE ID=:project.ID LIMIT 1];
            System.assertEquals(projlList1[0].Name,TEST_COMMENTS_STR,'project name');//positive test
        }
    }
    
    
    /*************************************************************************************************************************
    * @description Test Data
    */
    static void initializeTestMethodData(){
        
        Set<String> projectNameSet = new Set<String>{TEST_COMMENTS_STR};
        globalUser = [Select Id,LastName from User where LastName='PLATFORM_USER' limit 1]; 
        
        system.runAs(globalUser){
            projectListObj = [Select Id, Name, (Select Id,IPM_GateDocuments__c from Project_Documents__r),(Select Id from IPM_Financials_Consolidated__r ),
            (Select Id,Name,IPM_Task_Complexity__c from Tasks__r),(Select Id,Name from IPM_Milestones__r),(select ID,IPM_Project__c from IPM_Questionnaires__r)
            from IPM_Project__c where Name in:projectNameSet];
            project=projectListObj[0];
            projlList=[SELECT ID,Name,IPM_Phase__c,IPM_Complexity__c,IPM_GateKeeping_Model__c FROM IPM_Project__c WHERE ID=:projectListObj[0].ID LIMIT 1];
            System.assertEquals(projlList[0].id,project.id);//positive test
            for(IPM_Project__c projectObj : projectListObj) {
                projDocList = projectObj.Project_Documents__r;
                quesList=projectObj.IPM_Questionnaires__r;
                System.assertEquals(projDocList[0].IPM_GateDocuments__c,IPM_ConstantUtils.CHARTER_GATE,PROJECT_DOC_CREATED_STR);
            }
            projectDocSecListObj = [Select Id,IPM_Section_Name__c,IPM_Section_Sequence__c,IPM_Project_Document__c from IPM_Project_Document_Section__c 
            where IPM_Project_Document__c=:projDocList[0].Id];
            system.assertEquals(projectDocSecListObj[0].IPM_Project_Document__c,projDocList[0].Id);
            
            ipm_gateRiskManage=new IPM_GateDocumentRiskManagement();
            
        }
    }
    
    
    /*************************************************************************************************************************
    * @description Running Test Script
    */
    static testMethod void saveScoreTest(){
        initializeTestMethodData();
        test.startTest();
        system.runAs(globalUser){
            quesList[0].RecordTypeId=Schema.SObjectType.IPM_Questionnaire__c.RecordTypeInfosByName.get(IPM_ConstantUtils.POS_QUESTIONNAIRE_RECORDTYPE).RecordTypeId;
            update quesList[0];
            ipm_gateRiskManage.projectId=projectListObj[0].Id;
            ipm_gateRiskManage.qId=quesList[0].Id;
            IPM_GateDocumentRiskManagement.questions=new List<IPM_Questionnaire__c>();
            IPM_GateDocumentRiskManagement.questionsForProject=new List<IPM_Questionnaire__c>();
            IPM_GateDocumentRiskManagement.questionsForProject.add(quesList[0]);
            IPM_GateDocumentRiskManagement.questions.add(quesList[0]);
            ipm_gateRiskManage.getRecords();
            ipm_gateRiskManage.score=5;
            ipm_gateRiskManage.saveScore();
            List<IPM_Questionnaire__c>quesListObj=[select IPM_Score__c from IPM_Questionnaire__c where Id=:ipm_gateRiskManage.posQuestionsList[0].Id];
            System.assertEquals(quesListObj[0].IPM_Score__c,ipm_gateRiskManage.score,'score saved');
            test.stopTest();
        }
    }
    
    /*************************************************************************************************************************
* @description Running Test Script
*/ 
    static testMethod void getRecordsTest(){
        initializeTestMethodData();
        test.startTest();
        system.runAs(globalUser){
            quesList[0].RecordTypeId=Schema.SObjectType.IPM_Questionnaire__c.RecordTypeInfosByName.get(IPM_ConstantUtils.POS_QUESTIONNAIRE_RECORDTYPE).RecordTypeId;
            update quesList[0];
            ipm_gateRiskManage.projectId=projectListObj[0].Id;
            ipm_gateRiskManage.qId=quesList[0].Id;
            ipm_gateRiskManage.getRecords();  
            quesList[0].RecordTypeId=Schema.SObjectType.IPM_Questionnaire__c.RecordTypeInfosByName.get(IPM_ConstantUtils.RQS_QUESTIONNAIRE_RECORDTYPE).RecordTypeId;
            quesList[0].IPM_Active_RQS__c=true;
            quesList[0].IPM_RQS_Gate_Type__c=IPM_ConstantUtils.CHARTER_GATE;
            update quesList[0];
            ipm_gateRiskManage.projDocType=IPM_ConstantUtils.CHARTER_GATE;
            ipm_gateRiskManage.getRecords(); 
            ipm_gateRiskManage.projDocType=IPM_ConstantUtils.CONTRACT_GATE;
            ipm_gateRiskManage.getRecords(); 
            quesList[0].IPM_Active_RQS__c=false;
            quesList[0].IPM_Is_Added_Question__c=false;
            update quesList[0];
            ipm_gateRiskManage.getPOSList();
            ipm_gateRiskManage.generateMitigationPlan();
            ipm_gateRiskManage.getRecords(); 
            List<IPM_Questionnaire__c>quesListObj=[SELECT Id,IPM_Is_Added_Question__c FROM IPM_Questionnaire__c where Id=:ipm_gateRiskManage.questionsList[0].Id];
            System.assertEquals(quesListObj[0].IPM_Is_Added_Question__c,false,'records retrieved');
            test.stopTest();
        }
    }

    
    /*************************************************************************************************************************
* @description Running Test Script
*/ 
    static testMethod void saveRQSScoreTest(){
        initializeTestMethodData();
        test.startTest();
        system.runAs(globalUser){
            ipm_gateRiskManage.qId=quesList[0].Id;
            ipm_gateRiskManage.saveRQSScore();
            List<IPM_Questionnaire__c>quesListObj=[SELECT Id,IPM_Score__c,IPM_Is_Added_Question__c FROM IPM_Questionnaire__c where Id=:ipm_gateRiskManage.question.Id];
            System.assertEquals(quesListObj[0].IPM_Score__c,ipm_gateRiskManage.score,'score saved');
            test.stopTest();
        }
    }
    
    /*************************************************************************************************************************
* @description Running Test Script
*/ 
    static testMethod void proceedTest(){
        initializeTestMethodData();
        test.startTest();
        system.runAs(globalUser){
            quesList[0].RecordTypeId=Schema.SObjectType.IPM_Questionnaire__c.RecordTypeInfosByName.get(IPM_ConstantUtils.POS_QUESTIONNAIRE_RECORDTYPE).RecordTypeId;
            quesList[0].IPM_Score__c = IPM_ConstantUtils.POS_QUESTIONNAIRE_SCORE;
            update quesList[0];
            ipm_gateRiskManage.projectId=projectListObj[0].Id;
            ipm_gateRiskManage.rqsSeqActiveNumberCharter=new List<String>();
            ipm_gateRiskManage.rqsSeqActiveNumberCharter.add('1');
            ipm_gateRiskManage.rqsSeqActiveNumberContract=new List<String>();
            ipm_gateRiskManage.rqsSeqActiveNumberContract.add('2');
            ipm_gateRiskManage.proceed();
            ipm_gateRiskManage.projDocType=IPM_ConstantUtils.CHARTER_GATE;
            quesList[0].RecordTypeId=Schema.SObjectType.IPM_Questionnaire__c.RecordTypeInfosByName.get(IPM_ConstantUtils.RQS_QUESTIONNAIRE_RECORDTYPE).RecordTypeId;
            quesList[0].IPM_Score__c = IPM_ConstantUtils.POS_QUESTIONNAIRE_SCORE;
            quesList[0].IPM_Sequence_Number__c=1;
            update quesList[0];
            ipm_gateRiskManage.proceed();
            quesList[0].IPM_Sequence_Number__c=2;
            update quesList[0];
            ipm_gateRiskManage.proceed();
            List<IPM_Questionnaire__c>quesListObj=[SELECT Id FROM IPM_Questionnaire__c where IPM_Project__c =:ipm_gateRiskManage.projectId limit 1];
            System.assertEquals(quesListObj[0].Id,quesList[0].Id,'record is there so we can proceed');
            test.stopTest();
            
        }
    }
    
    /*************************************************************************************************************************
* @description Running Test Script
*/ 
    static testMethod void addQuestionTest(){
        initializeTestMethodData();
        test.startTest();
        system.runAs(globalUser){
            ipm_gateRiskManage=new IPM_GateDocumentRiskManagement();
            ipm_gateRiskManage.addQuestion();
            ipm_gateRiskManage.question.IPM_Question__c=null;
            ipm_gateRiskManage.addQuestion();
            ipm_gateRiskManage.question.IPM_Question__c='abc';
            ipm_gateRiskManage.question.IPM_RQS_Question_Type__c='Consumer';
            ipm_gateRiskManage.addQuestion();
            List<IPM_Questionnaire__c>quesListObj=[SELECT Id,IPM_RQS_Gate_Type__c FROM IPM_Questionnaire__c where Id=:ipm_gateRiskManage.question.Id limit 1];
            System.assertEquals(quesListObj.size(),0,'clear view state');
            test.stopTest();
            
        }
    }
    
    /*************************************************************************************************************************
* @description Running Test Script
*/ 
    static testMethod void deleteQuestionTest(){
        initializeTestMethodData();
        test.startTest();
        system.runAs(globalUser){
            ipm_gateRiskManage.qId=quesList[0].Id;
            ipm_gateRiskManage.stayRQSPage();
            ipm_gateRiskManage.changeQuestionView();
            ipm_gateRiskManage.cancelQuestion();
            ipm_gateRiskManage.backToPos();
            ipm_gateRiskManage.deleteQuestion();
            List<IPM_Questionnaire__c>quesListObj=[SELECT Id FROM IPM_Questionnaire__c WHERE Id=:ipm_gateRiskManage.qId];
            System.assertEquals(quesListObj.size(),0,'record deleted');
            test.stopTest();
        }
    }
}