src/objects/IPM_OTIF_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contents of OTIF Status for Gate Documents</description>
    <fields>
        <fullName>IPM_Section_Number__c</fullName>
        <description>The section number related to the OTIF question</description>
        <label>IPM Section Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>IPM OTIF Status</label>
</CustomObject>

src/objects/IPM_Project_Document_Section__c.object
<CustomObject>
    <description>To be used in IPM project to store Gate Document Sections. It refers to the IPM Section object to pick what section/subsection it needs.</description>
    <fields>
        <fullName>IPM_Section_Name__c</fullName>
        <description>Contains section name</description>
        <label>Section Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Number__c</fullName>
        <description>To capture section number</description>
        <formula>VALUE(IPM_Section__r.IPM_Section_Sequence__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IPM Section Number</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Sequence__c</fullName>
        <description>To display section sequence number</description>
        <formula>IPM_Section__r.IPM_Section_Sequence__c</formula>
        <label>IPM_Section_Sequence</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Type__c</fullName>
        <description>To describe the type of section</description>
        <label>Section Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Static Table</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project Document Section</label>
    <nameField>
        <label>Section Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Document Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document_Section_Content__c.object
<CustomObject>
    <description>This is used in IPM to hold section contents</description>
    <fields>
        <fullName>IPM_OTIF_HelpText_Amber__c</fullName>
        <description>Holds the value for Amber helptext</description>
        <label>IPM OTIF HelpText Amber</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_HelpText_Green__c</fullName>
        <description>Hold the helptext for Green</description>
        <label>IPM OTIF HelpText Green</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_HelpText_NA__c</fullName>
        <description>Holds the helptext for NA</description>
        <label>IPM OTIF HelpText NA</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_HelpText_Red__c</fullName>
        <description>Holds the help text from custom settings</description>
        <label>IPM OTIF HelpText Red</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_Measure__c</fullName>
        <description>contains otif measure</description>
        <label>IPM OTIF Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_No_of_Status__c</fullName>
        <description>contains no of status</description>
        <label>IPM_OTIF_No of Status</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_Responsibility__c</fullName>
        <description>contains otif responsbility</description>
        <label>IPM OTIF Responsibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_Sequence__c</fullName>
        <description>TO capture the OTIF questions Sequence</description>
        <label>IPM OTIF Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_Status__c</fullName>
        <description>contains otif status</description>
        <label>IPM OTIF Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Document_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to project document section</description>
        <label>IPM Project Document Section</label>
        <referenceTo>IPM_Project_Document_Section__c</referenceTo>
        <relationshipLabel>IPM Project Document Section Contents</relationshipLabel>
        <relationshipName>IPM_Section_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Id__c</fullName>
        <description>To store the ID of the related section used for re-direction</description>
        <label>IPM Section Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Name__c</fullName>
        <description>To store the Name of the Related Section for OTIF</description>
        <label>IPM Section Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Number__c</fullName>
        <description>To hold the related sequence number</description>
        <label>IPM Section Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_type__c</fullName>
        <description>to store section type</description>
        <label>Section Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Static Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamic Complex Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamic Static Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Parameters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project Document Section Content</label>
    <nameField>
        <displayFormat>SecCon-{0000}</displayFormat>
        <label>Section Content Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Document Section Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IPM_OTIFStatusController.cls
public class IPM_OTIFStatusController
{
    public Id projDocSecId;
    public ID getprojDocSecId(){ return projDocSecId; }
        public void setprojDocSecId (ID p){
            projDocSecId= p;
            showSectionContent();
        }
    public Id secConId{get; set;}
    public Boolean edit{get; set;}
    public string status{get; set;}
    public List<IPM_Project_Document_Section_Content__c> secConList{get; set;}
    public IPM_Project_Document_Section_Content__c secCon{get; set;}
    public boolean Iseditable{get;set;}
    public ID projectId{get;set;}
    public IPM_Project_Document_Section__c projDocSec{get;set;}
    public String type{get; set;}
    public void showSectionContent()
    {
        projectId=ApexPages.currentPage().getParameters().get('Id');
        System.debug(projDocSecId+'Before Error');
        projDocSec=[Select Id,IPM_Section_Sequence__c from IPM_Project_Document_Section__c where Id=:projDocSecId];
        System.debug(type+'OTIF Type');
        if(type=='Table')
            secConList=[Select Id,IPM_OTIF_No_of_Status__c,IPM_OTIF_Measure__c,IPM_OTIF_Responsibility__c,IPM_OTIF_Status__c,IPM_Project_Document_Section__c,IPM_Section_type__c,IPM_OTIF_HelpText_Red__c,IPM_OTIF_HelpText_NA__c,IPM_OTIF_HelpText_Green__c,IPM_OTIF_HelpText_Amber__c,IPM_Section_Number__c,IPM_OTIF_Sequence__c,IPM_Section_Id__c,IPM_Section_Name__c from IPM_Project_Document_Section_Content__c where IPM_Project_Document_Section__c=:projDocSecId order by IPM_OTIF_Sequence__c asc];
        else if(type=='Section')
            secConList=[Select Id,IPM_OTIF_No_of_Status__c,IPM_OTIF_Measure__c,IPM_OTIF_Responsibility__c,IPM_OTIF_Status__c,IPM_Project_Document_Section__c,IPM_Section_type__c,IPM_OTIF_HelpText_Red__c,IPM_OTIF_HelpText_NA__c,IPM_OTIF_HelpText_Green__c,IPM_OTIF_HelpText_Amber__c,IPM_Section_Number__c,IPM_OTIF_Sequence__c,IPM_Section_Id__c,IPM_Section_Name__c from IPM_Project_Document_Section_Content__c where IPM_Section_Id__c=:projDocSecId order by IPM_OTIF_Sequence__c asc];     
    }
    public pageReference updateOTIFStatus()
    {
        secCon=[Select Id,IPM_OTIF_No_of_Status__c,IPM_OTIF_Measure__c,IPM_OTIF_Responsibility__c,IPM_OTIF_Status__c,IPM_Project_Document_Section__c,IPM_Section_type__c,IPM_OTIF_HelpText_Red__c,IPM_OTIF_HelpText_NA__c,IPM_OTIF_HelpText_Green__c,IPM_OTIF_HelpText_Amber__c,IPM_Section_Id__c,IPM_Section_Name__c from IPM_Project_Document_Section_Content__c where Id=:secConId];
        secCon.IPM_OTIF_Status__c=status;
        update secCon;
        showSectionContent();
        return null;     
    }
}