src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_Complexity__c</fullName>
        <description>To capture the complexity of the project.</description>
        <label>Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>To capture the GK model</description>
        <label>IPM GateKeeping Model</label>
        <picklist>
            <picklistValues>
                <fullName>CCVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCLT Leader &amp; CCVP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/mdm_Geography__c.object
<CustomObject>
    <description>MDM - mdm_Geography__c</description>
    <fields>
        <fullName>Country_Cluster__c</fullName>
        <label>Country Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Unilever Geography</label>
    <nameField>
        <label>Unilever Geography   Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unilever Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IPM_GeoWrapper_Test.cls
@isTest
public class IPM_GeoWrapper_Test {
public static IPM_Project__c project;
public static mdm_Geography__c geo=new mdm_Geography__c();

static testMethod void initializeData(){
project=new IPM_Project__c();


project.Name='TestComments';
project.IPM_Phase__c='Ideas';
project.IPM_Complexity__c='Full';
project.IPM_GateKeeping_Model__c='Both'; 
insert project;
 
 geo.Name='Name';
 geo.Country_Cluster__c='con';
 insert geo;

}


 
  
     static testMethod void dotest()
     {
     initializeData();
          PageReference pRef = new PageReference('/apex/IPM_GeoWrapper?id='+project.Id);
         Test.setCurrentPage(pRef);
         
          // ApexPages.StandardController sc1= new ApexPages.StandardController(proTask1);
         IPM_GeoWrapper ipmGeo=new IPM_GeoWrapper();
         list<mdm_Geography__c> cS=new list<mdm_Geography__c>();
        
         IPM_GeoWrapper.mco m=new IPM_GeoWrapper.mco(geo.Name,cs);
         list<IPM_GeoWrapper.mco> mS=new list<IPM_GeoWrapper.mco>();
         //ms.add(geo.Name);
         IPM_GeoWrapper.clusterMCO cm=new IPM_GeoWrapper.clusterMCO('abc',ms);
         
       list<IPM_GeoWrapper.clusterMCO> LClusMco=new list<IPM_GeoWrapper.clusterMCO>();
       LClusMco=ipmGeo.getclusterMCOWrapper();
         
     
         
     }
}