src/objects/IPM_Financial__c.object
<CustomObject>
    <fields>
        <fullName>IPM_BD_BB_Feedback__c</fullName>
        <description>captures the BD BB Feedback</description>
        <label>IPM BD-BB Feedback</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IPM_Business_Case_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To capture if BB is confirming the Local Business Case</description>
        <label>Business Case Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Country_Feedback__c</fullName>
        <description>To Capture the Feedback of BB</description>
        <label>Country Feedback</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Local_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Local Project associated with the financial.</description>
        <label>Local Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Financials (Local)</relationshipLabel>
        <relationshipName>IPM_Financials_Local</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Misaligned__c</fullName>
        <description>This shows the misalignment between regional and local business case.</description>
        <formula>IF(
( Volume_Unit_Difference__c +  
 NPV_Difference__c +
 IRR_Difference__c +
 Payback_Difference__c +
 CAPEX_Difference__c +
 BIC_Difference__c +
 Total_FY_Difference__c ) &gt; 0, TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Misaligned</label>
        <type>Checkbox</type>
    </fields>
    <label>IPM Financial</label>
    <nameField>
        <displayFormat>FIN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Financials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>Deputy_Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user.</description>
        <label>Deputy Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPMProject_Span__c</fullName>
        <description>To capture the span of project.</description>
        <label>Project Span</label>
        <picklist>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Parent_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To Capture Parent Project based on region and country rollouts</description>
        <label>IPM Parent Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user in this case the project leader.</description>
        <label>Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Name__c</fullName>
        <description>To store the name of the project.</description>
        <externalId>true</externalId>
        <inlineHelpText>Project Name is mandatory</inlineHelpText>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IPM_Target_Launch_Dates__c</fullName>
        <description>To capture the target launch date of the project.</description>
        <label>IPM Target Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Archieved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO indicate if the IPM NG Project Is Archieved</description>
        <label>Is Archived</label>
        <type>Checkbox</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Resource__c.object
<CustomObject>
    <description>To store the IPM Project Team Members</description>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>lookup for IPM project</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Resources</relationshipLabel>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Role_Type__c</fullName>
        <description>Store role type</description>
        <label>IPM Role Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to IPM User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resource Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IPM_BCCController.cls
/************************************************************************
    @Description : This class is used for business case functionality
    @Created Date: 15/04/2014
    @Author: Cognizant
    @Referenced: IPM_Bcc_Document page
************************************************************************/
    
public with sharing class IPM_BCCController extends IPM_ProjectIntermediateController { 
          
    //public IPM_Project__c project{get; set;} //used to store query result from IPM_Project__c object 
    public IPM_Financial__c finance{get; set;} //used to store query result from IPM_Financial__c object 
    public string projectId{get; set;} //used to store current project id
    public Boolean saveMsg{get; set;} //true if we want to show save message to VF page
    public List<IPM_Project__c> projList{get; set;} //Not used
    public Boolean tldAlignment{get; set;} //true if we want to aligned output text
    public Boolean isEditable{get;set;}//used for security 
    public Boolean isPDFDownload{get;set;}//used for security 
    private static final string CLASS_NAME = 'IPM_BCCController';

    /************************************************************************
    @Description : This is the constructor for the class
    ************************************************************************/
    
    public IPM_BCCController(){
        projectId= ApexPages.currentPage().getParameters().get('Id');
        isEditable=false;
        if (projectId != NULL){
          /*  project = [SELECT Id,IPM_Project_Name__c,IPMProject_Span__c,IPM_Phase__c,IPM_Target_Launch_Dates__c,
                              IPM_Parent_Project__c,IPM_Parent_Project__r.IPM_Target_Launch_Dates__c 
                       FROM IPM_Project__c 
                       WHERE Id=:projectId];*/
            if(project.IPM_Target_Launch_Dates__c==project.IPM_Parent_Project__r.IPM_Target_Launch_Dates__c){
                tldAlignment=true;
            }
            finance = [SELECT Id,IPM_BD_BB_Feedback__c,Local_Project__c,Local_Project__r.name,Misaligned__c,IPM_Business_Case_Confirmed__c,IPM_Country_Feedback__c 
                       FROM IPM_Financial__c 
                       WHERE Local_Project__c=:projectId];    
            if(project.IPM_Project_Leader__c==userinfo.getuserid() || project.Deputy_Project_Leader__c==userinfo.getuserid()){
                isEditable=true;
            }
            //security for central team and BP users
            IPM_CustomPermission cpr = new IPM_CustomPermission();
            boolean isCentralTeam=false;
            boolean isBPUser=false;
            isCentralTeam = cpr.hasPermission(IPM_ConstantUtils.IPM_CENTRALTEAM_PERMISSION);
            isBPUser=cpr.hasPermission(IPM_ConstantUtils.IPM_BUSINESSPARTNER_PERMISSION);
            if(isCentralTeam || isBPUser){
               isEditable=true; 
            }
            Integer guestCount=0;
            guestCount=[SELECT COUNT() FROM IPM_Project_Resource__c WHERE IPM_Role_Type__c=:IPM_ConstantUtils.IPM_ROLE_GUEST
                        AND IPM_Project__c=:projectId AND IPM_User__c=:userinfo.getuserid()  AND IPM_Project__r.Is_Archieved__c=false LIMIT 1];
            if(guestCount>0){
                isPDFDownload=false;
            }
               
        }
    }

    /************************************************************************
    @Description : This method is used when we want to add save message to VF page
    ************************************************************************/
    
    public void save(){
        try{
            if(finance!=null)
                update finance;//will alwasys be 1 record.
            saveMsg=true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,System.Label.IPM_BCC_SAVED_SUCCESFULLY));
        }
        catch (DmlException ex) {
            ExceptionLoggingHelper.createErrorLogofIPM(UserInfo.getUserId(),CLASS_NAME,
                            'save',ex.getMessage(),ex, 'Error', null, null, null);
        }
    }

    /************************************************************************
    @Description :This method is used for update status in current IPM_Financial__c object
     ************************************************************************/
    
    public void changeStatus(){
        
        finance.IPM_Business_Case_Confirmed__c=true;
        try{
            if(finance!=null){
                finance.IPM_Business_Case_Confirmed__c=true;
                update finance;//will alwasys be 1 record.
            }
                 
        }
        catch (DmlException ex) {
            ExceptionLoggingHelper.createErrorLogofIPM(UserInfo.getUserId(),CLASS_NAME,
                            'changeStatus',ex.getMessage(),ex, 'Error', null, null, null);
        }
       
    }

    /************************************************************************
    @Description : This method is used for when hide save message
    ************************************************************************/
    public void hideSaveMsg(){
        saveMsg=false;
    }
}