src/objects/IPM_Country__c.object
<CustomObject>
    <description>This object is used to describe the Countries the project is rolling out</description>
    <fields>
        <fullName>IPM_Project_Rollout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to fetch related Rollout</description>
        <label>IPM Project Rollout</label>
        <referenceTo>IPM_Project_Rollout__c</referenceTo>
        <relationshipLabel>IPM Countries</relationshipLabel>
        <relationshipName>IPM_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for the global project.</description>
        <label>Global Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Countries</relationshipLabel>
        <relationshipName>IPM_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Rollout_Status__c</fullName>
        <description>Check Rollout status whether it is &apos;With MCO&apos; Or &apos;Seperate&apos; Or &apos;No Rollout&apos;</description>
        <label>IPM Rollout Status</label>
        <picklist>
            <picklistValues>
                <fullName>With MCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seperate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Rollout</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Rollout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship between country and local rollout</description>
        <label>Local Rollout</label>
        <referenceTo>IPM_Project_Rollout__c</referenceTo>
        <relationshipLabel>IPM Countries (Local)</relationshipLabel>
        <relationshipName>IPM_Countries_Local</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MDO_Geography__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It is Used to store new MDO Geography Object Values for Rollout generation</description>
        <label>MDO_Geography</label>
        <referenceTo>MDO_Geography__c</referenceTo>
        <relationshipLabel>IPM Countries</relationshipLabel>
        <relationshipName>IPM_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Country</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>IPM Country No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_Project_Rollout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related rollout project.</description>
        <label>IPM Source Rollout</label>
        <referenceTo>IPM_Project_Rollout__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Rollout_Status__c</fullName>
        <description>To capture the status of the rollout.</description>
        <label>Rollout Status</label>
        <picklist>
            <picklistValues>
                <fullName>Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follower</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Rollout__c.object
<CustomObject>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship between global project and rollout</description>
        <label>Global Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Rollout</relationshipLabel>
        <relationshipName>IPM_Project_Rollout</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Rollout_Project__c</fullName>
        <description>Project Created for Rollout</description>
        <externalId>true</externalId>
        <label>Rollout Project</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>IPM Project Rollout</label>
    <nameField>
        <label>IPM Project Rollout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Rollout</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDO_Geography__c.object
<CustomObject>
    <description>MDO geography master data</description>
    <fields>
        <fullName>ISO_3166_1_code__c</fullName>
        <label>ISO 3166-1 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geography</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IPM_Gate_RollOuts_Controller_Test.cls
/*******************************************************
 * @Description: Test class for IPM_Gate_RollOuts_Controller
 * @Author:Cognizant
 * @Date:05/08/2015
 * *****************************************************/

@isTest
public class IPM_Gate_RollOuts_Controller_Test{

   
     public static list<IPM_Country__c> countryList;
    
    /*******************************************************
     * @Description: Method to initilize data
     * *****************************************************/
   
     public testmethod static void projectSetUp() 
     {
  
        List<User> userList = IPM_TestFactory_Helper.createUserList();
         
        IPM_TestFactory_Helper.getProjectMasterData();
         
        List<IPM_Project__c> projectList = IPM_TestFactory_Helper.projectSetUp(1,userList[0]);
        System.runAs(userList[0])
        {
            insert projectList;
        }   
        
        system.assertEquals(projectList.size(),1,'Projects are created'); 
        System.runAs(userList[0])
        {
            // Create Regional Rollouts for Created Global project.
            List<IPM_Project_Rollout__c> regionalRolloutList = IPM_TestFactory_Helper.createRegionalRolloutList(false,projectList,new List<User>{userList[1],userList[1],userList[1]});
            insert regionalRolloutList;
            
            
            system.assertEquals(regionalRolloutList.size(),2);
            Map<Id,List<IPM_Project_Rollout__c>> projectToRolloutMap = new Map<Id,List<IPM_Project_Rollout__c>>();
            for(IPM_Project_Rollout__c projectRollout : regionalRolloutList)
            {
                List<IPM_Project_Rollout__c> projectRolloutList = new List<IPM_Project_Rollout__c>();
                if(projectToRolloutMap.containsKey(projectRollout.IPM_Project__c))
                {
                    projectRolloutList = projectToRolloutMap.get(projectRollout.IPM_Project__c);
                }
                projectRolloutList.add(projectRollout);
                projectToRolloutMap.put(projectRollout.IPM_Project__c,projectRolloutList);
               
            }
            
           // Create local Rollouts for Created regional Rollouts.
            List<IPM_Project_Rollout__c> localRolloutList = IPM_TestFactory_Helper.createLocalRolloutsList(false,projectToRolloutMap,new List<User>{userList[2]});  
            insert localRolloutList; 
           
            system.assertEquals(localRolloutList.size(),2,'Local Rollouts Created');
            
            // Create Country specific information.
             countryList= new List<IPM_Country__c>();
            
            for(IPM_Project_Rollout__c localRolloutObj : localRolloutList)
            {
                String geoExternalId = '';
                if(localRolloutObj.IPM_Rollout_Project__c.contains('AFR'))
                {
                    geoExternalId = 'AG';
                }
                else if(localRolloutObj.IPM_Rollout_Project__c.contains('LA'))
                {
                    geoExternalId = 'BR';
                }
                MDO_Geography__c mdo = new MDO_Geography__c(ISO_3166_1_Code__c = geoExternalId);
                IPM_Country__c tempCountry = new  IPM_Country__c(MDO_Geography__c = mdo.id,
                IPM_Project__c = localRolloutObj.IPM_Project__c,local_Rollout__c = localRolloutObj.Id,IPM_Rollout_Status__c = 'With MCO');    
                
                countryList.add(tempCountry);
            }
            
            insert countryList;
            
            
            List<IPM_Gate_RollOuts_Controller.LocalRolloutWrapper> lstLocalWrapper = new List<IPM_Gate_RollOuts_Controller.LocalRolloutWrapper>();
            IPM_Gate_RollOuts_Controller.LocalRolloutWrapper localRolloutWrapper = new IPM_Gate_RollOuts_Controller.LocalRolloutWrapper(localRolloutList[0],countryList);
            lstLocalWrapper.add(localRolloutWrapper);
            IPM_Gate_RollOuts_Controller.RegionalRollOutWrapper regionalRolloutWrapper = new IPM_Gate_RollOuts_Controller.RegionalRollOutWrapper(regionalRolloutList[0],lstLocalWrapper); // NO SONAR used to cover the test coverage of constructor  
            IPM_Gate_RollOuts_Controller gateController = new IPM_Gate_RollOuts_Controller(); 
            gateController.proId = projectList[0].Id; 
           
          
           
        }
     }
     
  	}