src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPMProject_Span__c</fullName>
        <description>To capture the span of project.</description>
        <label>Project Span</label>
        <picklist>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_CompanyCardText__c</fullName>
        <description>To capture the Company Card Text.</description>
        <label>Source Company Card</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Complexity__c</fullName>
        <description>To capture the complexity of the project.</description>
        <label>Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>To capture the GK model</description>
        <label>IPM GateKeeping Model</label>
        <picklist>
            <picklistValues>
                <fullName>CCVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCLT Leader &amp; CCVP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user in this case the project leader.</description>
        <label>Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Name__c</fullName>
        <description>To store the name of the project.</description>
        <externalId>true</externalId>
        <inlineHelpText>Project Name is mandatory</inlineHelpText>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IPM_Project_Type__c</fullName>
        <description>To capture the type of project.</description>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_SourceProjectType__c</fullName>
        <description>To capture the Source Project Type.</description>
        <label>Source Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Target_Launch_Dates__c</fullName>
        <description>To capture the target launch date of the project.</description>
        <label>IPM Target Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sustainability_Period__c</fullName>
        <description>Defines the number of Innovation years for the project</description>
        <inlineHelpText>Defines the number of Innovation years for the project</inlineHelpText>
        <label>Sustainability Period</label>
        <picklist>
            <picklistValues>
                <fullName>3</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>Gate Keeping Model for IPM project</description>
        <label>GateKeeping Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>project phase</description>
        <label>Phase</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Type__c</fullName>
        <description>Project Type i.e. rollout ,global</description>
        <label>Project Type</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IPM Project Type</label>
</CustomObject>

src/classes/IPM_FunnelController_Test.cls
/**
* @author       Cognizant 
* @date         15/04/2015
* @description  This class is used to test the functionality of IPM_FileUploadController class 
*/ 
@isTest
public with sharing class IPM_FunnelController_Test {
    private static IPM_Project__c project;
    private static user testUser;
    private static List<IPM_Project__c>projectList=new list<IPM_Project__c>();
    private static List<user>userList=new List<user>();
     
    private static void initializeData(){
        testUser=IPM_TestFactory_Helper.createUser(false);
        insert testUser;
        userList.add(testUser);
        List<User>userLists=[SELECT id FROM user WHERE id=:testUser.id LIMIT 1];
        System.AssertEquals(userLists[0].id, testUser.id,'User not found');
        IPM_TestFactory_Helper.createIPMProjectMetadata();
        IPM_Project__c projectRecord = IPM_TestFactory_Helper.createIPMProject(FALSE);
        projectRecord.Name = 'DEF1153BLOC';
        projectRecord.IPM_Project_Name__c = 'DEF1153BLOC';
        projectRecord.Sustainability_Period__c = '3';
        projectRecord.IPMProject_Span__c = 'Global';
        projectRecord.IPM_Project_Type__c = 'Original';
        projectRecord.IPM_Target_Launch_Dates__c = Date.newInstance(2020, 04, 07);
        projectRecord.IPM_Project_Leader__c = testUser.Id;
        projectRecord.IPM_Phase__c = 'Ideas';
        projectRecord.IPM_SourceProjectType__c=projectRecord.IPM_Project_Type__c;
        insert projectRecord;
        projectList.add(projectRecord);
        List<IPM_Project__c> projlList=[SELECT ID,Name,IPM_CompanyCardText__c,IPM_Phase__c,IPM_Project_Name__c,IPM_Complexity__c,IPM_GateKeeping_Model__c, IPM_SourceProjectType__c, IPM_Project_Type__c FROM IPM_Project__c WHERE ID=:projectRecord.ID LIMIT 1];
        project=projlList[0];
        System.assertEquals(projlList[0].id,projectRecord.id, 'Project insertion failed}');
        
        
    }
    
    static testmethod void testGetAssociatedProjectPhases(){
        initializeData();
        test.startTest();
        system.runAs(testUser){
            IPM_FunnelController funnelController = new IPM_FunnelController ();
            funnelController.ipmProject = project;
            funnelController.currentProjectPhaseSeq=4;
            funnelController.getAssociatedProjectPhases();
            funnelController.ipmProject.IPM_CompanyCardText__c='Global Company Card';
            List<string> projectPhases = funnelController.getAssociatedProjectPhases();
            system.assertEquals(funnelController.ipmProject, project, 'project record is not same');
            
        }
        test.stopTest();
    } 

}