src/objects/IPM_OTIF_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contents of OTIF Status for Gate Documents</description>
    <fields>
        <fullName>IPM_Section_Number__c</fullName>
        <description>The section number related to the OTIF question</description>
        <label>IPM Section Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>IPM OTIF Status</label>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_IsCompleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if project is completed.</description>
        <label>IsCompleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Target_Launch_Dates__c</fullName>
        <description>To capture the target launch date of the project.</description>
        <label>IPM Target Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sustainability_Period__c</fullName>
        <description>Defines the number of Innovation years for the project</description>
        <inlineHelpText>Defines the number of Innovation years for the project</inlineHelpText>
        <label>Sustainability Period</label>
        <picklist>
            <picklistValues>
                <fullName>3</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document__c.object
<CustomObject>
    <description>THis is used in IPM to store Project documents</description>
    <fields>
        <fullName>IPM_GateDocuments__c</fullName>
        <description>To capture gate document name</description>
        <label>IPM_GateDocuments</label>
        <picklist>
            <picklistValues>
                <fullName>Charter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Design Lock</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Document_External_Id__c</fullName>
        <description>To identify the document when data load from external system</description>
        <externalId>true</externalId>
        <label>Project Document External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>Relation to the Project Object</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Documents</relationshipLabel>
        <relationshipName>Project_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Project Document</label>
    <nameField>
        <label>Project Document Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document_Section__c.object
<CustomObject>
    <description>To be used in IPM project to store Gate Document Sections. It refers to the IPM Section object to pick what section/subsection it needs.</description>
    <fields>
        <fullName>IPM_Project_Document__c</fullName>
        <description>Relationship to Project Document</description>
        <label>IPM Project Document</label>
        <referenceTo>IPM_Project_Document__c</referenceTo>
        <relationshipLabel>IPM Project Document Sections</relationshipLabel>
        <relationshipName>IPM_Project_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Name__c</fullName>
        <description>Contains section name</description>
        <label>Section Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Number__c</fullName>
        <description>To capture section number</description>
        <formula>VALUE(IPM_Section__r.IPM_Section_Sequence__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IPM Section Number</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Type__c</fullName>
        <description>To describe the type of section</description>
        <label>Section Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Static Table</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project Document Section</label>
    <nameField>
        <label>Section Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Document Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document_Section_Content__c.object
<CustomObject>
    <description>This is used in IPM to hold section contents</description>
    <fields>
        <fullName>IPM_Content_Type__c</fullName>
        <description>Used for storing content  type</description>
        <label>Content Type</label>
        <picklist>
            <picklistValues>
                <fullName>CMI Gate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Evidence Concepts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Channels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assortment Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assumptions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cu_Complexity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Action Standards</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_HelpText_Amber__c</fullName>
        <description>Holds the value for Amber helptext</description>
        <label>IPM OTIF HelpText Amber</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_HelpText_Green__c</fullName>
        <description>Hold the helptext for Green</description>
        <label>IPM OTIF HelpText Green</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_HelpText_NA__c</fullName>
        <description>Holds the helptext for NA</description>
        <label>IPM OTIF HelpText NA</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_HelpText_Red__c</fullName>
        <description>Holds the help text from custom settings</description>
        <label>IPM OTIF HelpText Red</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_Measure__c</fullName>
        <description>contains otif measure</description>
        <label>IPM OTIF Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_No_of_Status__c</fullName>
        <description>contains no of status</description>
        <label>IPM_OTIF_No of Status</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_Responsibility__c</fullName>
        <description>contains otif responsbility</description>
        <label>IPM OTIF Responsibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_Sequence__c</fullName>
        <description>TO capture the OTIF questions Sequence</description>
        <label>IPM OTIF Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IPM_OTIF_Status__c</fullName>
        <description>contains otif status</description>
        <label>IPM OTIF Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Document_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to project document section</description>
        <label>IPM Project Document Section</label>
        <referenceTo>IPM_Project_Document_Section__c</referenceTo>
        <relationshipLabel>IPM Project Document Section Contents</relationshipLabel>
        <relationshipName>IPM_Section_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Id__c</fullName>
        <description>To store the ID of the related section used for re-direction</description>
        <label>IPM Section Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Name__c</fullName>
        <description>To store the Name of the Related Section for OTIF</description>
        <label>IPM Section Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Number__c</fullName>
        <description>To hold the related sequence number</description>
        <label>IPM Section Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_type__c</fullName>
        <description>to store section type</description>
        <label>Section Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Static Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamic Complex Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamic Static Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Parameters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project Document Section Content</label>
    <nameField>
        <displayFormat>SecCon-{0000}</displayFormat>
        <label>Section Content Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Document Section Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IPM_OTIFstatusController_Test.cls
/**
@Author  Cognizant 
@name IPM_OTIFstatusController_Test
@CreateDate 15/04/2015
@DescriptionChecks the OTIF status of the Gate Document
@Version <1.0>
@reference IPM_OTIFstatusController
*/
@isTest
private class IPM_OTIFstatusController_Test {
    
    private static IPM_Project__c project;
    private static IPM_Project_Document__c projDoc;
    private static List<IPM_Project_Document__c> projDocList;
    private static IPM_Project_Document_Section__c projDocSec;
    private static IPM_Project_Document_Section_Content__c projDocSecCon;
    private static User otifUser;
    private static string RECORD_NOT_SAVED_SUCCESSFULLY='record not saved successfully';
    private static string SECTION_CONTENT_LIST_IS_EMPTY='section content list empty';
    
    /*Name: initializeData
    * @Description: Initialises the data needed for creating OTIF situation
    */
    static void initializeData() { 
        otifUser = IPM_TestFactory_Helper.createUser(true);
        system.assert(otifUser.id!=null);//positive test
        system.RunAs(otifUser){
            project = IPM_TestFactory_Helper.createIPMProject(FALSE);
            project.Sustainability_Period__c='3';
            project.IPM_Target_Launch_Dates__c=system.today();
            project.IPM_IsCompleted__c=true; 
            insert project;
            IPM_Project__c projectObj=[select IPM_IsCompleted__c from IPM_Project__c where id=:project.Id];
            system.assert(projectObj.IPM_IsCompleted__c,RECORD_NOT_SAVED_SUCCESSFULLY);
            
            projDoc = IPM_TestFactory_Helper.createIPMProjectDocument(false);
            projDoc.IPM_Project__c=project.ID;
            projDoc.IPM_GateDocuments__c='Charter';
            projDoc.IPM_Project_Document_External_Id__c = 'Test_Ext_Id';
            insert projDoc;
            IPM_Project_Document__c projectDocObj=[select IPM_Project__c from IPM_Project_Document__c where id=:projDoc.Id];
            system.assertEquals(projectDocObj.IPM_Project__c,project.ID,RECORD_NOT_SAVED_SUCCESSFULLY);
            
            projDocList=new List<IPM_Project_Document__c>();
            projDocList.add(projDoc);
            
            projDocSec = IPM_TestFactory_Helper.createIPMProjectDocumentSection(false);
            projDocSec.IPM_Project_Document__c=projDoc.ID;
            insert projDocSec;
            
            IPM_Project_Document_Section__c projectDocSecObj=[select IPM_Project_Document__c from IPM_Project_Document_Section__c where id=:projDocSec.Id];
            system.assertEquals(projectDocSecObj.IPM_Project_Document__c,projDoc.ID,RECORD_NOT_SAVED_SUCCESSFULLY);
            
            projDocSecCon = IPM_TestFactory_Helper.createIPMProjectDocumentSectionContent(false);
            projDocSecCon.IPM_Project_Document_Section__c=projDocSec.ID;
            projDocSecCon.IPM_OTIF_No_of_Status__c=4;
            projDocSecCon.IPM_OTIF_Measure__c='Measure 1';
            projDocSeccon.IPM_OTIF_Responsibility__c='BD';
            projDocSecCon.IPM_OTIF_Status__c='Not Applicable';
            projDocSecCon.IPM_OTIF_HelpText_Red__c='Red';
            projDocSecCon.IPM_OTIF_HelpText_NA__c='NA';
            projDocSecCon.IPM_OTIF_HelpText_Green__c='Green';
            projDocSecCon.IPM_OTIF_HelpText_Amber__c='Amber';
            projDocSecCon.IPM_Section_Number__c='2.2';
            projDocSecCon.IPM_OTIF_Sequence__c=1;
            projDocSecCon.IPM_Section_Id__c=projDocSec.ID;
            projDocSecCon.IPM_Section_Name__c='Customer Channel';
            projDocSecCon.IPM_Section_type__c='Checklist';
            insert projDocSecCon;
            
            IPM_Project_Document_Section_Content__c projectDocSecConObj=[select IPM_Project_Document_Section__c from IPM_Project_Document_Section_Content__c where id=:projDocSecCon.Id];
            system.assertEquals(projectDocSecConObj.IPM_Project_Document_Section__c,projDocSec.ID,RECORD_NOT_SAVED_SUCCESSFULLY);
        }
    }
    
    /*Name: testShowContent
    * @Description: Tests actual content
    */
    static testMethod void testShowContent() {
        initializeData();
        system.RunAs(otifUser){
            Test.startTest();
            IPM_OTIFstatusController otif=new IPM_OTIFstatusController();
            otif.secConId=project.Id;
            otif.updateOTIFStatus();
            System.assertNotEquals(otif.secCon.IPM_Content_Type__c,IPM_ConstantUtils.OTIF_CONTENT_TYPE,System.Label.IPM_CATCH_BLOCK_CALLED);
            otif.iseditable=true;
            otif.showSectionContent();
            System.assertEquals(otif.secConList,Null,SECTION_CONTENT_LIST_IS_EMPTY);
            otif.projDocSecId=projDocSec.Id;
            otif.otifType=IPM_ConstantUtils.OTIF_TABLE;
            otif.showSectionContent();
            System.assertNotEquals(otif.secConList,Null,SECTION_CONTENT_LIST_IS_EMPTY);
            otif.otifType=IPM_ConstantUtils.OTIF_SECTION;
            otif.showSectionContent();
            System.assertNotEquals(otif.secConList,Null,'');
            otif.secConId=projDocSecCon.Id;
            otif.status='Red';
            otif.updateOTIFStatus();
            System.assertEquals(otif.secCon.IPM_OTIF_Status__c,'Red',System.Label.IPM_FUNC_CALLED_SUCCESSFULLY);
            Test.stopTest();
        }
    }
}