src/objects/IPM_Financial_File__c.object
<CustomObject>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Financial Files</relationshipLabel>
        <relationshipName>IPM_Financial_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Financial File</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Financial Files</pluralLabel>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <label>Template</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPMProject_Span__c</fullName>
        <description>To capture the span of project.</description>
        <label>Project Span</label>
        <picklist>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Parent_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To Capture Parent Project based on region and country rollouts</description>
        <label>IPM Parent Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Name__c</fullName>
        <description>To store the name of the project.</description>
        <externalId>true</externalId>
        <inlineHelpText>Project Name is mandatory</inlineHelpText>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Market_Cluster__c</fullName>
        <description>To capture the master cluster.</description>
        <label>Market Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sustainability_Period__c</fullName>
        <description>Defines the number of Innovation years for the project</description>
        <inlineHelpText>Defines the number of Innovation years for the project</inlineHelpText>
        <label>Sustainability Period</label>
        <picklist>
            <picklistValues>
                <fullName>3</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ipmDownloadTemplateController.cls
public with sharing class ipmDownloadTemplateController
{
    // Zip file paths
    public List<String> paths {get;set;}
    
    // Generated zip file data (see receiveZipFile)
    public transient String zipFileData {get;set;}
    public String fileId {get;set;}
    public IPM_Project__c project {get; set;}
    
    //private ApexPages.StandardController controller;
    
    public ipmDownloadTemplateController(){
        //IE-9 Fix
        Apexpages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=edge');

        String projectId = ApexPages.currentPage().getParameters().get('Id');
        if (projectId != NULL){
            project = [SELECT Id, IPM_Project_Name__c, Sustainability_Period__c, IPMProject_Span__c, Market_Cluster__c, IPM_Parent_Project__c, IPM_Parent_Project__r.Market_Cluster__c, IPM_Phase__c 
                        FROM IPM_Project__C 
                        WHERE Id=:projectId];
        fileId = ApexPages.currentPage().getParameters().get('fileId');
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'The template is being generated, please wait'));
            
        List<Attachment> attachments = [select Name from Attachment where ParentId =: fileId];
        paths = new List<String>();
        for(Attachment attachment : attachments)
          paths.add(attachment.Name);      
        }
    }
    
    public PageReference receiveZipFile(){
        // Receive the generated zip file and store it (in this case as a Document)
        IPM_Financial_File__c zipFile = [select Name from IPM_Financial_File__c where Id =: fileId]; 
        Database.SaveResult saveResult = Database.insert(
            new Attachment(
                Name = zipFile.Name,
                Body = EncodingUtil.base64Decode(zipFileData),
                ParentId = zipFile.Id
            )
        );
        
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'The template has been generated and downloaded'));
        
        return new PageReference('/servlet/servlet.FileDownload?file='+saveResult.getId());
    }
    
    @RemoteAction
    public static String getZipFileEntry(String path, String state){
        // Retrieve or generate the Base64 encoded data for each file path to be added to the zip
        Attachment attachment = [select Name, Body from Attachment where ParentId =:state and Name =:path];
        return EncodingUtil.base64Encode(attachment.body);
    }  
}