src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user in this case the project leader.</description>
        <label>Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document_Section__c.object
<CustomObject>
    <description>To be used in IPM project to store Gate Document Sections. It refers to the IPM Section object to pick what section/subsection it needs.</description>
    <fields>
        <fullName>IPM_Section_Status__c</fullName>
        <description>To store section status</description>
        <label>IPM_Section_Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Filled-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excluded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project Document Section</label>
    <nameField>
        <label>Section Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Document Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Resource__c.object
<CustomObject>
    <description>To store the IPM Project Team Members</description>
    <fields>
        <fullName>IPM_Project_Document_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>look up of object IPM_Project_Document_Section.</description>
        <label>IPM Project Document Section</label>
        <referenceTo>IPM_Project_Document_Section__c</referenceTo>
        <relationshipLabel>IPM Project Resources</relationshipLabel>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Role_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to capture the owner of role in team member</description>
        <label>Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>lookup for IPM project</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Resources</relationshipLabel>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Role_Type__c</fullName>
        <description>Store role type</description>
        <label>IPM Role Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to IPM User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resource Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Task__c.object
<CustomObject>
    <fields>
        <fullName>IPM_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User to whom the task is assigned</description>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value is checked when the task is completed</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Function__c</fullName>
        <description>Function describes the Role of the user task is related</description>
        <label>Function</label>
        <picklist>
            <picklistValues>
                <fullName>CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MKTG DEV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MKTG LOCAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Document_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The project document section for which the task is created</description>
        <label>IPM Project Document Section</label>
        <referenceTo>IPM_Project_Document_Section__c</referenceTo>
        <relationshipLabel>IPM Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>The project for which the task is created</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Task_Type__c</fullName>
        <description>The type of the task created</description>
        <label>Task Type</label>
        <picklist>
            <picklistValues>
                <fullName>Negotiable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Negotiable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Task</label>
    <nameField>
        <label>Task ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IPM_TaskHelper.cls
public without sharing class IPM_TaskHelper {
    
    public static void reAssignFunctionalWiseTasks(IPM_Project_Resource__c[] newProjectResources) {
    	
    	list<IPM_Task__c> tasksToUpdate = new list<IPM_Task__c>();
    	Map<String, String> functionalRoleUserMap = new Map<String, String>();
    	Set<Id> projectIds = new Set<Id>();
        Set<String> functionalRolesSet = new Set<String>();
    	for(IPM_Project_Resource__c eachPR : newProjectResources) {
    		functionalRolesSet.add(eachPR.IPM_Role_Type__c);
    		projectIds.add(eachPR.IPM_Project__c);
    		functionalRoleUserMap.put(eachPR.IPM_Role_Type__c+'-'+eachPR.IPM_Project__c, eachPR.IPM_User__c);
    	}
    	list<IPM_Task__c> tasksList = [SELECT IPM_Assignee__c, IPM_Function__c, IPM_Project__c FROM IPM_Task__c 
                                            WHERE IPM_Project__c IN :projectIds
                                            AND IPM_Function__c IN :functionalRolesSet AND IPM_Completed__c != true];
        for(IPM_Task__c eachTask : tasksList) {
            IPM_Task__c tskObj = eachTask;
            tskObj.IPM_Assignee__c = functionalRoleUserMap.get(eachTask.IPM_Function__c+'-'+eachTask.IPM_Project__c);
            tasksToUpdate.add(tskObj);
        }
        system.debug('** tasksToUpdate FROM FUNCTION WISE : ' + tasksToUpdate);
        update tasksToUpdate;
    }
    
    @future
    public static void reAssign(Set<Id> usersId) {
        
        system.debug('** usersId future : ' + usersId);
        IPM_Project_Resource__c[] newProResourcesList = new list<IPM_Project_Resource__c>();
        map<Id, IPM_Project_Resource__c> newProResourcesMap = new map<Id, IPM_Project_Resource__c>();
        Map<Id, IPM_Project_Resource__c> oldProResourcesMap = new Map<Id, IPM_Project_Resource__c>
                                                                ([SELECT IPM_User__c, IPM_Project__c, IPM_Project__r.IPM_Project_Leader__c, 
                                                                    IPM_Project_Role_Owner__c 
                                                                FROM IPM_Project_Resource__c 
                                                                WHERE IPM_Project_Role_Owner__c = true AND
                                                                        IPM_User__c IN :usersId]);
        for(IPM_Project_Resource__c eachNewPR : oldProResourcesMap.values()) {
            IPM_Project_Resource__c prSobj = eachNewPR;
            prSobj.IPM_User__c = null;
            newProResourcesList.add(prSobj);
            newProResourcesMap.put(eachNewPR.Id, prSobj);
        }
        oldProResourcesMap = new Map<Id, IPM_Project_Resource__c>
                                                                ([SELECT IPM_User__c, IPM_Project__c, IPM_Project__r.IPM_Project_Leader__c, 
                                                                    IPM_Project_Role_Owner__c 
                                                                FROM IPM_Project_Resource__c 
                                                                WHERE IPM_Project_Role_Owner__c = true AND
                                                                        IPM_User__c IN :usersId]);
        system.debug('** oldProResourcesMap USER AFTER : ' + oldProResourcesMap);
        system.debug('** newProResourcesMap USER AFTER : ' + newProResourcesMap);
        reAssignTasks(newProResourcesList, newProResourcesMap, oldProResourcesMap); 
    }
    
    public static void reAssignTasksForInActiveUsrs(User[] inActiveUsrsList) {
        
        Set<Id> usersId = new Set<Id>();
        for(User eachUser : inActiveUsrsList) {
            usersId.add(eachUser.Id);
        }
        system.debug('** usersId : ' + usersId);
        reAssign(usersId);
    }
    
    public static void reAssignTasks(IPM_Project_Resource__c[] newProjectsResources, 
                                        map<Id, IPM_Project_Resource__c> newProjectResourcesMap,
                                        map<Id, IPM_Project_Resource__c> oldProjectResourcesMap) {
        
        list<IPM_Task__c> tasksToUpdate = new list<IPM_Task__c>();
        list<IPM_Project_Resource__c> projectResourcesToUpdate = new list<IPM_Project_Resource__c>();
        IPM_Project_Resource__c oldProjectResource = new IPM_Project_Resource__c();
        Set<Id> projectIds = new Set<Id>();
        Set<String> functionalRolesSet = new Set<String>();
        map<Id, Id> usersToReplaceMap = new map<Id, Id>(); // old user => new user
        map<Id, IPM_Project_Resource__c> removedUsersMap = new map<Id, IPM_Project_Resource__c>();
        map<Id, IPM_Project_Resource__c> replacedUsersMap = new map<Id, IPM_Project_Resource__c>();
        map<Id, Id> projectLeaderMap = new map<Id, Id>();
        system.debug('** newProjectsResources : ' + newProjectsResources);
        system.debug('** newProjectResourcesMap : ' + newProjectResourcesMap);
        system.debug('** oldProjectResourcesMap : ' + oldProjectResourcesMap);
        for(IPM_Project_Resource__c eachProject : newProjectsResources) {
        	functionalRolesSet.add(eachProject.IPM_Role_Type__c);
            oldProjectResource = oldProjectResourcesMap.get(eachProject.Id);
            //check for those users who are removed frm the owner's role, find out their ManagerIds and replace their tasks with them.
            if(oldProjectResource.IPM_User__c != eachProject.IPM_User__c && eachProject.IPM_User__c == null &&
                eachProject.IPM_Project_Role_Owner__c) {
                removedUsersMap.put(oldProjectResource.IPM_User__c, oldProjectResource);
                projectIds.add(eachProject.IPM_Project__c);
            }
            //check for those users who are replaced by the system itself.
            if(oldProjectResource.IPM_User__c != eachProject.IPM_User__c && eachProject.IPM_User__c != null &&
                eachProject.IPM_Project_Role_Owner__c) {
                replacedUsersMap.put(eachProject.IPM_User__c, eachProject);
                usersToReplaceMap.put(oldProjectResource.IPM_User__c, eachProject.IPM_User__c);
                projectIds.add(eachProject.IPM_Project__c);
            }
        }
        system.debug('** removedUsersMap : ' + removedUsersMap);
        list<IPM_Project_Resource__c> projectResourcesList = [SELECT IPM_Project__r.IPM_Project_Leader__c, IPM_User__c 
                                                                FROM IPM_Project_Resource__c
                                                                WHERE Id IN: oldProjectResourcesMap.keySet()];
        for(IPM_Project_Resource__c eachPR : projectResourcesList) {
            IPM_Project_Resource__c oldPR = oldProjectResourcesMap.get(eachPR.Id);
            projectLeaderMap.put(oldPR.IPM_User__c, eachPR.IPM_Project__r.IPM_Project_Leader__c);
        }
        list<User> usersList = [SELECT ManagerId, Manager.IsActive FROM User WHERE Id IN :removedUsersMap.keySet()];
        for(User eachUser : usersList) {
            if(eachUser.ManagerId != null && eachUser.Manager.IsActive) {
                usersToReplaceMap.put(eachUser.Id, eachUser.ManagerId);
            }else {
                usersToReplaceMap.put(eachUser.Id, projectLeaderMap.get(removedUsersMap.get(eachUser.Id).IPM_User__c));
            }
        }
        
        system.debug('** projectLeaderMap : ' + projectLeaderMap);
        system.debug('** usersToReplaceMap : ' + usersToReplaceMap);
        Set<Id> pResourceIdsToUpdate = new Set<Id>();
        Set<Id> usersId = new Set<Id>();
        Set<Id> presourceIds = new Set<Id>();
        for(IPM_Project_Resource__c eachPR : removedUsersMap.values()) {
            pResourceIdsToUpdate.add(removedUsersMap.get(eachPR.IPM_User__c).Id);
        }
        
        list<IPM_Project_Resource__c> prList = [SELECT IPM_User__c, IPM_Project__c FROM IPM_Project_Resource__c WHERE Id IN :pResourceIdsToUpdate];
        for(IPM_Project_Resource__c eachPR : prList) {
            IPM_Project_Resource__c prObj = eachPR;
            IPM_Project_Resource__c oldPR = oldProjectResourcesMap.get(eachPR.Id);
            prObj.IPM_User__c = usersToReplaceMap.get(oldPR.IPM_User__c);
            prObj.IPM_Project__c = eachPR.IPM_Project__c;
            projectResourcesToUpdate.add(prObj);
            usersId.add(prObj.IPM_User__c);
            usersId.add(oldPR.IPM_User__c);
        }
        
        list<IPM_Task__c> tasksList = [SELECT IPM_Assignee__c FROM IPM_Task__c 
                                            WHERE IPM_Assignee__c IN :usersToReplaceMap.keySet()
                                            AND IPM_Project__c IN :projectIds];
        for(IPM_Task__c eachTask : tasksList) {
            IPM_Task__c tskObj = eachTask;
            tskObj.IPM_Assignee__c = usersToReplaceMap.get(eachTask.IPM_Assignee__c);
            tasksToUpdate.add(tskObj);
        }
        system.debug('** tasksToUpdate : ' + tasksToUpdate);
        update tasksToUpdate;
        update projectResourcesToUpdate;
        
        for(IPM_Project_Resource__c eachPResource : projectResourcesToUpdate) {
            presourceIds.add(eachPResource.Id);
        }
        IPM_Project_Resource__c[] projectResourcesUpdtdList = [SELECT IPM_User__c, IPM_Project__c, IPM_Project__r.IPM_Project_Leader__c
                                        FROM IPM_Project_Resource__c
                                        WHERE Id IN :presourceIds];
        Map<Id, Set<Id>> projectUserMap = new Map<Id, Set<Id>>();
        Map<Id, String> chatterTextMap = new Map<Id, String>();
        Map<Id, User> userDetailsMap = IPM_Utils.getUserDetailsMap(usersId);
        system.debug('** projectResourcesUpdtdList : ' + projectResourcesUpdtdList);
        system.debug('** oldProjectResourcesMap : ' + oldProjectResourcesMap);
        system.debug('** projectResourcesUpdtdList : ' + projectResourcesUpdtdList);
        for(IPM_Project_Resource__c eachPResource : projectResourcesUpdtdList) {
            if(!projectUserMap.containsKey(eachPResource.IPM_Project__c)) {
                set<Id> tmpSet = new Set<Id>();
                tmpSet.add(eachPResource.IPM_Project__r.IPM_Project_Leader__c);
                projectUserMap.put(eachPResource.IPM_Project__c, tmpSet);
            } else {
                projectUserMap.get(eachPResource.IPM_Project__c).add(eachPResource.IPM_Project__r.IPM_Project_Leader__c);
            }
            IPM_Project_Resource__c oldPR = oldProjectResourcesMap.get(eachPResource.Id);
            system.debug('** eachPResource.Id ' + eachPResource.Id);
            chatterTextMap.put(eachPResource.IPM_Project__c, userDetailsMap.get(oldPR.IPM_User__c).Name + IPM_ChatterUtils.INACTIVE_USERS_TEXT);
        }
        system.debug('** projectUserMap : ' + projectUserMap);
        system.debug('** chatterTextMap : ' + chatterTextMap);
        IPM_ChatterFeedHelper.postDynamicChatterUpdateToRecord(projectUserMap, chatterTextMap);
    }
    
    /*
        If there are tasks added to an excluded section then mark them as not excluded.
    */
    public static void markSectionNotStarted(Set<Id> sectionIds) {
        
        IPM_Project_Document_Section__c[] sectionsToUpdate = new List<IPM_Project_Document_Section__c>();
        IPM_Project_Document_Section__c[] projectSectionList = [SELECT IPM_Section_Status__c 
                                                                    FROM IPM_Project_Document_Section__c
                                                                    WHERE Id IN :sectionIds AND 
                                                                        IPM_Section_Status__c =:IPM_ConstantUtils.STATUS_EXCLUDED];
        for(IPM_Project_Document_Section__c eachSection : projectSectionList) {
            IPM_Project_Document_Section__c sectionObj = eachSection;
            sectionObj.IPM_Section_Status__c = IPM_ConstantUtils.STATUS_NOT_STARTED;
            sectionsToUpdate.add(sectionObj);
        }
        
        update sectionsToUpdate;
    }
    
    /*
        If there are no tasks related to a section then mark them as excluded.
    */
    public static void markSectionExcluded(Set<Id> sectionIds) {
        
        IPM_Project_Document_Section__c[] sectionsToUpdate = new List<IPM_Project_Document_Section__c>();
        IPM_Project_Document_Section__c[] projectSectionList = [SELECT (SELECT Id FROM Tasks__r WHERE IPM_Task_Type__c = 'Negotiable'),IPM_Section_Status__c 
                                                                    FROM IPM_Project_Document_Section__c
                                                                    WHERE Id IN :sectionIds];
        for(IPM_Project_Document_Section__c eachSection : projectSectionList) {
            IPM_Task__c[] tasksList = eachSection.Tasks__r;
            if(tasksList.size() == 0) {
                IPM_Project_Document_Section__c sectionObj = eachSection;
                sectionObj.IPM_Section_Status__c = IPM_ConstantUtils.STATUS_EXCLUDED;
                sectionsToUpdate.add(sectionObj);
            }
        }
        
        update sectionsToUpdate;
    }
}