src/objects/IPM_Financial__c.object
<CustomObject>
    <fields>
        <fullName>IPM_Category__c</fullName>
        <description>Used in sharing rules</description>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Rollout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Regional Rollout associated to financial.</description>
        <label>Regional Rollout</label>
        <referenceTo>IPM_Project_Rollout__c</referenceTo>
        <relationshipLabel>IPM Financials</relationshipLabel>
        <relationshipName>IPM_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Launch_Date__c</fullName>
        <description>Project Target Launch date.</description>
        <label>Target Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>IPM Financial</label>
    <nameField>
        <displayFormat>FIN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Financials</pluralLabel>
    <recordTypes>
        <fullName>Consolidated</fullName>
        <active>true</active>
        <description>Consolidated Financials</description>
        <label>Consolidated</label>
    </recordTypes>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Financial_Year__c.object
<CustomObject>
    <fields>
        <fullName>IPM_Financial__c</fullName>
        <description>Associated financial record</description>
        <label>IPM Financial</label>
        <referenceTo>IPM_Financial__c</referenceTo>
        <relationshipLabel>IPM Financial Years</relationshipLabel>
        <relationshipName>IPM_Financial_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_Launch_Date__c</fullName>
        <description>Stores related financial record&apos;s Target Launch date</description>
        <formula>IPM_Financial__r.Target_Launch_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>Stores year value</description>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Financial Year</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Financial Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_Brand_Positioning__c</fullName>
        <description>To capture the brand of product for the project.</description>
        <label>Brand Positioning</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related category.</description>
        <label>IPM_Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related company card.</description>
        <label>IPM Company Card</label>
        <referenceTo>IPM_Company_Card__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Complexity__c</fullName>
        <description>To capture the complexity of the project.</description>
        <label>Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_GateKeeping_Model__c</fullName>
        <description>To capture the GK model</description>
        <label>IPM GateKeeping Model</label>
        <picklist>
            <picklistValues>
                <fullName>CCVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GCLT Leader &amp; CCVP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Rollout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related rollout project.</description>
        <label>IPM Source Rollout</label>
        <referenceTo>IPM_Project_Rollout__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Sub_Category__c</fullName>
        <description>To capture the sub category.</description>
        <label>Sub Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sustainability_Period__c</fullName>
        <description>Defines the number of Innovation years for the project</description>
        <inlineHelpText>Defines the number of Innovation years for the project</inlineHelpText>
        <label>Sustainability Period</label>
        <picklist>
            <picklistValues>
                <fullName>3</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Resource__c.object
<CustomObject>
    <description>To store the IPM Project Team Members</description>
    <fields>
        <fullName>IPM_Category__c</fullName>
        <description>displaying from user record</description>
        <formula>$User.IPM_Category__c</formula>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <description>Project&apos;s company card value will be populated in this field.</description>
        <formula>IPM_Project__r.IPM_Company_Card__c</formula>
        <label>Company Card</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>lookup for IPM project</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Resources</relationshipLabel>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Role_Type__c</fullName>
        <description>Store role type</description>
        <label>IPM Role Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Role__c</fullName>
        <description>Displaying from user record</description>
        <formula>(text(IPM_User__r.IPM_Role__c))</formula>
        <label>Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to IPM User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resource Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Rollout__c.object
<CustomObject>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company card related with project Rollout</description>
        <label>IPM Company Card</label>
        <referenceTo>IPM_Company_Card__c</referenceTo>
        <relationshipLabel>IPM Project Rollout</relationshipLabel>
        <relationshipName>IPM_Project_Rollout</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship between global project and rollout</description>
        <label>Global Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Rollout</relationshipLabel>
        <relationshipName>IPM_Project_Rollout</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project Rollout</label>
    <nameField>
        <label>IPM Project Rollout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Rollout</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IPM_Brand_Name__c</fullName>
        <description>to store brand name from AD</description>
        <label>Brand Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Brand_Positioning__c</fullName>
        <label>Brand Positioning</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IPM_Category__c</fullName>
        <description>to store category of user(information will be fetch from AD)</description>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Role__c</fullName>
        <description>to stroe role from AD</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Project Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gate Keeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Leader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/IPM_FinancialShare_Test.cls
@isTest
public class  IPM_FinancialShare_Test {
    public static IPM_Project__c project;
    public static IPM_Project__c childProject;
    public static IPM_Project_Rollout__c proRoll=new IPM_Project_Rollout__c();
    public static List<IPM_Financial__c> lstFinancial=new List<IPM_Financial__c>();
    public static Id currentFinancialId;
    public static IPM_Financial__c finCon=new IPM_Financial__c();
    public static IPM_Financial__c finDef=new IPM_Financial__c();
    public static IPM_Financial_Year__c finYear=new IPM_Financial_Year__c();
    //public static  List<RolloutWrapper> lstRolloutWrappers=new  List<RolloutWrapper>();
   public static Map<String, IPM_Financial_Year__c> mapFinancialYearRecords=new Map<String, IPM_Financial_Year__c>();
    
   public static String REGIONAL_ROLLOUT_RECORDTYPE;
    public static String LOCAL_ROLLOUT_RECORDTYPE;
    public static String DEFAULT_FINANCIAL_RECORDTYPE;
    public static String CONSOLIDATED_FINANCIAL_RECORDTYPE;
     public static IPM_Company_Card__c comCard=new IPM_Company_Card__c();
       public static IPM_Financial_File__Share   ipmFinFileShare = new IPM_Financial_File__Share();
       public static List<IPM_Financial_File__Share> listipmFinFileShare  = new List<IPM_Financial_File__Share>();
     public static List<IPM_Project__c> prolst=new List<IPM_Project__c>();
    

    static testMethod void initializeData(){
        PermissionSet Fps=new PermissionSet();
        Fps=[SELECT Id FROM PermissionSet WHERE Name = 'IPMNG_Basic' limit 1]; 
        PermissionSetAssignment psa = new PermissionSetAssignment();
       
        User u1 = new User();
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        u1 = new User(Alias = 'fin30', Email='fin30@testorg4.com', 
        EmailEncodingKey='UTF-8', LastName='fin20', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='fin30@testorg4.com', 
        IPM_Category__c = 'test4'  , IPM_Brand_Positioning__c= 'test4',IPM_Brand_Name__c ='test1',
        IPM_Role__c='Gate Keeper' ,IPM_Sub_Category__c='test', isActive =true);
        insert u1;
          System.runAs(u1) {
                psa.AssigneeId = u1.Id;
                psa.PermissionSetId = Fps.Id;
                insert psa;
           }
        
        project=new IPM_Project__c();
        project.Name='TESTAPPROVERCL';
        project.IPM_Phase__c='Feasibility';
        project.IPM_Complexity__c='Full';
        project.IPM_GateKeeping_Model__c='RCLT'; 
        project.Sustainability_Period__c='3';
        insert project;
        IPM_Project_Resource__c  ipmProjectResource = new IPM_Project_Resource__c();
        ipmProjectResource.IPM_Role_Type__c = 'Finance';
        ipmProjectResource.IPM_Project__c = project.Id ;
        ipmProjectResource.IPM_User__c = psa.AssigneeId ;
        insert ipmProjectResource;
        childProject=new IPM_Project__c();
        childProject.Name='TESTAPPROVERCL_SEAA';
        childProject.IPM_Phase__c='Feasibility';
        childProject.IPM_Complexity__c='Full';
        childProject.IPM_GateKeeping_Model__c='RCLT'; 
        childProject.Sustainability_Period__c='3';
        insert childProject;

        String strRecordTypeId=[Select Id From RecordType Where SobjectType='IPM_Project_Rollout__c' and Name='Regional Rollout'].Id;
        proRoll=new IPM_Project_Rollout__c();
        proRoll.Name='TESTAPPROVERCL_SEAA';
        proRoll.RecordTypeId=strRecordTypeId;
        proRoll.IPM_Project__c=project.ID;
        proRoll.Target_Launch_Date__c=System.today();
        proRoll.Market_Cluster_Name__c='SEAA';
        proRoll.Market_Cluster__c='GEO0022';
        proRoll.Local_Project__c=project.Id;
        proRoll.Regional_Project__c=project.Id;
        insert proRoll;
        
        String strRecordTypeId1=[Select Id From RecordType Where SobjectType='IPM_Financial__c' and Name='Consolidated'].Id;
        finCon.RecordTypeId=strRecordTypeId1;
       // finCon.Volume_Unit__c='Total Tons';
        finCon.Financial_External_ID__c='TESTAPPROVERCL_CONSOLIDATED';
        finCon.Target_Launch_Date__c=System.today();
        finCon.Status__c='Not Started';
        finCon.IPM_Project_Rollout__c=proRoll.Id;
        finCon.Parent_Project__c=project.Id;
        finCon.IPM_Project_Rollout__c=proRoll.Id;
        insert finCon;
         
        String strRecordTypeId2=[Select Id From RecordType Where SobjectType='IPM_Financial__c' and Name='Default'].Id;
        finDef.RecordTypeId=strRecordTypeId2;
       // finDef.Volume_Unit__c='Total Tons';
        finDef.Financial_External_ID__c='external11';
        finDef.Target_Launch_Date__c=System.today();
        finDef.Status__c='Not Started';
        finDef.IPM_Project_Rollout__c=proRoll.Id;
        finDef.Parent_Project__c=project.Id;
        finDef.IPM_Project_Rollout__c=proRoll.Id;
        insert finDef;
        
        currentFinancialId=finDef.Id;
         
        finYear.IPM_Financial__c=finCon.Id;
        finYear.Name='Y0';
        finYear.Year__c='0';
        finYear.Year_Type__c='Innovation';
        insert finYear;
        IPM_FinancialShare fishare=new IPM_FinancialShare();
        map<id,IPM_Financial__c>mpfin=new map<id,IPM_Financial__c>();
        mpfin.put(finCon.id,finCon);
        fishare.Sharerecords(mpfin);
           
    }
 
    static testMethod void dotest1(){
        initializeData();
        PageReference pRef = new PageReference('/apex/IPMFinancialController?id='+project.Id);
        Test.setCurrentPage(pRef);
        IPMFinancialController ipmFinCon=new IPMFinancialController();
        ipmFinCon.sustainabilityPeriod=3;
        ipmFinCon.colSpan=2;
        ipmFinCon.isEditMode=true;
        ipmFinCon.currentFinancialId=finCon.Id;
        ipmFinCon.showTopDownTab=true;
       
        ipmFinCon.volumeUnit='Total Tons';
        ipmFinCon.tabLabelMyView='TOP DOWN';
        ipmFinCon.tabLabelTopDown='TOP DOWN';
        ipmFinCon.tabLabelRollup='BOTTOM UP';
        REGIONAL_ROLLOUT_RECORDTYPE=proRoll.RecordTypeId;
        DEFAULT_FINANCIAL_RECORDTYPE=finDef.RecordTypeId;
        CONSOLIDATED_FINANCIAL_RECORDTYPE=finCon.RecordTypeId;
        
        ipmFinCon.changeTabs();
        
        
       
    }
}