src/objects/IPM_Document_Template__c.object
<CustomObject>
    <description>To Capture the Document Template Master based on the Project Template</description>
    <fields>
        <fullName>IPM_Document_Template_Name__c</fullName>
        <description>To capture the Name of the Document Template</description>
        <label>IPM Document Template Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Document_Type__c</fullName>
        <description>To capture the Document Type</description>
        <label>IPM Document Type</label>
        <picklist>
            <picklistValues>
                <fullName>Charter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Project Template</description>
        <label>IPM Project Template</label>
        <referenceTo>IPM_Project_Template__c</referenceTo>
        <relationshipLabel>IPM Document Templates</relationshipLabel>
        <relationshipName>IPM_Document_Templates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>IPM Document Template</label>
    <nameField>
        <displayFormat>IDT-{0000}</displayFormat>
        <label>IPM Document Template Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Document Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Milestone__c.object
<CustomObject>
    <description>This object is used to capture Milestone Dates</description>
    <fields>
        <fullName>IPM_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent master milestone lookup.</description>
        <label>IPM Milestone</label>
        <referenceTo>IPM_Milestone__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>phase of milestone.</description>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Launch Evaluation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>IPM Project Master data</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Milestone</label>
    <nameField>
        <label>IPM Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>Deputy_Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user.</description>
        <label>Deputy Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Gatekeeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user in this case the gatekeeper.</description>
        <label>Project Gatekeeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related user in this case the project leader.</description>
        <label>Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related project template.</description>
        <label>IPM Project Template</label>
        <referenceTo>IPM_Project_Template__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Technical_Project_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to related user in this case the Technical Project Leader.</description>
        <label>Technical Project Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document__c.object
<CustomObject>
    <description>THis is used in IPM to store Project documents</description>
    <fields>
        <fullName>IPM_Document_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship to document template</description>
        <label>IPM Document Template</label>
        <referenceTo>IPM_Document_Template__c</referenceTo>
        <relationshipLabel>IPM Project Documents</relationshipLabel>
        <relationshipName>IPM_Project_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship to Project Template</description>
        <label>IPM Project Template</label>
        <referenceTo>IPM_Project_Template__c</referenceTo>
        <relationshipLabel>IPM Project Documents</relationshipLabel>
        <relationshipName>IPM_Project_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>Relation to the Project Object</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Documents</relationshipLabel>
        <relationshipName>Project_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Project Document</label>
    <nameField>
        <label>Project Document Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Document_Section__c.object
<CustomObject>
    <description>To be used in IPM project to store Gate Document Sections. It refers to the IPM Section object to pick what section/subsection it needs.</description>
    <fields>
        <fullName>IPM_Project_Document__c</fullName>
        <description>Relationship to Project Document</description>
        <label>IPM Project Document</label>
        <referenceTo>IPM_Project_Document__c</referenceTo>
        <relationshipLabel>IPM Project Document Sections</relationshipLabel>
        <relationshipName>IPM_Project_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Name__c</fullName>
        <description>Contains section name</description>
        <label>Section Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Sequence__c</fullName>
        <description>To display section sequence number</description>
        <formula>IPM_Section__r.IPM_Section_Sequence__c</formula>
        <label>IPM_Section_Sequence</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Master Section object</description>
        <label>IPM Section</label>
        <referenceTo>IPM_Section__c</referenceTo>
        <relationshipLabel>IPM Project Sections</relationshipLabel>
        <relationshipName>IPM_Project_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project Document Section</label>
    <nameField>
        <label>Section Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Project Document Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Resource__c.object
<CustomObject>
    <description>To store the IPM Project Team Members</description>
    <fields>
        <fullName>IPM_Project_Document_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>look up of object IPM_Project_Document_Section.</description>
        <label>IPM Project Document Section</label>
        <referenceTo>IPM_Project_Document_Section__c</referenceTo>
        <relationshipLabel>IPM Project Resources</relationshipLabel>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>lookup for IPM project</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Resources</relationshipLabel>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IPM_Role_Type__c</fullName>
        <description>Store role type</description>
        <label>IPM Role Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to IPM User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IPM_Project_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resource Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project_Template__c.object
<CustomObject>
    <description>a Detailed object to Project and a Master object to the the Project Section object.</description>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Project. Mostly a 1:1 Relationship</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Project Templates</relationshipLabel>
        <relationshipName>IPM_Project_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Template_Complexity__c</fullName>
        <description>To store the complexity of the project.</description>
        <label>IPM_Template_Complexity</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project Template</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>IPM Project Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Project Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Section__c.object
<CustomObject>
    <description>This will be the main section object, Using this object, it will be roll out to Project/Gate Document Sections are defined.</description>
    <fields>
        <fullName>IPM_Document_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To capture the Document in thisch the Section Belongs</description>
        <label>IPM Document Template</label>
        <referenceTo>IPM_Document_Template__c</referenceTo>
        <relationshipLabel>IPM Sections</relationshipLabel>
        <relationshipName>IPM_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Name__c</fullName>
        <description>To store section name</description>
        <label>Section Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Section_Sequence__c</fullName>
        <description>TO capture the sequence of the Sections</description>
        <label>IPM Section Sequence</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>IPM Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Section ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IPM_ShareMilestone_Trigger_Test.cls
@isTest
private class IPM_ShareMilestone_Trigger_Test{

    public static IPM_Project__c project;
    public static IPM_Project_Document__c projDoc;
    public static IPM_Project_Template__c projTemp; 
    public static IPM_Project_Document_Section__c projDocSec;
    public static IPM_Document_Template__c ipdt;
    public static IPM_Project_Template__c projTempl;
    public static IPM_Section__c secMst;


    static testmethod void testCreateIPMMilestone(){
    
        initializedData();
        
        IPM_TestDataUtils testData = new IPM_TestDataUtils();

        Test.startTest();       
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User  u1 = testData.testRunAs();
              
       
        
        
        project.IPM_Technical_Project_Leader__c =u1.Id;
        project.IPM_Project_Leader__c = u1.Id;
        project.Deputy_Project_Leader__c = u1.Id;
        project.IPM_Project_Gatekeeper__c = u1.Id;
        update project;
       
       
        
       /*IPM_Project_Resource__c  ipmProjectResource = new IPM_Project_Resource__c();
       
       ipmProjectResource.IPM_Role_Type__c = 'Finance';
       ipmProjectResource.IPM_Project__c = project.Id ;
       ipmProjectResource.IPM_User__c = u.Id ;
       insert ipmProjectResource;
        

       testData.createIPMProjectResource ('BD',project);*/
        
       IPM_Milestone__c  ipmMilestone1 = testData.createIPMMilestone(project, 'Charter Gate Approval');
        
       IPM_Milestone__share  milestoneShare = new IPM_Milestone__share  ();
       List<IPM_Milestone__share> listIPMMilestone = new List<IPM_Milestone__share>();
        
        
       milestoneShare.ParentId= ipmMilestone1.Id;
       System.debug('*********'+ u1.id);
       milestoneShare.userOrGroupId =u1.Id ;
       milestoneShare.accesslevel = 'Edit';
       listIPMMilestone.add(milestoneShare);
        
       //IPM_Questionnaire__share  questShareCopy = questShare;
       //delete questShare;
        
       //insert questShareCopy;
        
       try{

            insert listIPMMilestone ;
            testData.createIPMProjectResource ('BD',project);
            IPM_Milestone__c ipmQuestionaire = testData.createIPMMilestone(project, 'Charter Gate Approval'); 
       }
        
       catch(Exception e){
        
        
       }
        
       finally{

       }
        
        
        /*
        
        IPM_Milestone__c  ipmMilestone2 = testData.createIPMMilestone(project, 'Contract Gate Approval');
        IPM_Milestone__c  ipmMilestone3 = testData.createIPMMilestone(project, 'Market Ready Gate Approval');
        IPM_Milestone__c  ipmMilestone4 = testData.createIPMMilestone(project, 'Market Deployment Gate Approval');
        IPM_Milestone__c  ipmMilestone5 = testData.createIPMMilestone(project, 'Ship To Trade');
        */
        
        
        Test.stopTest();  
        
    
    }


static void initializedData()
    { 
        
        projTempl=new IPM_Project_Template__c();
        projTempl.IPM_Template_Complexity__c='Full';
        insert projTempl;
        
        ipdt=new IPM_Document_Template__c();
        ipdt.IPM_Project_Template__c=projTempl.ID;
        ipdt.IPM_Document_Template_Name__c='Contract';
        ipdt.IPM_Document_Type__c='Charter';
        insert ipdt;
        
        secMst=new IPM_Section__c();
        secMst.IPM_Document_Template__c=ipdt.ID;
        secMst.IPM_Section_Sequence__c='1.1';
        secMst.IPM_Section_Name__c='Ideas';
        insert secMst;
        
        
        project=new IPM_Project__c();
        project.Name='TestGate';
        project.IPM_Phase__c='Ideas';
        project.IPM_Complexity__c='Full';
        insert project;
        
        projTemp=new IPM_Project_Template__c();
        projTemp.IPM_Template_Complexity__c='Full';
        insert projTemp;
        
        projDoc=new IPM_Project_Document__c();
        projDoc.IPM_GateDocuments__c='Charter'; 
        projDoc.IPM_Project__c=project.ID;
        projDoc.IPM_Project_Template__c=projTemp.Id;
        insert projDoc;     
        
        projDocSec=new IPM_Project_Document_Section__c();
        projDocSec.IPM_Project_Document__c=projDoc.ID;
        projDocSec.IPM_Section__c=secMst.Id;
        projDocSec.IPM_Negotiable__c=true;
        insert projDocSec;  
        
    }
    
    


}