src/objects/IPM_Milestone__c.object
<CustomObject>
    <description>This object is used to capture Milestone Dates</description>
    <fields>
        <fullName>IPM_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active flag to identify the milestone is applicable for current project.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Completed_On__c</fullName>
        <description>Date when milestone is marked as completed.</description>
        <label>Completed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to identify milestone is completed.</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Due_Date_Capability__c</fullName>
        <description>Snapshot of Capability Due Date</description>
        <inlineHelpText>Snapshot of Capability Due Date</inlineHelpText>
        <label>Due Date@Capability</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Due_Date_Feasibility__c</fullName>
        <description>Snapshot of Feasibility Due Date</description>
        <inlineHelpText>Snapshot of Feasibility Due Date</inlineHelpText>
        <label>Due Date@Feasibility</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Due_Date_Idea__c</fullName>
        <description>Snapshot of Idea Due Date</description>
        <inlineHelpText>Snapshot of Idea Due Date</inlineHelpText>
        <label>Due Date@Idea</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Due_Date_Market_Deployment__c</fullName>
        <description>Snapshot of Market Deployment Due Date</description>
        <inlineHelpText>Snapshot of Market Deployment Due Date</inlineHelpText>
        <label>Due Date@Market Deployment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Due_Date_Market_Ready__c</fullName>
        <description>Snapshot of Market Ready Due Date</description>
        <inlineHelpText>Snapshot of Market Ready Due Date</inlineHelpText>
        <label>Due Date@Market Ready</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Due_Date_Post_Launch_Evaluation__c</fullName>
        <description>Sanpshot of Post Launch Evaluation Due Date</description>
        <inlineHelpText>Sanpshot of Post Launch Evaluation Due Date</inlineHelpText>
        <label>Due Date@Post Launch Evaluation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Due_Date__c</fullName>
        <description>Due date of milestone</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IPM_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent master milestone lookup.</description>
        <label>IPM Milestone</label>
        <referenceTo>IPM_Milestone__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Name__c</fullName>
        <description>Milestone name</description>
        <label>Milestone Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPM_Phase_Order__c</fullName>
        <description>To sort according to phase</description>
        <formula>IF(text(IPM_Phase__c)=&apos;Ideas&apos;,
1, 
IF(text(IPM_Phase__c)=&apos;Feasibility&apos;, 
2, 
IF(text(IPM_Phase__c)=&apos;Capability&apos;, 
3, 
IF(text(IPM_Phase__c)=&apos;Market Ready&apos;, 
4, 
IF(text(IPM_Phase__c)=&apos;Market Deployment&apos;,
5,
IF(text(IPM_Phase__c)=&apos;Post Launch Evaluation&apos;, 
6, 
-1) 
) 
) 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IPM Phase Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>phase of milestone.</description>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Launch Evaluation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Project__c</fullName>
        <description>IPM Project Master data</description>
        <label>IPM Project</label>
        <referenceTo>IPM_Project__c</referenceTo>
        <relationshipLabel>IPM Milestones</relationshipLabel>
        <relationshipName>IPM_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>IPM Milestone</label>
    <nameField>
        <label>IPM Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_Phase__c</fullName>
        <description>To capture the phase of the project.</description>
        <label>IPM_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IPM_Gate_Milestones.cls
/****************************************************************************************************************************
@Author: Cognizant
@Name: IPM_Gate_Milestones
@Created Date: 15/04/2015
@Description: To Display project's milestones for gate Documents
@Version: 1.0
@Reference: IPM_MilestoneList_PDF component
*/
public with sharing class IPM_Gate_Milestones {
    //For exception handler
    private static final String IPM_GATE_MILESTONES_STR = IPM_Gate_Milestones.class.getName();
    private static final String SHOW_MILESTONES_STR='showMilestones';
    public string gateType{get;set;}
    public string gateDocumentStatus{get;set;}
    public boolean isCurrentDueDate{get;set;}
    public boolean isIdeaSnapShot{get;set;}
    public boolean isFeasibilitySnapShot{get;set;}
    public boolean isCapabilitySnapShot{get;set;}
    public boolean isMarketReadySnapShot{get;set;}
    public Id projectId{ // getter setter method for project id from the component attribute
        get {
            return projectId;
        }
        set {
            projectId= value;
            showMilestones();// calling the function
        }
    }
    public transient List<IPM_Milestone__c> projectMilestones{get;set;}//used to store the value return by  loadMilestones function 

    /************************************************************************************************************************
    *  Description Getting list of milestones to display in gate docuemnt and pdf
    *  @name loadMilestones
    *  @param none
    *  @return void
    *  @throws query exception
    */
    private void showMilestones(){
        try{
            IPM_IECompatible.ieFix();//For IE Compatibility
            if(String.isNotBlank(projectId)){
                projectMilestones=new List<IPM_Milestone__c>();
                String soql  =  'SELECT IPM_Completed__c, IPM_Name__c, IPM_Due_Date__c,IPM_Due_Date_Idea__c,IPM_Due_Date_Feasibility__c,IPM_Due_Date_Capability__c,IPM_Due_Date_Market_Ready__c,IPM_Due_Date_Market_Deployment__c,IPM_Due_Date_Post_Launch_Evaluation__c, IPM_Completed_On__c, IPM_phase__c,IPM_Phase_Order__c,IPM_Milestone__c';
                soql += ' FROM IPM_Milestone__c ';
                soql += 'WHERE IPM_Project__c = \'' + projectId + '\'';
                soql += ' AND recordtypeId=\'' + IPM_Utils.getMilestoneRecordType(IPM_ConstantUtils.MILESTONES_RECORDTYPE) + '\'';
                soql += ' AND IPM_Active__c=true';
                soql += ' ORDER BY IPM_Phase_Order__c asc LIMIT 1000';
                projectMilestones = Database.query(soql); 
                
                showSnapshot();             
                
            }
        }
        catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,Label.IPM_PLEASE_CONTACT_ADMINISTRATOR));
            ExceptionLoggingHelper.createErrorLog(UserInfo.getUserId(),IPM_GATE_MILESTONES_STR,
                SHOW_MILESTONES_STR,ex.getMessage(),ex, IPM_ConstantUtils.ERROR, null, null, null, IPM_ConstantUtils.IPM_NG_APPLICATION);
        }
    }
    
    private void showSnapshot(){
    	isIdeaSnapShot=false;
		isFeasibilitySnapShot=false;
		isCapabilitySnapShot=false;
		isMarketReadySnapShot=false;
		isCurrentDueDate=true;
		if(String.isNotBlank(gateType) && String.isNotBlank(gateDocumentStatus))
		{ 
			if(IPM_ConstantUtils.CHARTER_GATE==gateType && IPM_ConstantUtils.STATUS_APPROVED==gateDocumentStatus)
			{				
				isIdeaSnapShot=true;
				isCurrentDueDate=false;
			}
			else if(IPM_ConstantUtils.CONTRACT_GATE==gateType && IPM_ConstantUtils.STATUS_APPROVED==gateDocumentStatus)
			{
				isFeasibilitySnapShot=true;
				isCurrentDueDate=false;
			}
			else if(IPM_ConstantUtils.MARKET_READY_GATE==gateType && IPM_ConstantUtils.STATUS_APPROVED==gateDocumentStatus)
			{
				isCapabilitySnapShot=true;
				isCurrentDueDate=false;
			}
			else if(IPM_ConstantUtils.MARKET_DEPLOYMENT_GATE==gateType && IPM_ConstantUtils.STATUS_APPROVED==gateDocumentStatus)
			{
				isMarketReadySnapShot=true;
				isCurrentDueDate=false;
			}
			
		}
    
    }
}