src/objects/IPM_Bosscard__c.object
<CustomObject>
    <description>This object is created to hold the Bosscard Details</description>
    <fields>
        <fullName>IPM_Bosscard_Status__c</fullName>
        <description>Stores the status of BOSSCARD</description>
        <label>IPM Bosscard Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To relate BOSSCARD to a Company card.</description>
        <label>IPM Company Card</label>
        <referenceTo>IPM_Company_Card__c</referenceTo>
        <relationshipLabel>IPM Bosscard</relationshipLabel>
        <relationshipName>IPM_Bosscard</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Is_Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when the BOSSCARD status is Archived.</description>
        <label>Is Archived</label>
        <type>Checkbox</type>
    </fields>
    <label>IPM Bosscard</label>
    <nameField>
        <label>IPM Bosscard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Bosscard</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Company_Card__c.object
<CustomObject>
    <description>This object store company cards details</description>
    <fields>
        <fullName>IPM_Currency__c</fullName>
        <description>to store currency type</description>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BGN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BYR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CYP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EGP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_Managed_Category__c</fullName>
        <description>to store company card category</description>
        <label>Managed Category</label>
        <picklist>
            <picklistValues>
                <fullName>Savoury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ice Cream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laundry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Cleansing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spreads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dressings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hair Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deodorants &amp; Fragrances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Foods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tea and Soy &amp; Fruit Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee &amp; Snacks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Purification Category</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>IPM_TxtGeographical_Scope__c</fullName>
        <description>to store geographical scope values as Global or market cluster or countries names</description>
        <label>Geographical Scope</label>
        <type>TextArea</type>
    </fields>
    <label>IPM Company Card</label>
    <nameField>
        <label>IPM Company Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Company Card</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_Project__c.object
<CustomObject>
    <description>Used by the IPM project.</description>
    <fields>
        <fullName>IPM_Bosscard_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To tell whether bosscard is available for the project.</description>
        <label>Bosscard Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IPM_Bosscard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Bosscard.</description>
        <label>Bosscard</label>
        <referenceTo>IPM_Bosscard__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related company card.</description>
        <label>IPM Company Card</label>
        <referenceTo>IPM_Company_Card__c</referenceTo>
        <relationshipLabel>IPM Projects</relationshipLabel>
        <relationshipName>IPM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IPM Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IPM_User_Profile__c.object
<CustomObject>
    <fields>
        <fullName>IPM_Company_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to associate the User Profile to Company card.</description>
        <inlineHelpText>This field is to associate the User Profile to Company card</inlineHelpText>
        <label>Company Card</label>
        <referenceTo>IPM_Company_Card__c</referenceTo>
        <relationshipLabel>User Profiles</relationshipLabel>
        <relationshipName>IPM_User_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IPM_User_Category__c</fullName>
        <description>To select the category of the project.</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Household Care</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Laundry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ice Cream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savoury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hair Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skin Cleansing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deodorants &amp; Fragrances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dressings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spreads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tea and Soy &amp; Fruit Beverages</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>IPM_User_Function__c</fullName>
        <description>To select the user function associated to the user profile.</description>
        <label>User Role</label>
        <picklist>
            <picklistValues>
                <fullName>Team-worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Business Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gatekeeper</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IPM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To store the user associated.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IPM User Profile</label>
    <nameField>
        <displayFormat>UP-{00000}</displayFormat>
        <label>ObjectUser ProfileIPM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IPM User Profile</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IPM_BosscardStatusController_Test.cls
/**
* IPM_BosscardStatusController_Test : This Test class for IPM_BosscardStatusController apex class
* @author 
*
*/
@isTest
public class IPM_BosscardStatusController_Test
{   
    
    
    private static String SF_ID = 'Id';
    private static String BOSSFEEDBACK = 'Project has approved';
    private static User loginUser = new User();
    private static User readUser = new User();
    private static IPM_Bosscard__c boss = new IPM_Bosscard__c();
    private static IPM_Company_Card__c compCard = new IPM_Company_Card__c();
    private static IPM_User_Profile__c up = new IPM_User_Profile__c();
    private static IPM_BosscardStatusController bossCtrl;
    private static string IPMUSER_LASTNAME='IPMUSER_LASTNAME';
    private static string lastUserName_STR='user last name is:';
    private static string bosscardStatus_STR='Bosscard status is:';
    private static string category_STR='Household Care';
    /*********************************************************************
    * @Description: This method is used to initialize data for test class
    * *******************************************************************/
    static void initializeData(){
        
        //Insert User
        loginUser = IPM_TestFactory_Helper.createIPMPlatformProfileUser(IPM_ConstantUtils.PROJECT_LEADER);//only created by user can do update operation
        readUser = IPM_TestFactory_Helper.createUser(false);
        insert readUser;
        
        List<User>userList=[SELECT LastName FROM user WHERE id=:loginUser.id LIMIT 1];
        System.AssertEquals(userList[0].LastName, loginUser.LastName,lastUserName_STR+userList[0].LastName);//positive test
        List<User>userLists=[SELECT LastName FROM user WHERE id=:readUser.id LIMIT 1];
        System.AssertEquals(userLists[0].LastName, readUser.LastName,lastUserName_STR+userLists[0].LastName);//positive test
       
        system.RunAs(loginUser){
            //Insert Company Card
            compCard=IPM_TestFactory_Helper.createGlobalCompanyCard(false);
            compCard.Name='bosscard company card';
            compCard.IPM_Managed_Category__c=category_STR;
            compCard.IPM_Currency__c='10';
            compCard.IPM_TxtGeographical_Scope__c='Global';
            insert compCard;
            List<IPM_Company_Card__c>companyCList=[SELECT Name FROM IPM_Company_Card__c WHERE ID=:compCard.id LIMIT 1];
            System.AssertEquals(companyCList[0].Name,compCard.Name, 'company card name is:'+companyCList[0].Name); //Positive test
            
            //Insert User Profile
            up=IPM_TestFactory_Helper.createUserProfile(false);
            up.IPM_User__c=loginUser.Id; 
            up.IPM_Company_Card__c= compCard.id;
            up.IPM_User_Function__c='Project Leader';
            up.IPM_User_Category__c=category_STR;
            insert up;
            List<IPM_User_Profile__c>userProfileCList=[SELECT IPM_User__c FROM IPM_User_Profile__c WHERE ID=:up.id LIMIT 1];
            System.AssertEquals(userProfileCList[0].IPM_User__c,loginUser.Id, 'user profile user name is:'+userProfileCList[0].IPM_User__c); //Positive test
            
            //Insert Bosscard
            boss = IPM_TestFactory_Helper.createIPMBosscard(false);
            boss.IPM_Bosscard_Status__c = IPM_ConstantUtils.STATUS_IN_PROGRESS;
            boss.IPM_Company_Card__c=compCard.id;
            insert boss;
            List<IPM_Bosscard__c>bossList=[SELECT IPM_Bosscard_Status__c FROM IPM_Bosscard__c WHERE ID=:boss.id LIMIT 1];
            System.AssertEquals(bossList[0].IPM_Bosscard_Status__c,IPM_ConstantUtils.STATUS_IN_PROGRESS, bosscardStatus_STR+bossList[0].IPM_Bosscard_Status__c); //Positive test
                    
            //call class constructor as project leader role
            
            PageReference pg = Page.IPM_BosscardStatus;
            Test.setCurrentPageReference(pg);
            ApexPages.CurrentPage().getparameters().put(SF_ID, boss.id);
            bossCtrl=new IPM_BosscardStatusController();
            
        }
        
    }
    /*************************************************
    * @Description: Test invoke updateStatus
    * ***********************************************/
    public Static testMethod void testBosscardStatus()
    {      
        initializeData();
        Test.startTest();
        System.runAs(loginUser)
        { 
            
            bossCtrl.updateStatus();//for first time update as in progress
            List<IPM_Bosscard__c>bossLists=[SELECT IPM_Bosscard_Status__c FROM IPM_Bosscard__c WHERE ID=:boss.id LIMIT 1];
            System.AssertEquals(bossLists[0].IPM_Bosscard_Status__c,IPM_ConstantUtils.STATUS_IN_PROGRESS, bosscardStatus_STR+bossLists[0].IPM_Bosscard_Status__c); //Positive test
            //for the status - Not Approved
            bossCtrl.Statusvalue=IPM_ConstantUtils.STATUS_NOT_APPROVED;
            bossCtrl.updateStatus();
            List<IPM_Bosscard__c>bossUpdateList=[SELECT IPM_Bosscard_Status__c FROM IPM_Bosscard__c WHERE ID=:boss.id LIMIT 1];
            System.AssertEquals(bossUpdateList[0].IPM_Bosscard_Status__c,IPM_ConstantUtils.STATUS_NOT_APPROVED, bosscardStatus_STR+bossUpdateList[0].IPM_Bosscard_Status__c); //Positive test
            
        }
        Test.stopTest();
    }
     
    
     /*****************************************************
     * @Description: Test invoke updateStatus and getStatus
     * ****************************************************/
    Static testMethod void testBosscardUpdate()
    {
        
        initializeData();
        Test.startTest();
        system.runAs(loginUser)
        {
            
            bossCtrl.selectedPL =IPMUSER_LASTNAME;
            bossCtrl.filterprojectLeader();
            IPM_BosscardStatusController.createProject(boss.id,loginUser.id,BOSSFEEDBACK );
            //project should get created
            List<IPM_Project__c>projectList=[SELECT IPM_Bosscard__c FROM IPM_Project__c WHERE IPM_Bosscard__c=:boss.id LIMIT 1];
            System.AssertEquals(projectList[0].IPM_Bosscard__c,boss.id, 'project bosscard name is:'+projectList[0].IPM_Bosscard__c); //Positive test
            
            List<SelectOption>statusList=bossCtrl.getStatusValue();
            system.assertEquals(statusList.isEmpty(),false,'statusList is Empty');//positive test
            
            bossCtrl.Statusvalue=IPM_ConstantUtils.STATUS_NOT_APPROVED; 
            bossCtrl.setStatus();
            system.assertEquals(bossCtrl.bosscard.IPM_Bosscard_Status__c,IPM_ConstantUtils.STATUS_NOT_APPROVED,'Bosscard Status is:'+bossCtrl.bosscard.IPM_Bosscard_Status__c);//positive test
            
            bossCtrl.holdPLUserId();
            system.assertEquals(bossCtrl.isPLSelected_Booln,true);//positive test
            
            bossCtrl.Statusvalue=IPM_ConstantUtils.STATUS_DISCARD; 
            bossCtrl.updateStatus();
            List<IPM_Bosscard__c>bossUpdateList=[SELECT IPM_Is_Archived__c FROM IPM_Bosscard__c WHERE ID=:boss.id LIMIT 1];
            System.AssertEquals(bossUpdateList[0].IPM_Is_Archived__c,true, 'Bosscard archived is:'+bossUpdateList[0].IPM_Is_Archived__c); //Positive test
            
        }
        Test.stopTest();
    }
     /*****************************************************
     * @Description: Test invoke updateStatus and getStatus with read only user
     * ****************************************************/
    Static testMethod void testBosscardReadUpdate()
    {
        
        initializeData();
        Test.startTest(); 
        system.runAs(readUser)
        {
            //Negative test
            //current user does not has access to the bosscard 
            IPM_BosscardStatusController.createProject(boss.id,loginUser.id,BOSSFEEDBACK );
            bossCtrl.Statusvalue=IPM_ConstantUtils.STATUS_DISCARD; 
            bossCtrl.updateStatus();
            List<IPM_Bosscard__c>bossUpdateList=[SELECT IPM_Is_Archived__c FROM IPM_Bosscard__c WHERE ID=:boss.id LIMIT 1];
            System.AssertEquals(bossUpdateList.isEmpty(),true,'bosscard list is not empty :'+bossUpdateList); //Negative test
            
        }
        Test.stopTest();
    }
}