src/objects/kof_Account__c.object
<CustomObject>
    <description>KOF - Custom Account object for Stakeholder App</description>
    <fields>
        <fullName>BillingCity__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountry__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingPostcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingState__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingStreet__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Organisation</label>
    <nameField>
        <label>Organisation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/kof_Contact__c.object
<CustomObject>
    <description>KOF - Custom object used to store Stakeholders contact details</description>
    <fields>
        <fullName>MailingCity__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingCountry__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingPostcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingState__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingStreet__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>kof_Account__c</referenceTo>
        <relationshipLabel>Stakeholders</relationshipLabel>
        <relationshipName>Stakeholders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stakeholder</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/kof_ContactTriggerHandler.cls
public with sharing class kof_ContactTriggerHandler {
	
	public void onBeforeInsert(kof_Contact__c[] newItems, Map<Id, kof_Contact__c> itemMap) {
		Set<Id> kofAccountId = new Set<Id>(); 
		for (kof_Contact__c c : newItems) {
			kofAccountId.add(c.Organisation__c);
		}
		
		Map<Id,kof_Account__c> kofAccount = new Map<Id,kof_Account__c>([SELECT BillingCity__c, BillingCountry__c, BillingPostcode__c, 
			BillingState__c, BillingStreet__c FROM kof_Account__c WHERE Id IN :kofAccountId ]);
			
		for (kof_Contact__c c : newItems) {
			try {
				if (String.isBlank(c.MailingStreet__c) && String.isBlank(c.MailingCity__c) && String.isBlank(c.MailingPostcode__c) 
					&& String.isBlank(c.MailingState__c) && String.isBlank(c.MailingCountry__c)) {
					
					c.MailingStreet__c = (!String.isBlank(kofAccount.get(c.Organisation__c).BillingStreet__c)) 
						? kofAccount.get(c.Organisation__c).BillingStreet__c 
						: c.MailingStreet__c;
					c.MailingCity__c = (!String.isBlank(kofAccount.get(c.Organisation__c).BillingCity__c)) 
						? kofAccount.get(c.Organisation__c).BillingCity__c 
						: c.MailingCity__c;
					c.MailingPostcode__c = (!String.isBlank(kofAccount.get(c.Organisation__c).BillingPostcode__c)) 
						? kofAccount.get(c.Organisation__c).BillingPostcode__c 
						: c.MailingPostcode__c;
					c.MailingState__c = (!String.isBlank(kofAccount.get(c.Organisation__c).BillingState__c)) 
						? kofAccount.get(c.Organisation__c).BillingState__c 
						: c.MailingState__c;
					c.MailingCountry__c = (!String.isBlank(kofAccount.get(c.Organisation__c).BillingCountry__c)) 
						? kofAccount.get(c.Organisation__c).BillingCountry__c 
						: c.MailingCountry__c;
				}
			} catch(Exception e) {
				System.debug('An error occurred updating Stakeholder fields: ' + e.getMessage());
			}
		}
	}
	
}