src/objects/KUN_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Capability_Searchable_Field__c</fullName>
        <description>Custom Search Field to create a copy of the pick list value in an additional text field so that it is &quot;searchable&quot;</description>
        <label>Capability Searchable Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capability__c</fullName>
        <description>KUN Business Operations function that a user is mapped to (for example Make or Deliver or Procurement etc)</description>
        <inlineHelpText>Refers to the Business Operations function you are mapped (for example Make or Deliver or Procurement etc)</inlineHelpText>
        <label>Capability</label>
        <picklist>
            <picklistValues>
                <fullName>Make</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deliver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order-to-Cash (O2C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan-to-Forecast (P2F)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase-to-Pay (P2P)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record-to-Report (R2R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain Finance (SCF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-to-Tax (C2T)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information &amp; Management (IM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Launch-to-Grow (L2G)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data-to-Insights (D2I)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Data Management (MDM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Cluster_Searchable_Field__c</fullName>
        <label>Cluster Searchable Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <description>Grouping of MCOs for business organization purposes</description>
        <inlineHelpText>Refers to the grouping of MCOs for business organization purposes such as SEAA, NA, SA, North America.</inlineHelpText>
        <label>Cluster</label>
        <picklist>
            <picklistValues>
                <fullName>North Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uapl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uscc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Latin America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Namet &amp; Rub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>E2E_Process_Searchable_Field__c</fullName>
        <description>E2E Process Searchable Field</description>
        <label>E2E Process Searchable Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E2E_Process__c</fullName>
        <description>End to End Business Process</description>
        <inlineHelpText>End to End Business Process</inlineHelpText>
        <label>E2E Process</label>
        <picklist>
            <picklistValues>
                <fullName>Plan-to-Forecast (P2F)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Make-to-Deliver (M2D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order-to-Cash (O2C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record-to-Report (R2R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply-to-Finance (SCF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information &amp; Technology (IT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Launch-to-Grow (L2G)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data-to-Insight (D2I)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Data Management (MDM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Management (IM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Govern-to-Comply (G2C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hire-to-Retire (H2R)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase-to-Pay (P2P)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Employee_Type_Searchable_Field__c</fullName>
        <description>Employee Type Searchable Field</description>
        <label>Employee Type Searchable Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Type__c</fullName>
        <description>Unilever or 3rd Party Employee</description>
        <inlineHelpText>Unilever or 3rd Party Employee</inlineHelpText>
        <label>Employee Type</label>
        <picklist>
            <picklistValues>
                <fullName>Unilever</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>3rd party</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KUN_Role_Type_Searchable_Field__c</fullName>
        <description>KUN Role Type Searchable Field</description>
        <label>KUN Role Type Searchable Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KUN_Role_Type__c</fullName>
        <inlineHelpText>Are you a participating full time or part time in Key User Network activities</inlineHelpText>
        <label>KUN Role Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Time</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Part time</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organization_Searchable_Field__c</fullName>
        <description>Organization Searchable Field</description>
        <label>Organization Searchable Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Either you are from Country or Operating Center or ETS Business Ops</description>
        <inlineHelpText>Either you are from Country or Operating Center or ETS Business Ops</inlineHelpText>
        <label>Organization</label>
        <picklist>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operating Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position_Searchable_Field__c</fullName>
        <description>Position Searchable Field</description>
        <label>Position Searchable Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>What is your Key User Network Position in your country, such as Process Champions or Key Users</description>
        <inlineHelpText>What is your Key User Network Position in your country, such as Process Champions or Key Users</inlineHelpText>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>Key User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process Champion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RT Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Excellence Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geography IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ETS Capability Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ETS Capability Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ETS Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Unilever_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unilever Profile</label>
        <referenceTo>User</referenceTo>
        <relationshipName>KUN_Profiles_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>KUN Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KUN Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/KUN_ProfileTriggerHandler.cls
/**********************************************************************
Name:  KUN_ProfileTriggerHandler ()
Copyright  2016  Unilever
======================================================================
======================================================================
Purpose:  Trigger Helper Class                                                
To Handle the extendated Search Requirment & for Apex Sharing 
Rules                                 
======================================================================
======================================================================
History                                                            
-------                                                            
VERSION  AUTHOR       DATE             DETAIL                  Description
****************************************************************************/
public with sharing class KUN_ProfileTriggerHandler {

    /*******************************************************************
    Purpose: This method before Insert 
    Parameters : newProfiles- List of profiles Updated
    ********************************************************************/     
    public void OnBeforeInsert(List<KUN_Profile__c> newProfiles)
    {
        system.debug('Profile Trigger On Before Insert');
                       
        for(KUN_Profile__c moProfile : newProfiles){        
          PopulateSearchableFields(moProfile ); 
        }
    }
    /*******************************************************************
    Purpose: This method after Insert of records 
    Parameters : newProfiles- List of profiles Updated
    ********************************************************************/
     public void OnAfterInsert(List<KUN_Profile__c> newProfiles)
     {
        // Create a new list of sharing objects for Job
        List<KUN_Profile__Share> Profileshare  = new List<KUN_Profile__Share>();
        
        // Declare variables for KUN Community Profile sharing with User for Edit 
        KUN_Profile__Share userShare;   

         for(KUN_Profile__c moProfile : newProfiles){        
            // Instantiate the sharing objects
            userShare = new KUN_Profile__Share ();
                        
            // Set the ID of record being shared
            userShare.ParentId = moProfile.Id;
             // Set the ID of user or group being granted access
            userShare.UserOrGroupId = moProfile.Unilever_Profile__c;           
            // Set the access level
            userShare.AccessLevel = 'edit';
            // Set the Apex sharing reason for KUN Profile 
            userShare.RowCause = Schema.KUN_Profile__Share.RowCause.KUN_Self_Update__c;
             // Add objects to list for insert
            Profileshare.add(userShare);
           } 
           // Insert sharing records and capture save result 
        // The false parameter allows for partial processing if multiple records are passed 
        // into the operation 
        Database.SaveResult[] lsr = Database.insert(Profileshare,false);
        
           
    }
  /*******************************************************************
    Purpose: This method before Insert 
    Parameters : newProfiles- List of profiles Updated
    ********************************************************************/
    public void OnBeforeUpdate( List<KUN_Profile__c> newProfiles)
    {
        system.debug('Profile Trigger On Before Update ');       
        for(KUN_Profile__c moProfile : newProfiles){        
            PopulateSearchableFields(moProfile );
        }
        //Update newProfiles ;
    }

   /*******************************************************************
    Code to update the Picklist value to Searchable Field to make it Searchable
    Parameters : numRecords- copy the fields in profile 
    ********************************************************************/
   private void PopulateSearchableFields(KUN_Profile__c moProfile){    
            moProfile.Capability_Searchable_Field__c      =     moProfile.Capability__c;
            moProfile.Cluster_Searchable_Field__c         =     moProfile.Cluster__c ;
            moProfile.E2E_Process_Searchable_Field__c     =     moProfile.E2E_Process__c;
            moProfile.Employee_Type_Searchable_Field__c   =     moProfile.Employee_Type__c;
            moProfile.KUN_Role_Type_Searchable_Field__c   =     moProfile.KUN_Role_Type__c ;
            moProfile.Organization_Searchable_Field__c    =     moProfile.Organization__c;
            moProfile.Position_Searchable_Field__c        =     moProfile.Position__c;
            moProfile.Profile_Id__c                       =     moProfile.Unilever_Profile__c ;
   }
   
   

}