src/objects/OV_Category__c.object
<CustomObject>
    <label>One View Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_ContentProxy__c.object
<CustomObject>
    <label>One View Content Proxy</label>
    <nameField>
        <label>OV Proxy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Content Proxy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OV_Function__c.object
<CustomObject>
    <description>OneView Master List of Functions. Used for Filters.</description>
    <label>One View Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Functions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_Geography__c.object
<CustomObject>
    <description>OneView Geographies. Used to categorise Reports and for screen Filters/Preferences</description>
    <label>One View Geography</label>
    <nameField>
        <label>OV_Geography Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Geographies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_KPI_Name__c.object
<CustomObject>
    <description>One View KPI Dimension - Flat</description>
    <fields>
        <fullName>Code_Text__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Code Text</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Visible_Columns__c</fullName>
        <label>Visible Columns</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>One View KPI Dimension KPI Name</label>
    <nameField>
        <label>OV KPI Dimension KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension KPI Names</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Transaction__c.object
<CustomObject>
    <description>One View KPI Transaction - Junction / Join for all OV KPI Dimensions Entities</description>
    <fields>
        <fullName>Data_Tag__c</fullName>
        <label>Data Tag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Version__c</fullName>
        <label>File Version</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Name_Code__c</fullName>
        <label>KPI Name Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>KPI Name</label>
        <referenceTo>OV_KPI_Dimension_KPI_Name__c</referenceTo>
        <relationshipLabel>One View KPI Transactions</relationshipLabel>
        <relationshipName>One_View_KPI_Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Timestamp__c</fullName>
        <label>Source Timestamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Current_Period__c</fullName>
        <label>Value Current Period</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Previous_Period__c</fullName>
        <label>Value Previous Period</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>One View KPI Transaction</label>
    <nameField>
        <displayFormat>KPITX {00000000}</displayFormat>
        <label>OV KPI Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>One View KPI Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_Profile__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OV_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>One View Profile</label>
    <nameField>
        <label>One View Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_Report__c.object
<CustomObject>
    <description>OneView - Report Tile: Report Detail Page to create a One View  Report Tile</description>
    <fields>
        <fullName>Views__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Views</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>One View Report Tile</label>
    <nameField>
        <label>Report Tile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Report Tiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_Report_Favourite__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>OV_Profile__c</referenceTo>
        <relationshipLabel>One View Report Favourites</relationshipLabel>
        <relationshipName>One_View_Report_Favourites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>One View Report Favourite</label>
    <nameField>
        <label>OV Favourite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Report Favourites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OV_Shelf__c.object
<CustomObject>
    <description>One View Shelf for Displaying Shelf Tiles</description>
    <label>One View Shelf</label>
    <nameField>
        <label>Shelf Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Shelves</pluralLabel>
    <recordTypes>
        <fullName>Subject</fullName>
        <active>true</active>
        <description>Shelves with this Record Type will appear under the Tab labelled Subjects within One View</description>
        <label>Subject</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_Shelf_Tile__c.object
<CustomObject>
    <description>Shelf Tile for storing 1 or more Report Tiles and Report Folders underneath</description>
    <label>One View Shelf Tile</label>
    <nameField>
        <label>Shelf Tile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Shelf Tiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OV_ReportService_Test.cls
@isTest
global class OV_ReportService_Test{

    static final String brandLabel = 'brand';
    static final String channelLabel = 'channel';
    static final String customerLabel = 'customer';
    static final String geographyLabel = 'geography';
    static final String categoryLabel = 'category';
    static final String functionLabel = 'function';
    public static final String TILE1_LABEL           = 'Tile 1';
    public static final String SAMPLE_IMAGE_URL      = 'www.test.com/image.png';
    public static final String GRAY_COLOR           = '#ccc';
    public static final String SUBJECT_LABEL         = 'Subject';

    public static testMethod Void runTest(){
        User u = OV_TestingHelper.createAdminUser('Test', 'test@test.com', 'test2');
        system.runAs(u){
            OV_Profile__c profile = new OV_Profile__c(User__c = u.Id);
            insert profile;

            OV_KPI_Dimension_KPI_Name__c kpiName = new OV_KPI_Dimension_KPI_Name__c(Visible_Columns__c='brand;businessUnit;channel;', Code__c = TILE1_LABEL,  Code_Text__c = 'LABEL_1234');
            insert kpiName;
        
            List<OV_KPI_Transaction__c> transactions = new List<OV_KPI_Transaction__c>();
            transactions.add(new OV_KPI_Transaction__c(Value_Current_Period__c='10', Value_Previous_Period__c = '5', Direction__c ='NO CHANGE', KPI_Name__c=kpiName.Id, KPI_Name_Code__c=TILE1_LABEL, Source__c='test123', File_Version__c='222', Source_Timestamp__c=Datetime.now(), Data_Tag__c=TILE1_LABEL));
            transactions.add(new OV_KPI_Transaction__c(Value_Current_Period__c='10', Value_Previous_Period__c = '5', Direction__c ='NO CHANGE', KPI_Name__c=kpiName.Id, KPI_Name_Code__c=TILE1_LABEL, Source__c='test123', File_Version__c='222', Source_Timestamp__c=Datetime.now(), Data_Tag__c=TILE1_LABEL));
            insert transactions;
            
            OV_Category__c category1   = OV_TestingHelper.initCategory(categoryLabel, true);
            OV_Geography__c geography1 = OV_TestingHelper.initGeography(geographyLabel, true);
            OV_Function__c function1   = OV_TestingHelper.initFunction(functionLabel, true);
            ContentVersion contentVersion1 = OV_TestingHelper.initContentVersion('Test 1', true);
            ContentDocument document1 = [select Id from ContentDocument where Id = :contentVersion1.ContentDocumentId limit 1][0];
            OV_ContentProxy__c proxy1 = OV_TestingHelper.initContentProxy(document1.Id, 'proxy test title1', contentVersion1.Id, 'www.salesforce.com', true);
            OV_Report__c report       = OV_TestingHelper.initReportWithProxyHeaderFolder('Test Report', category1, function1, geography1, 'Desktop', proxy1.Id, 'Heading 1', 'Folder 1', true);
        
            OV_Shelf__c shelf         = OV_TestingHelper.initShelf('Shelf', SUBJECT_LABEL, true);
            OV_Shelf_Tile__c tile     = OV_TestingHelper.initShelfTile(TILE1_LABEL, GRAY_COLOR, SAMPLE_IMAGE_URL, shelf, true);
            
            OV_ReportService.addReportToFavourites(report.Id,tile.Id);
            List<OV_Report_Favourite__c> favouriteReports = [SELECT Id FROM OV_Report_Favourite__c LIMIT 10000];
            system.assertEquals(1, favouriteReports.size());
            
            OV_ReportService.deleteReportFromFavourites(report.Id);
            favouriteReports = [SELECT Id FROM OV_Report_Favourite__c LIMIT 10000];
            system.assertEquals(0, favouriteReports.size());
            
            OV_ReportService.increaseViewsCounter(report.Id);
            List<OV_Report__c> reports = [SELECT Id, Views__c FROM OV_Report__c LIMIT 1];
            system.assertEquals(1, reports.get(0).Views__c);
        }
    }
}