src/objects/OV_GetKPI_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header__c</fullName>
        <label>Header</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>OV Get KPI Mapping</label>
</CustomObject>

src/objects/OV_KPI_Dimension_Brand__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierarchical</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension Brand</label>
    <nameField>
        <label>One View KPI Dimension Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_Business_Unit__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierarchical</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension Business Unit</label>
    <nameField>
        <label>One View KPI Dimension Business Unit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension Business Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_Channel__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierarchical</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension Channel</label>
    <nameField>
        <label>One View KPI Dimension Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_Customer__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierarchical</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension Customer</label>
    <nameField>
        <label>One View KPI Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_Geography__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierarchical</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension Geography</label>
    <nameField>
        <label>One View KPI Dimension Geography</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension Geographies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_KPI_Name__c.object
<CustomObject>
    <description>One View KPI Dimension - Flat</description>
    <fields>
        <fullName>Code_Text__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Code Text</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Visible_Columns__c</fullName>
        <label>Visible Columns</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>One View KPI Dimension KPI Name</label>
    <nameField>
        <label>OV KPI Dimension KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension KPI Names</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_NA_Brand__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierarchical</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>OV Hierarchical Dimension</description>
        <externalId>true</externalId>
        <inlineHelpText>OV Hierarchical Dimension</inlineHelpText>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension NA Brand</label>
    <nameField>
        <label>one View KPI Dimension NA  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension NA Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_NA_OPCO__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension NA OPCO</label>
    <nameField>
        <label>One View KPI Dimension NA OPCO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension NA OPCOs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_NA_Sales_Org__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierachical</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension NA Sales Org</label>
    <nameField>
        <label>One View KPI Dimension NA Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimensions NA Sales Orgs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_NAProductCategory__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierarchical</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension NA Product Catego</label>
    <nameField>
        <label>OV KPI Dimension NA Product Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension NA ProductCategor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_Org_Unit__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierarchical</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension Org Unit</label>
    <nameField>
        <label>One View Dimension Organisational Unit N</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension Org Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_Product_Category__c.object
<CustomObject>
    <description>One View KPI Dimension - Hierarchical</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension Product Category</label>
    <nameField>
        <label>OV KPI Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI DimensionProduct Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_Time_Range__c.object
<CustomObject>
    <description>One View KPI Dimension - Flat</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension Time Range</label>
    <nameField>
        <label>OV KPI Dimension Time Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension Time Ranges</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Dimension_WL_GROUP__c.object
<CustomObject>
    <description>One View KPI Dimension - Flat</description>
    <fields>
        <fullName>Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>One View KPI Dimension WL GROUP</label>
    <nameField>
        <label>One View KPI WL GROUP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Dimension WL GROUPs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Transaction__c.object
<CustomObject>
    <description>One View KPI Transaction - Junction / Join for all OV KPI Dimensions Entities</description>
    <fields>
        <fullName>Data_Tag__c</fullName>
        <label>Data Tag</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Version__c</fullName>
        <label>File Version</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Name_Code__c</fullName>
        <label>KPI Name Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>KPI Name</label>
        <referenceTo>OV_KPI_Dimension_KPI_Name__c</referenceTo>
        <relationshipLabel>One View KPI Transactions</relationshipLabel>
        <relationshipName>One_View_KPI_Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Timestamp__c</fullName>
        <label>Source Timestamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Current_Period__c</fullName>
        <label>Value Current Period</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Previous_Period__c</fullName>
        <label>Value Previous Period</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>One View KPI Transaction</label>
    <nameField>
        <displayFormat>KPITX {00000000}</displayFormat>
        <label>OV KPI Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>One View KPI Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OV_KPI_Transaction_Favorite__c.object
<CustomObject>
    <fields>
        <fullName>KPI_Transaction__c</fullName>
        <label>KPI Transaction</label>
        <referenceTo>OV_KPI_Transaction__c</referenceTo>
        <relationshipLabel>One View KPI Transaction Favorites</relationshipLabel>
        <relationshipName>One_View_KPI_Transaction_Favorites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>OV_Profile__c</referenceTo>
        <relationshipLabel>One View KPI Transaction Favorites</relationshipLabel>
        <relationshipName>One_View_KPI_Transaction_Favorites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wants_Notifications__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wants Notifications</label>
        <type>Checkbox</type>
    </fields>
    <label>One View KPI Transaction Favorite</label>
    <nameField>
        <label>One View KPI Transaction Favorite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View KPI Transaction Favorites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OV_Profile__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OV_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>One View Profile</label>
    <nameField>
        <label>One View Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One View Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OV_BatchKpiNotification_Test.cls
/**********************************************************************
Name: OV_BatchKpiNotification_Test
Copyright © 2015 Salesforce.

============================================================================
============================================================================
Purpose: Test for OV_BatchKpiNotification
============================================================================

============================================================================
History
-------
VERSION AUTHOR                  DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   Maciej Krol             16/10/2015      INITIAL DEVELOPMENT
**********************************************************************/
@isTest
private class OV_BatchKpiNotification_Test {

    public static final String TEST_EMAIL         = 'test@test.com';
    public static final String TEST_LABEL            = 'test';
    public static final String TEST2_LABEL           = 'test2';
    
    @isTest static void batchTest() {
        User u = OV_TestingHelper.createAdminUser(TEST_LABEL, TEST_EMAIL, TEST2_LABEL);
        OV_Profile__c profile = new OV_Profile__c(User__c = u.Id);
        insert profile;
        OV_KPI_Dimension_KPI_Name__c kpiName = new OV_KPI_Dimension_KPI_Name__c(Visible_Columns__c='brand;businessUnit;channel;', Code__c = TEST2_LABEL, Code_Text__c = TEST2_LABEL);
        insert kpiName;
        List<OV_KPI_Transaction__c> transactions = new List<OV_KPI_Transaction__c>();
        for(Integer i=0;i<200;i++){
            transactions.add(new OV_KPI_Transaction__c(Direction__c ='NO CHANGE', KPI_Name__c=kpiName.Id, KPI_Name_Code__c=TEST2_LABEL, Source__c='test123', File_Version__c='222', Source_Timestamp__c=Datetime.now(), Data_Tag__c=TEST2_LABEL, Value_Current_Period__c='1.2', Value_Previous_Period__c='2.2'));
        }
        insert transactions;

        List<OV_KPI_Transaction_Favorite__c> favouriteTransactions = new List<OV_KPI_Transaction_Favorite__c>();
        for(Integer i=0;i<150;i++){
            favouriteTransactions.add(new OV_KPI_Transaction_Favorite__c(User__c = profile.Id, KPI_Transaction__c = transactions[i].Id, Wants_Notifications__c = true));
        }
        insert favouriteTransactions;

        Test.startTest();
        String query = 'SELECT Id FROM OV_KPI_Transaction__c';
        OV_BatchKpiNotification c = new OV_BatchKpiNotification(query);
        Database.executeBatch(c);
        Test.stopTest();
        system.assertEquals(150, OV_BatchKpiNotification.testBatchSize);
    }
    
    @isTest static void noFavouriteTransactionTest() {
        List<OV_GetKPI_Mapping__c > mappingList = new List<OV_GetKPI_Mapping__c >();
        mappingList.add(new OV_GetKPI_Mapping__c(Name='timeRange', Header__c = 'Time Range', Field_API_Name__c = 'Time_Range__c',  Object_API_Name__c = 'OV_KPI_Dimension_Time_Range__c',  Order__c = 1, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='wlGroup', Header__c = 'WL Group', Field_API_Name__c = 'WL_Group__c',  Object_API_Name__c = 'OV_KPI_Dimension_WL_GROUP__c',  Order__c = 2, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='businessUnit', Header__c = 'Business Unit', Field_API_Name__c = 'Business_Unit__c',  Object_API_Name__c = 'OV_KPI_Dimension_Business_Unit__c',  Order__c = 3, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='geography', Header__c = 'Geography', Field_API_Name__c = 'Geography__c',  Object_API_Name__c = 'OV_KPI_Dimension_Geography__c',  Order__c = 4, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='organisationalUnit', Header__c = 'Org Unit', Field_API_Name__c = 'Organisational_Unit__c',  Object_API_Name__c = 'OV_KPI_Dimension_Org_Unit__c',  Order__c = 5, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='salesOrgNA', Header__c = 'Org Unit', Field_API_Name__c = 'NA_Sales_Org__c',  Object_API_Name__c = 'OV_KPI_Dimension_NA_Sales_Org__c',  Order__c = 6, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='opcoNA', Header__c = 'NA OPCO', Field_API_Name__c = 'NA_OPCO__c',  Object_API_Name__c = 'OV_KPI_Dimension_NA_OPCO__c',  Order__c = 7, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='productCategory', Header__c = 'Product Category', Field_API_Name__c = 'Product_Category__c',  Object_API_Name__c = 'OV_KPI_Dimension_Product_Category__c',  Order__c = 8, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='productCategoryNA', Header__c = 'NA Product Category', Field_API_Name__c = 'NA_Product_Category__c',  Object_API_Name__c = 'OV_KPI_Dimension_NAProductCategory__c',  Order__c = 9, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='brand', Header__c = 'Brand', Field_API_Name__c = 'Brand__c',  Object_API_Name__c = 'OV_KPI_Dimension_Brand__c',  Order__c = 10, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='brandNA', Header__c = 'NA Brand', Field_API_Name__c = 'NA_Brand__c',  Object_API_Name__c = 'OV_KPI_Dimension_NA_Brand__c',  Order__c = 11, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='customer', Header__c = 'Customer', Field_API_Name__c = 'Customer__c',  Object_API_Name__c = 'OV_KPI_Dimension_Customer__c',  Order__c = 12, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='channel', Header__c = 'Channel', Field_API_Name__c = 'Channel__c',  Object_API_Name__c = 'OV_KPI_Dimension_Channel__c',  Order__c = 13, isDisplayed__c = true));
        mappingList.add(new OV_GetKPI_Mapping__c(Name='kpiName', Header__c = 'KPI Name', Field_API_Name__c = 'KPI_Name__c',  Object_API_Name__c = 'OV_KPI_Dimension_KPI_Name__c',  Order__c = 14, isDisplayed__c = true));
             
        insert mappingList;     

        List<OV_KPI_Transaction__c> transactions = new List<OV_KPI_Transaction__c>();
        OV_KPI_Dimension_KPI_Name__c kpiName = new OV_KPI_Dimension_KPI_Name__c(Visible_Columns__c='brand;businessUnit;channel;', Code__c = TEST2_LABEL, Code_Text__c = TEST2_LABEL);
        insert kpiName;

        for(Integer i=0;i<200;i++){
            transactions.add(new OV_KPI_Transaction__c(Direction__c ='NO CHANGE', KPI_Name__c=kpiName.Id, KPI_Name_Code__c=TEST2_LABEL, Source__c='test123', File_Version__c='222', Source_Timestamp__c=Datetime.now(), Data_Tag__c=TEST2_LABEL, Value_Current_Period__c='1.2', Value_Previous_Period__c='2.2'));
        }
        insert transactions;
        Test.startTest();
        String query = 'SELECT Id FROM OV_KPI_Transaction__c';
        OV_BatchKpiNotification c = new OV_BatchKpiNotification(query);
        Database.executeBatch(c);
        Test.stopTest();
        system.assertEquals(null, OV_BatchKpiNotification.testBatchSize);
    }
}