src/objects/OV_GetKPI_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header__c</fullName>
        <label>Header</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsHierarchical__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsHierarchical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OV Get KPI Mapping</label>
</CustomObject>

src/classes/OV_KpiUtils_Test.cls
@IsTest
public class OV_KpiUtils_Test {

    public static final String wrongObjectName = 'wrongObjectName';

    public static testMethod void runTest(){
        OV_KpiUtils utils = new OV_KpiUtils();// constructor code coverage
        OV_GetKPI_Mapping__c kpiMapping1 = new OV_GetKPI_Mapping__c(Name='Mapping 1', Object_API_Name__c = wrongObjectName,  Order__c = 1, Field_API_Name__c = wrongObjectName, IsHierarchical__c = false, Header__c = 'Test');
        insert kpiMapping1;
        OV_GetKPI_Mapping__c kpiMapping2 = new OV_GetKPI_Mapping__c(Name='Mapping 2', Object_API_Name__c = wrongObjectName,  Order__c = 1, Field_API_Name__c = wrongObjectName, IsHierarchical__c = false, Header__c = 'Test');
        insert kpiMapping2;
        
        system.assertEquals(2, OV_KpiUtils.getKpiSearchMapping().size());
        system.assertEquals(2, OV_KpiUtils.getKpiSearchMappingCS().size());
    }
}