src/objects/PACV_Answers__c.object
<CustomObject>
    <label>PACV Answers</label>
    <nameField>
        <label>Answer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PACV Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PACV_Questions__c.object
<CustomObject>
    <fields>
        <fullName>PACV_Answering_Method__c</fullName>
        <description>Radio Button Objective Answering</description>
        <label>Answering Method</label>
        <picklist>
            <picklistValues>
                <fullName>Radio Button Objective Answering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox Objective Answering</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PACV_Answers__c</fullName>
        <inlineHelpText>Please enter the values separated by semi-colon.</inlineHelpText>
        <label>Answers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PACV_Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PACV_Question_Status__c</fullName>
        <label>Question Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PACV_Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire</label>
        <referenceTo>PACV_Risk_Assessment_Questionnaire__c</referenceTo>
        <relationshipLabel>PACV Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PACV_Scores__c</fullName>
        <inlineHelpText>Please enter the values separated by semi-colon.</inlineHelpText>
        <label>Scores</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PACV_Weightage__c</fullName>
        <label>Weightage %</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>PACV Questions</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PACV Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PACV_Risk_Assessment_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>PACV_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PACV_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Published</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PACV Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PACV Questionnaire</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>This record type is used to have the right page layout for a Published questionnaire</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PACV_Questions_AnswerCreation_Test.cls
/**
 * Name:        -   PACV_Questions_AnswerCreation_Test
 * @description -   This is the test class for PACV_Questions_AnswerCreation Trigger to verify the code  while creating PACV Question record. 
 * @Author      -   Deepika Gulati, Mindtree Ltd     
 */

@isTest
public class PACV_Questions_AnswerCreation_Test {
/*******************************************************************
Purpose: Method to test trigger by creating a question record.
********************************************************************/
    static testMethod void createQuestionTest() {
    
           PACV_Risk_Assessment_Questionnaire__c questionnaire = createQuestionnaire();
        try{
        
            PACV_Questions__c question = new PACV_Questions__c();
            question.PACV_Questionnaire__c = questionnaire.Id;
            question.PACV_Answers__c ='Ans1;Ans2;Ans3';
            question.PACV_Scores__c = '1;2;3';
            question.PACV_Answering_Method__c = 'Radio Button Objective Answering';
            question.PACV_Weightage__c = 12;
            question.PACV_Question_Status__c = 'Activated';
            question.PACV_Help_Text__c = 'Test';
            insert question; 
        }
        catch(Exception e)
        {
            System.debug(e.getMessage());
        }
    }
    static testMethod void createQuestionTest1() 
    {
        PACV_Risk_Assessment_Questionnaire__c questionnaire = createQuestionnaire();
        try{
            PACV_Questions__c question1 = new PACV_Questions__c();
            question1.PACV_Questionnaire__c = questionnaire.Id;
            question1.PACV_Answers__c ='Ans1;Ans2;Ans3';
            question1.PACV_Scores__c = '1;2';
            question1.PACV_Answering_Method__c = 'Radio Button Objective Answering';
            question1.PACV_Weightage__c = 12;
            question1.PACV_Question_Status__c = 'Activated';
            question1.PACV_Help_Text__c = 'Test';
            insert question1; 
        }
        catch(Exception e)
        {
            System.debug(e.getMessage());
        }
    }
    
    static testMethod void createQuestionTest2() 
    {    
        
        PACV_Risk_Assessment_Questionnaire__c questionnaire = createQuestionnaire();
        try{
            PACV_Questions__c question2 = new PACV_Questions__c();
            question2.PACV_Questionnaire__c = questionnaire.Id;
            question2.PACV_Answers__c ='Ans1;Ans2;Ans3';
            question2.PACV_Scores__c = '1;Ans;Ans2';
            question2.PACV_Answering_Method__c = 'Radio Button Objective Answering';
            question2.PACV_Weightage__c = 12;
            question2.PACV_Question_Status__c = 'Activated';
            question2.PACV_Help_Text__c = 'Test';
            insert question2;
        }
        catch(Exception e)
        {
            System.debug(e.getMessage());
        }
        
    }
    
    public static PACV_Risk_Assessment_Questionnaire__c createQuestionnaire()
    {
        PACV_Risk_Assessment_Questionnaire__c questionnaire = new PACV_Risk_Assessment_Questionnaire__c();
        questionnaire.Name = 'Test';
        questionnaire.PACV_Description__c = 'Test';
        questionnaire.PACV_Status__c    = 'Published';
        insert questionnaire;
        return questionnaire ;
        
    }
}