src/objects/PACV_Risk_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>PACV_Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PACV_Project_Start_Date1__c</fullName>
        <formula>IPM_Project__r.IPM_Project_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PACV_Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PACV_Risk_Status__c</fullName>
        <label>Risk Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PACV_Solution_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution Name</label>
        <referenceTo>PACV_Solutions__c</referenceTo>
        <relationshipName>Risk_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PACV_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PACV Risk Assessment</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Risk Assessment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PACV Risk Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PACVRiskAssesmentRecords_CC.cls
public with sharing class PACVRiskAssesmentRecords_CC{ 
public List<PACV_Risk_Assessment__c> Records {get; set;} 

public string userid {get; set;}



public PACVRiskAssesmentRecords_CC()
{ 
userid = Userinfo.getUserId();
Records = [SELECT CreatedById,PACV_Project_Name__c,PACV_Project_Start_Date1__c,PACV_Project_Start_Date__c,PACV_Risk_Status__c,PACV_Solution_Name__c,PACV_Status__c,Name FROM PACV_Risk_Assessment__c WHERE CreatedById = :userid]; 
} 
}