src/objects/PQN_Pallet_Quality_Non_Conformance__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <description>Cluster to be Auto-populated based upon DC master data</description>
        <label>Cluster</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Offer of corrects based on standard English</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DC_Country__c</fullName>
        <description>Auto-populated based upon DC master data</description>
        <label>DC Country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Pallet_Received__c</fullName>
        <description>Date on which the pallet was recieved</description>
        <label>Date Pallet Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_Left_Before_Freeze__c</fullName>
        <description>no of days left before user can submit before ed of month</description>
        <label>Days Left Before Freeze</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Delivery_Note_Number__c</fullName>
        <description>The delivery number of the pallet recieved</description>
        <label>Delivery Note Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCO__c</fullName>
        <description>MCO to be Auto-populated based upon DC master data</description>
        <label>MCO</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_compliance_reason_code__c</fullName>
        <description>Manually keyed/ Copied in/ drop-down box based upon Pallet or Customer Loss tree.Code within product and Customer loss tree L4. Errorred if outside of valid range</description>
        <inlineHelpText>Loss Level 4</inlineHelpText>
        <label>Non-compliance reason code</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Pallets_Per_SKU_Non_Compliant__c</fullName>
        <description>Number of pallets per SKU that are non-compliant.</description>
        <label>Number of Pallets Per SKU Non-Compliant</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Product Category is auto-populated based upon SKU master data</description>
        <label>Product Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>Product Group to be auto populated based upon SKU master data</description>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Product Name is auto-populated Based upon SKU master data</description>
        <label>Product Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Auto-populated Based upon DC master data</description>
        <label>Region</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_DC__c</fullName>
        <description>Auto-populated based upon user if a single DC user, Copied in, drop-down box populated with DCs based upon user</description>
        <label>Reporting DC</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <description>Manually keyed/ Copied in. Validated against SKU master data. Show error if not correctly entered.</description>
        <label>SKU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Cluster__c</fullName>
        <description>Sub-cluster to be Auto-populated based upon DC master data</description>
        <label>Sub-Cluster</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_type__c</fullName>
        <description>Auto populated based upon supplier Master data</description>
        <label>Supplier type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pallet Quality Non Conformance</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pallet Quality Non Conformance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PQN_singleEntryScreen.cls
public with sharing class PQN_singleEntryScreen{
    public PQN_Pallet_Quality_Non_Conformance__c pqn{get; set;}
    public boolean immediate{get; set;}
    Id pqnId;
    public PQN_singleEntryScreen(ApexPages.StandardController controller){
        immediate=true;
        pqn = new PQN_Pallet_Quality_Non_Conformance__c();
        pqnId = Apexpages.currentpage().getparameters().get('id');
        if(pqnId!=null){
            pqn = [select id,Reporting_DC__c,Region__c,DC_Country__c,MCO__c,Cluster__c,Sub_Cluster__c,Delivery_Note_Number__c,Description__c,
                    Product_Name__c,Product_Group__c,Product_Category__c,SKU__c,Supplier_type__c,Non_compliance_reason_code__c,
                    Number_of_Pallets_Per_SKU_Non_Compliant__c,Date_Pallet_Received__c,Comments__c,Days_Left_Before_Freeze__c 
                    from PQN_Pallet_Quality_Non_Conformance__c where id=: pqnId];    
        }
    }
    
    public void validate(){
    
        try{
               
               String skuName =Apexpages.currentPage().getParameters().get('skuName');
               
               system.debug(skuName +'********');
               if(skuName.length()>0){
                   List<PQN_Pallet_Quality_Non_Conformance__c > xPQNCList= [select id,Product_Category__c,Product_Name__c,Product_Group__c,SKU__c from PQN_Pallet_Quality_Non_Conformance__c where SKU__c=:skuName Limit 1];
                   if(xPQNCList.size()>0){
                       for(PQN_Pallet_Quality_Non_Conformance__c  xP: xPQNCList){
                       
                           pqn.Product_Category__c = xP.Product_Category__c;
                           pqn.Product_Name__c = xP.Product_Name__c ;
                           pqn.Product_Group__c = xP.Product_Group__c;
                           immediate=false;
                       }
                   }else{
                       ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'No Product Found.');
                       ApexPages.addMessage(myMsg);
                   }
                   
               }else{
                   ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'SKU is null.');
                   ApexPages.addMessage(myMsg);
               }
       }
        catch(Exception e){
            
        }
        //return null;
    }
    
    public pagereference savePQN(){
        try{
            if(pqn!=null){
                upsert pqn;
                //PageReference redirectPage = new PageReference('/'+pqn.id);
                PageReference redirectPage = page.PQN_Conformance_Detail_VF;
                redirectPage.setRedirect(true);
                redirectPage.getParameters().put('id',pqn.id);
                return redirectPage;
            }
        }
        catch(Exception e){
        
        }
        return null;
    }
    
    
    public pagereference cancelPQN(){
        if(pqn.id==null){
            PageReference pqnhomePage = page.PQN_home;
            pqnhomePage.setRedirect(true);        
            return pqnhomePage;
        } 
        else{
            PageReference recordPage = page.PQN_Conformance_Detail_VF;
            recordPage.setRedirect(true);   
            recordPage.getParameters().put('id',pqn.id);     
            return recordPage;
        } 
        
        return null;
          
    }
}