src/objects/PQN_Pallet_Quality_Non_Conformance__c.object
<CustomObject>
    <fields>
        <fullName>Date_Pallet_Received__c</fullName>
        <description>Date on which the pallet was recieved</description>
        <label>Date Pallet Received</label>
        <type>Date</type>
    </fields>
    <label>Pallet Quality Non Conformance</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pallet Quality Non Conformance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PQN_User_Account_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PQN_Account_Access_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PQN_User_Creation_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PQN User Creation Request</label>
        <referenceTo>PQN_User_Creation_Request__c</referenceTo>
        <relationshipLabel>PQN User Account Request</relationshipLabel>
        <relationshipName>PQN_User_Account_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PQN User Account Request</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>PQN Account Access Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PQN User Account Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PQN_User_Creation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>PQN User Creation Request</label>
    <nameField>
        <displayFormat>UR_{00000000}</displayFormat>
        <label>PQN User Creation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PQN User Creation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PQNFreezeDate__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is created to store the value of Freeze Date</description>
    <fields>
        <fullName>Freeze_Date__c</fullName>
        <description>This field holds the freeze date for the PQN records</description>
        <label>Freeze Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Numeric_Value__c</fullName>
        <label>Numeric Value</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PQN Freeze Date</label>
</CustomObject>

src/classes/PQN_SendEmailtoDC_ClusterBatch.cls
global class PQN_SendEmailtoDC_ClusterBatch implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
        List<PQNFreezeDate__c> listFreeze = PQNFreezeDate__c.getall().values();
        date d = system.today();
        date startDate = date.newInstance(d.year(), d.month(), 1);
        date freezeDate;
        for(PQNFreezeDate__c xFP: listFreeze){
            if(xFP.Numeric_Value__c==d.month()){
                //system.debug('---->>>'+xFP.Freeze_Date__c);
                
                freezeDate = xFP.Freeze_Date__c;
            }
        }
        set<Id> accIDS = new set<Id>();
        if(freezeDate==null){
            for(PQN_Pallet_Quality_Non_Conformance__c xPQN : [Select Id,Account__c from PQN_Pallet_Quality_Non_Conformance__c Where Date_Pallet_Received__c >:startDate and Date_Pallet_Received__c <:freezeDate]){
                accIDS.add(xPQN.Account__c);
            }
            
        }
        
        return Database.getQueryLocator('Select Id,Name,Email__c From PQN_User_Creation_Request__c where Id in (Select PQN_User_Creation_Request__c from PQN_User_Account_Request__c where Account__c =:accIDS)');
    }
    
    global void execute(Database.BatchableContext BC, List<PQN_User_Creation_Request__c> listSobject)
    {
        string subject = 'Non Conformance';
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        for(PQN_User_Creation_Request__c xP : listSobject){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new String[] {xP.Email__c});
                mail.setReplyTo(xP.Email__c);
                mail.setSubject(subject);
                string body = '<html><body>Dear ' + xP.Name+',<br><br>';
                mail.setHtmlBody(body);
                mails.add(mail);
        }

        Messaging.sendEmail(mails);
    }
    
    global void finish(Database.BatchableContext BC)
    {
    
    }
}