src/objects/SAFE_Risk_Assessment_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>SAFE_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SAFE_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Published</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SAFE Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAFE Questionnaire</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <description>This record type is used to have the right page layout for a Published questionnaire</description>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SAFE_Questionnaire_StatusUpdate_Test.cls
/**
 * Name:        -   SAFE_Questionnaire_StatusUpdate_Test
 * @description -   This is the test class for SAFE_Questionnaire_StatusUpdate_Test Trigger to verify the code  while SAFE status as 'Published' in SAFE Questionnaire record. 
 * @Author      -   ChandraSekaran, Mindtree Ltd     
 */

@isTest
public class SAFE_Questionnaire_StatusUpdate_Test {

static testMethod void myStatusTest() {
    SAFE_Risk_Assessment_Questionnaire__c questionnaire = new SAFE_Risk_Assessment_Questionnaire__c();
        questionnaire.Name = 'Test';
        questionnaire.SAFE_Description__c = 'Test';
        questionnaire.SAFE_Status__c    = 'Published';
        test.startTest(); 
        insert questionnaire;
        test.stopTest();
    Integer count;
    count=0;
    List<SAFE_Risk_Assessment_Questionnaire__c> statusList = [SELECT id, SAFE_Status__c FROM SAFE_Risk_Assessment_Questionnaire__c WHERE Name != 'Test'];
    for(SAFE_Risk_Assessment_Questionnaire__c ra:statusList){
        if (ra.SAFE_Status__c == 'Not Published'){
           count = 1;
                         system.assertEquals(1, count);

        }
        else{
            count=0;
             system.assertEquals(0, count);
        }
       
        
    }
   

}
}