src/objects/SAFE_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>SAFE_Material_Type__c</fullName>
        <label>Material Type</label>
        <picklist>
            <picklistValues>
                <fullName>Rigids</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Label</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corrugate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tube</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alu Can</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAFE_Price_Per_Unit__c</fullName>
        <label>Price Per Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SAFE_Solution_Category__c</fullName>
        <label>Solution Category</label>
        <picklist>
            <picklistValues>
                <fullName>Overt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Covert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAFE_Solution_Status__c</fullName>
        <label>Solution Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAFE_Solution_Type__c</fullName>
        <label>Solution Type</label>
        <picklist>
            <picklistValues>
                <fullName>Taggents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Marks</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAFE_Solution_in_Use__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Solution in Use</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAFE_Supplier_Name__c</fullName>
        <label>Supplier Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>SAFE Solutions</label>
    <nameField>
        <label>Solutions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAFE Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SAFE_SolutionsTab_CC.cls
/**
 * Name:        -   SAFE_SolutionsTab_CC
 * @Description -   This Solution tab will display the list of solutions related to loggedin user and giving access to selected user by clicking the grant access button. 
 * @Author      -   Anusha S from Mindtree     
 */

public with sharing class SAFE_SolutionsTab_CC{

    public Boolean displayPopup {get;set;}
    public List<SAFE_Solutions__c> Records {get; set;} 
  //  public User username {get; set;} 
    public string userid {get; set;}
    public String searchTerm {get; set;}
    public String selecteduser {get; set;}
  //  public String uId {get; set;}
    public List<User> UserTemp = new List<User>();
    
    // To load data into the table
    public SAFE_SolutionsTab_CC(ApexPages.StandardController controller) 
    {
        userid = Userinfo.getUserId();       
        Records =   [SELECT Name,SAFE_Solution_Status__c,SAFE_Supplier_Name__c,SAFE_Solution_Type__c,
                     SAFE_Solution_in_Use__c,SAFE_Solution_Category__c,SAFE_Price_Per_Unit__c,SAFE_Material_Type__c,
                     Owner.name FROM SAFE_Solutions__c WHERE CreatedById = :userid]; 
    system.debug(Records);
    } 
         
    // User Auto Complete related code
    public String getSearchTerm() 
    {
        return null;
    }
     // For auto complete functionality
    
        @RemoteAction
        public static List<User> searchuser(String searchTerm) {
       
        System.debug('user Name is: '+searchTerm );
        List<User> user = Database.query('SELECT Name,Id FROM User where Name like \'%' + String.escapeSingleQuotes(searchTerm) + '%\' Limit 20');  
        system.debug('user'+user);
        return user;
    }
    // Assigns permission sets to the appropriate users
    // This is run as part of the setup wizard and after installations.       
            
     public void savepermissionset()
     {
     system.debug('hi:');
         if(selecteduser == '')
         {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please Enter User'));
            //return null; 
         }
         else
         {         
           system.debug('uId1='+selecteduser);
          PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'SAFE_PM_User'];
           list <PermissionSetAssignment> PSAssignments = new list <PermissionSetAssignment>();
          
           List<User> users = [SELECT ID,(Select id,AssigneeId FROM PermissionSetAssignments WHERE PermissionSetID = :ps.Id) 
                               FROM User WHERE Profile.UserLicense.Name= 'Salesforce Platform' AND IsActive = true AND Id = :selecteduser];
          system.debug('selecteduser:'+selecteduser);   
          for( User u : users ){
                    if(u.PermissionSetAssignments.size() == 0) 
                      PSAssignments.add( new PermissionSetAssignment(AssigneeId = u.id,PermissionSetId = ps.ID ) );
            }
            insert PSAssignments;
        
          closePopup();
         }
       
            //return null;
        }
    
    // To show popup and its functionality   onclick="MyjavaFunction('{!$Component.inptID}')"
    
    public void showPopup()
    {       
        displayPopup = true;    
    }
    
    public void closePopup() 
    {
        displayPopup = false;        
    }
    
}