src/objects/SAFE_Solutions__c.object
<CustomObject>
    <fields>
        <fullName>SAFE_Material_Type__c</fullName>
        <label>Material Type</label>
        <picklist>
            <picklistValues>
                <fullName>Rigids</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Label</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corrugate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tube</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alu Can</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAFE_Price_Per_Unit__c</fullName>
        <label>Price Per Unit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SAFE_Solution_Category__c</fullName>
        <label>Solution Category</label>
        <picklist>
            <picklistValues>
                <fullName>Overt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Covert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAFE_Solution_Status__c</fullName>
        <label>Solution Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAFE_Solution_Type__c</fullName>
        <label>Solution Type</label>
        <picklist>
            <picklistValues>
                <fullName>Taggents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Marks</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAFE_Solution_in_Use__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Solution in Use</label>
        <type>Checkbox</type>
    </fields>
    <label>SAFE Solutions</label>
    <nameField>
        <label>Solutions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAFE Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SAFE_SolutionArchivedTabBPSec_CC.cls
public class SAFE_SolutionArchivedTabBPSec_CC 
{
    integer totalRecs = 0;
    integer count= 0;    
    integer limitSize= 5;
    public string userid {get; set;}
    
    // To load data into the table
    public SAFE_SolutionArchivedTabBPSec_CC(ApexPages.StandardController controller)
    {
        totalRecs = [select count() from SAFE_Solutions__c ];
        userid = Userinfo.getUserId();       
        
    } 
    
    public List<SAFE_Solutions__c> getsolutionList()
    {
        List<SAFE_Solutions__c> solutionList = [SELECT Name,SAFE_Solution_Status__c,SAFE_Solution_Type__c,
                                                SAFE_Solution_in_Use__c,SAFE_Solution_Category__c,SAFE_Price_Per_Unit__c,SAFE_Material_Type__c
                                                FROM SAFE_Solutions__c WHERE SAFE_Solution_Status__c = 'Archived'];         
        return solutionList;
    }
    
    /*Risk Assessments List as pagination implementation*/
    public PageReference Firstbtn() 
    {
        count=0;
        return null;
    }
    
    /*Risk Assessments List as pagination implementation*/
    public PageReference prvbtn() 
    {
        count=count-limitsize;
        return null;
    }
    
    /*Risk Assessments List as pagination implementation*/
    public PageReference Nxtbtn() 
    {
        system.debug(count);
        count=count+limitsize;system.debug('limitsize'+limitsize);
        return null;
    }
    
    /*Risk Assessments List as pagination implementation*/
    public PageReference lstbtn() 
    {
        count= totalrecs - math.mod(totalRecs,LimitSize);
        return null;
    }
    
    /*Risk Assessments List as pagination implementation*/
    public Boolean getNxt() 
    {
        if((count+ LimitSize) > totalRecs)
            return true;
        else
            return false;
    }
    
    /*Risk Assessments List as pagination implementation*/
    public Boolean getPrv() 
    {
        if(count== 0)
            return true;
        else
            return false;
    }          
    
}