src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AF_Agency_Fees_User_Type__c</fullName>
        <label>Agency Fees User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO Super User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMCO User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Category Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AF_Brand__c</fullName>
        <description>This represents Brands on the user level</description>
        <inlineHelpText>List of brands assigned to user</inlineHelpText>
        <label>Brand</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AF_Category__c</fullName>
        <description>This represents the categories</description>
        <inlineHelpText>List of Categories assigned to the user</inlineHelpText>
        <label>Category</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_AF_usersearch.cls
/*****************************************************************************************************************************
@Author :Cognizant
@name : Test_AF_usersearch
@Created Date : 02/08/2014.
@Description : This Test class for af_usersearch apex class.
@Version : 1.0
@reference : none
****************************************************************************************************************************/
@isTest(SeeAlldata=false)
public class Test_AF_usersearch{
	/**********************************************************************
*  @Description: This method will have Test data.
*  @name : af_usersearch
*  @param : none
*  @return : none
*************************************************************************/   
	static testMethod void af_usersearch() {
		Profile p=[Select Id from Profile where Name='System Administrator'];       
		//Insert User 
		User u= new User(Alias = 'test123', Email='standarduser@unilever.com', 
		EmailEncodingKey='UTF-8', LastName='af test', LanguageLocaleKey='en_US', 
		LocaleSidKey='en_US', ProfileId = p.Id,firstname='sf test one', 
		TimeZoneSidKey='Europe/London',AF_Agency_Fees_User_Type__c='Category Finance',isActive=true, 
		UserName='testuser@test123321.com',AF_Brand__c='Test Brand1',AF_Category__c='Test Beverages1');
		insert u;  
		System.Assert(u.Id != null, 'The User record not inserted');
		test.starttest(); 
		af_usersearch  aff=new af_usersearch();
		aff.firstName=u.firstname;
		aff.lastname=u.lastname;
		aff.email=u.email;
		aff.name=u.name;
		aff.sortField='Email';
		aff.sortDir='desc';
		//aff.af_usersearch();
		//aff.debugSoql();
		aff.toggleSort();
		aff.runSearch();
		test.stoptest();
	}
	/**********************************************************************
*  @Description: This method will have Test data.
*  @name : af_usersearch1
*  @param : none
*  @return : none
*************************************************************************/   
	static testmethod void af_usersearch1(){
		Profile p=[Select Id from Profile where Name='System Administrator'];       
		//Insert User 
		User u= new User(Alias = 'test123', Email='standarduser@unilever.com', 
		EmailEncodingKey='UTF-8', LastName='af test', LanguageLocaleKey='en_US', 
		LocaleSidKey='en_US', ProfileId = p.Id,firstname='sf test one', 
		TimeZoneSidKey='Europe/London',AF_Agency_Fees_User_Type__c='Category Finance',isActive=true, 
		UserName='testuser@test123321.com',AF_Brand__c='Test Brand1',AF_Category__c='Test Beverages1');
		insert u; 
		System.Assert(u.Id != null, 'The User record not inserted');
		test.starttest();
		af_usersearch  aff=new af_usersearch();
		aff.firstName=u.firstname;
		aff.lastname=u.lastname;
		aff.email=u.email;
		aff.name=u.name;   
		aff.toggleSort();
		aff.runSearch();
		test.stoptest();
	}
}